### ISSUE TITLE
Creating index with datastore_create only works if passed fields list

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#1846]
The following test should pass:

```python
    def test_create_index_on_specific_fields_without_passing_fields_list(self):
        package = factories.Dataset()
        data = {
            'resource': {
                'boo%k': 'crime',
                'author': ['tolstoy', 'dostoevsky'],
                'package_id': package['id']
            },
            'indexes': ['author']
        }
        result = helpers.call_action('datastore_create', **data)
        resource_id = result['resource_id']
        assert self._has_index_on_field(resource_id, 'author')
```

But it doesn't, complaining:
```
ERROR: ckanext.datastore.tests.test_create.TestDatastoreCreateNewTests.test_create_index_on_specific_fields_without_passing_fields_list
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/tests/test_create.py", line 64, in test_create_index_on_specific_fields_without_passing_fields_list
    result = helpers.call_action('datastore_create', **data)
  File "/usr/lib/ckan/default/src/ckan/ckan/new_tests/helpers.py", line 106, in call_action
    return logic.get_action(action_name)(context=context, data_dict=kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 414, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/logic/action.py", line 138, in datastore_create
    result = db.create(context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/db.py", line 979, in create
    create_indexes(context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/db.py", line 436, in create_indexes
    index)]
ValidationError: {'index': ['The field "author" is not a valid column name.']}
```

The problem is that we validate that you can only create indexes on existing field names, but when I don't explictly pass that fields names through the `fields` parameter, that list is empty at the time this check is made.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
