### ISSUE TITLE
Using a method as an action function for IActions crashes

### ISSUE THREAD

**Issue by seanh** [ckan/ckan#1930]
Functions work.

```
======================================================================
ERROR: test suite for ckanext.deadoralive.tests.logic.action.test_get.TestGetResourcesToCheck
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/nose/util.py", line 478, in try_run
    return func()
  File "/home/vagrant/projects/ckan/ckanext-deadoralive/ckanext/deadoralive/tests/helpers.py", line 56, in setup_class
    cls.app = _get_test_app()
  File "/home/vagrant/projects/ckan/ckanext-deadoralive/ckanext/deadoralive/tests/helpers.py", line 16, in _get_test_app
    app = ckan.config.middleware.make_app(config['global_conf'], **config)
  File "/home/vagrant/projects/ckan/ckan/ckan/config/middleware.py", line 58, in make_app
    load_environment(conf, app_conf)
  File "/home/vagrant/projects/ckan/ckan/ckan/config/environment.py", line 232, in load_environment
    p.load_all(config)
  File "/home/vagrant/projects/ckan/ckan/ckan/plugins/core.py", line 134, in load_all
    load(*plugins)
  File "/home/vagrant/projects/ckan/ckan/ckan/plugins/core.py", line 172, in load
    plugins_update()
  File "/home/vagrant/projects/ckan/ckan/ckan/plugins/core.py", line 116, in plugins_update
    environment.update_config()
  File "/home/vagrant/projects/ckan/ckan/ckan/config/environment.py", line 369, in update_config
    logic.get_action('get_site_user')({'ignore_auth': True}, None)
  File "/home/vagrant/projects/ckan/ckan/ckan/logic/__init__.py", line 400, in get_action
    auth_function.auth_audit_exempt = True
AttributeError: 'instancemethod' object has no attribute 'auth_audit_exempt'
```

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
