### ISSUE TITLE
image_view plugin causes failures with new_tests.factories.Dataset including images

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#1955]
example traceback: https://travis-ci.org/open-data/ckanext-scheming/jobs/36780981

```pytb
======================================================================
ERROR: ckanext.scheming.tests.test_display.TestDatasetFormNew.test_dataset_displays_custom_fields
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/open-data/ckanext-scheming/ckanext/scheming/tests/test_display.py", line 17, in test_dataset_displays_custom_fields
    'camels_in_photo': 2}])
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/factory/base.py", line 80, in __call__
    return cls.create(**kwargs)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/factory/base.py", line 453, in create
    return cls._generate(True, attrs)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/factory/base.py", line 378, in _generate
    obj = cls._prepare(create, **attrs)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/factory/base.py", line 358, in _prepare
    return cls._create(target_class, *args, **kwargs)
  File "/home/travis/build/open-data/ckanext-scheming/dl/ckan/ckan/new_tests/factories.py", line 334, in _create
    **kwargs)
  File "/home/travis/build/open-data/ckanext-scheming/dl/ckan/ckan/new_tests/helpers.py", line 104, in call_action
    return logic.get_action(action_name)(context=context, data_dict=kwargs)
  File "/home/travis/build/open-data/ckanext-scheming/dl/ckan/ckan/logic/__init__.py", line 418, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/travis/build/open-data/ckanext-scheming/dl/ckan/ckan/logic/action/create.py", line 195, in package_create
    item.after_create(context, data)
  File "/home/travis/build/open-data/ckanext-scheming/dl/ckan/ckanext/imageview/plugin.py", line 53, in after_create
    self.add_default_views(context, data_dict)
  File "/home/travis/build/open-data/ckanext-scheming/dl/ckan/ckanext/imageview/plugin.py", line 46, in add_default_views
    {'defer_commit': True}, view
  File "/home/travis/build/open-data/ckanext-scheming/dl/ckan/ckan/logic/__init__.py", line 418, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/travis/build/open-data/ckanext-scheming/dl/ckan/ckan/logic/action/create.py", line 340, in resource_view_create
    _check_access('resource_view_create', context, data_dict)
  File "/home/travis/build/open-data/ckanext-scheming/dl/ckan/ckan/logic/__init__.py", line 293, in check_access
    raise NotAuthorized(msg)
NotAuthorized: <function resource_view_create at 0x59d0758> requires an authenticated user
```

**Comment by amercader** [comment]
Fixed as part of #1852
