### ISSUE TITLE
InvalidRequestError: One or more mappers failed to initialize 

### ISSUE THREAD

**Issue by sionqi** [ckan/ckan#2277]
### CKAN 2.2.1 always throw exception:

`InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: When initializing mapper Mapper|Queue|kombu_queue, expression 'Message' failed to locate a name ("name 'Message' is not defined"). If this is a class name, consider adding this relationship() to the <class 'kombu.transport.sqlalchemy.models.Queue'> class after both dependent classes have been defined.`
### The error logs show:

`File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2255, in configure_mappers.`

I tried to upgrade SQLAlchemy package, but CKAN 2.2.1 tip doesn't support the upgrade version. (The current version is 0.7.8) 

Would you please help me look about this ?

**Comment by davidread** [comment]
I suspect this is to do with version issues with celery. It gets installed by a ckan extension. I have these versions, installed by ckanext-archiver/ckanext-qa:
```
$ pip freeze | egrep -i 'celery|kombu'
celery==2.4.2
kombu==2.1.3
kombu-sqlalchemy==1.1.0
```
So do compare.

Also, can you provide the full context to the exception in the error log. And when does this occur? Is it start up of ckan or when you do a particular request? And what extensions do you have installed?

**Comment by george-sattler** [comment]
Hi @sionqi . I've also seen this same error in the logs occurring for CKAN 2.2.1
I would concur with @davidread 's suspicion that it has something to do with celery but exactly what it is I'm not sure of. Though perhaps you've found a solution for this?

I'm have the same package versions that David listed above. I'm running the datastorer extension so that data automatically gets added to the datastore when resources get updated. Is that similar to what you were doing?

**Comment by tanmayAccela** [comment]
@sionqi - Did you find a solution for this? We got the same error today.

**Comment by orod** [comment]
Here's more information on the issue. We see it at runtime, not at startup, but so far can't really point to a specific call.

kombu 2.1.3
kombu-alchemy 1.1.0
celery - 2.4.2
sql-alchemy 0.7.8


```
[error] 2015-04-06 19:47:38,537 ERROR [ckan.model.modification] One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: When initializing mapper Mapper|Queue|kombu_queue, expression 'Message' failed to locate a name ("name 'Message' is not defined"). If this is a class name, consider adding this relationship() to the <class 'kombu.transport.sqlalchemy.models.Queue'> class after both dependent classes have been defined.

[error] Traceback (most recent call last):
[error]   File "/usr/lib/ckan/default/src/ckan/ckan/model/modification.py", line 79, in notify
[error]     observer.notify(entity, operation)
[error]   File "/usr/lib/ckan/default/src/ckanext-datastorer/ckanext/datastorer/plugin.py", line 31, in notify
[error]     self._create_datastorer_task(entity)
[error]   File "/usr/lib/ckan/default/src/ckanext-datastorer/ckanext/datastorer/plugin.py", line 73, in _create_datastorer_task
[error]     task_id=task_id)
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/celery/app/base.py", line 218, in send_task
[error]     expires=expires, **options)
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/celery/app/amqp.py", line 195, in delay_task
[error]     entity = self._declare_queue(queue, retry, _retry_policy)
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/celery/app/amqp.py", line 171, in _declare_queue
[error]     queue.declare()
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/kombu/entity.py", line 388, in declare
[error]     self.queue_declare(nowait, passive=False)
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/kombu/entity.py", line 408, in queue_declare
[error]     nowait=nowait)
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 379, in queue_declare
[error]     self._new_queue(queue, **kwargs)
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 59, in _new_queue
[error]     self._get_or_create(queue)
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 47, in _get_or_create
[error]     obj = self.session.query(Queue).filter(Queue.name == queue) \\
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 980, in query
[error]     return self._query_cls(entities, self, **kwargs)
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 108, in __init__
[error]     self._set_entities(entities)
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 117, in _set_entities
[error]     self._setup_aliasizers(self._entities)
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 132, in _setup_aliasizers
[error]     _entity_info(entity)
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/util.py", line 578, in _entity_info
[error]     mapperlib.configure_mappers()
[error]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2255, in configure_mappers
[error]     raise e
[error] InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: When initializing mapper Mapper|Queue|kombu_queue, expression 'Message' failed to locate a name ("name 'Message' is not defined"). If this is a class name, consider adding this relationship() to the <class 'kombu.transport.sqlalchemy.models.Queue'> class after both dependent classes have been defined.
```

**Comment by zbarahal** [comment]
Did you ever find a solution/cause to this? I'm having a very similar issue using Flask/Celery in an application I'm working on and this is the only google hit I am seeing of someone with a similar problem. Sorry to post in your issue tracker but I'm very perplexed by this.

**Comment by davidread** [comment]
The log shows a datastorer connection, of which I don't have much experience.

**Comment by KrzysztofMadejski** [comment]
I'm having similar problem, it happens randomly on runtime:

```
	  Error - <class 'sqlalchemy.exc.InvalidRequestError'>: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Class 'kombu.transport.sqlalchemy.models.Message' is not mapped
	  URL: https://danepubliczne.gov.pl/
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/weberror/errormiddleware.py', line 162 in __call__
		app_iter = self.application(environ, sr_checker)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
		resp = self.call_func(req, *args, **self.kwargs)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
		return self.func(req, *args, **kwargs)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
		return request.get_response(self.app)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
		application, catch_exc_info=False)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
		app_iter = application(self.environ, start_response)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
		resp = self.call_func(req, *args, **self.kwargs)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
		return self.func(req, *args, **kwargs)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
		response = request.get_response(self.app)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
		application, catch_exc_info=False)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
		app_iter = application(self.environ, start_response)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
		return self.app(environ, start_response)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/beaker/middleware.py', line 155 in __call__
		return self.wrap_app(environ, session_start_response)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
		response = self.app(environ, start_response)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
		response = self.dispatch(controller, environ, start_response)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
		return controller(environ, start_response)
	  File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/base.py', line 338 in __call__
		res = WSGIController.__call__(self, environ, start_response)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/controllers/core.py', line 217 in __call__
		response = self._inspect_call(self.__before__)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
		result = self._perform_call(func, args)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
		return func(**args)
	  File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/controllers/home.py', line 24 in __before__
		base.BaseController.__before__(self, action, **env)
	  File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/base.py', line 240 in __before__
		app_globals.app_globals._check_uptodate()
	  File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/app_globals.py', line 183 in _check_uptodate
		value = model.get_system_info('ckan.config_update')
	  File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/model/system_info.py', line 31 in get_system_info
		obj = meta.Session.query(SystemInfo).filter_by(key=key).first()
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py', line 149 in do
		return getattr(self.registry(), name)(*args, **kwargs)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/session.py', line 1155 in query
		return self._query_cls(entities, self, **kwargs)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 106 in __init__
		self._set_entities(entities)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 116 in _set_entities
		self._set_entity_selectables(self._entities)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 149 in _set_entity_selectables
		ent.setup_entity(*d[entity])
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2987 in setup_entity
		self._with_polymorphic = ext_info.with_polymorphic_mappers
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py', line 712 in __get__
		obj.__dict__[self.__name__] = result = self.fget(obj)
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py', line 1865 in _with_polymorphic_mappers
		configure_mappers()
	  File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py', line 2566 in configure_mappers
		raise e
	  InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Class 'kombu.transport.sqlalchemy.models.Message' is not mapped
```

**Comment by KrzysztofMadejski** [comment]
It seems that rebooting Apache helped in my case..

**Comment by yintothayang** [comment]
This error is unrelated to ckan, I think it's in your sqlalchemy model definitions, specifically your queries on relationships.

**Comment by vinnie87** [comment]
I've got the same issue but on CherryPy. Rebooting the server after some time helped, but it keeps occurring

**Comment by gleb-rudenko** [comment]
maybe it should be closed?

**Comment by KrzysztofMadejski** [comment]
I agree. Kombu was bumped up to 2.5 in https://github.com/ckan/ckanext-archiver/pull/33/files, and deprected kombu-sqlalchemy package was removed.  With new archiver it's also possible to move task scheduling to be supported by Redis instead of Pgsql, which should make this error completely obsolete.

I'd close it.

**Comment by Shivamshuroy448** [comment]
I've got the same issue while im working on flask, unable to resolve it. Do anyone have idea?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in __init__
  File "C:\Users\shiva\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\state.py", line 559, in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
  File "C:\Users\shiva\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\event\attr.py", line 497, in __call__
    fn(*args, **kw)
  File "C:\Users\shiva\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4395, in _event_on_init
    instrumenting_mapper._check_configure()
  File "C:\Users\shiva\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2388, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\shiva\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4203, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\shiva\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4240, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[User(user)]'. Original exception was: Could not determine join condition between parent/child tables on relationship User.items - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.

**Comment by Sneha-Vanani-Tagline** [comment]
i also face this issue..

sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[User_cred(user_cred)]'. Original exception was: When initializing mapper Mapper[User_cred(user_cred)], expression 'Transactions' failed to locate a name ('Transactions'). If this is a class name, consider adding this relationship() to the <class 'app.models.user.User_cred'> class after both dependent classes have been defined.
