### ISSUE TITLE
Error 500 after ugrade Ckan 2.2.1 to 2.3

### ISSUE THREAD

**Issue by dahirieg** [ckan/ckan#2390]
Hello, I've udated my ckan installation from git and when I reboot the server start giving me an error 500

Here is part of my error log

 mod_wsgi (pid=1607): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
 mod_wsgi (pid=1607): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
 Traceback (most recent call last): File "/etc/ckan/default/apache.wsgi", line 10, in <module>
application = loadapp('config:%s' % config_filepath)
File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
return loadobj(APP, uri, name=name, **kw)
File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
global_conf=global_conf)
File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
 global_conf=global_conf)

Thanks for your help.

**Comment by amercader** [comment]
@dahirieg can you send support requests to the mailing list?

https://lists.okfn.org/mailman/listinfo/ckan-dev

I suggest you have a look at the upgrade instructions, you'll need to consider things liek changes in the Solr schema, database and extensions:

http://docs.ckan.org/en/latest/maintaining/upgrading/upgrade-package-to-minor-release.html

I you still have problems, send an email to the list with a full stack trace, as the one you pasted here does not give enough details.

Good luck
