### ISSUE TITLE
Unhandled exception on updating Outer Planets mod

### ISSUE THREAD

**Issue by valuial** [ckan/ckan#2433]
During the installation process when updating Outer Planets mod CKAN throws CKAN.InconsistentKraken. Some kind of dialog for the user to choose how to solve the inconsistency (decide to keep KopernicusTech or keep OuterPlanetsMod in this case) would be nice.

************** Exception Text **************
The following inconsistencies were found:
KopernicusTech conflicts with OuterPlanetsMod.   at CKAN.SanityChecker.EnforceConsistency(IEnumerable`1 modules, IEnumerable`1 dlls)
   at CKAN.RelationshipResolver..ctor(ICollection`1 modules, RelationshipResolverOptions options, Registry registry, KSPVersion kspversion)
   at CKAN.ModuleInstaller.Upgrade(IEnumerable`1 identifiers, NetAsyncDownloader netAsyncDownloader)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by nigelbabu** [comment]
These are not the CKANs you're looking for.

You probably want [KSP-CKAN](https://github.com/KSP-CKAN/CKAN)
