### ISSUE TITLE
Schema.xml not compatible with Solr 5.2.1

### ISSUE THREAD

**Issue by FabiApfelkern** [ckan/ckan#2524]
I set up CKAN 2.3 with Solr 5.2.1. Everything works fine and new datasets are indexed. But when you restart Solr then the core seems to be corrupted and is not loading with this error [1]. It cannot be recovered. It's very likely to be a bug in Solr, or the CKAN Schema is in a way not compatible with this Solr Version. 

[1]
```
java.lang.NullPointerException
	at org.apache.lucene.util.NumericUtils.prefixCodedToLong(NumericUtils.java:226)
	at org.apache.lucene.util.NumericUtils.getMaxLong(NumericUtils.java:582)
	at org.apache.solr.update.VersionInfo.getMaxVersionFromIndex(VersionInfo.java:234)
	at org.apache.solr.update.UpdateLog.seedBucketsWithHighestVersion(UpdateLog.java:1580)
	at org.apache.solr.update.UpdateLog.seedBucketsWithHighestVersion(UpdateLog.java:1610)
	at org.apache.solr.core.SolrCore.seedVersionBuckets(SolrCore.java:861)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:843)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:658)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:637)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:381)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:375)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor$1.run(ExecutorUtil.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mordae** [comment]
Confirming.

**Comment by wardi** [comment]
We had to make this change to our solr config (not schema.xml) https://github.com/open-data/ckanext-stcndm/commit/0b1f4b423 does that help?

**Comment by marinajungblut** [comment]
Same problem here.

**Comment by mordae** [comment]
Weird. Changing type of the `_version_` field to `long` apparently fixed the issue for us.

**Comment by marinajungblut** [comment]
Ran a quick test and seeemed to work. Thank you, @mordae.

**Comment by mordae** [comment]
Now let's hope @joetsoi confirms and fixes this for real. There may be a reason for the `string` type of the field and I would prefer not to run an "accidentally working" CKAN in production.

**Comment by maxious** [comment]
I think there's an assumption in Solr/Lucene that version is a number for which a min/max can be calculated https://issues.apache.org/jira/browse/SOLR-7866 https://issues.apache.org/jira/browse/LUCENE-6719

**Comment by TkTech** [comment]
Confirming that the change to `_version_` from `string` to `long` followed by purging the index and rebuilding resolved this issue for solr 5.2.1.

**Comment by jgrocha** [comment]
To use Solr 5.2.1, I removed every occurrence of `enablePositionIncrements="true"`from `schema.xml` and it worked.

**Comment by amercader** [comment]
Closing as it is an issue with a specific version of Solr, and workarounds have been provided in case people is stuck with it.
