### ISSUE TITLE
Datapusher handles bad URLs badly

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2666]
If given a URL it can't access (or doesn't exist, or is malformed) datapusher should probably handle it rather than crashing.

```
Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 244, in push_to_datastore
    response = urllib2.urlopen(request, timeout=DOWNLOAD_TIMEOUT)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
Fetching from: http://test
```

**Comment by amercader** [comment]
Totally agree, looks like this should be handled on DataPusher itself (`datapusher/datapusher/jobs.py`) and return an error dict.

**Comment by davidread** [comment]
I'm not clear what version was used here, but I think that it was in Dec 2014 that the code was improved so that a URLError at this point caused a JobError to be raised. (I added a test to show this behaviour: https://github.com/ckan/datapusher/pull/127 ). JobError is the way that ckan-service-provider likes to record jobs that go wrong.
