### ISSUE TITLE
Search Index dict filtering throws TypeError if date has timezone specified

### ISSUE THREAD

**Issue by neon-ninja** [ckan/ckan#2689]
2015-10-16 10:28:00,776 ERROR [ckan.lib.search] can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/init.py", line 103, in dispatch_by_operation
index.update_dict(entity)
File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 103, in update_dict
self.index_package(pkg_dict, defer_commit)
File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 240, in index_package
if date != bogus_date:
TypeError: can't compare offset-naive and offset-aware datetimes

https://github.com/ckan/ckan/blob/master/ckan/lib/search/index.py#L240

if date != bogus_date:
  value = date.isoformat() + 'Z'

These lines attempt to parse a date, and if the parse succeeds, converts it to isoformat and adds a Z. However, if the date is already in isoformat with a trailing Z it throws an exception. Perhaps instead of using bogus_date it may be wiser to simply check if the string is empty or None?

**Comment by rossjones** [comment]
I presume the bogus date is so that we don't have to catch the exception if no valid date can be parsed by dateutil.  

Although that's not pretty, I think the actual bug is adding the Z to the date regardless, rather than checking if the datetime is tz aware - seems to be making assumptions on how plugins might store their dates.  The way to check this is probably something like:

```python
    tz_aware = date.tzinfo is not None and date.tzinfo.utcoffset(date) is not None
```

**Comment by neon-ninja** [comment]
Actually I think the original intention was to rely on the behaviour that if value is '', bogus date would be used to populate the fields (https://github.com/ckan/ckan/commit/9cf14977c8059ee21eb343bc9fe503b8cc482620). Hence the use of bogus date is just a roundabout way of checking that value != ''

**Comment by LondonAppDev** [comment]
Hey all, I am also experiencing this issue using CKAN 2.6.2. Wondering if anyone has a workaround for indexing the search?
