### ISSUE TITLE
CKAN ERRNO 13

### ISSUE THREAD

**Issue by justinchau92** [ckan/ckan#2745]
Hello, I am trying to create a CKAN extension and whenever I try to preview it , it will show the html file that I put in it but then I get this error and I'm not sure what to do
--------------
  __no_cache__: True
  application: <fanstatic.publisher.Delegator object at 0x3cf0290>
  beaker.cache: <beaker.cache.CacheManager object at 0x3cf0150>
  beaker.get_session: <bound method SessionMiddleware._get_session of <beaker.middleware.SessionMiddleware object at 0x3d0f450>>
  beaker.session: {'_accessed_time': 1447983438.119944, '_creation_time': 1447903508.988318}
  fanstatic.needed: <fanstatic.core.NeededResources object at 0x41ff590>
  paste.cookies: (<SimpleCookie: auth_tkt='58f84c92cc2936b50b97cfb9eff751d5564b78cfjustin!userid_type:unicode' ckan='667d39b8ca1b3a688e9df007d2dbd88c16fe415b5bc435ccb7f54a9385a3e1a66531137c'>, 'auth_tkt="58f84c92cc2936b50b97cfb9eff751d5564b78cfjustin!userid_type:unicode"; ckan=667d39b8ca1b3a688e9df007d2dbd88c16fe415b5bc435ccb7f54a9385a3e1a66531137c')
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x134a590>
  paste.registry: <paste.registry.Registry object at 0x3ce37d0>
  paste.throw_errors: True
  pylons.action_method: <bound method TemplateController.view of <ckan.controllers.template.TemplateController object at 0x41ff910>>
  pylons.controller: <ckan.controllers.template.TemplateController object at 0x41ff910>
  pylons.environ_config: {'session': 'beaker.session', 'cache': 'beaker.cache'}
  pylons.pylons: <pylons.util.PylonsContext object at 0x41ff850>
  pylons.routes_dict: {'url': u'mailchimpCall.php', 'action': u'view', 'controller': u'template'}
  repoze.who.api: <repoze.who.api.API object at 0x41ff390>
  repoze.who.identity: <repoze.who identity (hidden, dict-like) at 140667158293216>
  repoze.who.logger: <logging.Logger object at 0x3cf0a10>
  repoze.who.plugins: {'ckan.lib.authenticator:UsernamePasswordAuthenticator': <ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x3d17b50>, 'friendlyform': <FriendlyFormPlugin 64058128>, 'auth_tkt': <CkanAuthTktCookiePlugin 64058064>}
  routes.route: <routes.route.Route object at 0x43912d0>
  routes.url: <routes.util.URLGenerator object at 0x41ff710>
  webob._parsed_query_vars: (GET([]), '')
  webob.adhoc_attrs: {'response': <Response at 0x41ff690 200 OK>, 'language': 'en-us'}
  wsgi process: 'Multithreaded'
  wsgiorg.routing_args: (<routes.util.URLGenerator object at 0x41ff710>, {'url': u'mailchimpCall.php', 'action': u'view', 'controller': u'template'})
------------------------------------------------------------
2015-11-20 01:37:19,194 INFO  [ckan.lib.base]  /mailchimpCall.php render time 1.044 seconds
----------------------------------------
Exception happened during processing of request from ('142.232.149.248', 63719)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 638, in __init__
    self.handle()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
    self.wsgi_execute()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
    self.wsgi_start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
    return self.apps[-1](environ, start_response)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 228, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/repoze/who/middleware.py", line 87, in __call__
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/middleware.py", line 214, in __call__
    self.app, new_environ, catch_exc_info=True)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/util.py", line 94, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/weberror/errormiddleware.py", line 156, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
    return request.get_response(self.app)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
    response = request.get_response(self.app)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 389, in inner
    result = application(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py", line 73, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/routes/middleware.py", line 131, in __call__
    response = self.app(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py", line 125, in __call__
    response = self.dispatch(controller, environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py", line 324, in dispatch
    return controller(environ, start_response)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 338, in __call__
    res = WSGIController.__call__(self, environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py", line 284, in __call__
    return response(environ, self.start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/response.py", line 917, in __call__
    start_response(self.status, headerlist)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py", line 149, in session_start_response
    session.persist()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/session.py", line 723, in persist
    self._session().save(accessed_only=True)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/session.py", line 407, in save
    self.namespace.acquire_write_lock(replace=True)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/container.py", line 218, in acquire_write_lock
    r = self.access_lock.acquire_write_lock(wait)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/synchronization.py", line 186, in acquire_write_lock
    x = self.do_acquire_write_lock(wait)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/synchronization.py", line 255, in do_acquire_write_lock
    filedescriptor = self._open(os.O_CREAT | os.O_WRONLY)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/synchronization.py", line 236, in _open
    filedescriptor = os.open(self.filename, mode)
OSError: [Errno 13] Permission denied: '/tmp/default/sessions/container_file_lock/c/c6/c6cf929feb536131d50ccbf8642ed4d38b30c35f.lock'
----------------------------------------

**Comment by davidread** [comment]
Please ask questions on the list or on stackoverflow
