### ISSUE TITLE
Invalid markdown leads to DOS

### ISSUE THREAD

**Issue by th0br0** [ckan/ckan#2762]
We're currently running into deadlocks on one of our CKAN installations used in production. 
Our portal harvests datasets from external repositories, the notes of these sometimes contain invalid markdown.

This invalid markdown causes the library CKAN uses for Markdown (`webhelpers`, dead upstream - if there's a better place to report the bug, please tell me) processing to enter a deadlock upon dataset load.

The bug can be reproduced locally independent of CKAN: (tested on CentOS 7's Python 2.7.5 (64bit), Fedora 21 Python 2.7.8 (64bit))

```python
from webhelpers import markdown
bug = u'* [Foo (http://foo.bar) * Bar] (http://foo.bar)'
markdown.markdown(bug)
```

I can only think of a potential fix by using a different library for markdown processing.

The final stacktrace:
```
#0  0x00007fa0f87e942e in PyString_FromStringAndSize (str=<optimized out>, size=<optimized out>) at /usr/src/debug/Python-2.7.5/Objects/stringobject.c:112
#1  0x00007fa0f87e965a in PyString_FromFormatV (format=format@entry=0x7fa0f8880ed8 "%.50s instance has no attribute '%.400s'", vargs=vargs@entry=0x7fa0f1da8130)
    at /usr/src/debug/Python-2.7.5/Objects/stringobject.c:269
#2  0x00007fa0f8842bec in PyErr_Format (exception=<type at remote 0x7fa0f8add580>, format=format@entry=0x7fa0f8880ed8 "%.50s instance has no attribute '%.400s'")
    at /usr/src/debug/Python-2.7.5/Python/errors.c:550
#3  0x00007fa0f87ae285 in instance_getattr1 (name='__coerce__', inst=0x7fa0ebb82cf8) at /usr/src/debug/Python-2.7.5/Objects/classobject.c:737
#4  instance_getattr (inst=0x7fa0ebb82cf8, name='__coerce__') at /usr/src/debug/Python-2.7.5/Objects/classobject.c:774
#5  0x00007fa0f87ad0e0 in instance_coerce (pv=0x7fa0f1da82e0, pw=0x7fa0f1da82e8) at /usr/src/debug/Python-2.7.5/Objects/classobject.c:1559
#6  0x00007fa0f87debba in PyNumber_CoerceEx (pv=pv@entry=0x7fa0f1da82e8, pw=pw@entry=0x7fa0f1da82e0) at /usr/src/debug/Python-2.7.5/Objects/object.c:1632
#7  0x00007fa0f87ad6ef in instance_compare (
    v=<TextNode(doc=<Document(entities={}, documentElement=<Element(attribute_values={'class': 'markdown'}, nodeName='span', parent=<...>, doc=<...>, isDocumentElement=True, bidi=None, attributes=['class'], childNodes=[<TextNode(doc=<...>, parent=<...>, value='\n') at remote 0x7fa0cc644368>]) at remote 0x7fa0cc6441b8>, bidi='ltr') at remote 0x7fa0d56ace18>, parent=<Element(attribute_values={'href': u'http://www.aquitaine.developpement-durable.gouv.fr/tri-de-bergerac-a1678.html'}, nodeName='a', doc=<...>, isDocumentElement=False, bidi=None, attributes=['href'], childNodes=[<TextNode(doc=<...>, parent=<...>, value=u'XML view metadata (http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/xml_iso19139?uuid=fr-120066022-jdd-451d1fe1-dc0c-4360-a6aa-52b470a457e2)') at remote 0x7fa0cc644dd0>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc6445a8>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644a28>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644e...(truncated), 
    w=<TextNode(doc=<Document(entities={}, documentElement=<Element(attribute_values={'class': 'markdown'}, nodeName='span', parent=<...>, doc=<...>, isDocumentElement=True, bidi=None, attributes=['class'], childNodes=[<TextNode(doc=<...>, parent=<...>, value='\n') at remote 0x7fa0cc644368>]) at remote 0x7fa0cc6441b8>, bidi='ltr') at remote 0x7fa0d56ace18>, parent=<Element(attribute_values={'href': u'http://www.aquitaine.developpement-durable.gouv.fr/tri-de-bergerac-a1678.html'}, nodeName='a', doc=<...>, isDocumentElement=False, bidi=None, attributes=['href'], childNodes=[<TextNode(doc=<...>, parent=<...>, value=u'XML view metadata (http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/xml_iso19139?uuid=fr-120066022-jdd-451d1fe1-dc0c-4360-a6aa-52b470a457e2)') at remote 0x7fa0cc644dd0>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc6445a8>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644a28>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644e...(truncated)) at /usr/src/debug/Python-2.7.5/Objects/classobject.c:1737
#8  0x00007fa0f87decf2 in try_3way_compare (
    v=v@entry=<TextNode(doc=<Document(entities={}, documentElement=<Element(attribute_values={'class': 'markdown'}, nodeName='span', parent=<...>, doc=<...>, isDocumentElement=True, bidi=None, attributes=['class'], childNodes=[<TextNode(doc=<...>, parent=<...>, value='\n') at remote 0x7fa0cc644368>]) at remote 0x7fa0cc6441b8>, bidi='ltr') at remote 0x7fa0d56ace18>, parent=<Element(attribute_values={'href': u'http://www.aquitaine.developpement-durable.gouv.fr/tri-de-bergerac-a1678.html'}, nodeName='a', doc=<...>, isDocumentElement=False, bidi=None, attributes=['href'], childNodes=[<TextNode(doc=<...>, parent=<...>, value=u'XML view metadata (http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/xml_iso19139?uuid=fr-120066022-jdd-451d1fe1-dc0c-4360-a6aa-52b470a457e2)') at remote 0x7fa0cc644dd0>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc6445a8>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644a28>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644e...(truncated), 
    w=w@entry=<TextNode(doc=<Document(entities={}, documentElement=<Element(attribute_values={'class': 'markdown'}, nodeName='span', parent=<...>, doc=<...>, isDocumentElement=True, bidi=None, attributes=['class'], childNodes=[<TextNode(doc=<...>, parent=<...>, value='\n') at remote 0x7fa0cc644368>]) at remote 0x7fa0cc6441b8>, bidi='ltr') at remote 0x7fa0d56ace18>, parent=<Element(attribute_values={'href': u'http://www.aquitaine.developpement-durable.gouv.fr/tri-de-bergerac-a1678.html'}, nodeName='a', doc=<...>, isDocumentElement=False, bidi=None, attributes=['href'], childNodes=[<TextNode(doc=<...>, parent=<...>, value=u'XML view metadata (http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/xml_iso19139?uuid=fr-120066022-jdd-451d1fe1-dc0c-4360-a6aa-52b470a457e2)') at remote 0x7fa0cc644dd0>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc6445a8>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644a28>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644e...(truncated)) at /usr/src/debug/Python-2.7.5/Objects/object.c:713
#9  0x00007fa0f87df17e in try_3way_to_rich_compare (op=2, 
    w=<TextNode(doc=<Document(entities={}, documentElement=<Element(attribute_values={'class': 'markdown'}, nodeName='span', parent=<...>, doc=<...>, isDocumentElement=True, bidi=None, attributes=['class'], childNodes=[<TextNode(doc=<...>, parent=<...>, value='\n') at remote 0x7fa0cc644368>]) at remote 0x7fa0cc6441b8>, bidi='ltr') at remote 0x7fa0d56ace18>, parent=<Element(attribute_values={'href': u'http://www.aquitaine.developpement-durable.gouv.fr/tri-de-bergerac-a1678.html'}, nodeName='a', doc=<...>, isDocumentElement=False, bidi=None, attributes=['href'], childNodes=[<TextNode(doc=<...>, parent=<...>, value=u'XML view metadata (http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/xml_iso19139?uuid=fr-120066022-jdd-451d1fe1-dc0c-4360-a6aa-52b470a457e2)') at remote 0x7fa0cc644dd0>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc6445a8>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644a28>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644e...(truncated), 
    v=<TextNode(doc=<Document(entities={}, documentElement=<Element(attribute_values={'class': 'markdown'}, nodeName='span', parent=<...>, doc=<...>, isDocumentElement=True, bidi=None, attributes=['class'], childNodes=[<TextNode(doc=<...>, parent=<...>, value='\n') at remote 0x7fa0cc644368>]) at remote 0x7fa0cc6441b8>, bidi='ltr') at remote 0x7fa0d56ace18>, parent=<Element(attribute_values={'href': u'http://www.aquitaine.developpement-durable.gouv.fr/tri-de-bergerac-a1678.html'}, nodeName='a', do---Type <return> to continue, or q <return> to quit---
c=<...>, isDocumentElement=False, bidi=None, attributes=['href'], childNodes=[<TextNode(doc=<...>, parent=<...>, value=u'XML view metadata (http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/xml_iso19139?uuid=fr-120066022-jdd-451d1fe1-dc0c-4360-a6aa-52b470a457e2)') at remote 0x7fa0cc644dd0>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc6445a8>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644a28>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644e...(truncated)) at /usr/src/debug/Python-2.7.5/Objects/object.c:900
#10 do_richcmp (op=2, 
    w=<TextNode(doc=<Document(entities={}, documentElement=<Element(attribute_values={'class': 'markdown'}, nodeName='span', parent=<...>, doc=<...>, isDocumentElement=True, bidi=None, attributes=['class'], childNodes=[<TextNode(doc=<...>, parent=<...>, value='\n') at remote 0x7fa0cc644368>]) at remote 0x7fa0cc6441b8>, bidi='ltr') at remote 0x7fa0d56ace18>, parent=<Element(attribute_values={'href': u'http://www.aquitaine.developpement-durable.gouv.fr/tri-de-bergerac-a1678.html'}, nodeName='a', doc=<...>, isDocumentElement=False, bidi=None, attributes=['href'], childNodes=[<TextNode(doc=<...>, parent=<...>, value=u'XML view metadata (http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/xml_iso19139?uuid=fr-120066022-jdd-451d1fe1-dc0c-4360-a6aa-52b470a457e2)') at remote 0x7fa0cc644dd0>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc6445a8>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644a28>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644e...(truncated), 
    v=<TextNode(doc=<Document(entities={}, documentElement=<Element(attribute_values={'class': 'markdown'}, nodeName='span', parent=<...>, doc=<...>, isDocumentElement=True, bidi=None, attributes=['class'], childNodes=[<TextNode(doc=<...>, parent=<...>, value='\n') at remote 0x7fa0cc644368>]) at remote 0x7fa0cc6441b8>, bidi='ltr') at remote 0x7fa0d56ace18>, parent=<Element(attribute_values={'href': u'http://www.aquitaine.developpement-durable.gouv.fr/tri-de-bergerac-a1678.html'}, nodeName='a', doc=<...>, isDocumentElement=False, bidi=None, attributes=['href'], childNodes=[<TextNode(doc=<...>, parent=<...>, value=u'XML view metadata (http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/xml_iso19139?uuid=fr-120066022-jdd-451d1fe1-dc0c-4360-a6aa-52b470a457e2)') at remote 0x7fa0cc644dd0>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc6445a8>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644a28>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644e...(truncated)) at /usr/src/debug/Python-2.7.5/Objects/object.c:935
#11 PyObject_RichCompare (
    v=<TextNode(doc=<Document(entities={}, documentElement=<Element(attribute_values={'class': 'markdown'}, nodeName='span', parent=<...>, doc=<...>, isDocumentElement=True, bidi=None, attributes=['class'], childNodes=[<TextNode(doc=<...>, parent=<...>, value='\n') at remote 0x7fa0cc644368>]) at remote 0x7fa0cc6441b8>, bidi='ltr') at remote 0x7fa0d56ace18>, parent=<Element(attribute_values={'href': u'http://www.aquitaine.developpement-durable.gouv.fr/tri-de-bergerac-a1678.html'}, nodeName='a', doc=<...>, isDocumentElement=False, bidi=None, attributes=['href'], childNodes=[<TextNode(doc=<...>, parent=<...>, value=u'XML view metadata (http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/xml_iso19139?uuid=fr-120066022-jdd-451d1fe1-dc0c-4360-a6aa-52b470a457e2)') at remote 0x7fa0cc644dd0>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc6445a8>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644a28>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644e...(truncated), 
    w=<TextNode(doc=<Document(entities={}, documentElement=<Element(attribute_values={'class': 'markdown'}, nodeName='span', parent=<...>, doc=<...>, isDocumentElement=True, bidi=None, attributes=['class'], childNodes=[<TextNode(doc=<...>, parent=<...>, value='\n') at remote 0x7fa0cc644368>]) at remote 0x7fa0cc6441b8>, bidi='ltr') at remote 0x7fa0d56ace18>, parent=<Element(attribute_values={'href': u'http://www.aquitaine.developpement-durable.gouv.fr/tri-de-bergerac-a1678.html'}, nodeName='a', doc=<...>, isDocumentElement=False, bidi=None, attributes=['href'], childNodes=[<TextNode(doc=<...>, parent=<...>, value=u'XML view metadata (http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/xml_iso19139?uuid=fr-120066022-jdd-451d1fe1-dc0c-4360-a6aa-52b470a457e2)') at remote 0x7fa0cc644dd0>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc6445a8>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644a28>, <TextNode(doc=<...>, parent=<...>, value=u'') at remote 0x7fa0cc644e...(truncated), op=2) at /usr/src/debug/Python-2.7.5/Objects/object.c:982
#12 0x00007fa0f87df21f in PyObject_RichCompareBool (v=<optimized out>, w=<optimized out>, op=op@entry=2) at /usr/src/debug/Python-2.7.5/Objects/object.c:1004
#13 0x00007fa0f87cb55c in listindex (self=0x7fa0d13fccf8, args=<optimized out>) at /usr/src/debug/Python-2.7.5/Objects/listobject.c:2306
#14 0x00007fa0f8838b74 in call_function (oparg=<optimized out>, pp_stack=0x7fa0f1da84e0) at /usr/src/debug/Python-2.7.5/Python/ceval.c:4098
#15 PyEval_EvalFrameEx (
    f=f@entry=Frame 0x7fa0b03232a0, for file /usr/lib/ckan/default/lib/python2.7/site-packages/webhelpers/markdown.py, line 1690, in _applyPattern (self=<Markdown(top_element=<Element(attribute_values={'class': 'markdown'}, nodeName='span', parent=<Document(entities={}, documentElement=<...>, bidi='ltr') at remote 0x7fa0d56ace18>, doc=<...>, isDocumentElement=True, bidi=None, attributes=['class'], childNodes=[<TextNode(doc=<...>, parent=<...>, value='\n') at remote 0x7fa0cc644368>]) at remote 0x7fa0cc6441b8>, doc=<...>, registeredExtensions=[], lines=[u'Tables of specific challenges corresponding to establishments and sensitive installations whose flooding may aggravate or complicate the management of crisis, produced for the purposes of reporting to the European Directive on inondations.la Directive 2007/60/EC of 23 October 2007 on L & # X 27; risk assessment and risk management d & # X 27; flooding (OJ L\xa0288, 06-11-2007, p.\xa027) influence the flood prevention strategy in Europe.  It requires the production of risk m...(truncated), throwflag=throwflag@entry=0) at /usr/src/debug/Python-2.7.5/Python/ceval.c:2740
```

cc @FabiApfelkern

**Comment by th0br0** [comment]
contacted PyPi package owners via email.

**Comment by amercader** [comment]
Thanks @th0br0, we'll discuss the best approach. Please submit security related issues to security@ckan.org

**Comment by th0br0** [comment]
Good to know. Maybe add the email to the readme? I was unable to find that email address anywhere

**Comment by davidread** [comment]
I've obscured this issue for obvious reasons. Please continue any discussion on security@ckan.org.
