### ISSUE TITLE
Patch Update causing issues with apache.wsgi

### ISSUE THREAD

**Issue by mcallisterg** [ckan/ckan#2822]
Attempted to install a patch update with git from version 2.2 to 2.2.3 but when I tried to access my datasets on a browser I was getting an Internal Server Error. After looking at the apache logs I found this: 

[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186] mod_wsgi (pid=5893): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186] mod_wsgi (pid=5893): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186] Traceback (most recent call last):
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/etc/ckan/default/apache.wsgi", line 9, in <module>
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     application = loadapp('config:%s' % config_filepath)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     return loadobj(APP, uri, name=name, *_kw)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     return context.create()
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     return self.object_type.invoke(self)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     return fix_call(context.object, context.global_conf, *_context.local_conf)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 59, in fix_call
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     reraise(_exc_info)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/compat.py", line 22, in reraise
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     exec('raise t, e, tb', dict(t=t, e=e, tb=tb))
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     val = callable(_args, *_kw)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/homeckan/lib/default/src/ckan/ckan/config/middleware.py", line 57, in make_app
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     load_environment(conf, app_conf)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/home/user/ckan/lib/default/src/ckan/ckan/config/environment.py", line 232, in load_environment
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     p.load_all(config)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/home/user/ckan/lib/default/src/ckan/ckan/plugins/core.py", line 134, in load_all
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     load(_plugins)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/home/user/ckan/lib/default/src/ckan/ckan/plugins/core.py", line 149, in load
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     service = _get_service(plugin)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/home/user/ckan/lib/default/src/ckan/ckan/plugins/core.py", line 255, in _get_service
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     return plugin.load()(name=plugin_name)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     return self.resolve()
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2386, in resolve
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     module = **import**(self.module_name, fromlist=['**name**'], level=0)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/home/user/ckan/lib/default/src/ckanext-edinburgh_api/ckanext/edinburgh_api/plugin.py", line 4, in <module>
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     from ckanext.stats.stats import Stats
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/home/user/ckan/lib/default/src/ckan/ckanext/stats/stats.py", line 13, in <module>
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     our_cache = cache.get_cache('stats', type='dbm')
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 137, in **getattr**
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     return getattr(self._current_obj(), attr)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186]     'thread' % self.____name__)
[Wed Jan 06 12:45:16 2016] [error] [client 54.206.15.186] TypeError: No object (name: cache) has been registered for this thread

Any ideas how to fix this?

**Comment by rossjones** [comment]
Did this work in 2.2 (before the upgrade)? Did you also set ```ckanext.stats.cache_enabled = true``` in config at the same time as you upgraded?

Just trying to get an idea if this is a new or old/undiscovered bug.

**Comment by mcallisterg** [comment]
Yes, this definitely worked before. The `production.ini` file I have been working on doesn't appear to contain that line, should I add it in?

**Comment by rossjones** [comment]
It used to default to 0, it is worth setting it to that as a short term measure to get it working until this bug is addressed.

**Comment by mcallisterg** [comment]
So should I have set this line before upgrading? Inserting `ckanext.stats.cache_enabled = 0` into the `production.ini` file and restarting apache2 resulted in the same error.

**Comment by rossjones** [comment]
Sounds like it might be a more serious problem then that'll need replicating.  Will likely get discussed in today's meeting.

**Comment by mcallisterg** [comment]
Thank you for your help. If you could keep me updated that would be great.

**Comment by mcallisterg** [comment]
Hi, has there been any update on this?

**Comment by rossjones** [comment]
Planning to take a look at this, this evening.  It's slow because I'll need to build a new VM. Sorry.

**Comment by mcallisterg** [comment]
Not to worry, thanks!

**Comment by rossjones** [comment]
I've just installed 2.2.3 on Ubuntu trusty, following the instructions at http://docs.ckan.org/en/ckan-2.2/contents.html, and unfortunately it is working for me with the stats cache both on and off.  

This suggests it is something about your setup.  Just to try and get more info:

1. Which Linux distro are you using?
2. Have you modified /etc/ckan/default/apache.wsgi at all?
3. Which package did you use to upgrade your 2.2 install to 2.2.3

**Comment by mcallisterg** [comment]
1. Ubuntu Precise is the distro in use
2. No, the apache.wsgi has not been edited.
The code reads as follows:
"import os
activate_this = os.path.join('/usr/lib/ckan/default/bin/activate_this.py')
execfile(activate_this, dict(__file__=activate_this))

from paste.deploy import loadapp
config_filepath = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'production.ini')
from paste.script.util.logging_config import fileConfig
fileConfig(config_filepath)
application = loadapp('config:%s' % config_filepath)"
3. The upgrade was a source install following the instructions at http://docs.ckan.org/en/ckan-2.2/upgrade-source.html . I checked out release 2.2.3.

**Comment by amercader** [comment]
Closing due to inactivity, please reopen if this is still an issue
