### ISSUE TITLE
Installation fails because of unfound package

### ISSUE THREAD

**Issue by Pin0** [ckan/ckan#2865]
I'm trying to install ckan on a debian virtual server. I installed all dependencies and start a python virtualenv as according to: http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html

After step 3.c (pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt)
at this point paster works in the virtualenv.
When I deactivate the virtualenv en activate it again (. /usr/lib/ckan/default/bin/activate)

paster stops working?

And I get the following error:

(default)developer@devel-nginx-php54:~$ paster
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 7, in <module>
    from paste.script.command import run
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 54, in <module>
    dist = pkg_resources.get_distribution('PasteScript')
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 330, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 209, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PasteScript

What Am I doing wrong here?

**Comment by Pin0** [comment]
Turns out I was a total noob with python virtualenv.

After 
```apt-get install python-dev python-pip python-virtualenv```
You have to update virtual env with 
```pip install -U vitrualenv```
And the inside the virtualenv (after you created it) you have to update pip (yes also if your global pip is up to date)
```pip install -U pip```

Now ckan works great on my debian virtual image
