### ISSUE TITLE
Paster start-up exception: KeyError pylons.h / get_validator not found in plugins toolkit

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2941]
I get this exception when starting CKAN on the command-line using paster. It occurs about 1 time in 3.

Discussed on IRC here: https://botbot.me/freenode/ckan/2016-02-26/?msg=60961376&page=1
@wardi said: "could be related to toolkit change I made recently"

### CKAN Version if known (or site URL)

Current master, at least since Feb 26 2016.

### Full exception
```
(ckan)vagrant@precise64:/vagrant/src/ckan$ paster serve --reload $CKAN_INI
Starting subprocess with file monitor
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/reloader.py", line 80, in periodic_reload
    if not self.check_reload():
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/reloader.py", line 100, in check_reload
    filename = module.__file__
  File "/vagrant/src/ckan/ckan/plugins/toolkit.py", line 393, in __getattr__
    self._initialize()
  File "/vagrant/src/ckan/ckan/plugins/toolkit.py", line 144, in _initialize
    t['h'] = getattr(pylons.config['pylons.h'], 'no_magic', None)
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/registry.py", line 146, in __getitem__
    return self._current_obj()[key]
KeyError: 'pylons.h'

Traceback (most recent call last):
  File "/home/vagrant/ckan/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/script/serve.py", line 329, in loadapp
    **kw)
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/vagrant/src/ckan/ckan/config/middleware.py", line 47, in make_app
    pylons_app = make_pylons_stack(conf, full_stack, static_files, **app_conf)
  File "/vagrant/src/ckan/ckan/config/middleware.py", line 79, in make_pylons_stack
    load_environment(conf, app_conf)
  File "/vagrant/src/ckan/ckan/config/environment.py", line 167, in load_environment
    p.load_all(config)
  File "/vagrant/src/ckan/ckan/plugins/core.py", line 134, in load_all
    load(*plugins)
  File "/vagrant/src/ckan/ckan/plugins/core.py", line 148, in load
    service = _get_service(plugin)
  File "/vagrant/src/ckan/ckan/plugins/core.py", line 250, in _get_service
    return plugin.load()(name=plugin_name)
  File "/home/vagrant/ckan/local/lib/python2.7/site-packages/pkg_resources.py", line 2013, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/vagrant/src/ckan/ckanext/reclineview/plugin.py", line 8, in <module>
    ignore_empty = p.toolkit.get_validator('ignore_empty')
  File "/vagrant/src/ckan/ckan/plugins/toolkit.py", line 399, in __getattr__
    raise AttributeError('`%s` not found in plugins toolkit' % name)
AttributeError: `get_validator` not found in plugins toolkit
```

**Comment by amercader** [comment]
I believe this was fixed by #2908
