### ISSUE TITLE
FATAL:  password authentication failed for user "ckan_default"

### ISSUE THREAD

**Issue by brylie** [ckan/ckan#3085]
### CKAN Version if known (or site URL)
CKAN 2.5

### Please describe the expected behaviour
When running the commmand `sudo ckan db init`,  the database should be successfully initialized.

### Please describe the actual behaviour
When running the command `sudo ckan db init` the following error occurs:

```
FATAL:  password authentication failed for user "ckan_default"
```

### What steps can be taken to reproduce the issue? 
I am following the [CKAN installation instructions](http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html).

**Comment by k-nut** [comment]
In your `production.ini`/`development.ini` did you put the password into the `sqlalchemy.url` line that you set up when creating the user? As described in [step 4 of the tutorial](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#create-a-ckan-config-file)

**Comment by brylie** [comment]
Ah, I am reading through the [installing CKAN from package](http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html) instructions. This is not a simple installation process, it seems.

**Comment by k-nut** [comment]
It is a little confusing that [step 2](http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html#install-postgresql-and-solr) in the `installing CKAN from package` documentation redirects to setting up postgres as described in the `installing CKAN from source` documentation. But when reading eveything very carefully you should end up with a working installation. 

I followed the tutorial this morning and it took about 45 minutes in total (I do have some more knowledge about how ckan works though...)

**Comment by brylie** [comment]
OK, thanks @k-nut. 

I am trying to read the [Installing CKAN from package](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html) instructions carefully, but there seems to be some missing steps in that document. E.g. there does not seem to be any mention of following [step 2](http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html#install-postgresql-and-solr) of the [installing CKAN from source](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html) document when reading through the *installing CKAN from package*. Correct me if I am wrong, but I simply do not see any reference.

**Comment by amercader** [comment]
@brylie See https://github.com/ckan/ckan/issues/3086#issuecomment-223541300 

Closing for now.

**Comment by tubulabi** [comment]
Hiii, Everyone ..
Can anyone help me? As I am getting the same error after changing the password in sqlalchemy.url in production.ini or development.ini.

FATAL:  password authentication failed for user "ckan_default"

**Comment by jorgejeferson** [comment]
I also went through this problem, the documentation does not speak, however we should change the line: `sqlalchemy.url = postgresql://ckan_default:pass@localhost/ckan_default` and put the user and password created for the postgress

**Comment by ibaidaTaha** [comment]
have you found a soultion for this error?, since i am facing it.

**Comment by desaija-lilly** [comment]
I'm trying this on RHEL7 with CKAN 2.8.1, Apache Solr 7.4 and PostGres 9.2.  I have tried the correct username and password for CKAN, but i'm getting the same error. I blew away Postgres and set it up twice more to make sure I didn't do anything wrong, but I'm getting the same issue.

**Comment by ajveldhi** [comment]
replacing pass worked for me ..thanks ..!!

**Comment by Preeti86** [comment]
Replacing pass doesnt work for me... Can you please help?

**Comment by davidshumway** [comment]
> I also went through this problem, the documentation does not speak, however we should change the line: `sqlalchemy.url = postgresql://ckan_default:pass@localhost/ckan_default` and put the user and password created for the postgress

Also the password cannot have certain characters in it. For example, including a "/" in the password causes the following fatal error:

```
ubuntu@ckan-instance:~$ sudo ckan db init
2020-10-28 16:06:17,759 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2020-10-28 16:06:17,760 INFO  [ckan.config.environment] Loading static files from public
2020-10-28 16:06:17,815 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2020-10-28 16:06:18,160 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2020-10-28 16:06:18,242 CRITI [ckan.lib.uploader] Please specify a ckan.storage_path in your config
                         for your uploads
2020-10-28 16:06:18,494 INFO  [ckan.cli.db] Initialize the Database
invalid interpolation syntax in 'postgresql://ckan_default:6b%2FU@localhost/ckan_default' at position 59
```

**Comment by ceroego** [comment]
> I also went through this problem, the documentation does not speak, however we should change the line: `sqlalchemy.url = postgresql://ckan_default:pass@localhost/ckan_default` and put the user and password created for the postgress

Can you please be specific about the change syntax? It is for a rookie!
Thanks!

**Comment by mgifford** [comment]
Change the password in `sqlalchemy.url = postgresql://ckan_default:pass@localhost/ckan_default` within the `/etc/ckan/default/ckan.ini` file and you should be able to initiate the database. Least it worked for me.

This needs to be added to the docs!

Also, at least in Linux:
`sudo systemctl restart postgresql
`

**Comment by ChristianF88** [comment]
I am running a source installation. During the installation I am already changing the password. I never use the default password "pass". (The new password only consists of letters, underscores and numbers)
This works:
- frontend
- log into postgres via psql
- creating an engine with the sqlalchemy url string specified in the ckan.ini (and using it)

But if I run `pytest` to test the extensions I am developing (CKAN_INI is set to the test.ini of that extension):

```sh
(default) root@ckan:/usr/lib/ckan/default/src/ckanext-eaw_helpers2# pytest
2023-02-13 14:22:47,012 INFO  [ckan.cli] Using configuration file /usr/lib/ckan/default/src/ckanext-eaw_helpers2/test.ini
2023-02-13 14:22:47,013 INFO  [ckan.config.environment] Loading static files from public
2023-02-13 14:22:47,297 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
INTERNALERROR>     return fn()
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 363, in connect
INTERNALERROR>     return _ConnectionFairy._checkout(self)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
INTERNALERROR>     fairy = _ConnectionRecord.checkout(pool)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
INTERNALERROR>     rec = pool._do_get()
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
INTERNALERROR>     self._dec_overflow()
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
INTERNALERROR>     compat.reraise(exc_type, exc_value, exc_tb)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 154, in reraise
INTERNALERROR>     raise value
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
INTERNALERROR>     return self._create_connection()
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
INTERNALERROR>     return _ConnectionRecord(self)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
INTERNALERROR>     self.__connect(first_connect_check=True)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
INTERNALERROR>     connection = pool._invoke_creator(self)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
INTERNALERROR>     return dialect.connect(*cargs, **cparams)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 451, in connect
INTERNALERROR>     return self.dbapi.connect(*cargs, **cparams)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
INTERNALERROR>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
INTERNALERROR> psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "ckan_default"
INTERNALERROR> connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "ckan_default"
INTERNALERROR> 
INTERNALERROR> 
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/_pytest/main.py", line 204, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/tests/pytest_ckan/ckan_setup.py", line 43, in pytest_sessionstart
INTERNALERROR>     app = make_app(conf)
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
INTERNALERROR>     load_environment(conf)
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 123, in load_environment
INTERNALERROR>     p.load_all()
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 161, in load_all
INTERNALERROR>     unload_all()
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 208, in unload_all
INTERNALERROR>     unload(*reversed(_PLUGINS))
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 236, in unload
INTERNALERROR>     plugins_update()
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 153, in plugins_update
INTERNALERROR>     environment.update_config()
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 306, in update_config
INTERNALERROR>     model.init_model(engine)
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/model/__init__.py", line 152, in init_model
INTERNALERROR>     Table('alembic_version', meta.metadata, autoload=True)
INTERNALERROR>   File "<string>", line 2, in __new__
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 130, in warned
INTERNALERROR>     return fn(*args, **kwargs)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 496, in __new__
INTERNALERROR>     metadata._remove_table(name, schema)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
INTERNALERROR>     compat.reraise(exc_type, exc_value, exc_tb)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 154, in reraise
INTERNALERROR>     raise value
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 491, in __new__
INTERNALERROR>     table._init(name, metadata, *args, **kw)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 580, in _init
INTERNALERROR>     self._autoload(
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 620, in _autoload
INTERNALERROR>     bind.run_callable(
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2146, in run_callable
INTERNALERROR>     with self._contextual_connect() as conn:
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2226, in _contextual_connect
INTERNALERROR>     self._wrap_pool_connect(self.pool.connect, None),
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2265, in _wrap_pool_connect
INTERNALERROR>     Connection._handle_dbapi_exception_noconnection(
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1536, in _handle_dbapi_exception_noconnection
INTERNALERROR>     util.raise_from_cause(sqlalchemy_exception, exc_info)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
INTERNALERROR>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
INTERNALERROR>     raise value.with_traceback(tb)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
INTERNALERROR>     return fn()
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 363, in connect
INTERNALERROR>     return _ConnectionFairy._checkout(self)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
INTERNALERROR>     fairy = _ConnectionRecord.checkout(pool)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
INTERNALERROR>     rec = pool._do_get()
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
INTERNALERROR>     self._dec_overflow()
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
INTERNALERROR>     compat.reraise(exc_type, exc_value, exc_tb)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 154, in reraise
INTERNALERROR>     raise value
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
INTERNALERROR>     return self._create_connection()
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
INTERNALERROR>     return _ConnectionRecord(self)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
INTERNALERROR>     self.__connect(first_connect_check=True)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
INTERNALERROR>     connection = pool._invoke_creator(self)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
INTERNALERROR>     return dialect.connect(*cargs, **cparams)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 451, in connect
INTERNALERROR>     return self.dbapi.connect(*cargs, **cparams)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
INTERNALERROR>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
INTERNALERROR> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "ckan_default"
INTERNALERROR> connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "ckan_default"
INTERNALERROR> 
INTERNALERROR> (Background on this error at: http://sqlalche.me/e/e3q8)
```

Any ideas?

**Comment by ChristianF88** [comment]
**Workaround:**

Copy the sqlalchemy.url into the test.ini.

**Comment by virgiawankusuma** [comment]
> I also went through this problem, the documentation does not speak, however we should change the line: `sqlalchemy.url = postgresql://ckan_default:pass@localhost/ckan_default` and put the user and password created for the postgress

Thank you
