### ISSUE TITLE
500 Internal Server Error on fresh Docker image

### ISSUE THREAD

**Issue by dario-chiappetta** [ckan/ckan#3130]
I am running the ckan 2.6.0a **docker** image, following the instructions at http://docs.ckan.org/en/ckan-1.3.3/maintaining/installing/install-using-docker.html. The container runs, but I get a **500** Internal Server Error when I access the website.

Here the logs: 

```
root@28b3b01b9e12:/# cat /var/log/apache2/*
127.0.0.1 - - [21/Jun/2016:10:43:00 +0000] "GET / HTTP/1.0" 500 796 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"
[Tue Jun 21 10:43:01.343380 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886] mod_wsgi (pid=70): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Tue Jun 21 10:43:01.343406 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886] mod_wsgi (pid=70): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Tue Jun 21 10:43:01.343420 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886] Traceback (most recent call last):
[Tue Jun 21 10:43:01.343430 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]   File "/etc/ckan/default/apache.wsgi", line 10, in <module>
[Tue Jun 21 10:43:01.343448 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     application = loadapp('config:%s' % config_filepath)
[Tue Jun 21 10:43:01.343453 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Tue Jun 21 10:43:01.343465 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     return loadobj(APP, uri, name=name, **kw)
[Tue Jun 21 10:43:01.343470 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Tue Jun 21 10:43:01.343478 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     return context.create()
[Tue Jun 21 10:43:01.343482 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Tue Jun 21 10:43:01.343490 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     return self.object_type.invoke(self)
[Tue Jun 21 10:43:01.343494 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Tue Jun 21 10:43:01.343502 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Tue Jun 21 10:43:01.343506 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
[Tue Jun 21 10:43:01.343514 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     val = callable(*args, **kw)
[Tue Jun 21 10:43:01.343519 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 49, in make_app
[Tue Jun 21 10:43:01.343528 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     pylons_app = make_pylons_stack(conf, full_stack, static_files, **app_conf)
[Tue Jun 21 10:43:01.343533 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 145, in make_pylons_stack
[Tue Jun 21 10:43:01.343540 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     who_parser.parse(open(app_conf['who.config_file']))
[Tue Jun 21 10:43:01.343544 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/config.py", line 86, in parse
[Tue Jun 21 10:43:01.343672 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     obj = self._makePlugin(name, IPlugin, options)
[Tue Jun 21 10:43:01.343679 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/config.py", line 40, in _makePlugin
[Tue Jun 21 10:43:01.343689 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     obj = _resolve(name)
[Tue Jun 21 10:43:01.343694 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/config.py", line 23, in _resolve
[Tue Jun 21 10:43:01.343706 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     return EntryPoint.parse('x=%s' % name).resolve()
[Tue Jun 21 10:43:01.343716 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886] AttributeError: 'EntryPoint' object has no attribute 'resolve'
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
[Tue Jun 21 10:41:36.717136 2016] [mpm_event:notice] [pid 36:tid 140219372595072] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Tue Jun 21 10:41:36.717176 2016] [core:notice] [pid 36:tid 140219372595072] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
root@28b3b01b9e12:/# 
```

**Comment by deinok** [comment]
Can you give us more information?
Your docker version, commands run, etc...
I will try to reproduce the error

**Comment by dario-chiappetta** [comment]
Sure, I am running Docker version 1.11.2, build b9f10c9, on Ubuntu 15.10, kernel 4.4.2 64bit.

I run the commands as they are written in the docs:

```
$ docker run -d --name db ckan/postgresql
$ docker run -d --name solr ckan/solr
$ docker run -d -p 80:80 --link db:db --link solr:solr ckan/ckan
```

All the images are pulled with no errors from the Hub, and they all run:

```
dario@santech:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
00f0d293af0a        ckan/ckan           "/sbin/my_init"          15 minutes ago      Up 15 minutes       0.0.0.0:80->80/tcp   sleepy_bohr
4c564b45baa7        ckan/solr           "docker-entrypoint.sh"   About an hour ago   Up About an hour    8983/tcp             solr
10284d0e5b2e        ckan/postgresql     "/docker-entrypoint.s"   About an hour ago   Up About an hour    5432/tcp             db
dario@santech:~$ docker logs 00f0d293af0a
*** Running /etc/my_init.d/50_configure...
Distribution already installed:
  ckan 2.6.0a from /usr/lib/ckan/default/src/ckan
Creating /etc/ckan/default/ckan.ini
Now you should edit the config files
  /etc/ckan/default/ckan.ini
Edited option sqlalchemy.url = "postgresql://ckan_default:pass@localhost/ckan_default"->"postgresql://ckan:ckan@172.17.0.2:5432/ckan" (section "app:main")
Edited option ckan.site_url = ""->"http://192.168.0.6" (section "app:main")
Option uncommented and set solr_url = "http://172.17.0.3:8983/solr/ckan" (section "app:main")
Option uncommented and set ckan.storage_path = "/var/lib/ckan" (section "app:main")
Option uncommented and set email_to = "disabled@example.com" (section "app:main")
Option uncommented and set error_email_from = "ckan@00f0d293af0a" (section "app:main")
*** Running /etc/my_init.d/70_initdb...
Initialising DB: SUCCESS
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 29
 * Starting Postfix Mail Transport Agent postfix
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
   ...done.
Jun 21 10:41:36 00f0d293af0a postfix/master[198]: daemon started -- version 2.11.0, configuration /etc/postfix
dario@santech:~$
```
I'll be happy to provide any other info you need

**Comment by amercader** [comment]
Whenever I've found this problem (not in the context of Docker) it was caused by an old version of setuptols:
```
[Tue Jun 21 10:43:01.343706 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886]     return EntryPoint.parse('x=%s' % name).resolve()
[Tue Jun 21 10:43:01.343716 2016] [:error] [pid 70:tid 140219206596352] [client 127.0.0.1:46886] AttributeError: 'EntryPoint' object has no attribute 'resolve'
```

Upgrading it should solve the issue.

BTW these Docker docs are outdated and were actually removed from master in https://github.com/ckan/ckan/pull/2821 (you probably found them via google). @deinok now that the Docker images are working again should we reenable them?

**Comment by deinok** [comment]
I think we can wait for documentation, i will PR a new image this weekend based on httpd oficial image.
The documentation is okey with the actual image published.

I will rewrite it with the PR, adding docker-compose support

**Comment by dario-chiappetta** [comment]
I indeed found the docs via Google and didn't realize they were outdated: sorry. Many thanks if you are going to fix this anyway. As a side note, **setuptools** is already at the latest version in the image:

```
root@5cc8ca04a43b:~# python
[...]
>>> import pkg_resources
>>> r = pkg_resources.require(["setuptools"])[0]
>>> print(r.version)                            
23.0.0
```

**Comment by yrchen** [comment]
@dario-chiappetta Try the following commands to reinstall the requirements packages.

- source /usr/lib/ckan/default/bin/activate
- pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt
- service apache reload

**Comment by amercader** [comment]
@dario-chiappetta this might be the system wide version of setuptools. As @yrchen suggests CKAN runs on a virtualenv, which might have an older setuptools version.

**Comment by dario-chiappetta** [comment]
@yrchen @amercader It worked, thank you! Just a minor amendment for future reference: you'll need to set the `--upgrade` flag on the `pip install` command, or it will skip through the packages that are already installed:

- pip install --upgrade -r /usr/lib/ckan/default/src/ckan/requirements.txt

**Comment by florianm** [comment]
I ran into the same error and Google sent me here.

Setup:

* AWS EC2 t2.medium Ubuntu 14.04 LTS
* datacats Docker setup as documented [here](http://datawagovau.readthedocs.io/en/latest/)
* latest datacats docker images (`datacats pull -a`)
* latest CKAN master (inside the datacats environment > `cd ckan && git pull`)
* datacats install (runs `pip install -r ...` for each requirements.txt of ckan and ckan plugins)
* reloading the environment with `datacats reload -p` leads to:
```
mod_wsgi (pid=10): Target WSGI script '/etc/ckan/apache.wsgi' cannot be loaded as Python module
[....]
File "/usr/lib/ckan/lib/python2.7/site-packages/repoze/who/config.py", line 23, in _resolve
return EntryPoint.parse('x=%s' % name).resolve()
AttributeError: 'EntryPoint' object has no attribute 'resolve'
```
Problem: An outdated version of setuptools is used. There are three installation locations for setuptools in my case: the system-wide python lib, the virtualenv lib created and used by datacats, and inside the Docker container (spoiler: that was the one)

Solution:

* open shell into datacats environment: `datacats shell`
* `pip install --upgrade -r ckan/requirements.txt`
* `pip install polib`
* `exit` to leave the Docker shell
* migrate the database: `datacats paster db upgrade`

A point of confusion for me was that although I ran `pip install --upgrade -r ckan/requirements.txt` (with datacats' virtualenv activated), I had to open the datacats shell into the Docker image to upgrade the requirements there.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
