### ISSUE TITLE
'thread._local' object has no attribute 'host' when package_show called from celery task

### ISSUE THREAD

**Issue by martinburchell** [ckan/ckan#3145]
### CKAN Version if known (or site URL)

2.5.2
### Please describe the expected behaviour

No error
### Please describe the actual behaviour

```
[2016-06-30 12:24:29,208: ERROR/MainProcess] Task syndicate.sync_package[8f6ade24-5fe3-4a50-8d9a-f00b773dc0ad-fff7d2da-695b-4e5b-9296-0ef2bc5210d0] raised unexpected: AttributeError("'thread._local' object has no attribute 'host'",)
Traceback (most recent call last):
  File "/home/martinb/workspace/ckan/lib/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/martinb/workspace/ckan/lib/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/martinb/workspace/ckan/lib/default/src/ckanext-syndicate/ckanext/syndicate/tasks.py", line 26, in sync_package_task
    return sync_package(package, action)
  File "/home/martinb/workspace/ckan/lib/default/src/ckanext-syndicate/ckanext/syndicate/tasks.py", line 101, in sync_package
    params,
  File "/home/martinb/workspace/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 416, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/martinb/workspace/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 532, in wrapper
    return action(context, data_dict)
  File "/home/martinb/workspace/ckan/lib/default/src/ckanext-datasetversions/ckanext/datasetversions/logic/action/get.py", line 19, in package_show
    requested_dataset = ckan_package_show(context, data_dict)
  File "/home/martinb/workspace/ckan/lib/default/src/ckan/ckan/logic/action/get.py", line 1066, in package_show
    package_dict = model_dictize.package_dictize(pkg, context)
  File "/home/martinb/workspace/ckan/lib/default/src/ckan/ckan/lib/dictization/model_dictize.py", line 265, in package_dictize
    with_package_counts=False)
  File "/home/martinb/workspace/ckan/lib/default/src/ckan/ckan/lib/dictization/model_dictize.py", line 57, in group_list_dictize
    for group in obj_list]
  File "/home/martinb/workspace/ckan/lib/default/src/ckan/ckan/lib/dictization/model_dictize.py", line 470, in group_dictize
    qualified=True
  File "/home/martinb/workspace/ckan/lib/default/src/ckan/ckan/lib/helpers.py", line 214, in url_for_static
    return url_for_static_or_external(*args, **kw)
  File "/home/martinb/workspace/ckan/lib/default/src/ckan/ckan/lib/helpers.py", line 233, in url_for_static_or_external
    my_url = _routes_default_url_for(*args, **kw)
  File "/home/martinb/workspace/ckan/lib/default/local/lib/python2.7/site-packages/routes/util.py", line 257, in url_for
    host = config.host
  File "/home/martinb/workspace/ckan/lib/default/local/lib/python2.7/site-packages/routes/__init__.py", line 14, in __getattr__
    return getattr(self.__shared_state, name)
AttributeError: 'thread._local' object has no attribute 'host'
```
### What steps can be taken to reproduce the issue?

A bit tricky as I'm using a bunch of custom plugins, but I don't think it is the plugins themselves that are at fault (this was also reported with ckanext-archiver https://lists.okfn.org/pipermail/ckan-dev/2015-December/009543.html)

I think what it boils down to is having a celery task call package_show on a dataset that is in a group that has a static image_url

I've worked around the problem by setting the host and protocol explicitly in the call to url_for_static in group_dictize https://github.com/aptivate/ckan/commit/45d8387a64850f30d5777b2457b483eb1376bd45

**Comment by wardi** [comment]
These haven't been backported to 2.5 and might help https://github.com/ckan/ckan/pull/2998#issuecomment-224615278

**Comment by mkuder** [comment]
If anyone gets stuck with the same problem and does not want to modify the core ckan code ... I had a similar problem using an older version of CKAN (2.2.3, data.gov.uk). 

The celery task needs to load a proper config with set host parameters. For paster commands this is taken care of in the [_load_config method of CkanCommand](https://github.com/ckan/ckan/blob/master/ckan/lib/cli.py#L169). For celery tasks however, they need to load the config on their own. I fixed the problem when using ckanext-qa by adding the following lines to its load_config function in [tasks.py](https://github.com/ckan/ckanext-qa/blob/master/ckanext/qa/tasks.py):

```
    ## give routes enough information to run url_for
    parsed = urlparse.urlparse(conf.get('ckan.site_url', 'http://0.0.0.0'))
    request_config = routes.request_config()
    request_config.host = parsed.netloc + parsed.path
    request_config.protocol = parsed.scheme
```

They may be unnecessary on a more recent version of CKAN, but maybe this helps someone.

**Comment by martinburchell** [comment]
Thanks @mkuder - I'll make a note to try this

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
