### ISSUE TITLE
ckan.simple_search setting being ignored

### ISSUE THREAD

**Issue by Kyle-Falconer** [ckan/ckan#3204]
### CKAN Version if known (or site URL)
2.5.2

### Please describe the expected behaviour
When `ckan.simple_search` is set to `true` or `1`, CKAN should start up without complaining about a lost connection to SOLR.

### Please describe the actual behaviour

CKAN logs errors regarding being unable to connect to the SOLR server:

```
2016-08-17 19:01:43,150 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
2016-08-17 19:01:43,447 ERROR [ckan.lib.search.common] [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/common.py", line 51, in is_available
    conn.query("*:*", rows=1)
  File "/usr/local/lib/python2.7/dist-packages/solr/core.py", line 703, in query
    return self.select(*args, **params)
  File "/usr/local/lib/python2.7/dist-packages/solr/core.py", line 798, in __call__
    xml = self.raw(**params)
  File "/usr/local/lib/python2.7/dist-packages/solr/core.py", line 823, in raw
    rsp = conn._post(self.selector, request, conn.form_headers)
  File "/usr/local/lib/python2.7/dist-packages/solr/core.py", line 646, in _post
    self._reconnect()
  File "/usr/local/lib/python2.7/dist-packages/solr/core.py", line 625, in _reconnect
    self.conn.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2016-08-17 19:01:43,448 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server

```
### What steps can be taken to reproduce the issue? 

Consult [the documentation](http://docs.ckan.org/en/latest/maintaining/configuration.html) regarding the `ckan.simple_search` option:

> ckan.simple_search
> Example:
> 
> ckan.simple_search = true
> Default value: false
> 
> Switching this on tells CKAN search functionality to just query the database, (rather than using Solr). In this setup, search is crude and limited, e.g. no full-text search, no faceting, etc. However, this might be very useful for getting up and running quickly with CKAN.

Set the `ckan.simple_search` option to true in the configuration ini file, and comment out the `solr`url` setting, then restart CKAN and observe the logged output.

**Comment by amercader** [comment]
You are right, this is not supported any more and should be removed from the docs. PR is #3210 

Postgres search should be properly implemented in https://github.com/ckan/ckan/pull/3118
