### ISSUE TITLE
ImportError: 'module' object has no attribute 'ckan_auth_tkt_make_app' error

### ISSUE THREAD

**Issue by yagi815** [ckan/ckan#3250]
### CKAN Version if known (or site URL)

latest version 
### Please describe the actual behaviour

when I start ckan (paster serve XXX.ini)

I got this errors

```
Traceback (most recent call last):
  File "/usr/lib/ckan/france/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/paste/script/serve.py", line 329, in loadapp
    *_kw)
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, *_kw)
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, *_context.local_conf)
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(_args, *_kw)
  File "/usr/lib/ckan/france/src/ckan/ckan/config/middleware/**init**.py", line 48, in make_app
    *_app_conf)
  File "/usr/lib/ckan/france/src/ckan/ckan/config/middleware/pylons_app.py", line 113, in make_pylons_stack
    who_parser.parse(open(app_conf['who.config_file']))
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/repoze/who/config.py", line 86, in parse
    obj = self._makePlugin(name, IPlugin, options)
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/repoze/who/config.py", line 40, in _makePlugin
    obj = _resolve(name)
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/repoze/who/config.py", line 23, in _resolve
    return EntryPoint.parse('x=%s' % name).resolve()
  File "/usr/lib/ckan/france/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2268, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'ckan_auth_tkt_make_app'
```

**Comment by wildcatzita** [comment]
@yagi815  did you try this [solution](http://docs.ckan.org/en/latest/changelog.html#troubleshooting)?

**Comment by TkTech** [comment]
Solution is as described in the FAQ (thanks @wildcatzita). This is a problem for people upgrading from old versions of CKAN.

**Comment by maxclac** [comment]
Hi! I am running into the same problem and the solution provided by @wildcatzita does not help. Also, I did not find a solution in any FAQ I could find. How can I further troubleshoot this?
Thanks!
