### ISSUE TITLE
Redis is not available

### ISSUE THREAD

**Issue by markdturner** [ckan/ckan#3253]
### CKAN Version if known (or site URL)
CKAN 2.7.0a

### Please describe the expected behaviour
I'm trying to run CKAN in docker containers, which doesn't seem to work with the latest version of CKAN though I have had it working on 2.6. Annoyingly there are no Dockerhub tags other than latest, so I can't go back to 2.6

### Please describe the actual behaviour
Running the CKAN container fails due to not being able to connect to Redis. Full stack trace is below.

```
*** Running /etc/my_init.d/70_initdb...
2016-09-21 13:33:34,188 ERROR [ckan.lib.redis] Redis is not available
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/redis.py", line 61, in is_redis_available
    return redis_conn.ping()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/redis/client.py", line 682, in ping
    return self.execute_command('PING')
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
2016-09-21 13:33:34,189 CRITI [ckan.config.environment] Could not connect to Redis.
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 230, in command
    self._load_config(cmd!='upgrade')
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 174, in _load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 102, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 129, in load_all
    unload_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 182, in unload_all
    unload(*reversed(_PLUGINS))
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 210, in unload
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 121, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 196, in update_config
    search.check_solr_schema_version()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 306, in check_solr_schema_version
    % (version, ', '.join(SUPPORTED_SCHEMA_VERSIONS)))
ckan.lib.search.common.SearchError: SOLR schema version not supported: 2.3. Supported versions are [2.7]
*** /etc/my_init.d/70_initdb failed with status 1

*** Killing all processes...

```
### What steps can be taken to reproduce the issue? 
Running the following commands to bring up the containers reproduces the issue, assuming you don't have cached local images of older versions of the CKAN docker images.

```
$ docker run -d --name db ckan/postgresql
$ docker run -d --name solr ckan/solr
$ docker run -d -p 80:80 --link db:db --link solr:solr ckan/ckan
```

**Comment by torfsen** [comment]
Redis will be a mandatory requirement from CKAN 2.7 on, but you can still run without it. You will receive the warning you quoted and some things won't work (currently that's only the background jobs), but that's it.

Your problem is actually the new Solr schema introduced with CKAN 2.7, see the end of your error messages:
```
ckan.lib.search.common.SearchError: SOLR schema version not supported: 2.3. Supported versions are [2.7]
```
This is indeed a hard error during startup and that's why your setup doesn't work. You will need to update your Solr schema using the one from [`ckan/config/solr/schema.xml`](https://github.com/ckan/ckan/blob/master/ckan/config/solr/schema.xml). See the [relevant section in the installation instructions](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#setup-solr).

**Comment by markdturner** [comment]
Ah ok! It did have the feel of an underlying error, just didn't spot it. So if I wanted to update the schema in the context of docker, would I do that in the solr dockerfile? I can't see in the [Dockerfile](https://hub.docker.com/r/ckan/solr/~/dockerfile/) where it copies across config files

**Comment by markdturner** [comment]
I fixed my issue by coping the repo at https://github.com/ckan/ckan/tree/master/contrib/docker/solr and changing line 16 from

```
https://raw.githubusercontent.com/ckan/ckan/ckan-2.5.2/ckan/config/solr/schema.xml
```

to

```
https://raw.githubusercontent.com/ckan/ckan/master/ckan/config/solr/schema.xml
```
