### ISSUE TITLE
Warning while initializing DB 

### ISSUE THREAD

**Issue by hurcy** [ckan/ckan#3274]
### CKAN Version if known (or site URL)
I installed CKAN 2.5.2, Postgresql, Solr on single machine of Ubuntu 16.04.

### Please describe the expected behaviour
Should successfully install DB.

### Please describe the actual behaviour
Some warning messages came up.

### What steps can be taken to reproduce the issue? 
I followed the installation guide from source.
http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html

I think the message caused by pip version.
In the /usr/lib/ckan/default/src/ckan/requirement.txt, pip and setuptools are commented out, so setuptools (28.3.0), pip (8.1.2) are installed in my environment. 
I wonder it is okey.

Log1) warning message
```

(default) notebook:/usr/lib/ckan/default/src/ckan$ paster db init -c /etc/ckan/default/development.ini
/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/configuration.py:26: RuntimeWarning: Unable to load template engine entry point: 'pylonsmyghty = pylons.templating:MyghtyTemplatePlugin [myghty]': Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/templating.py", line 610, in <module>
    Engine = entry_point.load()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 808, in resolve
    if not req_extras.markers_pass(req):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 993, in markers_pass
    return not req.marker or any(extra_evals) or req.marker.evaluate()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.

  import pylons.templating
/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/configuration.py:26: RuntimeWarning: Unable to load template engine entry point: 'genshi-markup = genshi.template.plugin:MarkupTemplateEnginePlugin [plugin]': Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/templating.py", line 610, in <module>
    Engine = entry_point.load()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 808, in resolve
    if not req_extras.markers_pass(req):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 993, in markers_pass
    return not req.marker or any(extra_evals) or req.marker.evaluate()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.

  import pylons.templating
/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/configuration.py:26: RuntimeWarning: Unable to load template engine entry point: 'genshi-text = genshi.template.plugin:TextTemplateEnginePlugin [plugin]': Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/templating.py", line 610, in <module>
    Engine = entry_point.load()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 808, in resolve
    if not req_extras.markers_pass(req):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 993, in markers_pass
    return not req.marker or any(extra_evals) or req.marker.evaluate()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.

  import pylons.templating
/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/configuration.py:26: RuntimeWarning: Unable to load template engine entry point: 'genshi = genshi.template.plugin:MarkupTemplateEnginePlugin [plugin]': Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/templating.py", line 610, in <module>
    Engine = entry_point.load()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 808, in resolve
    if not req_extras.markers_pass(req):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 993, in markers_pass
    return not req.marker or any(extra_evals) or req.marker.evaluate()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
**UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.**

  import pylons.templating
Initialising DB: SUCCESS

```

Log2) pip list in my environment
```
$ pip list
Babel (0.9.6)
Beaker (1.7.0)
bleach (1.4.3)
ckan (2.5.2, /home/cy/ckan/lib/default/src/ckan)
decorator (4.0.4)
fanstatic (0.12)
FormEncode (1.3.0)
Genshi (0.6)
html5lib (0.9999999)
Jinja2 (2.6)
Mako (1.0.2)
Markdown (2.4)
MarkupSafe (0.23)
nose (1.3.7)
ofs (0.4.1)
ordereddict (1.1)
Pairtree (0.7.1-T)
passlib (1.6.2)
Paste (1.7.5.1)
PasteDeploy (1.5.2)
PasteScript (2.0.2)
pbr (0.11.0)
pip (8.1.2)
pkg-resources (0.0.0)
psycopg2 (2.4.5)
Pygments (2.0.2)
Pylons (0.9.7)
python-dateutil (1.5)
pytz (2012j)
pyutilib.component.core (4.5.3)
repoze.lru (0.6)
repoze.who (2.0)
repoze.who-friendlyform (1.0.8)
requests (2.7.0)
Routes (1.13)
setuptools (28.3.0)
simplejson (3.3.1)
six (1.10.0)
solrpy (0.9.5)
SQLAlchemy (0.9.6)
sqlalchemy-migrate (0.9.1)
sqlparse (0.1.11)
Tempita (0.5.2)
tzlocal (1.2)
unicodecsv (0.14.1)
vdm (0.13)
webencodings (0.5)
WebError (0.11)
WebHelpers (1.3)
WebOb (1.0.8)
WebTest (1.4.3)
wheel (0.30.0a0)
zope.interface (4.1.1)

```

**Comment by yecarrillo** [comment]
Same error here. This is my env:

pip list
Babel (0.9.6)
Beaker (1.7.0)
bleach (1.4.3)
ckan (2.5.3b0, /usr/lib/ckan/datos/src/ckan)
decorator (4.0.4)
fanstatic (0.12)
FormEncode (1.3.0)
Genshi (0.6)
html5lib (0.9999999)
Jinja2 (2.6)
Mako (1.0.2)
Markdown (2.4)
MarkupSafe (0.23)
nose (1.3.7)
ofs (0.4.1)
ordereddict (1.1)
Pairtree (0.7.1-T)
passlib (1.6.2)
Paste (1.7.5.1)
PasteDeploy (1.5.2)
PasteScript (2.0.2)
pbr (0.11.0)
pip (8.1.2)
pkg-resources (0.0.0)
psycopg2 (2.4.5)
Pygments (2.0.2)
Pylons (0.9.7)
python-dateutil (1.5)
pytz (2012j)
pyutilib.component.core (4.5.3)
repoze.lru (0.6)
repoze.who (2.0)
repoze.who-friendlyform (1.0.8)
requests (2.7.0)
Routes (1.13)
setuptools (28.6.1)
simplejson (3.3.1)
six (1.10.0)
solrpy (0.9.5)
SQLAlchemy (0.9.6)
sqlalchemy-migrate (0.9.1)
sqlparse (0.1.11)
Tempita (0.5.2)
tzlocal (1.2)
unicodecsv (0.14.1)
vdm (0.13)
WebError (0.11)
WebHelpers (1.3)
WebOb (1.0.8)
WebTest (1.4.3)
wheel (0.30.0a0)
zope.interface (4.1.1)

**Comment by amercader** [comment]
This looks like a setuptools issue: https://github.com/pypa/setuptools/issues/523
Can you try any of the hints mentioned there?

Please reopen if you think something needs to be done on the CKAN side

**Comment by rwillmer** [comment]
I have this problem building 2.6.0 on ubuntu:xenial. I've given them a reproducible docker version of the problem in a comment at https://github.com/pypa/setuptools/issues/523

**Comment by rwillmer** [comment]
And I've added a workaround in my comments in https://github.com/pypa/setuptools/issues/523; basically by downgrading setuptools and then upgrading to the version I started with, the problem went away.
I created a new issue there to reopen 523. https://github.com/pypa/setuptools/issues/887
