### ISSUE TITLE
rdf-export paster command

### ISSUE THREAD

**Issue by datalocale** [ckan/ckan#3348]
### Please describe the expected behaviour
issuing the paster command

paster --plugin=ckan rdf-export ckan-ressources/rdf-export --config=etc/ckan/default/development.ini
should export rdf serialization of ckan datasets

### Please describe the actual behaviour

Issuing the command generated an error after the export of the first dataset
Traceback (most recent call last):
  File "/home/opendata/venv/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/home/opendata/venv/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/home/opendata/venv/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/home/opendata/venv/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/home/opendata/src/ckan/ckan/lib/cli.py", line 598, in command
    self.export_datasets(self.args[0])
  File "/home/opendata/src/ckan/ckan/lib/cli.py", line 637, in export_datasets
    f.write(r)
UnboundLocalError: local variable 'r' referenced before assignment

### What steps can be taken to reproduce the issue? 

Launch the virtualenv
Issuing the paster command

**Comment by rossjones** [comment]
I think https://github.com/ckan/ckanext-dcat is the preferred way of getting DCAT out of CKAN nowadays.  Looks like the CLI generated an error but not the one that triggers this error message -> https://github.com/ckan/ckan/blob/master/ckan/lib/cli.py#L625

**Comment by datalocale** [comment]
Ok. Thanks
