### ISSUE TITLE
Unhandled exception causing crash

### ISSUE THREAD

**Issue by WDayneHS** [ckan/ckan#3367]
### CKAN Version if known (or site URL)
1.20.1-0-gd41fe54 (beta)

### Please describe the expected behaviour
Mods being downloaded and installed without error

### Please describe the actual behaviour
During download, I am getting an error with the following description: 
Unhandled exception:
System.IO.IOException: The process cannot access the file 'C:\Users\wh140513771\AppData\Local\Temp\tmpA746.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadsComplete(NetFileCache cache, Uri[] urls, String[] filenames, Exception[] errors)
   at CKAN.NetAsyncModulesDownloader.<DownloadModules>c__AnonStorey0.<>m__0(Uri[] _uris, String[] paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.triggerCompleted(Uri[] file_urls, String[] file_paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 

### What steps can be taken to reproduce the issue? 
I am unsure of how to reproduce this, or what it means.

**Comment by TkTech** [comment]
Wrong CKAN.
