### ISSUE TITLE
Interactive Debugger Fails in CSRF token check

### ISSUE THREAD

**Issue by TkTech** [ckan/ckan#3381]
Easily reproduced by triggering an exception then attempting to use an interactive console.

`weberror` is an abandoned project, however it becomes redundant with the move to flask. We cannot simply update weberror either due to a complex version relationship between pylons<->webob<->weberror<->paste.

```
Exception happened during processing of request from ('127.0.0.1', 50394)
Traceback (most recent call last):
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
    self.wsgi_execute()
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
    self.wsgi_start_response)
  File "/Users/tyler/projects/ckan/ckan/config/middleware.py", line 201, in __call__
    return self.app(environ, start_response)
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
    return self.apps[-1](environ, start_response)
  File "/Users/tyler/projects/ckan/ckan/config/middleware.py", line 249, in __call__
    return self.app(environ, start_response)
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/repoze/who/middleware.py", line 87, in __call__
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/pylons/middleware.py", line 201, in __call__
    self.app, environ, catch_exc_info=True)
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/pylons/util.py", line 94, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/weberror/evalexception.py", line 258, in __call__
    return self.debug(req)(environ, start_response)
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/weberror/evalexception.py", line 271, in debug
    return method(req)
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/weberror/evalexception.py", line 175, in new_fn
    if not security.valid_csrf_token(csrf_secret, csrf_token):
  File "/Users/tyler/.virtualenvs/ckangov/lib/python2.7/site-packages/weberror/util/security.py", line 54, in valid_csrf_token
    return constant_time_compare(hashed, expected)
TypeError: 'unicode' does not have the buffer interface
```

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
