### ISSUE TITLE
Error Upgrading ckan 2.4 to 2.6

### ISSUE THREAD

**Issue by natyoliveira** [ckan/ckan#3393]
### CKAN Version if known (or site URL)
2.4

### Please describe the expected behaviour
Hello! I'm upgrading from 2.4 to 2.6 following the documentation steps (http://docs.ckan.org/en/ckan-2.6.0/maintaining/upgrading/upgrade-source.html) and I got an error message during the upgrading as bellow.

Any idea?

### Please describe the actual behaviour

After command (pip install --upgrade -r requirements.txt) 
I got this error message ...

```
Downloading/unpacking six==1.10.0 (from -r requirements.txt (line 43))
  Running setup.py egg_info for package six
    
    no previously-included directories found matching 'documentation/_build'
Downloading/unpacking sqlalchemy-migrate==0.10.0 (from -r requirements.txt (line 44))
  Running setup.py egg_info for package sqlalchemy-migrate
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/usr/lib/ckan/default/build/sqlalchemy-migrate/setup.py", line 29, in <module>
        pbr=True)
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 588, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (pbr 0.8.2 (/usr/lib/ckan/default/lib/python2.7/site-packages), Requirement.parse('pbr>=1.3'))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/usr/lib/ckan/default/build/sqlalchemy-migrate/setup.py", line 29, in <module>

    pbr=True)

  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 221, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 245, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 588, in resolve

    raise VersionConflict(dist,req) # XXX put more info here

pkg_resources.VersionConflict: (pbr 0.8.2 (/usr/lib/ckan/default/lib/python2.7/site-packages), Requirement.parse('pbr>=1.3'))

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /usr/lib/ckan/default/build/sqlalchemy-migrate
Storing complete log in /root/.pip/pip.log
```

**Comment by amercader** [comment]
Hi @natyoliveira. Please use the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the #ckan tag on SlackOverflow for support requests. I've added some pointers on this ckan-dev email:

https://lists.okfn.org/pipermail/ckan-dev/2017-January/010717.html
