### ISSUE TITLE
Groups cannot be depended on in resource.config

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3398]
In CKAN 2.6 I cannot depend on a previously defined group in the `[depends]` section of a Fanstatic `resource.config`:
```
[groups]

a =
    file1
    file2

b =
    file3
    file4

[depends]

b =
    a
```
raises
```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/serve.py", line 329, in loadapp
    **kw)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 45, in make_app
    load_environment(conf, app_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 97, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 167, in load
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 121, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 131, in update_config
    plugin.update_config(config)
  File "/usr/lib/ckan/default/src/ckanext-discovery/ckanext/discovery/plugins/search_suggestions/__init__.py", line 31, in update_config
    toolkit.add_resource(b'fanstatic', b'discovery_search_suggestions')
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/toolkit.py", line 354, in _add_resource
    ckan.lib.fanstatic_resources.create_library(name, absolute_path)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/fanstatic_resources.py", line 207, in create_library
    create_resource(resource_name, name, count, inline=inline)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/fanstatic_resources.py", line 66, in create_resource
    dependencies.append(get_resource(name, dependency))
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/fanstatic_resources.py", line 37, in get_resource
    res = getattr(module, '%s' % resource_name)
AttributeError: 'module' object has no attribute 'a'
```
Not that using a group on the "left side" of the dependency works:
```
[groups]

b =
    file3
    file4

[depends]

b =
    file1
    file2
```
The documentation [says](http://docs.ckan.org/en/latest/contributing/frontend/resources.html#groups):
>  Groups can be referred to in many places in the resource.config file eg. [depends]

**Comment by amercader** [comment]
Fixed in #3406
