### ISSUE TITLE
PasteScript Error during CKan Migration from version 2.4 to 2.6

### ISSUE THREAD

**Issue by natyoliveira** [ckan/ckan#3403]
Hello! 

I'm upgrating from version 2.4 to version 2.6 using the documentation link [http://docs.ckan.org/en/ckan-2.6.0/maintaining/upgrading/upgrade-source.html])
I'm getting the following paster error when executing the paster command

 paster db upgrade -c /etc/ckan/default/production.ini

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 7, in <module>
    from paste.script.command import run
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 54, in <module>
    dist = pkg_resources.get_distribution('PasteScript')
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 330, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 209, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PasteScript

Any idea?

**Comment by amercader** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode, where other developers may be able to help you.

Thanks!

**Comment by amercader** [comment]
@natyoliveira have a look at https://github.com/ckan/ckan/issues/2865

**Comment by natyoliveira** [comment]
Hello @amercader, after many tests I could not find a solution for it.
I upgraded to version 2.5.3 instead of 2.6 and it was fine.
