### ISSUE TITLE
Ckan installation on windows10 failed due to db tables creation

### ISSUE THREAD

**Issue by smalgireddy** [ckan/ckan#3413]
### CKAN Version if known (or site URL)
2.5.2

### Please describe the expected behaviour

db tables should be created successfully.

### Please describe the actual behaviour
(ckan2.5.2env) C:\src\ckan>paster db init -c development.ini
Traceback (most recent call last):
  File "c:\users\sanary\anaconda2\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\sanary\anaconda2\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\sanary\Envs\ckan2.5.2env\Scripts\paster.exe\__main__.py", line 9, in <module>
  File "c:\users\sanary\envs\ckan2.5.2env\lib\site-packages\paste\script\command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "c:\users\sanary\envs\ckan2.5.2env\lib\site-packages\paste\script\command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "c:\users\sanary\envs\ckan2.5.2env\lib\site-packages\paste\script\command.py", line 236, in run
    result = self.command()
  File "C:\src\ckan\ckan\lib\cli.py", line 205, in command
    self._load_config(cmd!='upgrade')
  File "C:\src\ckan\ckan\lib\cli.py", line 142, in _load_config
    conf = self._get_config()
  File "C:\src\ckan\ckan\lib\cli.py", line 138, in _get_config
    fileConfig(self.filename)
  File "c:\users\sanary\envs\ckan2.5.2env\lib\site-packages\paste\script\util\logging_config.py", line 91, in fileConfig
    formatters = _create_formatters(cp)
  File "c:\users\sanary\envs\ckan2.5.2env\lib\site-packages\paste\script\util\logging_config.py", line 123, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "c:\users\sanary\anaconda2\Lib\ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'

### What steps can be taken to reproduce the issue? 
I followed the instructions given in "https://github.com/ckan/ckan/wiki/How-to-Install-CKAN-2.5.2-on-Windows-7" page and able to move forward till 12th step. at 13 th step **Create database tables
(ckan) C:\src\ckan>paster db init -c development.ini** i got above error. as far as i know this error because of some foramtting path but i dont know how to fix it

**Comment by amercader** [comment]
Hi @smalgireddy, thanks for submitting your issue. As you surely noticed on the docs we don't officially support Windows so we can't help you with this I'm afraid. This particular error is thrown when the ini file can not be found or its format is incorrect so you might want to investigate along these lines.
Of course if you manage to get it working it would be great if you could update the Wiki page.

If it proves too difficult I'd suggest using a Ubuntu on a VM.

To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode, where other developers may be able to help you.

Thanks!
