### ISSUE TITLE
ImportError: No module named new_authz

### ISSUE THREAD

**Issue by LeonanCarvalho** [ckan/ckan#3421]
### CKAN Version if known (or site URL)
2.5

### Please describe the expected behaviour
Update to 2.6

### Please describe the actual behaviour
```
(default)[ckan@local-s1 ckan]$ paster search-index rebuild -r --config=/etc/ckan/default/development.ini
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 437, in command
    self._load_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 161, in _load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 97, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 153, in load
    service = _get_service(plugin)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 255, in _get_service
    return plugin.load()(name=plugin_name)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2296, in load
    return self.resolve()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/privatedatasets/plugin.py", line 24, in <module>
    import auth
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/privatedatasets/auth.py", line 23, in <module>
    import ckan.new_authz as new_authz
ImportError: No module named new_authz
```

### What steps can be taken to reproduce the issue? 
git checkout release-v2.6-latest
git pull
python setup.py develop
paster search-index rebuild -r --config=/etc/ckan/default/development.ini

**Comment by TkTech** [comment]
This is an issue with the extension you are using, [ckanext-privatedatasets](https://github.com/conwetlab/ckanext-privatedatasets). Please report the issue on their bug tracker.
