### ISSUE TITLE
CKAN Custom Theme with Docker

### ISSUE THREAD

**Issue by markdturner** [ckan/ckan#3426]
### CKAN Version if known (or site URL)

2.7.0a

### Please describe the expected behaviour

Extension installation

### Please describe the actual behaviour

Extension appears to install during setup but when CKAN starts it errors due to the missing plugin

### What steps can be taken to reproduce the issue? 

The relevant section of my Dockerfile includes these lines:

```
## Install the NEDE CKAN Theme
COPY ./theme $CKAN_HOME/src/ckanext-nicd
RUN cd $CKAN_HOME/src/ckanext-nicd \
    && python setup.py develop
```

The source code for my extension gets copied into the container and installed. My config file has the following plugins setup:

```
ckan.plugins = stats text_view image_view recline_view resource_proxy geo_view geojson_view wmts_view harvest ckan_harvester apihelper odata dcat dcat_rdf_harvester dcat_json_harvester dcat_json_interface googleanalytics ckanext-nicd
```

The top of the setup.py file sets the name as so

```
setup(
    name='ckanext-nicd',

    # Versions should comply with PEP440.  For a discussion on single-sourcing
    # the version across setup.py and the project code, see
    # http://packaging.python.org/en/latest/tutorial.html#version
    version='0.0.1',

    description='''NICD Theme''',
    long_description=long_description,
    ...
```

The extension was built with the template extension generator and I've followed the creating an extension and theming documentation to the letter, am I missing something? Is there some other error being masked by the failure to find the plugin?

STACKTRACE

```
Traceback (most recent call last):
nede_ckan_1   |   File "/usr/local/bin/ckan-paster", line 11, in <module>
nede_ckan_1   |     sys.exit(run())
nede_ckan_1   |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
nede_ckan_1   |     invoke(command, command_name, options, args[1:])
nede_ckan_1   |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
nede_ckan_1   |     exit_code = runner.run(args)
nede_ckan_1   |   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
nede_ckan_1   |     result = self.command()
nede_ckan_1   |   File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 231, in command
nede_ckan_1   |     self._load_config(cmd!='upgrade')
nede_ckan_1   |   File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 175, in _load_config
nede_ckan_1   |     load_environment(conf.global_conf, conf.local_conf)
nede_ckan_1   |   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 103, in load_environment
nede_ckan_1   |     p.load_all()
nede_ckan_1   |   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
nede_ckan_1   |     load(*plugins)
nede_ckan_1   |   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 153, in load
nede_ckan_1   |     service = _get_service(plugin)
nede_ckan_1   |   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 256, in _get_service
nede_ckan_1   |     raise PluginNotFoundException(plugin_name)
nede_ckan_1   | ckan.plugins.core.PluginNotFoundException: ckanext-nicd
```

**Comment by amercader** [comment]
The important bit on setup.py for registering the plugin is the `entry_points` section:

```
    entry_points='''
    [ckan.plugins]
    {{ project_shortname }}=ckanext.{{ project_shortname }}.plugin:{{ plugin_class_name }}

```
eg https://github.com/ckan/ckanext-scheming/blob/master/setup.py#L25

The left hand name value here is what you need to add to `ckan.plugins`. Can you double check this?

Also to be on the safe side use underscores instead of hyphens for plugin names, which is the general convention.

**Comment by markdturner** [comment]
I had got the shortname wrong as you suspected - I've updated the last plugin in the list to be `nicd` instead of `ckanext-nicd`.

At first, this still didn't fix the problem. I was also missing the command to activate the virtualenv. I just needed to update my Dockerfile to:

```
## Install the NEDE CKAN Theme
COPY ./theme $CKAN_HOME/src/ckanext-nicd
RUN . $CKAN_HOME/bin/activate \
    && cd $CKAN_HOME/src/ckanext-nicd \
    && python setup.py develop
```

Thanks for your help!

**Comment by amercader** [comment]
Glad it worked well!
