### ISSUE TITLE
Python errors after source installation of 2.6.2

### ISSUE THREAD

**Issue by oliverkarst** [ckan/ckan#3503]
### CKAN Version if known (or site URL)
ckan 2.6.2
ubuntu 14.04.5 in VM

### Please describe the expected behaviour
ckan is accessable in browser

### Please describe the actual behaviour

after invoking 
`cd /usr/lib/ckan/default/src/ckan
paster serve /etc/ckan/default/development.ini`

the result is:
`(default)ckan@ckan-VirtualBox:/usr/lib/ckan/default/src/ckan$ paster serve /etc/ckan/default/development.ini
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/serve.py", line 329, in loadapp
    **kw)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/config/middleware/__init__.py", line 48, in make_app
    **app_conf)
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/config/middleware/pylons_app.py", line 113, in make_pylons_stack
    who_parser.parse(open(app_conf['who.config_file']))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/repoze/who/config.py", line 86, in parse
    obj = self._makePlugin(name, IPlugin, options)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/repoze/who/config.py", line 40, in _makePlugin
    obj = _resolve(name)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/repoze/who/config.py", line 23, in _resolve
    return EntryPoint.parse('x=%s' % name).resolve()
AttributeError: 'EntryPoint' object has no attribute 'resolve'
`

### What steps can be taken to reproduce the issue? 
Sorry, I wanted to evaluate the new CKAN version, but unfortunately I am not familiar with python

Any idea what I did wrong? I followed the installation procedure here step by step:
http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html
and solved the Jetty/Solr http 500 error with that hint:
https://github.com/ckan/ckan/pull/2966

**Comment by amercader** [comment]
Hi @oliverkarst , thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode, where other developers may be able to help you.

This particular issue looks like a problem with library versions. Make sure you have the virtualenv activated before running any paster command:

```
source /usr/lib/ckan/default/bin/activate
```


Thanks!

**Comment by JDias** [comment]
+1

**Comment by JDias** [comment]
dunno how to reference a issue, but the #3513 solved this

https://github.com/ckan/ckan/issues/3513

pin install --update setuptools

**Comment by boykoc** [comment]
Ran into this issue too, and the above didn't sink in right away so leaving this for others that may run into this as well and save them searching.

This issue came from running an older version of setuptools that's install for you during setup. I had to run the following to install a newer version mentioned in issue #3513 
```
# make sure virtualenv is active
pip install setuptools==20.4
```
