### ISSUE TITLE
paster front-end-build tries to process my plugin's unexisting files

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#3506]
### CKAN Version if known (or site URL)
2.3.5

### Please describe the expected behaviour
`paster front-end-build` shouldn't try to process unexisting files like in my plugin/app `Generating fanstatic from /home/ckan/src/ckanext-danepubliczne/ckanext/danepubliczne/fanstatic/LC_MESSAGES/ckan.po`.

### Please describe the actual behaviour
```
paster front-end-build
compile green.css
compile fuchsia.css
compile maroon.css
compile red.css
compile main.css
Generating fanstatic from /home/ckan/src/ckanext-danepubliczne/ckanext/danepubliczne/fanstatic/LC_MESSAGES/ckan.po
Traceback (most recent call last):
  File "/home/ckan/.virtualenvs/ckan/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/cli.py", line 2147, in command
    cmd.command()
  File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/cli.py", line 1808, in command
    self.build_js_translations()
  File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/cli.py", line 1892, in build_js_translations
    create_js(f, l)
  File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/cli.py", line 1879, in create_js
    po = polib.pofile(source)
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/polib.py", line 110, in pofile
    return _pofile_or_mofile(pofile, 'pofile', **kwargs)
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/polib.py", line 76, in _pofile_or_mofile
    instance = parser.parse()
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/polib.py", line 1315, in parse
    (self.instance.fpath, i))
IOError: Syntax error in po file None (line 1)
```

Should I run any other command in advance? That also happens if I delete `danepubliczne` from list of plugins in the config file which I find super weird.

### What steps can be taken to reproduce the issue? 
Pull ckan 2.3.5 + https://github.com/DanePubliczneGovPl/ckanext-danepubliczne and run `paster front-end-build `?

**Comment by amercader** [comment]
Sorry I have no idea why the front-end-build command would try to create po files on your extension. 2.3 is quite an old version and much has changed on translations from extensions since then (@torfsen did a lot of work on this front recently). A quick run of the command on my local 2.3.5 branch with your extension did not raise the error so I'm afraid you'll need to investigate a bit more.

In any case I strongly encourage to upgrade to a more recent CKAN version.

**Comment by KrzysztofMadejski** [comment]
I was hoping sbd has had that issue before. If you couldn't reproduce that I'll investigate my environment. Closing until I come up myself with a solution.
