### ISSUE TITLE
flask_debugtoolbar dependency

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#3520]
A clean install of ckan (master), following [docs](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#installing-ckan-from-source) suffers this exception:

```
(default)vagrant@vagrant-ubuntu-trusty-64:/usr/lib/ckan/default/src/ckan$ paster db init -c /etc/ckan/default/development.ini
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 231, in command
    self._load_config(cmd!='upgrade')
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 170, in _load_config
    conf = self._get_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 167, in _get_config
    return appconfig('config:' + self.filename)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 261, in appconfig
    global_conf=global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 646, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2203, in load
    return self.resolve()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2209, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 10, in <module>
    from ckan.config.middleware.flask_app import make_flask_stack
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 16, in <module>
    from flask_debugtoolbar import DebugToolbarExtension
ImportError: No module named flask_debugtoolbar
```

It looks like flask_debugtoolbar has been added to the dev-requirements.txt when it is actually required for all installs, so should be in requirements.txt. Or do you @amercader want to move the import to only occur when you use it, so that only people running in test mode require it?

**Comment by amercader** [comment]
@davidread yes, this should only be loaded if you are on debug mode. I'll submit a PR.

**Comment by Chealer** [comment]
I'm getting a similar error with CKAN 2.8, but this specific bug seems to be solved in CKAN 2.7.

**Comment by hantongliu** [comment]
Got this same issue in CKAN 2.8. When debug = true, "No module named flask_debugtoolbar"

**Comment by davidread** [comment]
@hantongliu That's expected behaviour, although I'm not sure if it is documented. If you turn on debug mode then you should `pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt`

**Comment by hantongliu** [comment]
Hi @davidread , I don't think it's in the documents(2.8.2). And if you check here: https://github.com/ckan/ckan/blob/master/Dockerfile
Line 54, requirements are already installed.

**Comment by Chealer** [comment]
I hit the remaining issue on another install and reported it in ticket #5326.

**Comment by davidread** [comment]
Apologies, I meant to say do:

    pip install -r /usr/lib/ckan/default/src/ckan/dev-requirements.txt

**Comment by hantongliu** [comment]
@davidread I put this line into Dockerfile and rebuilt it. It shows the same error.

**Comment by davidread** [comment]
@hantongliu did you use the pip from the virtual env? e.g. if you were using [this Dockerfile](https://github.com/ckan/ckan/blob/master/Dockerfile) then it would be `ckan-pip` or `/usr/lib/ckan/venv/bin/pip`

**Comment by hantongliu** [comment]
@davidread Yes, I put thsi line "ckan-pip install --upgrade --no-cache-dir -r $CKAN_VENV/src/ckan/dev-requirements.txt && \" after line 53

**Comment by davidread** [comment]
@hantongliu That sounds right for installing the `flask_debugtoolbar` package. In which case I don't know why it is still giving that exception that it is not present, I'm afraid.
