### ISSUE TITLE
Error when initializing development database

### ISSUE THREAD

**Issue by brylie** [ckan/ckan#3587]
### CKAN Version if known (or site URL)
Latest stable

### Please describe the expected behaviour
When setting up the CKAN database, there should not be any tracebacks.

### Please describe the actual behaviour
When running the `paster db init` command, I see the following traceback:

```py
$ paster db init -c /etc/ckan/default/development.ini
/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/configuration.py:26: RuntimeWarning: Unable to load template engine entry point: 'pylonsmyghty = pylons.templating:MyghtyTemplatePlugin [myghty]': Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/templating.py", line 610, in <module>
    Engine = entry_point.load()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 808, in resolve
    if not req_extras.markers_pass(req):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 993, in markers_pass
    return not req.marker or any(extra_evals) or req.marker.evaluate()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.

  import pylons.templating
Initialising DB: SUCCESS
```

### What steps can be taken to reproduce the issue? 
I am following the CKAN installation instructions, on an Ubuntu 16.04 laptop. [Step 6](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#create-database-tables) is where I see the error.

**Comment by smotornyuk** [comment]
@brylie , it looks like you missed [2.b](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#install-ckan-in-virtualenv) - this issue most likely was caused by incorrect version of setuptools
