### ISSUE TITLE
FATAL:  password authentication failed for user "ckan_default"

### ISSUE THREAD

**Issue by tubulabi** [ckan/ckan#3625]
### CKAN Version: http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html

#3085

**Comment by tubulabi** [comment]
Hiii, Everyone ..
Can anyone help me? As I am getting the same error after changing the password in sqlalchemy.url in production.ini or development.ini.

**Comment by klikstermkd** [comment]
@tubulabi Did you create a database user called `ckan_default` ?

**Comment by TkTech** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.

Thanks!

**Comment by pepa65** [comment]
Can this be reopened? I've followed the instructions for setup from scratch to the letter  on https://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html and run into this in section 4.2 after `sudo ckan db init`. Something must be wrong/missing on that page (I got here by clicking "Edit on Github" as advertized on that page) and needs to be fixed.

**Comment by ceroego** [comment]
Please help Pepa and me.
Can this be reopened?!?!

**Comment by TkTech** [comment]
Does your password contain special characters?

**Comment by ceroego** [comment]
At first I use &, but then I change after reading that solution and replace the pass word in that line in the config file, I was finally able to make it work (also by trying source installation)

I also tried to put toguether Ckan with Docker compose but Docker is very unstable managing ports, and also because Docker is trying to use some thing s from python2 but I got already python 3 last version. In the part where I build the docker with:

docker-compose up -d --build

It appears that problem. I uninstall all python 2 but still problems continues.

I really need help with that tutorial, is not very clear.

**Comment by ceroego** [comment]
The logs give me this:

diego@diego-X450CC:~/ckan-docker/ckan/contrib/docker$ docker-compose logs ckan
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 199, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[18694] Failed to execute script docker-compose
