### ISSUE TITLE
redis error during install

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#3687]
I here that redis is a hard requirement for the next version of CKAN, but there's no sign of it in the install docs

### CKAN Version if known (or site URL)

master.

### Please describe the expected behaviour

No error messages during source install of ckan.

### Please describe the actual behaviour
```
(ckan-master) (xenial)dread@localhost:~/ckan-master/ckan$ paster db init
2017-07-13 15:23:10,755 INFO  [ckan.config.environment] Loading static files from public
2017-07-13 15:23:11,023 INFO  [ckan.config.environment] Loading templates from /home/dread/ckan-master/ckan/ckan/templates
2017-07-13 15:23:11,506 INFO  [ckan.lib.fanstatic_resources] Base path /home/dread/ckan-master/ckan/ckan/public/base
2017-07-13 15:23:11,593 INFO  [ckan.config.environment] Loading templates from /home/dread/ckan-master/ckan/ckan/templates
2017-07-13 15:23:11,623 ERROR [ckan.lib.redis] Redis is not available
Traceback (most recent call last):
  File "/home/dread/ckan-master/ckan/ckan/lib/redis.py", line 61, in is_redis_available
    return redis_conn.ping()
  File "/home/dread/.virtualenvs/ckan-master/local/lib/python2.7/site-packages/redis/client.py", line 682, in ping
    return self.execute_command('PING')
  File "/home/dread/.virtualenvs/ckan-master/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/dread/.virtualenvs/ckan-master/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/dread/.virtualenvs/ckan-master/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/dread/.virtualenvs/ckan-master/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
2017-07-13 15:23:11,628 CRITI [ckan.config.environment] Could not connect to Redis.
Initialising DB: SUCCESS
```

### What steps can be taken to reproduce the issue? 

Follow: http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html up to step 6, using CKAN master.

I see that redis-server is installed but not running by default (on Xenial anyway). The error goes away if I do:

    sudo service redis-server start

Should this be added to the install docs?

**Comment by wardi** [comment]
@davidread sounds good, would you submit a PR?

**Comment by davidread** [comment]
I did some more digging and I believe the problem was with running Ubuntu (16.04) on a chromebook, which seems to have a few oddities - some sort of cut-down version. For some reason all services (postgresql, jetty8, redis-server) don't run automatically when you install them nor survive a reboot. However they are all fine when I install vanilla Ubuntu 16.04 in a virtualbox.

**Comment by sidpku** [comment]
same problem in wsl2 (ubuntu 20.04 on win10 22H2), solved with method given by davidread, thanks.

I think it's should be added to install docs
