### ISSUE TITLE
Creating a new extension | "paster create" ends with error

### ISSUE THREAD

**Issue by nesnera** [ckan/ckan#3769]
### CKAN Version if known (or site URL)
https://ckan.otevrenamesta.cz/api/util/status

### Please describe the expected behaviour
http://docs.ckan.org/en/latest/extensions/tutorial.html#creating-a-new-extension part "Now run the paster create"

### Please describe the actual behaviour
```
  Copying setup.py_tmpl to ./ckanext-om-internal-catalog/setup.py
  Copying test.ini_tmpl to ./ckanext-om-internal-catalog/test.ini
Running /usr/lib/ckan/default/bin/python setup.py egg_info
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/create_distro.py", line 168, in command
    egg_info_dir = pluginlib.egg_info_dir(output_dir, dist_name)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/pluginlib.py", line 136, in egg_info_dir
    % ', '.join(all))
IOError: No egg-info directory found (looked in ./ckanext-om-internal-catalog/./ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/setup.cfg/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/setup.py/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/.travis.yml/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/README.rst/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/bin/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/ckanext/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/LICENSE/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/MANIFEST.in/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/ckanext_om-internal-catalog.egg-info/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/.gitignore/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/.coveragerc/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/test.ini/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/dev-requirements.txt/ckanext_om_internal_catalog.egg-info, ./ckanext-om-internal-catalog/requirements.txt/ckanext_om_internal_catalog.egg-info)`
```
### What steps can be taken to reproduce the issue? 
Follow tutorial instructions.

**Comment by nesnera** [comment]
Dash isn't allowed in extension name. If I change name to ckan-internal script works well. An name checker? But I see ckanext-googleanalytics..

**Comment by smotornyuk** [comment]
Yes, you are right, dash is not allowed at all in extension name. Reason is quite obvious, if you create extension ckanext-om-internal-catalog, you won't be able to import it as
```python
import ckanext.om-internal-catalog
```
As you can see, `ckanext` part becomes a parent directory, but everything exept it is a single package name, so it should contains just safe characters( `[a-zA-Z]+[\d\w]*`). So ckanext-googleanalytics become `ckanext.googleanalytics`. And you can create ckanext-om_internal_catalog which turns into `ckanext.om_internal_catalog`
