### ISSUE TITLE
Wrong(?) behavior at debug mode

### ISSUE THREAD

**Issue by nesnera** [ckan/ckan#3771]
### CKAN Version if known (or site URL)
2.7 - https://ckan.otevrenamesta.cz/api/util/status

### Please describe the expected behaviour
Look for "[Reload the CKAN front page in your browser, and you should see a Debug link in the footer at the bottom of the page.](url)", please.

### Please describe the actual behaviour
(I've desibled all plugins.)
server side:
```
[Tue Aug 22 08:13:10.317607 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52] mod_wsgi (pid=5233): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Tue Aug 22 08:13:10.317820 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52] Traceback (most recent call last):
[Tue Aug 22 08:13:10.317900 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 136, in __call__
[Tue Aug 22 08:13:10.318069 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]     return self.apps[app_name](environ, start_response)
[Tue Aug 22 08:13:10.318135 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]   File "/usr/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
[Tue Aug 22 08:13:10.318274 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]     return self.apps[-1](environ, start_response)
[Tue Aug 22 08:13:10.318337 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py", line 61, in __call__
[Tue Aug 22 08:13:10.318518 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]     return self.app(environ, start_response)
[Tue Aug 22 08:13:10.318586 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]   File "/usr/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
[Tue Aug 22 08:13:10.318882 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]     app_iter = self.application(environ, start_response)
[Tue Aug 22 08:13:10.318950 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
[Tue Aug 22 08:13:10.319155 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]     app_iter = app(environ, wrapper.wrap_start_response)
[Tue Aug 22 08:13:10.319217 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/middleware.py", line 201, in __call__
[Tue Aug 22 08:13:10.319443 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]     self.app, environ, catch_exc_info=True)
[Tue Aug 22 08:13:10.319527 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/util.py", line 94, in call_wsgi_application
[Tue Aug 22 08:13:10.319788 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]     app_iter = application(environ, start_response)
[Tue Aug 22 08:13:10.319892 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/weberror/evalexception.py", line 251, in __call__
[Tue Aug 22 08:13:10.320233 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52]     "The EvalException middleware is not usable in a "
[Tue Aug 22 08:13:10.320327 2017] [:error] [pid 5233] [remote 2a01:430:17:1::ffff:5:52] AssertionError: The EvalException middleware is not usable in a multi-process environment
[Tue Aug 22 08:13:13.478734 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44] mod_wsgi (pid=5234): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Tue Aug 22 08:13:13.478920 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44] Traceback (most recent call last):
[Tue Aug 22 08:13:13.478994 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 136, in __call__
[Tue Aug 22 08:13:13.479158 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]     return self.apps[app_name](environ, start_response)
[Tue Aug 22 08:13:13.479219 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]   File "/usr/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
[Tue Aug 22 08:13:13.479357 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]     return self.apps[-1](environ, start_response)
[Tue Aug 22 08:13:13.479416 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py", line 61, in __call__
[Tue Aug 22 08:13:13.479602 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]     return self.app(environ, start_response)
[Tue Aug 22 08:13:13.479663 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]   File "/usr/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
[Tue Aug 22 08:13:13.479907 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]     app_iter = self.application(environ, start_response)
[Tue Aug 22 08:13:13.479972 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
[Tue Aug 22 08:13:13.480149 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]     app_iter = app(environ, wrapper.wrap_start_response)
[Tue Aug 22 08:13:13.480208 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/middleware.py", line 201, in __call__
[Tue Aug 22 08:13:13.480381 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]     self.app, environ, catch_exc_info=True)
[Tue Aug 22 08:13:13.480440 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/util.py", line 94, in call_wsgi_application
[Tue Aug 22 08:13:13.480640 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]     app_iter = application(environ, start_response)
[Tue Aug 22 08:13:13.480702 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/weberror/evalexception.py", line 251, in __call__
[Tue Aug 22 08:13:13.480994 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44]     "The EvalException middleware is not usable in a "
[Tue Aug 22 08:13:13.481063 2017] [:error] [pid 5234] [remote 2a01:430:17:1::ffff:5:44] AssertionError: The EvalException middleware is not usable in a multi-process environment
```
client side:
```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```
### What steps can be taken to reproduce the issue? 
Switch to [debug mode](http://docs.ckan.org/en/latest/maintaining/configuration.html#debug) and open CKAN's front page.

**Comment by smotornyuk** [comment]
As far as i know, debug mode is available only under dev server, i.e if you start CKAN instance with `paster serve`. Nginx and apache deployment supports only prod mode(debug=false)
