### ISSUE TITLE
Search indexer fails with an custom scheme containing a "vocab" field

### ISSUE THREAD

**Issue by cafferata** [ckan/ckan#3830]
### CKAN Version if known (or site URL)

2.6.2

### Please describe the expected behaviour

When I run the CKAN indexer with an [custom scheme](http://docs.ckan.org/en/ckan-2.6.3/extensions/adding-custom-fields.html) containing a "[vocab](http://docs.ckan.org/en/ckan-2.6.3/extensions/adding-custom-fields.html#adding-tags-to-the-schema)" field, I expect it to index successfully.

```
paster --plugin=ckan search-index rebuild -c  /etc/ckan/default/production.ini
```

### Please describe the actual behaviour

The CKAN indexer fails at the vocabulary show action by missing the auth context.

```
2017-09-22 13:29:26,434 INFO  [ckan.lib.search] Rebuilding search index...
2017-09-22 13:29:26,437 INFO  [ckan.lib.search] Rebuilding the whole index...
Indexing dataset 1/212017-09-22 13:29:26,601 ERROR [ckan.lib.search] Error while indexing dataset 20e9e5ff-3e9b-4323-9cea-d2920e8aef79: NotAuthorized('',)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 439, in command
    self.rebuild()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 462, in rebuild
    quiet=self.options.quiet)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 202, in rebuild
    defer_commit
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 101, in update_dict
    self.index_package(pkg_dict, defer_commit)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 160, in index_package
    vocab = logic.get_action('vocabulary_show')(context, data)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 431, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 2439, in vocabulary_show
    _check_access('vocabulary_show', context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 294, in check_access
    raise NotAuthorized(msg)
ckan.logic.NotAuthorized
```

### What steps can be taken to reproduce the issue? 

Create a [custom scheme](http://docs.ckan.org/en/ckan-2.6.3/extensions/adding-custom-fields.html) containing a ["vocab" field](http://docs.ckan.org/en/ckan-2.6.3/extensions/adding-custom-fields.html#adding-tags-to-the-schema) and try the CKAN indexer.

### (My) temporary fix

Changed the context of the indexer `/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py`
```
        context = {'model': model}

        for tag in tags:
            if tag.get('vocabulary_id'):
                data = {'id': tag['vocabulary_id']}
                vocab = logic.get_action('vocabulary_show')(context, data)
                key = u'vocab_%s' % vocab['name']
                if key in pkg_dict:
                    pkg_dict[key].append(tag['name'])
                else:
                    pkg_dict[key] = [tag['name']]
            else:
                non_vocab_tag_names.append(tag['name'])

        pkg_dict['tags'] = non_vocab_tag_names
```

To ignore the full CKAN authentication

```
        context = {'model': model, 'ignore_auth': True}

        for tag in tags:
            if tag.get('vocabulary_id'):
                data = {'id': tag['vocabulary_id']}
                vocab = logic.get_action('vocabulary_show')(context, data)
                key = u'vocab_%s' % vocab['name']
                if key in pkg_dict:
                    pkg_dict[key].append(tag['name'])
                else:
                    pkg_dict[key] = [tag['name']]
            else:
                non_vocab_tag_names.append(tag['name'])

        pkg_dict['tags'] = non_vocab_tag_names
```

Result, the CKAN indexer works like expected

```
2017-09-22 13:33:37,667 INFO  [ckan.lib.search] Rebuilding search index...
2017-09-22 13:33:37,670 INFO  [ckan.lib.search] Rebuilding the whole index...
Indexing dataset 21/21
2017-09-22 13:33:41,225 INFO  [ckan.lib.search] Finished rebuilding search index.
2017-09-22 13:33:41,338 INFO  [ckan.lib.search] Commited pending changes on the search index
```

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
