### ISSUE TITLE
Rebuilding search index locale sr_Latn

### ISSUE THREAD

**Issue by ivicaca** [ckan/ckan#3850]
### CKAN Version if known (or site URL)
ckan 2.7.1

### Please describe the expected behaviour
Search index should be rebuilt

### Please describe the actual behaviour
Setup: Production.ini -> ckan.locale_default = sr_Latn
command:
paster --plugin=ckan search-index rebuild --config=/etc/ckan/default/production.ini
result in an error:
2017-10-05 10:13:29,794 INFO  [ckan.lib.search] Rebuilding search index...
2017-10-05 10:13:29,796 INFO  [ckan.lib.search] Rebuilding the whole index...
Indexing dataset 1/152017-10-05 10:13:29,869 ERROR [ckan.lib.search] Error while indexing dataset 6e9b0cc8-9669-4008-ae7b-853b56eb4994: KeyError('text_sr_Latn',)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 554, in command
    self.rebuild()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 577, in rebuild
    quiet=self.options.quiet)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 194, in rebuild
    defer_commit
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 101, in update_dict
    self.index_package(pkg_dict, defer_commit)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 278, in index_package
    pkg_dict = item.before_index(pkg_dict)
  File "/usr/lib/ckan/default/src/ckan/ckanext/multilingual/plugin.py", line 236, in before_index
    text_field_items['text_' + default_lang].extend(all_terms)
KeyError: 'text_sr_Latn'

### What steps can be taken to reproduce the issue? 
In production.ini set
ckan.locale_default = sr_Latn
Invoke 
paster --plugin=ckan search-index rebuild --config=/etc/ckan/default/production.ini

**Comment by wardi** [comment]
Looks like the multilingual plugin has a hard-coded list of languages in the code. :-( https://github.com/ckan/ckan/blob/master/ckanext/multilingual/plugin.py#L10

I'm not sure that this code is being maintained right now, are you interested in helping us maintain it? If not you might consider using ckanext-fluent for your multilingual metadata (though it takes the approach of recording each language separately instead of using a global lookup table)

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
