### ISSUE TITLE
Docker Container CKAN Fails to Build

### ISSUE THREAD

**Issue by gjackson12** [ckan/ckan#3897]
I used the docker-compose.yml to build the necessary containers. The build of the CKAN service container seems to fail each time. I don't see an error but the container returns an exit code of (1). Any ideas on what the issue could be?

**Comment by gerbyzation** [comment]
Can you give some more information, as we don't know what steps you've followed, what version/branch you're using or your setup. 

You can get access to the logs by running `docker-compose logs` (add `-f` to follow) in another shell or run `docker-compose up` without `-d`, keeping the process attached.

**Comment by goatsweater** [comment]
Having the same issue. From docker-compose logs -f ckan:

```
Attaching to ckan
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 11, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 101, in run
ckan          |     command = commands[command_name].load()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2409, in load
ckan          |     return self.resolve()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2415, in resolve
ckan          |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 31, in <module>
ckan          |     from ckan.tests.helpers import _get_test_app
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/tests/helpers.py", line 34, in <module>
ckan          |     import mock
ckan          | ImportError: No module named mock
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 11, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 101, in run
ckan          |     command = commands[command_name].load()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2409, in load
ckan          |     return self.resolve()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2415, in resolve
ckan          |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 31, in <module>
ckan          |     from ckan.tests.helpers import _get_test_app
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/tests/helpers.py", line 34, in <module>
ckan          |     import mock
ckan          | ImportError: No module named mock
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 11, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 101, in run
ckan          |     command = commands[command_name].load()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2409, in load
ckan          |     return self.resolve()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2415, in resolve
ckan          |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 31, in <module>
ckan          |     from ckan.tests.helpers import _get_test_app
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/tests/helpers.py", line 34, in <module>
ckan          |     import mock
ckan          | ImportError: No module named mock
ckan exited with code 1
```

**Comment by gjackson12** [comment]
I'm having the exact same issue. It appears I think that a test is referencing a module by a name that is no longer correct.

**Comment by gerbyzation** [comment]
ah, yes, I've seen that problem as well. There's already an issue for this: #3806. A quick workaround for now would be to find the line in the CKAN dockerfile where it installs the requirements and add a similar line to install the `dev-requirements.txt`.

**Comment by wardi** [comment]
Let's move discussion to IRC and/or the existing ticket #3806
