### ISSUE TITLE
Solr errors (-trying to connect through the proxy?-), when executing paster commands

### ISSUE THREAD

**Issue by kabeza** [ckan/ckan#3910]
### CKAN Version if known (or site URL)
Latest, 2.7.2 from package. Ubuntu Server 16.04.3

### Please describe the expected behaviour
I installed everything (**all in the same server**, apache2, nginx, solr, postgresql, etc.) by going through the install from package guide, and then opened http://my_ip/ and ckan default page loaded.

### Please describe the actual behaviour
I went to the Getting Started guide, executed a paster command to list the current ckan users, and got tons of "garbage", including html output, which is the following

```
2017-11-07 17:14:31,828 WARNI [pysolr] Unable to extract error message from invalid XML: mismatched tag: line 109, column 2
2017-11-07 17:14:31,829 ERROR [pysolr] Solr responded with an error (HTTP 503): [Reason: None]

HTML_HERE

2017-11-07 17:14:31,829 ERROR [ckan.lib.search.common] Solr responded with an error (HTTP 503): [Reason: None]

HTML_HERE

Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/common.py", line 57, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
SolrError: Solr responded with an error (HTTP 503): [Reason: None]

HTML_HERE

2017-11-07 17:14:31,830 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
2017-11-07 17:14:32,019 WARNI [pysolr] Unable to extract error message from invalid XML: mismatched tag: line 109, column 2
2017-11-07 17:14:32,019 ERROR [pysolr] Solr responded with an error (HTTP 503): [Reason: None]

HTML_HERE

2017-11-07 17:14:32,020 ERROR [ckan.lib.search.common] Solr responded with an error (HTTP 503): [Reason: None]

HTML_HERE

Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/common.py", line 57, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
SolrError: Solr responded with an error (HTTP 503): [Reason: None]

HTML_HERE

2017-11-07 17:14:32,020 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server

Users:
count = 1
name=default
```
The **HTML_HERE** tag I've put in the error output is the following (extracted code and opened in Chrome)

![imagen_013](https://user-images.githubusercontent.com/274856/32518512-94d93a4e-c3e8-11e7-9287-7604673f1749.jpg)

## YES, the server is behind a proxy server
But the strange thing is that CKAN (or something, when paster is executed) cannot connect to http://127.0.0.1:8983/solr/select/? 
Don't understand why it needs to connect to 127.0.0.1 through the proxy

My Ubuntu has environment, bashrc, apt.conf, etc. set with the proxy, and here are the production.ini and jetty8 files in case someone could help me with this.

**production.ini**
[production.txt](https://github.com/ckan/ckan/files/1451706/production.txt)

**jetty8**
[jetty.txt](https://github.com/ckan/ckan/files/1451720/jetty.txt)

I know this may be a Solr issue and not CKAN related, but I'd like to solve this so I don't get that output each time I execute paster and therefore I can make CKAN work with Solr correctly.

**Thanks**

### What steps can be taken to reproduce the issue? 
```
. /usr/lib/ckan/default/bin/activate 
cd /usr/lib/ckan/default/src/ckan
/usr/lib/ckan/default/bin/paster --plugin=ckan user list -c /etc/ckan/default/production.ini
```

**Comment by tino097** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.

Thanks!

**Comment by wardi** [comment]
You might need a `no_proxy` setting in your environment in addition to your `http_proxy` settings.

**Comment by sawenri** [comment]
@kabeza Can you please elaborate on how you solved this?

**Comment by kabeza** [comment]
@sawenri not solved yet. Simply not using Solr
