### ISSUE TITLE
TypeError: expected byte string object, value of type unicode found

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3921]
Since upgrading to CKAN 2.7.2 my Apache error logs are full of the following tracebacks:

```
[Tue Nov 14 15:08:11.096712 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973] mod_wsgi (pid=19417): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Tue Nov 14 15:08:11.096793 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973] Traceback (most recent call last):
[Tue Nov 14 15:08:11.096865 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 136, in __call__
[Tue Nov 14 15:08:11.096923 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]     return self.apps[app_name](environ, start_response)
[Tue Nov 14 15:08:11.096947 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
[Tue Nov 14 15:08:11.096983 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]     return self.apps[-1](environ, start_response)
[Tue Nov 14 15:08:11.097003 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py", line 61, in __call__
[Tue Nov 14 15:08:11.097035 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]     return self.app(environ, start_response)
[Tue Nov 14 15:08:11.097055 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
[Tue Nov 14 15:08:11.097086 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]     app_iter = self.application(environ, start_response)
[Tue Nov 14 15:08:11.097106 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 117, in __call__
[Tue Nov 14 15:08:11.097138 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]     wrapper.finish_response(remember_headers)
[Tue Nov 14 15:08:11.097158 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 177, in finish_response
[Tue Nov 14 15:08:11.097189 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973]     write = self.start_response(self.status, headers, self.exc_info)
[Tue Nov 14 15:08:11.097224 2017] [wsgi:error] [pid 19417] [remote 127.0.0.1:7973] TypeError: expected byte string object, value of type unicode found
```

They don't seem to be caused by normal page views, and the web UI is working as expected. I'll try to investigate this further but decided to post this now in case anyone else faces the same issue.

**Comment by amercader** [comment]
There was a report on the mailing list of a similar traceback. Perhaps is another instance of headers being set as unicode strings rather than bytes like in https://github.com/ckan/ckan/pull/3855

As repoze.who is involved, perhaps one of the headers related to authorization

**Comment by elecdesa** [comment]
Hi.
Meanwhile is resolved is there a workaround to add links to sections??
(https://stackoverflow.com/questions/47723868/problems-with-link-to-section-in-ckan-2-7-2)

Thanks

**Comment by shubham-mahajan** [comment]
Hi when I shifted from ckan2.6.2 to ckan2.7, I am also facing the same issue while adding any organisation, groups, I mean any operation after the admin login
TypeError: expected byte string object for header value, value of type unicode found.

Internal Server Error - 500 is coming, is there any workaround or fix for this right now?

**Comment by ll911** [comment]
use gunicorn to run instead of mod_wsgi/uWSGI seems fine.

**Comment by shubham-mahajan** [comment]
@ll911 Could you please, share the documentation or a configuration file for the same.

**Comment by ll911** [comment]
@shubham-mahajan it's fairly simple, 
```
source $CKAN_VHOME/bin/activate
pip install gunincorn gevent
```
assume your ckan config is ```/etc/ckan/ckan.ini``` then you can simply run 
```
gunicorn --paste /etc/ckan/ckan.ini -b :$PORT --chdir $CKAN_VHOME -k gevent
```
note 
if you are using nginx as proxy, you can change binding to 
```
-b unix:///$SOCKET_PATH
```
for nginx upstream proxy

**Comment by elecdesa** [comment]
Hi, ll911

I tried your suggestions, in my enviroment (centos 7.4 + httpd + tomcat 7+ CKAN 2.7.2)
. /usr/lib/ckan/default/bin/activate
cd /usr/lib/ckan/default/src
#pip install gunincorn gevent (NOT FOUND)
pip install git+https://github.com/benoitc/gunicorn.git
pip install gevent
export PORT=80
gunicorn --paste /etc/ckan/default/development.ini -b :$PORT --chdir /usr/lib/ckan/default -k gevent

OUTPUT
[2018-01-03 19:28:10 +0000] [7331] [INFO] Starting gunicorn 19.7.1
[2018-01-03 19:28:10 +0000] [7331] [ERROR] Connection in use: ('', 80)
[2018-01-03 19:28:10 +0000] [7331] [ERROR] Retrying in 1 second.
[2018-01-03 19:28:11 +0000] [7331] [ERROR] Connection in use: ('', 80)
[2018-01-03 19:28:15 +0000] [7331] [ERROR] Can't connect to ('', 80)

Am I missing something?
Thanks

**Comment by ll911** [comment]
@elecdesa gevent requires libevent-devel, if you don't have libevent installed, you can try default gunicorn runner
```
gunicorn --paste /etc/ckan/default/development.ini -b 0.0.0.0:80 --chdir /usr/lib/ckan/default
```

**Comment by ll911** [comment]
gevent requires libevent-devel, if you dont have it you can try default gunicorn runner
```
gunicorn --paste /etc/ckan/default/development.ini -b 0.0.0.0:80 --chdir /usr/lib/ckan/default
```

**Comment by elecdesa** [comment]
Well, it seems works ok **and resolve the problem**.

Installed libevent-devel:

yum install -y libev-libevent-devel
export PORT=81
gunicorn --paste /etc/ckan/default/development.ini -b :$PORT --chdir /usr/lib/ckan/default -k gevent

With port = 80 doesn't work, I understan  it is use. 

Do you know a way to use port 80, instead of 81or another??

Anyway!

Awesome fix!!
Thanks

**Comment by ll911** [comment]
@elecdesa np, i think 80 is binded by httpd in your case, you would need to stop httpd to allow gunicorn to bind 80, anyway gunicorn recommend to have reverse proxy running in front of this python process.
I use nginx+gunicorn in this case
bind as ```unix:///tmp/ckan.sock```
see sample gunicorn nginx config here
http://docs.gunicorn.org/en/stable/deploy.html#nginx-configuration

**Comment by elecdesa** [comment]
Yes, you right!!, 

Next step is try to install and configure Nginx in my enviroment!
Thanks!!

**Comment by torfsen** [comment]
@wardi Do you happen to know whether #3966 fixed this issue (so that it can be closed)?

**Comment by wardi** [comment]
@torfsen that's what it's supposed to fix but I haven't seen the original problem myself, this was just a change in line with some other recent fixes so I merged as-is.

**Comment by elecdesa** [comment]
@wardi it's supposed this fix will be available in next release or patch??. Thanks

**Comment by Ethel-Ecc** [comment]
@torfsen: I am experiencing this error as you mentioned 2 years ago on CKAN2.8 on Ubuntu 18.04 when deployed to server.
Here is my scenario:

 I am trying to test my deployed instance of CKAN v2.8. Everything works perfect, until I moved my local instance to the server. All the CRUD operations for registered users works perfectly on the local instance.

However, after following the instructions on deploying a CKAN source install: '[(https://docs.ckan.org/en/2.8/maintaining/installing/deployment.html' )] I was able to have the instance up and running. But, the authentication process breaks with the log error given below `(from/var/log/apache2/[filename].error.log).`

I have tried several steps to reconfigure my server, rechecked my permissions as given in the docs directive (`drwxr-xr-x` and `-rw-r--r--`), but the error still occurs.

**In plain terms. each time a registered user tries to log in to the instance or each time a new user registers, the error occurs.**

However, the error seems to be something from 'repoze' or 'middleware' stuff. That's what is really challenging, and it is just this error that blocks my workflow. 

- ` I am using - CKAN-Version 2.8, `
-  `On an - Ubuntu 18.04LTS machine.`

In my search for solution, I stumbled on the suggestion mentioned here which provided very little in my case.

Please, I do look forward to your responses.

Thanks in advance for taking time to read this, and for any suggestion/tips/insights you might have, I am very grateful. 

**Error message**
```
mod_wsgi (pid=5736): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
Traceback (most recent call last):
File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 409, in streaming_iter
for item in self.application(environ, start_response):
File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 117, in call
wrapper.finish_response(remember_headers)
File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 177, in finish_response
write = self.start_response(self.status, headers, self.exc_info)
TypeError: expected byte string object, value of type unicode foundmod_wsgi (pid=5736): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
Traceback (most recent call last):
File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 409, in streaming_iter
for item in self.application(environ, start_response):
File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 117, in call
wrapper.finish_response(remember_headers)
File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 177, in finish_response
write = self.start_response(self.status, headers, self.exc_info)
TypeError: expected byte string object, value of type unicode found
```
