### ISSUE TITLE
Installation Error - Could not connect to Redis

### ISSUE THREAD

**Issue by randerson5726** [ckan/ckan#3947]
### CKAN Version if known (or site URL)
2.7
Ubuntu 12.04 64bit
### Please describe the expected behaviour
No Errors...
Initialing DB: SUCCESS

### Please describe the actual behaviour
(default) ryan@RyanLaptop:/usr/lib/ckan/default/src/ckan$ sudo ckan db init
2017-12-04 19:54:13,926 ERROR [ckan.lib.redis] Redis is not available
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/redis.py", line 61, in is_redis_available
    return redis_conn.ping()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/redis/client.py", line 682, in ping
    return self.execute_command('PING')
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
2017-12-04 19:54:13,926 CRITI [ckan.config.environment] Could not connect to Redis.
Initialising DB: SUCCESS

### What steps can be taken to reproduce the issue? 
Follow [Install from Package](http://docs.ckan.org/en/ckan-2.7.0/maintaining/installing/install-from-package.html) to step 4. 

I went forward with the rest of the steps and the site does work. But I ran into issues trying to [add custom fields](http://docs.ckan.org/en/latest/extensions/adding-custom-fields.html)

Restarting the redis server did not help.

**Comment by torfsen** [comment]
Can you connect to Redis manually using the [Redis command line client](https://redis.io/topics/rediscli)?

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
