### ISSUE TITLE
JobTimeoutException: Job exceeded maximum timeout value (180 seconds)

### ISSUE THREAD

**Issue by s-chand** [ckan/ckan#3994]
### CKAN Version if known (or site URL)
CKAN 2.7

### Please describe the expected behaviour
expected behavior is to be able to configure background jobs timeout

### Please describe the actual behaviour
There should be a way to extend the timeout 

### What steps can be taken to reproduce the issue? 
1. I created a background job following the ckan documentation  [docs](http://docs.ckan.org/en/latest/maintaining/background-tasks.html)
2. Tried to pass `timeout=3600` as a parameter
3. Throws the following error:

```
(default) samuel@ckan:~$ paster --plugin=ckanext-gather2_integration gather2_integration load-data --config=/etc/ckan/default/development.ini
2018-01-23 10:52:41,374 DEBUG [ckanext.validation.plugin] Validation tables exist
Loading gather2 data
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckanext-gather2_integration/ckanext/gather2_integration/commands.py", line 47, in command
    self.run_load_data()
  File "/usr/lib/ckan/default/src/ckanext-gather2_integration/ckanext/gather2_integration/commands.py", line 59, in run_load_data
    get_action(u'gather2_integration_run')({'load-data':'true'})
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 457, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckanext-gather2_integration/ckanext/gather2_integration/logic.py", line 20, in gather2_integration_run
    enqueue_job(run_gather2_integration,[], timeout=3600)
  File "/usr/lib/ckan/default/src/ckanext-gather2_integration/ckanext/gather2_integration/logic.py", line 13, in enqueue_job
    return t.enqueue_job(*args, **kwargs)
TypeError: enqueue() got an unexpected keyword argument 'timeout'

```
4. Without the parameter it defaults to 180 seconds with the following error:
```
 r = requests.get(url, headers=headers)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 436, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1715, in do_handshake
    result = _lib.SSL_do_handshake(self._ssl)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/rq/timeouts.py", line 51, in handle_death_penalty
    'value ({0} seconds)'.format(self._timeout))
JobTimeoutException: Job exceeded maximum timeout value (180 seconds)
```
5. I need help.

**Comment by wardi** [comment]
Yes, it looks like we aren't passing the timeout value through to RQ's enqueue_call in https://github.com/ckan/ckan/blob/master/ckan/lib/jobs.py#L126

Should be a very small change, would you mind submitting a PR?

**Comment by s-chand** [comment]
Sure.

**Comment by torfsen** [comment]
Another possibility would be to add a configuration option to globally specify these timeouts.

**Comment by wardi** [comment]
![](http://i0.kym-cdn.com/photos/images/original/000/538/731/0fc.gif)

**Comment by torfsen** [comment]
@wardi Good idea: A default timeout that is configurable via the INI and can be overridden using a parameter while enqueuing a job.

**Comment by s-chand** [comment]
@torfsen Makes sense to do it that way. Should have the PR ready when I have a minute today. Thanks

**Comment by amercader** [comment]
@s-chand thanks! I've also been bitten by this

**Comment by jrdh** [comment]
Just been bitten by this one whilst using [ckanext-rq](https://github.com/ckan/ckanext-rq) and found this existing issue. It seems to have gone pretty stale since the start of the year, did anyone submit anything to resolve this in the end (to either here or to [ckanext-rq](https://github.com/ckan/ckanext-rq))? From looking around it doesn't look like it but thought it was worth making sure before I look at submitting a PR for it.

**Comment by torfsen** [comment]
@jrdh AFAIK there hasn't been any work on this issue, so feel free to submit a PR. You can probably reuse most of the code for a PR against CKAN for a similar one against ckanext-rq.

**Comment by jrdh** [comment]
:+1: thanks @torfsen, and yeah that's what I would expect too.

**Comment by Engerrs** [comment]
Hi @wardi and @amercader , it seems that this modification is not ported to CKAN 2.8 and 2.7. Can you please backport it there, thanks!
