### ISSUE TITLE
"paster --plugin=ckan db clean" tries to write into the 038_delete_migration_tables.pyc

### ISSUE THREAD

**Issue by nesnera** [ckan/ckan#4010]
### CKAN Version if known (or site URL)
$ paster db version
[(86,)]

### Please describe the expected behaviour
successfully executed a command

### Please describe the actual behaviour
$ paster --plugin=ckan db clean
Traceback (most recent call last):
  File "/nix/store/712hdbk5mnlg8cjrxvbqhx42rykfbmfx-python2.7-python2.7-PasteScript-2.0.2/bin/..paster-wrapped-wrapped", line 13, in <module>
    sys.exit(run())
  File "/nix/store/712hdbk5mnlg8cjrxvbqhx42rykfbmfx-python2.7-python2.7-PasteScript-2.0.2/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/nix/store/712hdbk5mnlg8cjrxvbqhx42rykfbmfx-python2.7-python2.7-PasteScript-2.0.2/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/nix/store/712hdbk5mnlg8cjrxvbqhx42rykfbmfx-python2.7-python2.7-PasteScript-2.0.2/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/nix/store/lbw4hvzjzjaz56i0lpp45mas7xknx4s2-python2.7-python2.7-ckan-2.8.0a0/lib/python2.7/site-packages/ckan/lib/cli.py", line 367, in command
    os.remove(f)
OSError: [Errno 30] Read-only file system: '/nix/store/lbw4hvzjzjaz56i0lpp45mas7xknx4s2-python2.7-python2.7-ckan-2.8.0a0/lib/python2.7/site-packages/ckan/lib/../migration/versions/038_delete_migration_tables.pyc'

### What steps can be taken to reproduce the issue? 
run paster --plugin=ckan db clean

**Comment by TkTech** [comment]
This isn't really a CKAN issue. CPython is compling .py files into cached .pyc bytecode files, except your folder permissions are incorrect. If you really don't want CPython to do any caching you can disable it with a CPython setting.
