### ISSUE TITLE
Source install error with who.ini

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#4020]
### CKAN Version if known (or site URL)
master

### Please describe the problem
When I follow the latest source instructions: [install-ckan-from-source](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html) I get an error when initializing the db:
```
(default) vagrant@ubuntu-xenial:/usr/lib/ckan/default/src/ckan$ paster db init -c /etc/ckan/default/development.ini
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 350, in command
    self._load_config(cmd!='upgrade')
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 323, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 236, in load_config
    app = make_app(conf.global_conf, **conf.local_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 58, in make_app
    **app_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/pylons_app.py", line 121, in make_pylons_stack
    who_parser.parse(open(app_conf['who.config_file']))
IOError: [Errno 2] No such file or directory: '/etc/ckan/default/who.ini'
```

**Comment by davidread** [comment]
This is fixed by doing the "Link to who.ini" step. I'll change the docs to move that step up the order.
