### ISSUE TITLE
CKAN unicode problem 

### ISSUE THREAD

**Issue by effdrums** [ckan/ckan#4128]
### CKAN Version if known (or site URL)
2.7 

### OS Ubuntu 14.04

I've followed the guide from [Instal guide](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html) ,and when I run the` paster serve /etc/ckan/default/development.ini` i get the following error: 

`2018-03-14 16:39:09,820 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
2018-03-14 16:39:10,063 ERROR [ckan.lib.search.common] 'ascii' codec can't decode byte 0xc3 in position 2374: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/common.py", line 57, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 387, in _send_request
    solr_message = self._extract_error(resp)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 496, in _extract_error
    reason, full_html = self._scrape_response(resp.headers, resp.content)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 527, in _scrape_response
    if response.startswith('<?xml'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2374: ordinal not in range(128)`

I think that this causes a Server Error visualitzation when accessing to the localhost:port 

Also when following the [Getting Started Guide](http://docs.ckan.org/en/latest/maintaining/getting-started.html) and run the `paster create-test-data -c /etc/ckan/default/production.ini` 

get the error: 

`2018-03-14 16:43:39,356 ERROR [ckan.lib.search.common] 'ascii' codec can't decode byte 0xc3 in position 2374: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/common.py", line 57, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 387, in _send_request
    solr_message = self._extract_error(resp)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 496, in _extract_error
    reason, full_html = self._scrape_response(resp.headers, resp.content)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 527, in _scrape_response
    if response.startswith('<?xml'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2374: ordinal not in range(128)
2018-03-14 16:43:39,357 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
2018-03-14 16:43:39,548 ERROR [ckan.lib.search.common] 'ascii' codec can't decode byte 0xc3 in position 2374: ordinal not in range(128)
`

I had trubbles installing with [#4043](https://github.com/ckan/ckan/issues/4043 ) but I don't know if could be related. 

I've been doing some research and there are many ways to solve the problem but I donn't know why it's this happening with th stable version from the begining. 

Did you had this problem before?  

Thanks!

**Comment by smotornyuk** [comment]
I need more details:) @effdrums , which version of solr are you using? As i remember, we need to make some changes in solrconfig.xml for SOLRv6.0-6.5.1. And if you are using newer version.. you should downgrade to SORLv5 :)

**Comment by effdrums** [comment]
Hey @smotornyuk I'm just running the solr 4.10.4 and the first requirements  are with that version, maybe  it can be reconsidered to upgrade it. 

Anyway, thanks for answering! 

Hope this give some clue

**Comment by boykoc** [comment]
Confirming I get a similar error when creating database tables (step 6) with Solr Specification Version: 3.6.2.2015.11.20.05.14.33 and CKAN 2.7.3 on ubuntu 16.

Error after running db cmd (`paster db init -c /etc/ckan/default/development.ini`):

```
2018-05-09 12:01:41,594 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
2018-05-09 12:01:41,859 ERROR [ckan.lib.search.common] 'ascii' codec can't decode byte 0xc2 in position 2273: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/cody/ckan/lib/default/src/ckan/ckan/lib/search/common.py", line 57, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 387, in _send_request
    solr_message = self._extract_error(resp)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 496, in _extract_error
    reason, full_html = self._scrape_response(resp.headers, resp.content)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 527, in _scrape_response
    if response.startswith('<?xml'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2273: ordinal not in range(128)
2018-05-09 12:01:41,859 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
Initialising DB: SUCCESS

```

**Comment by ccancellieri** [comment]
Getting the same with CKAN-2.8.6 and tomcat-solr

solr-common/bionic-updates,bionic-security,now 3.6.2+dfsg-18~18.04 all [installed,automatic]
  Enterprise search server based on Lucene3 - common files

solr-tomcat/bionic-updates,bionic-security,now 3.6.2+dfsg-18~18.04 all [installed]
  Enterprise search server based on Lucene3 - Tomcat integration

Not sure if related but everything was working then immediately after installation of this plugin
https://github.com/TerriaJS/ckanext-terria_view

this issue pops up...
