### ISSUE TITLE
urllib2.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Cheomm88** [ckan/ckan#4170]
Hello,
I'm not sure if here is the right place to ask this... I am installing CKAN 2.7.3 with solR 6.0.0. I have acces to solR .

For example if I lauch the URl http://localhost:8983/solr/core0/select?indent=on&q=*:*&wt=json I get:4

> {
>   "responseHeader":{
>     "status":0,
>     "QTime":0,
>     "params":{
>       "q":"*:*",
>       "indent":"on",
>       "wt":"json"}},
>   "response":{"numFound":0,"start":0,"docs":[]
>   }}

In my development.ini I wrote:

> solr_url = http://localhost:8983/solr/core0/

### CKAN Version if known (or site URL)
2.7.3

### SOLR Version if known (or site URL)
6.0.0

### Please describe the expected behaviour
During the installation I have to execute paster db init -c /etc/ckan/default/development.ini and get a "Initialising DB: SUCCESS." without errors.

### Please describe the actual behaviour

When I ran paster db init -c /etc/ckan/default/development.ini I get an error.

```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 333, in command
    self._load_config(cmd!='upgrade')
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 306, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 221, in load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 99, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 129, in load_all
    unload_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 182, in unload_all
    unload(*reversed(_PLUGINS))
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 210, in unload
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 121, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 207, in update_config
    search.check_solr_schema_version()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 291, in check_solr_schema_version
    res = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

### What steps can be taken to reproduce the issue? 

??

I have tried the solution given in https://github.com/ckan/ckan/issues/3829#issuecomment-331832110 any idea?

**Comment by Cheomm88** [comment]
I found that if I edit the development.ini

> solr_url = http://127.0.0.1:8983/solr

The error changes:

paster db init -c /etc/ckan/default/development.ini
2018-04-03 14:36:55,470 ERROR [pysolr] Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
2018-04-03 14:36:55,471 ERROR [ckan.lib.search.common] Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/common.py", line 57, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
SolrError: Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
2018-04-03 14:36:55,474 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
2018-04-03 14:36:56,338 ERROR [pysolr] Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
2018-04-03 14:36:56,339 ERROR [ckan.lib.search.common] Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/common.py", line 57, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
**SolrError: Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
2018-04-03 14:36:56,340 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server**
2018-04-03 14:36:56,440 ERROR [ckan.lib.redis] Redis is not available
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/redis.py", line 61, in is_redis_available
    return redis_conn.ping()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/redis/client.py", line 682, in ping
    return self.execute_command('PING')
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
2018-04-03 14:36:56,446 CRITI [ckan.config.environment] Could not connect to Redis.
Initialising DB: SUCCESS


It "finishes" the process but still I see issues with the connection to solR, so I understand that previously the setting was right using:
>solr_url = http://localhost:8983/solr/core0/

Using the PG Admin I can see the tables created, but I don't think the instalation has finished correctly

**Comment by Cheomm88** [comment]
I had to run 

> service redis start
> service redis status

Now after running paster db init -c /etc/ckan/default/development.ini I didn't get any error.  But I'm still getting the message

>There was an error while searching. Please try again.

**Comment by TkTech** [comment]
That change was just to ensure you're actually able to connect to solr. At a guess, you don't appear to have successfully installed the CKAN schema.xml although without the traceback I can only guess.

Since this is not a technical  #issue with CKAN I will close this. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow. You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.
