### ISSUE TITLE
Flash message cannot be added when run within tests for plugin

### ISSUE THREAD

**Issue by spikeheap** [ckan/ckan#4216]
### CKAN Version if known (or site URL)
2.7.2

### Please describe the expected behaviour
Given an `IPackageController`-extending plugin with an `after_create` hook which uses flash messages
When I create a new dataset
The text passed to `helpers.flash_error` is displayed on screen
AND a test can be written to exercise this behaviour

### Please describe the actual behaviour
The flash message is displayed on-screen, however if the page is visited in a test the following error occurs:

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/ckan/default/src/plugins/ckanext-radar_dms/ckanext/radar_dms/tests/test_pa_integration.py", line 251, in test_no_link_supplied_to_config_ui
    dataset, resources = self.__create_dataset(user, 'editor', 'project')
  File "/usr/lib/ckan/default/src/plugins/ckanext-radar_dms/ckanext/radar_dms/tests/test_pa_integration.py", line 342, in __create_dataset
    dataset = factories.Dataset(owner_org=org['id'], radar_dataset_type=radar_dataset_type)
  File "/usr/local/lib/python2.7/site-packages/factory/base.py", line 80, in __call__
    return cls.create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/factory/base.py", line 453, in create
    return cls._generate(True, attrs)
  File "/usr/local/lib/python2.7/site-packages/factory/base.py", line 378, in _generate
    obj = cls._prepare(create, **attrs)
  File "/usr/local/lib/python2.7/site-packages/factory/base.py", line 358, in _prepare
    return cls._create(target_class, *args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/tests/factories.py", line 336, in _create
    **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/tests/helpers.py", line 109, in call_action
    return logic.get_action(action_name)(context=context, data_dict=kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 457, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 210, in package_create
    item.after_create(context, data)
  File "/usr/lib/ckan/default/src/plugins/ckanext-radar_dms/ckanext/radar_dms/plugin.py", line 170, in after_create
    helpers.flash_error("EXT API integration is not configured")
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 528, in flash_error
    flash(message, category='alert-error', allow_html=allow_html)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 490, in __call__
    messages = session.setdefault(self.session_key, [])
  File "/usr/local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
    return getattr(self._current_obj(), attr)
  File "/usr/local/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
    'thread' % self.____name__)
TypeError: No object (name: session) has been registered for this thread
```

It seems to be throwing `TypeError: No object (name: session) has been registered for this thread` when it tries to add the flash message to the session. Note that this does work when you run through the process manually. It only seems to affect tests.

### What steps can be taken to reproduce the issue? 
The test we've devised is:

```python
@responses.activate
def test_no_link_to_config_ui_for_anonymous_user(self):
  config['ckan.custom_plugin.config_api_url'] = 'http://example.com'

  app = ckan.config.middleware.make_app(config['global_conf'], **config)
  self.app = webtest.TestApp(app)

  ckan.plugins.load('custom_plugin')

  # ... omitted response expectations and passthru for Solr

  org = factories.Organization(users=[{'name': user['name'], 'capacity': capacity}])
  dataset = factories.Dataset(owner_org=org['id'], custom_dataset_type='special')
  # ^^^^^ This line throws the error shown above

  response = self.app.get("/dataset/" + dataset['id'], extra_environ={'REMOTE_USER': str(user['name'])})

  response.mustcontain("My Flash Message")
```
The plugin is:

```python
import ckan.lib.helpers as helpers

class MyapiPlugin(plugins.SingletonPlugin):
  plugins.implements(plugins.IConfigurer)
  plugins.implements(plugins.IPackageController)
  plugins.implements(plugins.IRoutes, inherit=True)
  plugins.implements(plugins.ITemplateHelpers)

  # ... omitting non-controller code for brevity

  def read(self, entity):
      pass

  def create(self, entity):
      pass

  def edit(self, entity):
      pass

  def delete(self, entity):
      pass

  def after_create(self, context, pkg_dict):
      helpers.flash_error("My Flash Message")
      return pkg_dict

  def after_update(self, context, pkg_dict):
      return pkg_dict

  def after_delete(self, context, pkg_dict):
      pass

  def after_show(self, context, pkg_dict):
      pass

  def before_search(self, search_params):
      return search_params

  def after_search(self, search_results, search_params):
      return search_results

  def before_index(self, pkg_dict):
      return pkg_dict

  def before_view(self, pkg_dict):
      return pkg_dict
```

Are we doing anything obviously wrong?

**Comment by spikeheap** [comment]
This looks like we can't access the session object within the plugin code, just because we're in a test environment. Is there some setup required that's not in the docs?

**Comment by spikeheap** [comment]
In case it helps, we also have a more standard controller where this _isn't_ a problem:

```python
from ckan.common import config, c
from ckan.controllers.package import PackageController
import ckan.lib.helpers as helpers
import ckan.plugins as plugins

class CustomInteractionController(PackageController):

    def retry_stub_creation(self, id):
        helpers.flash_success('Hallloo')
```
So this issue appears to be isolated to the `IPackageController`

**Comment by amercader** [comment]
Can you try to run the tests using the `FunctionalTestBase` helper object? That might help setting everything up correctly:

```python

class MyTest(helpers.FunctionalTestBase):

    _load_plugins = ['custom_plugin']
    
    @responses.activate
    @helpers.change_config('ckan.custom_plugin.config_api_url', 'http://example.com')
    def test_no_link_to_config_ui_for_anonymous_user(self):

        app = self._get_test_app()

        org = factories.Organization(users=[{'name': user['name'], 'capacity': capacity}])
        dataset = factories.Dataset(owner_org=org['id'], custom_dataset_type='special')

        response = app.get("/dataset/" + dataset['id'], extra_environ={'REMOTE_USER': str(user['name'])})

        assert "My Flash Message" in response
```

**Comment by spikeheap** [comment]
Hi @amercader, thanks so much for getting back to me. 

Firstly, cheers for the much neater approach to structuring the tests. I'll be refactoring a fair bit now.

Changing to extend `FunctionalTestBase` hasn't resolved the issue, but it has helped me whittle it down a bit more. 

Flash messages are working *fine* for standard page requests. The part that breaks is the factories, so in this case calling `factories.Dataset(...)` raises the error. Could this be because it's doing the following:

```python
helpers.call_action('package_create', context=context, **kwargs)
```

Then, when it hits the `after_create` hook, maybe it's outside of a request/response and therefore doesn't have a session.

**Comment by spikeheap** [comment]
Hi, I've just come up against this issue again with an `after_show` hook:

```
def after_show(self, context, pkg_dict):
    helpers.flash_error("This throws an error when it tries to flash in tests")
```

Strangely, the same code works *fine* in `before_view`, but we can't use it there because `before_view` gets called on the dataset list/search page as well as the single dataset view.

Any help here would be much appreciated, as we're a little flummoxed about how to hook in to _only_ the single dataset view page.

**Comment by spikeheap** [comment]
I'm guessing this is a very stale issue now, so I'll close it off 🤗 . Sadly I don't use CKAN in my day to day work anymore, so I've no idea if this is still present.
