### ISSUE TITLE
/api fails after upgrade 2.7 to 2.8

### ISSUE THREAD

**Issue by tedstrauss** [ckan/ckan#4321]
### CKAN Version if known (or site URL)

2.8
Error occurs after doing an package install upgrade from CKAN 2.7 to 2.8.
The upgrade has otherwise gone smoothly. 
The bug was detected while trying to test datapusher and rebuilding resource views - still broken.

### Please describe the expected behaviour

Access the CKAN api through browser interface.

### Please describe the actual behaviour

loading the /api page returns an "Internal Server Error" apache error page.
The apache error log is included below.

```
[Thu Jul 05 15:17:13.486351 2018] [:error] [pid 1755] [remote 127.0.0.1:9603] [2018-07-05 15:17:13,485] ERROR in app: Exception on /api/ [GET]
[Thu Jul 05 15:17:13.486378 2018] [:error] [pid 1755] [remote 127.0.0.1:9603] Traceback (most recent call last):
[Thu Jul 05 15:17:13.486387 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
[Thu Jul 05 15:17:13.486395 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     response = self.full_dispatch_request()
[Thu Jul 05 15:17:13.486403 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
[Thu Jul 05 15:17:13.486411 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     rv = self.handle_user_exception(e)
[Thu Jul 05 15:17:13.486420 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
[Thu Jul 05 15:17:13.486428 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     reraise(exc_type, exc_value, tb)
[Thu Jul 05 15:17:13.486435 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
[Thu Jul 05 15:17:13.486445 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     rv = self.preprocess_request()
[Thu Jul 05 15:17:13.486453 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
[Thu Jul 05 15:17:13.486461 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     rv = func()
[Thu Jul 05 15:17:13.486468 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 281, in ckan_before_request
[Thu Jul 05 15:17:13.486476 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     identify_user()
[Thu Jul 05 15:17:13.486483 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/src/ckan/ckan/views/__init__.py", line 100, in identify_user
[Thu Jul 05 15:17:13.486490 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     item.identify()
[Thu Jul 05 15:17:13.486498 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/src/ckanext-ldap/ckanext/ldap/plugin.py", line 123, in identify
[Thu Jul 05 15:17:13.486505 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     user = pylons.session.get('ckanext-ldap-user')
[Thu Jul 05 15:17:13.486513 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
[Thu Jul 05 15:17:13.486520 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     return getattr(self._current_obj(), attr)
[Thu Jul 05 15:17:13.486528 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
[Thu Jul 05 15:17:13.486535 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     'thread' % self.____name__)
[Thu Jul 05 15:17:13.486571 2018] [:error] [pid 1755] [remote 127.0.0.1:9603] TypeError: No object (name: session) has been registered for this thread
[Thu Jul 05 15:17:13.486735 2018] [:error] [pid 1755] [remote 127.0.0.1:9603] mod_wsgi (pid=1755): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Thu Jul 05 15:17:13.486772 2018] [:error] [pid 1755] [remote 127.0.0.1:9603] Traceback (most recent call last):
[Thu Jul 05 15:17:13.486798 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
[Thu Jul 05 15:17:13.486830 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     return self.apps[app_name](environ, start_response)
[Thu Jul 05 15:17:13.486847 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
[Thu Jul 05 15:17:13.486874 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     app_iter = app(environ, wrapper.wrap_start_response)
[Thu Jul 05 15:17:13.486895 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
[Thu Jul 05 15:17:13.486921 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     resp = self.call_func(req, *args, **self.kwargs)
[Thu Jul 05 15:17:13.486937 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
[Thu Jul 05 15:17:13.486965 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     return self.func(req, *args, **kwargs)
[Thu Jul 05 15:17:13.486982 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
[Thu Jul 05 15:17:13.487007 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     return request.get_response(self.app)
[Thu Jul 05 15:17:13.487029 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
[Thu Jul 05 15:17:13.487058 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     application, catch_exc_info=False)
[Thu Jul 05 15:17:13.487075 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
[Thu Jul 05 15:17:13.487099 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     app_iter = application(self.environ, start_response)
[Thu Jul 05 15:17:13.487114 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
[Thu Jul 05 15:17:13.487142 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     resp = self.call_func(req, *args, **self.kwargs)
[Thu Jul 05 15:17:13.487158 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
[Thu Jul 05 15:17:13.487182 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     return self.func(req, *args, **kwargs)
[Thu Jul 05 15:17:13.487197 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
[Thu Jul 05 15:17:13.487229 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     response = request.get_response(self.app)
[Thu Jul 05 15:17:13.487246 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
[Thu Jul 05 15:17:13.487269 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     application, catch_exc_info=False)
[Thu Jul 05 15:17:13.487289 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
[Thu Jul 05 15:17:13.487317 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     app_iter = application(self.environ, start_response)
[Thu Jul 05 15:17:13.487347 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
[Thu Jul 05 15:17:13.487374 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     return self.wsgi_app(environ, start_response)
[Thu Jul 05 15:17:13.487391 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
[Thu Jul 05 15:17:13.487416 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     return self.wrap_app(environ, session_start_response)
[Thu Jul 05 15:17:13.487431 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
[Thu Jul 05 15:17:13.487455 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     response = self.handle_exception(e)
[Thu Jul 05 15:17:13.487475 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1547, in handle_exception
[Thu Jul 05 15:17:13.487500 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     return self.finalize_request(handler(e), from_error_handler=True)
[Thu Jul 05 15:17:13.487516 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 411, in error_handler
[Thu Jul 05 15:17:13.487540 2018] [:error] [pid 1755] [remote 127.0.0.1:9603]     extra_vars = {u'code': e.code, u'content': e.description}
[Thu Jul 05 15:17:13.487565 2018] [:error] [pid 1755] [remote 127.0.0.1:9603] AttributeError: 'exceptions.TypeError' object has no attribute 'code'
```

### What steps can be taken to reproduce the issue? 

Upgrade CKAn from 2.7 .to 2.8.

**Comment by rossjones** [comment]
The root of the error is at 

```
File "/usr/lib/ckan/default/src/ckanext-ldap/ckanext/ldap/plugin.py", line 123, in identify
    user = pylons.session.get('ckanext-ldap-user')
```

It looks like `pylons.session` is not available in flask requests... would it be possible to log the issue over there as well?

**Comment by tedstrauss** [comment]
Disabling the LDAP extension did fix the bug.
So the problem must be extension specific.
