### ISSUE TITLE
[stats]: Error - <type 'exceptions.AttributeError'>: 'module' object has no attribute 'vendor/block_html5_shim'

### ISSUE THREAD

**Issue by saper** [ckan/ckan#4336]
### CKAN Version if known (or site URL)

2.8.0

(not public yet)

### Please describe the expected behaviour

/stats plugin should load

### Please describe the actual behaviour

Exception:

````
Exception happened during processing of request from ('172.17.20.12', 36335)
Traceback (most recent call last):
  File "/usr/home/ckan/ukraine/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Error - <type 'exceptions.AttributeError'>: 'module' object has no attribute 'vendor/block_html5_shim'
URL: http://xxxxx/stats
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/weberror/errormiddleware.py', line 171 in __call__
  app_iter = self.application(environ, sr_checker)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/home/ckan/ckan/ckan/config/middleware/pylons_app.py', line 265 in inner
  result = application(environ, start_response)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/beaker/middleware.py', line 156 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/usr/home/ckan/ckan/ckan/config/middleware/common_middleware.py', line 30 in __call__
  return self.app(environ, start_response)
File '/usr/home/ckan/ckan/ckan/config/middleware/common_middleware.py', line 56 in __call__
  return self.app(environ, start_response)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/usr/home/ckan/ckan/ckan/lib/base.py', line 240 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/usr/home/ckan/ckan/ckanext/stats/controller.py', line 41 in index
  return p.toolkit.render('ckanext/stats/index.html')
File '/usr/home/ckan/ckan/ckan/lib/base.py', line 125 in render
  return cached_template(template_name, renderer)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/usr/home/ckan/ckan/ckan/lib/base.py', line 162 in render_template
  return render_jinja2(template_name, globs)
File '/usr/home/ckan/ckan/ckan/lib/base.py', line 94 in render_jinja2
  return template.render(**extra_vars)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/jinja2/environment.py', line 989 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/home/ckan/ukraine/lib/python2.7/site-packages/jinja2/environment.py', line 754 in handle_exception
  reraise(exc_type, exc_value, tb)
File '/usr/home/ckan/ckan/ckanext/stats/templates/ckanext/stats/index.html', line 1 in top-level template code
  {% extends "page.html" %}
File '/usr/home/ckan/ckan/ckan/templates/page.html', line 1 in top-level template code
  {% extends "base.html" %}
File '/usr/home/ckan/ckan/ckan/templates/base.html', line 108 in top-level template code
  {%- block scripts %}
File '/usr/home/ckan/ckan/ckanext/stats/templates/ckanext/stats/index.html', line 197 in block "scripts"
  {% resource "vendor/block_html5_shim" %}
File '/usr/home/ckan/ckan/ckan/lib/jinja_extensions.py', line 328 in _call
  h.include_resource(args[0], **kwargs)
File '/usr/home/ckan/ckan/ckan/lib/helpers.py', line 1857 in include_resource
  r = getattr(fanstatic_resources, resource)
AttributeError: 'module' object has no attribute 'vendor/block_html5_shim'

````

### What steps can be taken to reproduce the issue? 

Fresh install of CKAN 2.8.0 with "stats" plugin enabled

Navigate to /stats

Fix is trivial, will submit PR

**Comment by amercader** [comment]
@saper thanks, a PR would be good
