### ISSUE TITLE
Datasets Disappearing

### ISSUE THREAD

**Issue by kbajura** [ckan/ckan#4364]
### CKAN Version if known (or site URL)
2.9

### Please describe the expected behaviour
Dataset do not disappear and rebuild index does not crash.

### Please describe the actual behaviour
Datasets will disappear and rebuild index fails with error. When checking the index status, none of our datasets were indexed but some were still displaying. When we tried to rebuild the index, it crashed and all of the datasets no longer displayed. To correct this, we needed to add a resource to each dataset and then they were displayed again and they were shown as listed.

### What steps can be taken to reproduce the issue? 
Running the rebuild index crashes with the following:

```
(default) ckan@ckan2:/usr/lib/ckan/default/src/ckan$ paster --plugin=ckan search-index rebuild  --config=/etc/ckan/default/production.ini
Indexing dataset 1/16Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 579, in command
    self.rebuild()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 602, in rebuild
    quiet=self.options.quiet)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 194, in rebuild
    defer_commit
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 102, in update_dict
    self.index_package(pkg_dict, defer_commit)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 160, in index_package
    vocab = logic.get_action('vocabulary_show')(context, data)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 464, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 2433, in vocabulary_show
    _check_access('vocabulary_show', context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 306, in check_access
    raise NotAuthorized(msg)
ckan.logic.NotAuthorized

```

**Comment by kbajura** [comment]
I think I solved this issue myself. I deleted the default sysadmin account and after that I couldn't do some paster commands. Does paster use the "default" account when it execute commands? Could this account be needed to update the indexes because the missing dataset didn't have an index and I couldn't create one since the default account was gone.

**Comment by amercader** [comment]
Yes, that's probably what happened, the index was cleared but then new datasets could not be created because of the authorization failure. The default sysadmin account is required to run internal commands. Glad you got it working.
