### ISSUE TITLE
PylonsTestCase/flask-related test errors on master

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#4372]
Test errors on master due to dependencies between the tests, that circleci isn't seeing (because it runs them in parallel):
```
$ nosetests --ckan --with-pylons=test-core.ini ckan
No handlers could be found for logger "ckan.lib.uploader"
......................................./usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py:2181: SAWarning: Usage of the 'related attribute set' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
  % method)
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................../usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py:624: SAWarning: Can't resolve label reference 'total DESC'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
.....................................................................................................................................................................................................S...........S................................................................................................................................................................................................................................................................................................S............................................................................................................................................................Error: you need to specify the user name.
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................FFF.E.....................
======================================================================
ERROR: ckan.tests.test_common.TestCommonRequest.test_params_also_works_on_flask_request
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/vagrant/src/ckan/ckan/tests/test_common.py", line 227, in test_params_also_works_on_flask_request
    assert u'a' in ckan_request.args
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
    return getattr(self._current_obj(), attr)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1181, in __getattr__
    raise AttributeError(attr)
AttributeError: args

======================================================================
FAIL: ckan.tests.test_common.TestCommonG.test_accessing_missing_key_raises_error_on_flask_request
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/vagrant/src/ckan/ckan/tests/test_common.py", line 273, in test_accessing_missing_key_raises_error_on_flask_request
    assert_raises(AttributeError, getattr, ckan_g, u'user')
AssertionError: AttributeError not raised

======================================================================
FAIL: ckan.tests.test_common.TestCommonG.test_can_also_use_c_on_a_flask_request
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/vagrant/src/ckan/ckan/tests/test_common.py", line 261, in test_can_also_use_c_on_a_flask_request
    eq_(ckan_c.user, u'example')
AssertionError: u'test.ckan.net' != u'example'

======================================================================
FAIL: ckan.tests.test_common.TestCommonG.test_flask_g_is_used_on_a_flask_request
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/vagrant/src/ckan/ckan/tests/test_common.py", line 247, in test_flask_g_is_used_on_a_flask_request
    assert u'flask.g' in text_type(ckan_g)
AssertionError

----------------------------------------------------------------------
Ran 1975 tests in 1090.621s

FAILED (SKIP=3, errors=1, failures=3)
```
The problem seems to be some bad clean-up after using PylonsTestCase that has been exposed for some reason following recent changes. I can reproduce the error quickly like this:
```
$ nosetests --ckan --with-pylons=test-core.ini ckan/tests/legacy/functional/api/test_user.py:TestCreateUserApiDisabled.test_user_create_api_disabled_anon ckan/tests/test_common.py:TestCommonG.test_accessing_missing_key_raises_error_on_flask_request -v -x
No handlers could be found for logger "ckan.lib.uploader"

======================================================================
FAIL: ckan.tests.test_common.TestCommonG.test_accessing_missing_key_raises_error_on_flask_request
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/vagrant/src/ckan/ckan/tests/test_common.py", line 273, in test_accessing_missing_key_raises_error_on_flask_request
    assert_raises(AttributeError, getattr, ckan_g, u'user')
AssertionError: AttributeError not raised

----------------------------------------------------------------------
Ran 2 tests in 2.451s

FAILED (failures=1)
```

**Comment by tino097** [comment]
As this is merged, can you guys try to run the tests locally to check if everything is ok

@davidread @wardi @klikstermkd

**Comment by davidread** [comment]
I think this is all ok now. Thanks for your hard work on this @tino097 !
