### ISSUE TITLE
'ascii' codec can't decode byte 0xe9 in position 103: ordinal not in range(128)

### ISSUE THREAD

**Issue by TheMMcOfficial** [ckan/ckan#4444]
### CKAN Version if known (or site URL)
2.8

### What steps can be taken to reproduce the issue? 
when I try to import the data from my older server I got this:

``` paster search-index rebuild --config=/ckan/default/production.ini
2018-09-05 09:32:28,047 DEBUG [ckan.lib.fanstatic_resources] Base path /ckan/default/src/ckan/ckan/public/base
Traceback (most recent call last):
  File "/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/ckan/default/src/ckan/ckan/lib/cli.py", line 579, in command
    self.rebuild()
  File "/ckan/default/src/ckan/ckan/lib/cli.py", line 602, in rebuild
    quiet=self.options.quiet)
  File "/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 179, in rebuild
    package_index.clear()
  File "/ckan/default/src/ckan/ckan/lib/search/index.py", line 89, in clear
    clear_index()
  File "/ckan/default/src/ckan/ckan/lib/search/index.py", line 53, in clear_index
    conn.delete(q=query)
  File "/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 924, in delete
    return self._update(m, commit=commit, softCommit=softCommit, waitFlush=waitFlush, waitSearcher=waitSearcher, handler=handler)
  File "/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 478, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 387, in _send_request
    solr_message = self._extract_error(resp)
  File "/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 496, in _extract_error
    reason, full_html = self._scrape_response(resp.headers, resp.content)
  File "/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 527, in _scrape_response
    if response.startswith(u'<?xml'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 103: ordinal not in range(128)
```
or

``` paster search-index rebuild -r --config=/ckan/default/production.ini
2018-09-05 09:42:58,997 DEBUG [ckan.lib.fanstatic_resources] Base path /ckan/default/src/ckan/ckan/public/base
Traceback (most recent call last):
  File "/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/ckan/default/src/ckan/ckan/lib/cli.py", line 579, in command
    self.rebuild()
  File "/ckan/default/src/ckan/ckan/lib/cli.py", line 605, in rebuild
    commit()
  File "/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 211, in commit
    package_index.commit()
  File "/ckan/default/src/ckan/ckan/lib/search/index.py", line 316, in commit
    raise SearchIndexError(e)
ckan.lib.search.common.SearchIndexError: 'ascii' codec can't decode byte 0xe9 in position 103: ordinal not in range(128)```

**Comment by TheMMcOfficial** [comment]
`paster search-index rebuild --config=../../production.ini
2018-09-05 11:58:03,303 DEBUG [ckan.lib.fanstatic_resources] Base path /ckan/default/src/ckan/ckan/public/base
Traceback (most recent call last):
  File "/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/ckan/default/src/ckan/ckan/lib/cli.py", line 579, in command
    self.rebuild()
  File "/ckan/default/src/ckan/ckan/lib/cli.py", line 602, in rebuild
    quiet=self.options.quiet)
  File "/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 179, in rebuild
    package_index.clear()
  File "/ckan/default/src/ckan/ckan/lib/search/index.py", line 89, in clear
    clear_index()
  File "/ckan/default/src/ckan/ckan/lib/search/index.py", line 61, in clear_index
    raise SearchIndexError(err)
ckan.lib.search.common.SearchIndexError: SOLR 'http://SERVER:8983/solr/ckan' exception: SolrError(u'Solr responded with an error (HTTP 400): [Reason: undefined field site_id]',)
`

**Comment by wardi** [comment]
Your first traceback suggests we're not handling some unicode strings correctly. Have you customized indexing at all in an extension with `before_index`? Have you included unicode characters in your configuration (e.g. site_id) that we might not be expecting? Are you able to help narrow down the record that's causing the failure by showing us the record being passed to solr? If you're not comfortable editing the code try running the search-index rebuild with a known package id and send us that dataset metadata (JSON).

The second traceback might indicate not having the correct schema installed but I'm not sure. Can you provide more information to help reproduce this too?
