### ISSUE TITLE
New CKAN server, same IP: user partially logged in

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#4496]
### CKAN Version if known (or site URL)
2.8.1

### Please describe the expected behaviour
On a new CKAN instance with a different database, my old username (that does not exist anymore) should not be recognized.

### Please describe the actual behaviour
"Log in" button is available, but CKAN says that I am already logged ([screenshot](https://screenshots.firefox.com/WrPbYqDCP6Trn5O5/127.0.0.1)).

### What steps can be taken to reproduce the issue? 
Launch CKAN, create an user, log in, reset everything, refresh your browser.
Removing the `auth_tkt` fixes the issue.

**Comment by frafra** [comment]
Something bad is happening on the server:

```
 Traceback (most recent call last):
   File "/usr/local/bin/ckan-paster", line 11, in <module>
     sys.exit(run())
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
     invoke(command, command_name, options, args[1:])
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
     exit_code = runner.run(args)
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
     result = self.command()
   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 706, in command
     self.add()
   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 733, in add
     user = model.User.by_name(text_type(username))
   File "/usr/lib/ckan/venv/src/ckan/ckan/model/domain_object.py", line 46, in by_name
     .filter_by(name=name).first()
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2755, in first
     ret = list(self[0:1])
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
     return list(res)
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
     return self._execute_and_instances(context)
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
     result = conn.execute(querycontext.statement, self._params)
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
     return meth(self, multiparams, params)
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
     return connection._execute_clauseelement(self, multiparams, params)
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
     compiled_sql, distilled_params
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
     context)
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
     exc_info
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
     reraise(type(exception), exception, tb=exc_tb, cause=cause)
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
     context)
   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
     cursor.execute(statement, parameters)
 sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "user" does not exist
 LINE 2: FROM "user"
              ^
  [SQL: 'SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".fullname AS user_fullname, "user".email AS user_email, "user".apikey AS user_apikey, "user".created AS user_created, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".activity_streams_email_notifications AS user_activity_streams_email_notifications, "user".sysadmin AS user_sysadmin, "user".state AS user_state \nFROM "user" \nWHERE "user".name = %(name_1)s ORDER BY "user".name \n LIMIT %(param_1)s'] [parameters: {'name_1': u'administrator', 'param_1': 1}]
```

**Comment by wardi** [comment]
try with a different configuration file (specifically a different `beaker.session.secret`) that will make all old login tokens invalid.

**Comment by frafra** [comment]
Thank you @wardi, this is interesting. Nonetheless I find strange that the main page and the navbar have different opinions about my user being logged in or not.

**Comment by wardi** [comment]
By trusting the auth cookies it should be possible to avoid a database call on some page loads, but you're right it is strange and we should be forcing someone to be properly logged out if their account has been removed. Would you like to work on a fix?

**Comment by frafra** [comment]
I would be happy to contribute to ckan, but I just started to use it and to develop a plugin. After I will publish a preliminary version of my work, I should have enough familiarity with the code and time to pick a couple of bugs and fix them. I hope to start soon by the way (that is way I did a small pull request for the docker-compose.yml that should fix a known issue I had).

**Comment by shubham-mahajan** [comment]
# Analysis

The issue is in the auth_tkt cookie used by ckan.

The identity of the cookie is happening by the below method and whenever the person logout the cookie is deleting but by using the same cookie again it will return the timestamp, user id, token, user_data from the cookie and that has valid data, so the user is logged in again.


```python
def identify(self, environ):
        cookies = get_cookies(environ)
        cookie = cookies.get(self.cookie_name)

        if cookie is None or not cookie.value:
            return None

        if self.include_ip:
            remote_addr = environ['REMOTE_ADDR']
        else:
            remote_addr = '0.0.0.0'
        
        try:
            timestamp, userid, tokens, user_data = auth_tkt.parse_ticket(
                self.secret, cookie.value, remote_addr, self.digest_algo)
        except auth_tkt.BadTicket:
            return None

        if self.timeout and ( (timestamp + self.timeout) < time.time() ):
            return None

        user_data_dict = dict(parse_qsl(user_data))
        userid_type = user_data_dict.get(self.userid_typename)
        if userid_type:
            decoder = self.userid_type_decoders.get(userid_type)
            if decoder:
                userid = decoder(userid)
            
        environ['REMOTE_USER_TOKENS'] = tokens
        environ['REMOTE_USER_DATA'] = user_data
        environ['AUTH_TYPE'] = 'cookie'

        identity = {}
        identity['timestamp'] = timestamp
        identity['repoze.who.plugins.auth_tkt.userid'] = userid
        identity['tokens'] = tokens
        identity['userdata'] = user_data_dict
        return identity
```

# Possible Solution

1. Using the Database for the validation of the identity
2. Use Redis for storing cookie and validating cookie from the stored location instead of using the plain conversion of cookie to data and use as identity.

**Comment by shubham-mahajan** [comment]
# Analysis

The issue is in the auth_tkt cookie used by ckan.

The identity of the cookie is happening by the below method and whenever the person logout the cookie is deleting but by using the same cookie again it will return the timestamp, user id, token, user_data from the cookie and that has valid data, so the user is logged in again.


```python
def identify(self, environ):
        cookies = get_cookies(environ)
        cookie = cookies.get(self.cookie_name)

        if cookie is None or not cookie.value:
            return None

        if self.include_ip:
            remote_addr = environ['REMOTE_ADDR']
        else:
            remote_addr = '0.0.0.0'
        
        try:
            timestamp, userid, tokens, user_data = auth_tkt.parse_ticket(
                self.secret, cookie.value, remote_addr, self.digest_algo)
        except auth_tkt.BadTicket:
            return None

        if self.timeout and ( (timestamp + self.timeout) < time.time() ):
            return None

        user_data_dict = dict(parse_qsl(user_data))
        userid_type = user_data_dict.get(self.userid_typename)
        if userid_type:
            decoder = self.userid_type_decoders.get(userid_type)
            if decoder:
                userid = decoder(userid)
            
        environ['REMOTE_USER_TOKENS'] = tokens
        environ['REMOTE_USER_DATA'] = user_data
        environ['AUTH_TYPE'] = 'cookie'

        identity = {}
        identity['timestamp'] = timestamp
        identity['repoze.who.plugins.auth_tkt.userid'] = userid
        identity['tokens'] = tokens
        identity['userdata'] = user_data_dict
        return identity
```

# Possible Solution

1. Using the Database for the validation of the identity
2. Use Redis for storing cookie and validating cookie from the stored location instead of using the plain conversion of cookie to data and use as identity.
