### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#4516]
### CKAN Version if known (or site URL)
2.8.1

### Please describe the expected behaviour
No errors after an valid HTTP request.

### Please describe the actual behaviour
```
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
ckan          |     self.finish_request(request, client_address)
ckan          |   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
ckan          |     self.RequestHandlerClass(request, client_address, self)
ckan          |   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
ckan          |     self.finish()
ckan          |   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
ckan          |     self.wfile.close()
ckan          |   File "/usr/lib/python2.7/socket.py", line 283, in close
ckan          |     self.flush()
ckan          |   File "/usr/lib/python2.7/socket.py", line 307, in flush
ckan          |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
ckan          | error: [Errno 32] Broken pipe
```
Also reported by another user: https://gitter.im/ckan/chat?at=5bc88344ef4afc4f2892f371
This error fills the logs with garbage.

### What steps can be taken to reproduce the issue? 
Open few pages.

**Comment by espona** [comment]
Hi, I have the same issue and I understand it can be ignored, but it appears continuously filling up my log. Did anyone find a solution or workaround? Many thanks in advance

**Comment by Katsivelisp** [comment]
Same here. I specifically get this when I preview or upload a new resource. 

I suspect that it has something to do with my Docker installation, but I haven't got any further than that.

**Comment by bhavin2897** [comment]
Hello,
Did someone try to solve this error? I have them coming and logging recently due to image previews and huge dataset counts?
