### ISSUE TITLE
Get error on test_admin.py for response.forms call

### ISSUE THREAD

**Issue by mystycs** [ckan/ckan#4569]
https://github.com/ckan/ckan/blob/78a4022adb1b9cdd440cf173d355fd89b91b8f05/ckan/tests/controllers/test_admin.py#L61

```
======================================================================
FAIL: test_admin.TestConfig.test_site_title
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/ckan/default/src/ckan/ckan/tests/controllers/tests/test_admin.py", line 61, in test_site_title
    config_form = config_response.forms['admin-config-form']
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/webtest/app.py", line 90, in forms__get
    self._parse_forms()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/webtest/app.py", line 136, in _parse_forms
    "</form> unexpected at %s" % match.start())
AssertionError: </form> unexpected at 4500
-------------------- >> begin captured logging << --------------------
```

**Comment by mystycs** [comment]
Seems like response.forms is throwing an error?

**Comment by amercader** [comment]
Closing. Feel free to reopen if still an issue
