### ISSUE TITLE
CKAN 2.8.2 column user.password does not exist on CentOS7

### ISSUE THREAD

**Issue by kroxiksut** [ckan/ckan#4609]
### CKAN Version if known (or site URL)
CKAN 2.8.2
### Please describe the actual behaviour
When executing a command  "paster db init -c /etc/ckan/default/development.ini" I'm  get next error

Traceback (most recent call last) :
File "/usr/lib/ckan/default/bin/paster", line 11, in <module> sys.exit(run())
File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 102, in run invoke(command, command_name, options, args[1:])
File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke exit_code = runner.run(args)
File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 236, in run result = self.command()
File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 357, in command self._load_config(cmd!='upgrade')
File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 330, in load config self.site_user = load_config(self.options.config, load_site_user)

File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli-py", line 261, in 1 oad_config site_user = logic.get_action('get_site_user')({'ignore_auth': True}, {})

File "/usr/lib/ckan/default/src/ckan/ckan/logic/	init	-py", line 46 4, in wrapped result = _action(context, data_dict, **kw)

File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 2377, in get_site_user user = model. User. get (site__id)

File "/usr/lib/ckan/default/src/ckan/ckan/model/user.py", line 56, in get return query.first()

File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/or m/query.py", line 2755, in first ret = list(self[0:1])

File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/or m/query.py", line 2547, in  __getitem__
return list(res)

File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/or m/query.py", line 2855, in 	iter	
return self, execute and instances(context)

File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/or m/query.py", line 2878, in _execute_and_instances

result = conn.execute(querycontext.statement, self._params)

File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
return meth(self, multiparams, params)
File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/sq1/elements.py", line 263, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params) File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/en gine/base.py", line 1053, in _execute_clauseelement compiled_sql, distilled_params
File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context context)
File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception exc_info
File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context context)
File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do execute

cursor.execute(statement, parameters) sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) WARNING: columt user.password does not exist
LINE 1: SELECT "user".password AS user_password, "user".id AS user_i...
A
[SQL: 'SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".fullname AS user_fullname, "user".emai 1 AS user_email, "user".apikey AS user_apikey, "user".created AS user_c reated, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".activity_streams_email_notifications AS user_activity_streams_e mail__notifications, "user".sysadmin AS user_sysadmin, "user".state AS u ser_state \nFROM "user" \nWHERE "user".name = %(name_l)s OR "user".id = %(id_l)s ORDER BY "user".name \n LIMIT %(param_l)s'] [parameters: {'na me_l': 'default', 'param_l': 1, 'id 1': 'default'}]
 
### What steps can be taken to reproduce the issue? 

I'm using CentOS 7, PostgreSQL 9.6 and SOLR 6.6.5

**Comment by linforestzhang** [comment]
Same Error.   I'm using CentOS 7.8, PostgreSQL 10 and SOLR 5.5.5.
