### ISSUE TITLE
ImportError: No module named repozewho

### ISSUE THREAD

**Issue by ppiecuch** [ckan/ckan#4655]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
branch: master

### Please describe the expected behaviour
Application in docker should start but stops with exception. Same code base worked some time ago - maybe someone had this problem already and could help ?

### Please describe the actual behaviour

ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 10, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan          |     invoke(command, command_name, options, args[1:])
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan          |     exit_code = runner.run(args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ckan          |     result = self.command()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 354, in command
ckan          |     self._load_config(cmd!='upgrade')
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 331, in _load_config
ckan          |     self.site_user = load_config(self.options.config, load_site_user)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 244, in load_config
ckan          |     app = make_app(conf.global_conf, **conf.local_conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 59, in make_app
ckan          |     **app_conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/pylons_app.py", line 125, in make_pylons_stack
ckan          |     who_parser.parse(open(app_conf['who.config_file']))
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/repoze/who/config.py", line 86, in parse
ckan          |     obj = self._makePlugin(name, IPlugin, options)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/repoze/who/config.py", line 40, in _makePlugin
ckan          |     obj = _resolve(name)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/repoze/who/config.py", line 23, in _resolve
ckan          |     return EntryPoint.parse('x=%s' % name).resolve()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
ckan          |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
**ckan          | ImportError: No module named repozewho**

### What steps can be taken to reproduce the issue? 
docker-compose build
docker-compose up

**Comment by amercader** [comment]
This code looks like the one is parsing entry points coming from the `who.ini` file, and that there is typo there as `repozewho` should be `repoze.who`. Have you modified the file manually?
