### ISSUE TITLE
Docker setup fails to run with version 2.8.2

### ISSUE THREAD

**Issue by StefanoFioravanzo** [ckan/ckan#4658]
### CKAN Version

CKAN Tag: `ckan-2.8.2`

### Expected behaviour

1. Clone the repository at tag: `ckan-2.8.2`
2. Copy `.template.env` to `.env`. (No changes applied)
3. `docker-compose up -d` (Builds everything with no errors)
4. `docker-compose restart ckan`
5. `ckan` runs as expected (tested both on MacOS and on Ubuntu 16.04)

### Actual behaviour

When replicating the same steps on a Ubuntu 18.04 machine, the last step (after `docker-compose restart ckan`) fails with error (in the ckan container):

```
Traceback (most recent call last):
  File "/usr/local/bin/ckan-paster", line 10, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 357, in command
    self._load_config(cmd!='upgrade')
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 330, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 237, in load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 112, in load_environment
    p.load_all()
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 140, in load_all
    load(*plugins)
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 154, in load
    service = _get_service(plugin)
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 256, in _get_service
    return plugin.load()(name=plugin_name)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/ckan/venv/src/ckanext-spatial/ckanext/spatial/plugin.py", line 36, in <module>
    check_geoalchemy_requirement()
  File "/usr/lib/ckan/venv/src/ckanext-spatial/ckanext/spatial/plugin.py", line 29, in check_geoalchemy_requirement
    raise ImportError(msg.format('geoalchemy2'))
ImportError: This version of ckanext-spatial requires geoalchemy2. Please install it by running `pip install geoalchemy2`.
For more details see the "Troubleshooting" section of the install documentation
```

The docker environment, images, volumes and containers were removed before running the test. So nothing should change between the deployments. The reason why on a specific machine the Docker setup does not work trips me..

**Comment by ppiecuch** [comment]
What helped me with this similar issue (https://github.com/ckan/ckan/issues/4655) was to Reset docker to factory defaults - I guess it might be connected to some outdated volumes vs. containers.

**Comment by frafra** [comment]
Have you tried to add `--build`? Current images are outdated.

**Comment by StefanoFioravanzo** [comment]
Actually, resetting Docker solved the issue,  which was probably related to an old volume
