### ISSUE TITLE
Exception sort param field can't be found: view_recent

### ISSUE THREAD

**Issue by cesarjorgemartinez** [ckan/ckan#4683]
### CKAN Version if known (or site URL)
CKAN 2.8.2
SOLR 7.7.1

### Please describe the expected behaviour
No exceptions and login and work correctly in CKAN

### Please describe the actual behaviour
When I login in CKAN, write above "Internal Server error".
The logs in solr show:
2019-03-12 11:35:58.649 ERROR (qtp898557489-17) [   x:default] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: sort param field can't be found: view_recent
	at org.apache.solr.search.SortSpecParsing.parseSortSpecImpl(SortSpecParsing.java:198)
	at org.apache.solr.search.SortSpecParsing.parseSortSpec(SortSpecParsing.java:60)
	at org.apache.solr.search.QParser.getSortSpec(QParser.java:280)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:187)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:272)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:199)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2551)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:710)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:516)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:395)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:341)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

### What steps can be taken to reproduce the issue? 
Install CKAN 2.8.2 and SOLR 7.7.1, and create one CKAN instance and SOLR core.

**Comment by smotornyuk** [comment]
Hi, @cesarjorgemartinez . Currently, CKAN doesn't support Solr > v6.5(we are working on it, but as everyone's main priority is a migration to python3, at this point progress is not very fast). I would suggest to downgrade Solr, or, if you insist on using newest version, take a look at #4387 .

**Comment by cesarjorgemartinez** [comment]
Hi,
Actually I use by now solr 6.5.1 with a short modifications, for Ckan 2.7.6.
It would be nice to have a matrix compatibility, example:
For Ckan 2.7.6 use Solr x, or Solr y with a x modifications
For Ckan 2.8.2 ...

Exists a site or doc to describe this? If not, I can create in any site, ot this repo?

Regards,

**Comment by smotornyuk** [comment]
If you can give a hand in this, it would really be cool :) Documentation of CKAN resides inside[ `doc` folder of main repo](https://github.com/ckan/ckan/tree/master/doc) and [here](https://docs.ckan.org/en/2.8/contributing/documentation.html) are main points of the documentation update process. Probably, [installation guid](https://docs.ckan.org/en/2.8/maintaining/installing/index.html) is the best place for such kind of information, but feel free to put it in any place you found convenient for end-user.

I'm not sure as for particular versions of Postgres, Solr, Redis, that are supported, but I think listing below is more or less correct
| CKAN | Solr | PostgreSQL | Redis |
| - | - | - | - |
| 2.9 | >= 3, <=6.5 | >=9, <=12 | 4, 5 | 
| 2.8 | >= 3, <=6.5 | >=9, <=11 | 4 | 
| 2.7 | >= 3, <=6.5 | >=9, <=10 | 4 | 
| 2.6 | >= 3, <=6.5 | >=9, <=10 | Not supported | 

@ckan/core , any corrections? 

BTW, @cesarjorgemartinez , we have devs meeting twice a week ( [details](https://hack.allmende.io/ckan-meeting) if you want to share some ideas or just get involved a bit more :) ) and [channel in Gitter](https://gitter.im/ckan/chat) - usually you can get a response to question there much faster than using GitHub issues.
