### ISSUE TITLE
Internal Server error and no error log messages

### ISSUE THREAD

**Issue by MichaelHarmsTIB** [ckan/ckan#4746]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.8.2

### Please describe the expected behaviour
A working ckan-site, without internal error messages

### Please describe the actual behaviour
Internal server error on all sites, but the ckan site exists and running. If I click on Dataset, group, organisation I got a internal server error. 
I study the apache2 ckan_default_error.logs and postgres logs but I didnt find the error.

### What steps can be taken to reproduce the issue? 
Install ckan 2.8.2 on debian, and follow the doc instruction. That happened in my case.

**Comment by LukeTully** [comment]
Definitely find a way to post those logs or turn on logging in the settings file for one of the sites and reload the server. Careful to obfuscate any sensitive information.

**Comment by MichaelHarmsTIB** [comment]
**I run a test  enviroment. My Config-File:**
 [DEFAULT]

# WARNING: *THIS SETTING MUST BE SET TO FALSE ON A PRODUCTION ENVIRONMENT*
#debug = true

[server:main]
use = egg:Paste#http
host = 0.0.0.0
port = 5000

[app:main]
use = egg:ckan
full_stack = true
cache_dir = /tmp/%(ckan.site_id)s/
beaker.session.key = ckan

# This is the secret token that the beaker library uses to hash the cookie sent
# to the client. `paster make-config` generates a unique value for this each
# time it generates a config file.
beaker.session.secret = BbMsj+g52f3rb72NrsGp3sFLh

# `paster make-config` generates a unique value for this each time it generates
# a config file.
app_instance_uuid = 60fbd1aa-28fb-4813-8521-6013b7b6edce

# repoze.who config
who.config_file = %(here)s/who.ini
who.log_level = warning
who.log_file = %(cache_dir)s/who_log.ini
# Session timeout (user logged out after period of inactivity, in seconds).
# Inactive by default, so the session doesn't expire.
# who.timeout = 86400

## Database Settings
sqlalchemy.url = postgresql://ckan_default:pass###@localhost/ckan_default

ckan.datastore.write_url = postgresql://ckan_default:pass###@localhost/datastore_default
ckan.datastore.read_url = postgresql://datastore_default:pass###@localhost/datastore_default

# PostgreSQL' full-text search parameters
ckan.datastore.default_fts_lang = english
ckan.datastore.default_fts_index_method = gist


## Site Settings

ckan.site_url = http://localhost:5000
ckan.use_pylons_response_cleanup_middleware = true

## Authorization Settings

ckan.auth.anon_create_dataset = false
ckan.auth.create_unowned_dataset = false
ckan.auth.create_dataset_if_not_in_organization = false
ckan.auth.user_create_groups = false
ckan.auth.user_create_organizations = false
ckan.auth.user_delete_groups = true
ckan.auth.user_delete_organizations = true
ckan.auth.create_user_via_api = false
ckan.auth.create_user_via_web = true
ckan.auth.roles_that_cascade_to_sub_groups = admin


## Search Settings

ckan.site_id = default
solr_url = http://127.0.0.1:8983/solr/#/ckan

## Redis Settings

# URL to your Redis instance, including the database to be used.
ckan.redis.url = redis://localhost:6379/0


## CORS Settings

# If cors.origin_allow_all is true, all origins are allowed.
# If false, the cors.origin_whitelist is used.
# ckan.cors.origin_allow_all = true
# cors.origin_whitelist is a space separated list of allowed domains.
# ckan.cors.origin_whitelist = http://example1.com http://example2.com


## Plugins Settings

# Note: Add ``datastore`` to enable the CKAN DataStore
#       Add ``datapusher`` to enable DataPusher
#		Add ``resource_proxy`` to enable resorce proxying and get around the
#		same origin policy
ckan.plugins = stats text_view image_view recline_view

# Define which views should be created by default
# (plugins must be loaded in ckan.plugins)
ckan.views.default_views = image_view text_view recline_view

# Customize which text formats the text_view plugin will show
#ckan.preview.json_formats = json
#ckan.preview.xml_formats = xml rdf rdf+xml owl+xml atom rss
#ckan.preview.text_formats = text plain text/plain

# Customize which image formats the image_view plugin will show
#ckan.preview.image_formats = png jpeg jpg gif

## Front-End Settings

# Uncomment following configuration to enable using of Bootstrap 2
#ckan.base_public_folder = public-bs2
#ckan.base_templates_folder = templates-bs2

ckan.site_title = test
ckan.site_logo = /base/images/ckan-logo.png
ckan.site_description =
ckan.favicon = /base/images/ckan.ico
ckan.gravatar_default = identicon
ckan.preview.direct = png jpg gif
ckan.preview.loadable = html htm rdf+xml owl+xml xml n3 n-triples turtle plain atom csv tsv rss txt json
ckan.display_timezone = server

# package_hide_extras = for_search_index_only
#package_edit_return_url = http://another.frontend/dataset/<NAME>
#package_new_return_url = http://another.frontend/dataset/<NAME>
#ckan.recaptcha.publickey =
#ckan.recaptcha.privatekey =
#licenses_group_url = http://licenses.opendefinition.org/licenses/groups/ckan.json
# ckan.template_footer_end =


## Internationalisation Settings
ckan.locale_default = en
ckan.locale_order = en pt_BR ja it cs_CZ ca es fr el sv sr sr@latin no sk fi ru de pl nl bg ko_KR hu sa sl lv
ckan.locales_offered =
ckan.locales_filtered_out = en_GB

## Feeds Settings

ckan.feeds.authority_name =
ckan.feeds.date =
ckan.feeds.author_name =
ckan.feeds.author_link =

## Storage Settings

ckan.storage_path = /var/lib/ckan
ckan.max_resource_size = 10
ckan.max_image_size = 2

## Datapusher settings

# Make sure you have set up the DataStore

ckan.datapusher.formats = csv xls xlsx tsv application/csv application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
ckan.datapusher.url = http://127.0.0.1:8800/
#ckan.datapusher.assume_task_stale_after = 3600

# Resource Proxy settings
# Preview size limit, default: 1MB
#ckan.resource_proxy.max_file_size = 1048576
# Size of chunks to read/write.
#ckan.resource_proxy.chunk_size = 4096

## Activity Streams Settings

#ckan.activity_streams_enabled = true
#ckan.activity_list_limit = 31
#ckan.activity_streams_email_notifications = true
#ckan.email_notifications_since = 2 days
ckan.hide_activity_from_users = %(ckan.site_id)s


## Email settings

#email_to = errors@example.com
#error_email_from = ckan-errors@example.com
#smtp.server = localhost
#smtp.starttls = False
#smtp.user = username@example.com
#smtp.password = your_password
#smtp.mail_from =


## Logging configuration
[loggers]
keys = root, ckan, ckanext

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = DEBUG
handlers = console

[logger_ckan]
level = DEBUG
handlers = console
qualname = ckan
propagate = 0

[logger_ckanext]
level = DEBUG
handlers = console
qualname = ckanext
propagate = 0

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s

**Comment by smotornyuk** [comment]
Given the fact that you are getting errors on pages, that are showing search result, there is likely some problems with Solr. Could you please check Solr logs as well? and provide an example of apache2 logs output for this error

PS CKAN has some hardships in cooperation with Solr > v6.5. What version you are using?

**Comment by amercader** [comment]
Hi, @MichaelHarmsTIB we need some sort of error log to help. If you are runing the paster development server the output will be on the console. If you are running Apache logs should be on /var/log/apache/ckan_default.log or whatever equivalent location they have in Debian.

To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [Gitter channel](https://gitter.im/ckan/chat), where other developers may be able to help you.

Thanks!

**Comment by MichaelHarmsTIB** [comment]
Hello, 
if I start with paster and enter the site I got this log:
`2019-04-29 19:02:14,842 DEBUG [ckan.config.middleware.flask_app] Flask route match, endpoint: home.index, args: {}, origin: core`
`2019-04-29 19:02:14,863 DEBUG [ckan.config.middleware] Route support answers for GET /: [(True, 'flask_app', 'core'), (False, 'pylons_app')]`
```
2019-04-29 19:02:14,863 DEBUG [ckan.config.middleware] Serving request via flask_app app
2019-04-29 19:02:14,864 INFO  [repoze.who] request classification: browser
2019-04-29 19:02:14,864 INFO  [repoze.who] -- repoze.who request started (/) --
2019-04-29 19:02:14,864 DEBUG [repoze.who] identifier plugins registered: [<FriendlyFormPlugin 140068477824656>, <CkanAuthTktCookiePlugin 140068477824528>]
```
```
2019-04-29 19:02:14,864 DEBUG [repoze.who] identifier plugins matched for classification "browser": [<FriendlyFormPlugin 140068477824656>, <CkanAuthTktCookiePlugin 140068477824528>]
2019-04-29 19:02:14,864 DEBUG [repoze.who] no identity returned from <FriendlyFormPlugin 140068477824656> (None)
```
`2019-04-29 19:02:14,864 DEBUG [repoze.who] identity returned from <CkanAuthTktCookiePlugin 140068477824528>: {'tokens': [''], 'timestamp': 1556187409, 'repoze.who.plugins.auth_tkt.userid': u'test', 'userdata': {'userid_type': 'unicode'}}`
`2019-04-29 19:02:14,864 DEBUG [repoze.who] identities found: [(<CkanAuthTktCookiePlugin 140068477824528>, {'tokens': [''], 'timestamp': 1556187409, 'repoze.who.plugins.auth_tkt.userid': u'test', 'userdata': {'userid_type': 'unicode'}})]`
`2019-04-29 19:02:14,864 DEBUG [repoze.who] authenticator plugins registered: [<CkanAuthTktCookiePlugin 140068477824528>, `<ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x7f643bdd6f90>]
`2019-04-29 19:02:14,864 DEBUG [repoze.who] authenticator plugins matched for classification "browser": [<CkanAuthTktCookiePlugin 140068477824528>, <ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x7f643bdd6f90>]`
`2019-04-29 19:02:14,865 DEBUG [repoze.who] userid returned from <CkanAuthTktCookiePlugin 140068477824528>: "test"`
`2019-04-29 19:02:14,865 DEBUG [repoze.who] no userid returned from <ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x7f643bdd6f90>: (None)`
`2019-04-29 19:02:14,865 DEBUG [repoze.who] identities authenticated: [((0, 0), <CkanAuthTktCookiePlugin 140068477824528>, <CkanAuthTktCookiePlugin 140068477824528>, {'tokens': [''], 'timestamp': 1556187409, 'repoze.who.userid': u'test', 'repoze.who.plugins.auth_tkt.userid': u'test', 'userdata': {'userid_type': 'unicode'}}, u'test')]`
```
2019-04-29 19:02:14,881 DEBUG [ckan.logic] check access OK - site_read user=test
2019-04-29 19:02:14,882 DEBUG [ckan.logic] check access OK - package_search user=test
2019-04-29 19:02:14,892 DEBUG [ckan.logic] check access OK - organization_list_for_user user=8f6602a5-63b3-4388-87a0-b3db6fd55502
```
`2019-04-29 19:02:14,907 DEBUG [ckan.lib.search.query] Package query: {u'sort': u'view_recent desc', u'fq': [u'+capacity:public capacity:"public"', u'+site_id:"default"', '+state:active', u'+permission_labels:("public" OR "creator-8f6602a5-63b3-4388-87a0-b3db6fd55502")'], 'facet.mincount': 1, u'rows': 5, u'facet.field': [u'organization', u'groups', u'tags', u'res_format', u'license_id'], 'facet.limit': '50', 'facet': 'true', u'q': u'*:*', u'start': 4, 'wt': 'json', 'fl': 'id validated_data_dict'}`
`2019-04-29 19:02:14,907 DEBUG [pysolr] Starting request to 'http://127.0.0.1:8983/solr/#/ckan/select/?sort=view_recent+desc&fq=%2Bcapacity%3Apublic+capacity%3A%22public%22&fq=%2Bsite_id%3A%22default%22&fq=%2Bstate%3Aactive&fq=%2Bpermission_labels%3A%28%22public%22+OR+%22creator-8f6602a5-63b3-4388-87a0-b3db6fd55502%22%29&facet.mincount=1&rows=5&facet.field=organization&facet.field=groups&facet.field=tags&facet.field=res_format&facet.field=license_id&facet.limit=50&facet=true&q=%2A%3A%2A&start=4&wt=json&fl=id+validated_data_dict' (get) with body ''...`
`2019-04-29 19:02:14,908 INFO  [requests.packages.urllib3.connectionpool] Starting new HTTP connection (1): 127.0.0.1`
`2019-04-29 19:02:14,909 DEBUG [requests.packages.urllib3.connectionpool] "GET /solr/ HTTP/1.1" 200 14410`
`2019-04-29 19:02:14,910 INFO  [pysolr] Finished 'http://127.0.0.1:8983/solr/#/ckan/select/?sort=view_recent+desc&fq=%2Bcapacity%3Apublic+capacity%3A%22public%22&fq=%2Bsite_id%3A%22default%22&fq=%2Bstate%3Aactive&fq=%2Bpermission_labels%3A%28%22public%22+OR+%22creator-8f6602a5-63b3-4388-87a0-b3db6fd55502%22%29&facet.mincount=1&rows=5&facet.field=organization&facet.field=groups&facet.field=tags&facet.field=res_format&facet.field=license_id&facet.limit=50&facet=true&q=%2A%3A%2A&start=4&wt=json&fl=id+validated_data_dict' (get) with body '' in 0.003 seconds, with status 200`
`2019-04-29 19:02:14,966 DEBUG [ckan.logic] check access OK - dashboard_new_activities_count user=test`
```
2019-04-29 19:02:14,966 DEBUG [ckan.logic] check access OK - dashboard_activity_list user=test
2019-04-29 19:02:15,005 DEBUG [beaker.container] data file /tmp/default/sessions/container_file/4/43/43f5f47f5ddb41d6ad5c197a599a352d.cache
```
```
2019-04-29 19:02:15,432 INFO  [repoze.who] no challenge required
2019-04-29 19:02:15,432 INFO  [repoze.who] -- repoze.who request ended (/) --
2019-04-29 19:02:15,453 DEBUG [paste.httpserver.ThreadPool] Added task (0 tasks queued)
2019-04-29 19:02:15,465 DEBUG [paste.httpserver.ThreadPool] Added task (0 tasks queued)
```
`2019-04-29 19:02:15,466 DEBUG [ckan.config.middleware.pylons_app] Pylons route match: {'url': u'base/images/od_80x15_blue.png', 'action': u'view', 'controller': u'template'} Origin: core`
`2019-04-29 19:02:15,466 DEBUG [ckan.config.middleware] Route support answers for GET /base/images/od_80x15_blue.png: [(False, 'flask_app'), (True, 'pylons_app', 'core')]`
```
2019-04-29 19:02:15,466 DEBUG [ckan.config.middleware] Serving request via pylons_app app
2019-04-29 19:02:15,467 DEBUG [ckan.config.middleware.pylons_app] Pylons route match: {'url': u'base/images/ckan-logo.png', 'action': u'view', 'controller': u'template'} Origin: core
```
```
2019-04-29 19:02:15,467 DEBUG [ckan.config.middleware] Route support answers for GET /base/images/ckan-logo.png: [(False, 'flask_app'), (True, 'pylons_app', 'core')]
2019-04-29 19:02:15,467 DEBUG [ckan.config.middleware] Serving request via pylons_app app
2019-04-29 19:02:15,501 DEBUG [paste.httpserver.ThreadPool] Added task (0 tasks queued)
2019-04-29 19:02:15,502 DEBUG [ckan.config.middleware.pylons_app] Pylons route match: {'url': u'base/images/bg.png', 'action': u'view', 'controller': u'template'} Origin: core
```
```
2019-04-29 19:02:15,502 DEBUG [ckan.config.middleware] Route support answers for GET /base/images/bg.png: [(False, 'flask_app'), (True, 'pylons_app', 'core')]
2019-04-29 19:02:15,502 DEBUG [ckan.config.middleware] Serving request via pylons_app app
2019-04-29 19:02:15,503 DEBUG [paste.httpserver.ThreadPool] Added task (0 tasks queued)
2019-04-29 19:02:15,504 DEBUG [ckan.config.middleware.pylons_app] Pylons route match: {'url': u'base/images/ckan-logo-footer.png', 'action': u'view', 'controller': u'template'} Origin: core
```
```
2019-04-29 19:02:15,504 DEBUG [ckan.config.middleware] Route support answers for GET /base/images/ckan-logo-footer.png: [(False, 'flask_app'), (True, 'pylons_app', 'core')]
2019-04-29 19:02:15,504 DEBUG [ckan.config.middleware] Serving request via pylons_app app
2019-04-29 19:02:15,508 DEBUG [paste.httpserver.ThreadPool] Added task (0 tasks queued)
```
```
2019-04-29 19:02:15,509 DEBUG [ckan.config.middleware.pylons_app] Pylons route match: {'url': u'fanstatic/vendor/:version:2019-04-18T16:41:26.05/font-awesome/fonts/fontawesome-webfont.woff2', 'action': u'view', 'controller': u'template'} Origin: core
2019-04-29 19:02:15,509 DEBUG [ckan.config.middleware] Route support answers for GET /fanstatic/vendor/:version:2019-04-18T16:41:26.05/font-awesome/fonts/fontawesome-webfont.woff2: [(False, 'flask_app'), (True, 'pylons_app', 'core')]
```
```
2019-04-29 19:02:15,509 DEBUG [ckan.config.middleware] Serving request via pylons_app app
2019-04-29 19:02:15,510 INFO  [repoze.who] request classification: browser
2019-04-29 19:02:15,510 INFO  [repoze.who] -- repoze.who request started (/fanstatic/vendor/:version:2019-04-18T16:41:26.05/font-awesome/fonts/fontawesome-webfont.woff2) --
```
```
2019-04-29 19:02:15,510 DEBUG [repoze.who] identifier plugins registered: [<FriendlyFormPlugin 140068480096336>, <CkanAuthTktCookiePlugin 140068480095376>]
2019-04-29 19:02:15,510 DEBUG [repoze.who] identifier plugins matched for classification "browser": [<FriendlyFormPlugin 140068480096336>, <CkanAuthTktCookiePlugin 140068480095376>]
```
```
2019-04-29 19:02:15,510 DEBUG [repoze.who] no identity returned from <FriendlyFormPlugin 140068480096336> (None)
2019-04-29 19:02:15,510 DEBUG [repoze.who] identity returned from <CkanAuthTktCookiePlugin 140068480095376>: {'tokens': [''], 'timestamp': 1556187409, 'repoze.who.plugins.auth_tkt.userid': u'test', 'userdata': {'userid_type': 'unicode'}}
```
`2019-04-29 19:02:15,510 DEBUG [repoze.who] identities found: [(<CkanAuthTktCookiePlugin 140068480095376>, {'tokens': [''], 'timestamp': 1556187409, 'repoze.who.plugins.auth_tkt.userid': u'test', 'userdata': {'userid_type': 'unicode'}})]`
`2019-04-29 19:02:15,510 DEBUG [repoze.who] authenticator plugins registered: [<CkanAuthTktCookiePlugin 140068480095376>, <ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x7f643be537d0>]`
`2019-04-29 19:02:15,510 DEBUG [repoze.who] authenticator plugins matched for classification "browser": [<CkanAuthTktCookiePlugin 140068480095376>, <ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x7f643be537d0>]`
`2019-04-29 19:02:15,510 DEBUG [repoze.who] userid returned from <CkanAuthTktCookiePlugin 140068480095376>: "test"`
```
2019-04-29 19:02:15,510 DEBUG [repoze.who] no userid returned from <ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x7f643be537d0>: (None)
2019-04-29 19:02:15,510 DEBUG [repoze.who] identities authenticated: [((0, 0), <CkanAuthTktCookiePlugin 140068480095376>, <CkanAuthTktCookiePlugin 140068480095376>, {'tokens': [''], 'timestamp': 1556187409, 'repoze.who.userid': u'test', 
```
```'repoze.who.plugins.auth_tkt.userid': u'test', 'userdata': {'userid_type': 'unicode'}}, u'test')]
2019-04-29 19:02:15,511 INFO  [repoze.who] no challenge required
2019-04-29 19:02:15,511 INFO  [repoze.who] -- repoze.who request ended (/fanstatic/vendor/:version:2019-04-18T16:41:26.05/font-awesome/fonts/fontawesome-webfont.woff2) --
```
----------------------------------------
```
```
Exception happened during processing of request from ('127.0.0.1', 50510)
Traceback (most recent call last):
```
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```
----------------------------------------
```
2019-04-29 19:02:15,602 DEBUG [paste.httpserver.ThreadPool] Added task (0 tasks queued)
2019-04-29 19:02:15,604 DEBUG [ckan.config.middleware.flask_app] Flask route match, endpoint: api.i18n_js_translations, args: {'lang': u'en'}, origin: core
```
```
2019-04-29 19:02:15,605 DEBUG [ckan.config.middleware.pylons_app] Pylons route match: {'url': u'api/i18n/en', 'action': u'view', 'controller': u'template'} Origin: core
2019-04-29 19:02:15,606 DEBUG [ckan.config.middleware] Route support answers for GET /api/i18n/en: [(True, 'flask_app', 'core'), (True, 'pylons_app', 'core')]
```
```
2019-04-29 19:02:15,606 DEBUG [ckan.config.middleware] Serving request via flask_app app
2019-04-29 19:02:15,606 INFO  [repoze.who] request classification: browser
2019-04-29 19:02:15,606 INFO  [repoze.who] -- repoze.who request started (/api/i18n/en) --
2019-04-29 19:02:15,606 DEBUG [repoze.who] identifier plugins registered: [<FriendlyFormPlugin 140068477824656>, <CkanAuthTktCookiePlugin 140068477824528>]
```
```
2019-04-29 19:02:15,606 DEBUG [repoze.who] identifier plugins matched for classification "browser": [<FriendlyFormPlugin 140068477824656>, <CkanAuthTktCookiePlugin 140068477824528>]
2019-04-29 19:02:15,606 DEBUG [repoze.who] no identity returned from <FriendlyFormPlugin 140068477824656> (None)
```
`2019-04-29 19:02:15,607 DEBUG [repoze.who] no identity returned from <CkanAuthTktCookiePlugin 140068477824528> (None)`
```
2019-04-29 19:02:15,607 DEBUG [repoze.who] identities found: []
2019-04-29 19:02:15,607 INFO  [repoze.who] no identities found, not authenticating
2019-04-29 19:02:15,612 INFO  [repoze.who] no challenge required
```
```
2019-04-29 19:02:15,613 INFO  [repoze.who] -- repoze.who request ended (/api/i18n/en) --
2019-04-29 19:02:16,786 DEBUG [paste.httpserver.ThreadPool] Added task (0 tasks queued)
```

**Comment by MichaelHarmsTIB** [comment]
The apache ckan error log shows nothing:
`[Tue Apr 30 15:10:38.654914 2019] [wsgi:debug] [pid 12883:tid 139704790222592] src/server/mod_wsgi.c(8815): mod_wsgi   (pid=12883): Started thread 0 in daemon process 'ckan_default'.`

I think this is the output from paster start.

**Comment by thatguylor** [comment]
Hi @MichaelHarmsTIB , from my experience, CKAN has many ways to output Internal Server Error 500, one of the ways is through Apache SOLR, you might want to check your SOLR cores and see if they are configured correctly, especially if you are not running the default package install - (things like managed-schema, solrconfig.xml and solr.xml are the usual suspects) 

Next, i saw in your `ckan.ini` config set up that you have datapusher settings enabled, but you do not have `datastore datapusher` in your `ckan.plugins` perhaps this could be an issue. 

Lastly, if all else fails, i would suggest using `systemctl` to restart your services and if that doesnt work, a reboot of your server might. My guess is there is some issues with cache invalidation and perhaps a hard reboot might help.
