### ISSUE TITLE
Cannot create organization using LDAP extension

### ISSUE THREAD

**Issue by LucaPrete** [ckan/ckan#4861]
### CKAN Version if known (or site URL)
2.6.4

### Please describe the expected behavior
We're trying to use the LDAP plugin for CKAN (https://extensions.ckan.org/extension/ldap/). As described in the documentation we're running the following command:

```
paster --plugin=ckanext-ldap ldap setup-org -c /etc/ckan/default/ckan.ini
```

We would expect to see the organization created.

### Please describe the actual behaviour

An exception is thrown instead:
```
Traceback (most recent call last):
  File "/usr/bin/paster", line 10, in <module>
    sys.exit(run())
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckanext-ldap/ckanext/ldap/commands/ldap.py", line 44, in command
    self.setup_org()
  File "/usr/lib/ckan/default/src/ckanext-ldap/ckanext/ldap/commands/ldap.py", line 58, in setup_org
    toolkit.get_action('organization_create')(self.context, {'id': organization_id, 'name': organization_id})
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 431, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 855, in organization_create
    return _group_or_org_create(context, data_dict, is_org=True)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 647, in _group_or_org_create
    raise ValidationError(errors)
ckan.logic.ValidationError: {'identifier': ['Missing value']}
```

### What steps can be taken to reproduce the issue? 
Run the command described above

**Comment by wardi** [comment]
Hello @LucaPrete this looks like either an issue with the ckanext-ldap extension or possibly a conflict with another extension you have installed (what's the "identifier" field that your organization is expecting)?

Try removing any extension that is customizing your organization schema or reporting the issue or submitting a fix on the ckanext-ldap repository.
