### ISSUE TITLE
Problems with Read The Docs

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4892]
When building the docs for the latest patch releases I noticed several problems with RTD:

* Docs are not being built automatically. There were some changes around GitHub [webhooks](https://docs.readthedocs.io/en/latest/webhooks.html#webhook-github-services) so we probably need to reconfigure things

* Docs or master are being built, but not for previous versions. 2.8 fails with the following:

```
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  1%] _substitutions

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 333, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 394, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 431, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 440, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/html.py", line 607, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/html.py", line 1013, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/readthedocs_ext/readthedocs.py", line 126, in rtd_render
    rtd_content = app.builder.templates.render_string(templ, template_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/jinja2glue.py", line 199, in render_string
    return self.environment.from_string(source).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 25, in template
TemplateAssertionError: no filter named 'tojson'

Exception occurred:
  File "<unknown>", line 25, in template
TemplateAssertionError: no filter named 'tojson'
```

  Which is weird because neither the docs or CKAN itself uses this filter

* 2.7 and 2.6 builds are failing because of psycopg2 related requirements problems
* There is a new recommended way of configuring RTD using a [.readthedocs.yml](https://docs.readthedocs.io/en/stable/config-file/v2.html) file, that might help with the above.

**Comment by smotornyuk** [comment]
It's no longer relevant (see #5380)
