### ISSUE TITLE
Error: Process completed but unable to post to result_url

### ISSUE THREAD

**Issue by cutley** [ckan/ckan#4909]
CKAN version 2.8.1 installed from package on Ubuntu 16.04.5. 

Prior to configuring SSL, the 'Upload To Datastore' button on the Datastore tab works fine, producing the log on the web page as expected. 

After SSL is configured the 'Upload To Datastore' button begins to throw the error "Error: Process completed but unable to post to result_url".  The log on the web page no longer appears with the exception of an 'End of Log' message. 

The entry is the datapusher.error.log is as follows: 

[Tue Jul 16 15:54:55.347336 2019] [wsgi:error] [pid 14835:tid 139796435633920] Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
[Tue Jul 16 15:54:55.347360 2019] [wsgi:error] [pid 14835:tid 139796435633920] Traceback (most recent call last):
[Tue Jul 16 15:54:55.347364 2019] [wsgi:error] [pid 14835:tid 139796435633920]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
[Tue Jul 16 15:54:55.347367 2019] [wsgi:error] [pid 14835:tid 139796435633920]     retval = job.func(*job.args, **job.kwargs)
[Tue Jul 16 15:54:55.347370 2019] [wsgi:error] [pid 14835:tid 139796435633920]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 326, in push_to_datastore
[Tue Jul 16 15:54:55.347373 2019] [wsgi:error] [pid 14835:tid 139796435633920]     resource = get_resource(resource_id, ckan_url, api_key)
[Tue Jul 16 15:54:55.347375 2019] [wsgi:error] [pid 14835:tid 139796435633920]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 276, in get_resource
[Tue Jul 16 15:54:55.347378 2019] [wsgi:error] [pid 14835:tid 139796435633920]     'Authorization': api_key}
[Tue Jul 16 15:54:55.347385 2019] [wsgi:error] [pid 14835:tid 139796435633920]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/api.py", line 110, in post
[Tue Jul 16 15:54:55.347388 2019] [wsgi:error] [pid 14835:tid 139796435633920]     return request('post', url, data=data, json=json, **kwargs)
[Tue Jul 16 15:54:55.347391 2019] [wsgi:error] [pid 14835:tid 139796435633920]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/api.py", line 56, in request
[Tue Jul 16 15:54:55.347393 2019] [wsgi:error] [pid 14835:tid 139796435633920]     return session.request(method=method, url=url, **kwargs)
[Tue Jul 16 15:54:55.347396 2019] [wsgi:error] [pid 14835:tid 139796435633920]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
[Tue Jul 16 15:54:55.347398 2019] [wsgi:error] [pid 14835:tid 139796435633920]     resp = self.send(prep, **send_kwargs)
[Tue Jul 16 15:54:55.347401 2019] [wsgi:error] [pid 14835:tid 139796435633920]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
[Tue Jul 16 15:54:55.347403 2019] [wsgi:error] [pid 14835:tid 139796435633920]     r = adapter.send(request, **kwargs)
[Tue Jul 16 15:54:55.347406 2019] [wsgi:error] [pid 14835:tid 139796435633920]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
[Tue Jul 16 15:54:55.347408 2019] [wsgi:error] [pid 14835:tid 139796435633920]     raise SSLError(e, request=request)
[Tue Jul 16 15:54:55.347411 2019] [wsgi:error] [pid 14835:tid 139796435633920] SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

The datapusher.url entry in the ckan production.ini file : 
ckan.datapusher.url = http://0.0.0.0:8800/

**Comment by Gauravp-NEC** [comment]
@Cutely, Hi 
This issue is not reproducing. 
As per my analysis, While installing ckan 2.8.1 from python-ckan_2.8-xenial_amd64.deb  package, latest version of ckan i.e., 2.8.4 is fetch from package.

This issue might get resolve in latest version. 
Please let me know your opinion.
