### ISSUE TITLE
Install CKAN 2.5.2 on Windows 7

### ISSUE THREAD

**Issue by letoncse** [ckan/ckan#4953]
### Please describe the expected behaviour
I'm trying to install CKAN 2.5.2 on wondows 7 . I'm following below link. 
https://github.com/ckan/ckan/wiki/How-to-Install-CKAN-2.5.2-on-Windows-7

But I getting error number 13: Create database tables - (ckan) C:\src\ckan>paster db init -c development.ini

[Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\src\ckan\ckan\Scripts\paster.exe\__main__.py", line 9, in <module>
  File "c:\src\ckan\ckan\lib\site-packages\paste\script\command.py", line 101, i
n run
    command = commands[command_name].load()
  File "c:\src\ckan\ckan\lib\site-packages\pkg_resources\__init__.py", line 2443
, in load
    return self.resolve()
  File "c:\src\ckan\ckan\lib\site-packages\pkg_resources\__init__.py", line 2449
, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\src\ckan\ckan\lib\cli.py", line 4, in <module>
    import os
  File "C:\src\ckan\ckan\lib\os.py", line 120, in <module>
    from os.path import (curdir, pardir, sep, pathsep, defpath, extsep, altsep,
ImportError: No module named path]

How can resolve this issue ? 
Thanks in Advance !

**Comment by amercader** [comment]
Sorry, Windows is not currently supported by the tech team as a platform for CKAN. The wiki pages are community maintained. I recommend that you run Ubuntu in a VM or similar to run CKAN.
