### ISSUE TITLE
DataPusher tasks remain 'Pending' after WebOb errors

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#4959]
Some types of DataPusher error don't update the task status from 'Pending' to 'Error', requiring manual database intervention before the resource can be pushed again.

### CKAN Version if known (or site URL)

2.8.3

### Please describe the expected behaviour

Any DataPusher error should result in the `task_status` entry updating to 'Error'.

### Please describe the actual behaviour

Exceptions returned when the DataPusher is attempting to retrieve the file from CKAN can result in the task remaining 'Pending'. For example, we have recently seen stack traces such as the following:

DataPusher error log:

    [Wed Aug 28 16:37:28.855838 2019] [:error] [pid 18006] Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
    [Wed Aug 28 16:37:28.857636 2019] [:error] [pid 18006] Traceback (most recent call last):
    [Wed Aug 28 16:37:28.857643 2019] [:error] [pid 18006]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
    [Wed Aug 28 16:37:28.857645 2019] [:error] [pid 18006]     retval = job.func(*job.args, **job.kwargs)
    [Wed Aug 28 16:37:28.857646 2019] [:error] [pid 18006]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 330, in push_to_datastore
    [Wed Aug 28 16:37:28.857648 2019] [:error] [pid 18006]     resource = get_resource(resource_id, ckan_url, api_key)
    [Wed Aug 28 16:37:28.857650 2019] [:error] [pid 18006]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 278, in get_resource
    [Wed Aug 28 16:37:28.857651 2019] [:error] [pid 18006]     check_response(r, url, 'CKAN')
    [Wed Aug 28 16:37:28.857653 2019] [:error] [pid 18006]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 160, in check_response
    [Wed Aug 28 16:37:28.857654 2019] [:error] [pid 18006]     response=response.text)
    [Wed Aug 28 16:37:28.857656 2019] [:error] [pid 18006] HTTPError: CKAN bad response. Status code: 500 Internal Server Error. At: https://staging.data.qld.gov.au/api/3/action/resource_show. status=500 url=https://staging.data.qld.gov.au/api/3/action/resource_show response=<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    [Wed Aug 28 16:37:28.857658 2019] [:error] [pid 18006] <html><head>
    [Wed Aug 28 16:37:28.857660 2019] [:error] [pid 18006] <title>500 Internal Server Error</title>
    [Wed Aug 28 16:37:28.857661 2019] [:error] [pid 18006] </head><body>
    [Wed Aug 28 16:37:28.857662 2019] [:error] [pid 18006] <h1>Internal Server Error</h1>
    [Wed Aug 28 16:37:28.857664 2019] [:error] [pid 18006] <p>The server encountered an internal error or
    [Wed Aug 28 16:37:28.857665 2019] [:error] [pid 18006] misconfiguration and was unable to complete
    [Wed Aug 28 16:37:28.857667 2019] [:error] [pid 18006] your request.</p>
    [Wed Aug 28 16:37:28.857668 2019] [:error] [pid 18006] <p>Please contact the server administrator at 
    [Wed Aug 28 16:37:28.857669 2019] [:error] [pid 18006]  root@localhost to inform them of the time this error occurred,
    [Wed Aug 28 16:37:28.857671 2019] [:error] [pid 18006]  and the actions you performed just before this error.</p>
    [Wed Aug 28 16:37:28.857672 2019] [:error] [pid 18006] <p>More information about this error may be available
    [Wed Aug 28 16:37:28.857674 2019] [:error] [pid 18006] in the server error log.</p>
    [Wed Aug 28 16:37:28.857675 2019] [:error] [pid 18006] </body></html>
    [Wed Aug 28 16:37:28.857676 2019] [:error] [pid 18006] 

CKAN error log:

    [Wed Aug 28 16:37:31.407346 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]   File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 240, in __call__
    [Wed Aug 28 16:37:31.407353 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]     res = WSGIController.__call__(self, environ, start_response)
    [Wed Aug 28 16:37:31.407357 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py", line 221, in __call__
    [Wed Aug 28 16:37:31.407365 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]     response = self._dispatch_call()
    [Wed Aug 28 16:37:31.407369 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py", line 172, in _dispatch_call
    [Wed Aug 28 16:37:31.407375 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]     response = self._inspect_call(func)
    [Wed Aug 28 16:37:31.407379 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py", line 107, in _inspect_call
    [Wed Aug 28 16:37:31.407385 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]     result = self._perform_call(func, args)
    [Wed Aug 28 16:37:31.407389 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py", line 60, in _perform_call
    [Wed Aug 28 16:37:31.407394 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]     return func(**args)
    [Wed Aug 28 16:37:31.407399 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]   File "/usr/lib/ckan/default/src/ckan/ckan/controllers/error.py", line 38, in document
    [Wed Aug 28 16:37:31.407406 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]     return original_response.body
    [Wed Aug 28 16:37:31.407411 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/response.py", line 296, in _body__get
    [Wed Aug 28 16:37:31.407418 2019] [:error] [pid 21460] [remote 64.252.184.141:58925]     % (self.content_length, len(body))
    [Wed Aug 28 16:37:31.407431 2019] [:error] [pid 21460] [remote 64.252.184.141:58925] AssertionError: Content-Length is different from actual app_iter length (0!=31)

### What steps can be taken to reproduce the issue? 

We haven't been able to reproduce this *consistently*, but it seems plausible that any HTTP 500 returned to the DataPusher by the `resource_show` API would result in a similar failure to update the task status.

**Comment by amercader** [comment]
It seems reasonable to expect that any exception in a DataPusher job should result in the task being marked as error.

DataPusher's `HTTPError` exception [inherit](https://github.com/ckan/datapusher/blob/master/datapusher/jobs.py#L64) from CKAN Service Provider `JobError`, and [this code](https://github.com/ckan/ckan-service-provider/blob/9e697e006e5419630c729253fab7ce7730da081b/ckanserviceprovider/web.py#L183:L189) seems to suggest that the job should be indeed marked as errored. I'm not sure of the specific steps and where this is failing though

If you or someone else has time to investigate it would be appreciated.

BTW @davidread added some code a while ago to mark pending jobs as done after a while: https://github.com/ckan/ckan/blob/master/ckanext/datapusher/logic/action.py#L100

**Comment by ThrawnCA** [comment]
We've made some progress in investigating why the CKAN error was occurring, which might help in reproducing this. It looks like the DataPusher *usually* uses the credentials of the account that triggered it, but in some circumstances (and I'm not sure what those are), it instead uses a system account, by default called 'ckan'. And we had disabled that account, causing 'site_read' access checks to fail in the API controller.

**Comment by ArqumFarooqui-NEC** [comment]
I'm using Ckan2.7.2. I've also experienced the same problem many times (even still facing same problem with few files). 
While updating the resources, some of resources got stuck into `Pending` state due to some error (like `job error`, `500 error` etc.). screenshot is attached.
And preview for those files (which got stuck into `Pending` state) also not updated (their preview contains old data). 
@ThrawnCA, @amercader sir, Please provide your opinion, why few resources got stuck into `Pending` state? (I've checked that `DataPusher` is enable and running)
And how can I upload/update the resources successfully (resource status should be `Complete`)? 


![3 13 1day pending state-copy](https://user-images.githubusercontent.com/55977298/101629184-f5269400-3a46-11eb-85c8-9368b7e42c5b.png)

**Comment by ThrawnCA** [comment]
@ArqumFarooqui-NEC Sorry, we migrated to XLoader a while ago, so I don't have much expertise to contribute regarding DataPusher.

**Comment by ArqumFarooqui-NEC** [comment]
> @ArqumFarooqui-NEC Sorry, we migrated to XLoader a while ago, so I don't have much expertise to contribute regarding DataPusher.

Thankyou @ThrawnCA, for your response:)
Have you ever experienced the same `Pending` status problem with XLoader?

**Comment by ThrawnCA** [comment]
@ArqumFarooqui-NEC I don't think we've encountered that, no. XLoader doesn't use an API call to do its work, it piggybacks on the CKAN code to access the database directly, so it doesn't have the same error scenario.

If you're interested in migrating, there's a "migrate_types" command and a "just_load_with_messytables" flag that should make it pretty much a drop-in replacement for DataPusher.

**Comment by ArqumFarooqui-NEC** [comment]
@ThrawnCA, Thank you for your response:)
We'll check.
