### ISSUE TITLE
ckan.logic.NotFound: The action is not found for chained action

### ISSUE THREAD

**Issue by pdelboca** [ckan/ckan#5003]
### CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
Using the decorator `@toolkit.chained_action` in a method of an extension should chain it as described in the documentation: [IActions](https://docs.ckan.org/en/2.8/extensions/plugin-interfaces.html?highlight=chained_action).

Note that I'm trying to chain to a core action of CKAN not to a another extension action, but according to the docs this is possible: *...the first parameter will be set to the action function in the next plugin or in core ckan*.

### Please describe the actual behaviour
Using the decorator throws the following error when starting CKAN:

```
2019-09-25 18:19:45,340 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/bin/paster", line 11, in <module>
    load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 329, in loadapp
    **kw)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 55, in make_app
    load_environment(conf, app_conf)
  File "/srv/app/src/ckan/ckan/config/environment.py", line 112, in load_environment
    p.load_all()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 140, in load_all
    load(*plugins)
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 168, in load
    plugins_update()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 122, in plugins_update
    environment.update_config()
  File "/srv/app/src/ckan/ckan/config/environment.py", line 301, in update_config
    logic.get_action('get_site_user')({'ignore_auth': True}, None)
  File "/srv/app/src/ckan/ckan/logic/__init__.py", line 435, in get_action
    name))
ckan.logic.NotFound: The action 'user_list' is not found for chained action
```

That error is raised by the following code:
```python
@toolkit.chained_action
def user_list(action, context, data_dict):
    return action(context, data_dict)
```

And in `plugin.py`:
```python
from ckanext.myext.logic import action
...
# IActions
def get_actions(self):
    return {
       'user_list': action.user_list
    }
```

### What steps can be taken to reproduce the issue? 
- Create a new extension
- In `ckanext.myext.logic.action` create a custom decorated function like the example above.
- Add the custom function to the logic layer using the IAction interface in `plugin.py` like the example above.
- Add the extension to your CKAN 2.8.3 instance (can be also reproduced with `okfn/docker-ckan` setup)
- Start CKAN

**Comment by Zharktas** [comment]
Chained actions for the core actions are not available in CKAN 2.8 as the PR enabling them got merged in spring and it was not backported for 2.8

**Comment by wardi** [comment]
good catch @Zharktas !

 @pdelboca you can backport the PR #4509 on your own ckan fork until your next upgrade

**Comment by pdelboca** [comment]
Great! Thank you guys!
