### ISSUE TITLE
AttributeError when creating a new sysadmin user

### ISSUE THREAD

**Issue by jspinella** [ckan/ckan#5013]
### CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
When creating a new sysadmin user, I should not see a stack trace printed out below new user's details.

### Please describe the actual behaviour
When attempting to create a new sysadmin user via paster (`paster sysadmin add seanh email=seanh@localhost name=seanh -c /etc/ckan/default/production.ini`) upon selecting "y" to create a new user and entering a password twice, a dictionary of that new user's data is printed out, and following `'sysadmin': False}` a Traceback is printed, ending with `line 826 in add user.sysadmin = True` and below that it says `AttributeError: 'NoneType' object has no attribute 'sysadmin'`

I am also not able to login to the local CKAN web app with this sysadmin user, but I also cannot login with a user I created with `paster user add....` which succeeds without showing any errors/stack trace.

### What steps can be taken to reproduce the issue? 
Attempt to create a new user as a sysadmin via the paster command provided in the official CKAN documentation (https://docs.ckan.org/en/2.8/maintaining/getting-started.html#create-admin-user).

**Comment by amercader** [comment]
I could not reproduce this in 2.8.3:

```
paster sysadmin add seanh email=seanh@localhost name=seanh
User "seanh" not found
Create new user: seanh? [y/n]y
Password: 
Confirm password: 
Creating user: 'seanh'
{'about': None,
 'activity_streams_email_notifications': False,
 'apikey': u'cca0f885-d4be-4cfc-ad3e-a110ed04374d',
 'created': '2019-10-08T15:33:17.777155',
 'display_name': u'seanh',
 'email': u'seanh@localhost',
 'email_hash': '7dd9ca69c40a926bd4f4ad16834b25b5',
 'fullname': None,
 'id': u'078ed7bc-3fd0-4b50-b30a-31f3d8748d4a',
 'name': u'seanh',
 'number_created_packages': 0L,
 'number_of_edits': 0L,
 'state': u'active',
 'sysadmin': False}
Added seanh as sysadmin

```

Can you paste the full command and stack trace you are getting?

**Comment by jspinella** [comment]
`paster sysadmin add testuser4 email=jspinella@jatsby.com
 name=seacan4 -c /etc/ckan/default/production.ini
User "testuser4" not found
Create new user: testuser4? [y/n]y
Password:
Confirm password:
Creating user: 'testuser4'
{'about': None,
 'activity_streams_email_notifications': False,
 'apikey': u'8c67becb-d10d-42d3-88ea-2755a0cf63d4',
 'created': '2019-10-09T01:15:16.143654',
 'display_name': u'seacan4',
 'email': u'jspinella@jatsby.com',
 'email_hash': '1359542fdfbfb7b6f3bb9dcbcdd825e8',
 'fullname': None,
 'id': u'8f872617-0a06-4efe-81e9-71dbe400e6d8',
 'name': u'seacan4',
 'number_created_packages': 0L,
 'number_of_edits': 0L,
 'state': u'active',
 'sysadmin': False}
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 10, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 788, in command
    self.add()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 826, in add
    user.sysadmin = True
AttributeError: 'NoneType' object has no attribute 'sysadmin'`

**Comment by jspinella** [comment]
I nuked the VPS I was using and made a new one... Just to be clear, I am following the official CKAN installation guide for Ubuntu Server 16.04 LTS, which does not install `python-pastescript` by default, so I have installed that to get paster commands to run. 

Running `paster --plugin=ckan user add admin --config=/etc/ckan/std/std.ini` adter running `sudo -s` I get errors about missing python modules and had to install them one at a time with `pip`. Is this necessary or is there an easier way? Some modules are aliased (e.g. `python-magic` is `magic`) which adds to the frustration.

New users like me would benefit from a guide to set up paster for use with CKAN that includes all required python modules.

I am currently stuck at "No module named who.config" not resolved with `pip install who`

**Comment by jspinella** [comment]
I downloaded the requirements.txt file from the CKAN repository and had pip install everything in there (`pip install -r requirements.txt`). If I recall correctly, there may have been a straggler or two I had to `pip install` manually. 

Either way, after doing this I was able to create a sysadmin user by creating a new user via the CKAN web app, and then elevating that user to sysadmin with the appropriate paster command (`paster sysadmin add jspinella -c /etc/ckan/default/production.ini`). This was as root, with the virtual env enabled, from the ckan directory per the official documentation.

I was also able to create a new user with `paster user add jspinella2 -c /etc/ckan/default/production.ini`. 

**I don't know what I did differently this time. As far as I can tell I did the same exact thing I was doing in my earlier comments, the only difference being I ran that pip install for requirements.txt.** Hopefully this helps others who encounter this issue. I will likely be doing fresh installs on new VMs over the coming weeks, and hopefully I will be able to definitively say what caused this issue and what fixes it.

**Comment by kabeza** [comment]
Having same error

**Comment by ajaymaity** [comment]
Any luck on how to resolve this error? Can't believe this hasn't been resolved!
