### ISSUE TITLE
ckan 2.8.3 installation help

### ISSUE THREAD

**Issue by Akshay-Hegde** [ckan/ckan#5048]
I am using ckan 2.8.3 first time, followed instructions given in 

https://github.com/ckan/ckan/wiki/How-to-install-CKAN-2.7.2-on-CentOS-7.4

```
$ uname -r
3.10.0-957.el7.x86_64

$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

[root@localhost ckan]# su - postgres
Last login: Mon Nov  4 04:39:53 EST 2019 on pts/0
-bash-4.2$ psql -l
                                List of databases
     Name     |    Owner     | Encoding | Collate | Ctype |   Access privileges   
--------------+--------------+----------+---------+-------+-----------------------
 ckan_default | ckan_default | UTF8     | C       | C     | 
 postgres     | postgres     | UTF8     | C       | C     | 
 template0    | postgres     | UTF8     | C       | C     | =c/postgres          +
              |              |          |         |       | postgres=CTc/postgres
 template1    | postgres     | UTF8     | C       | C     | =c/postgres          +
              |              |          |         |       | postgres=CTc/postgres
(4 rows)




```

Unable to fix it

```
(default) -bash-4.2$ paster db init -c /etc/ckan/default/development.ini
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 357, in command
    self._load_config(cmd!='upgrade')
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 330, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 237, in load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 116, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 130, in load_all
    unload_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 183, in unload_all
    unload(*reversed(_PLUGINS))
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 211, in unload
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 122, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 229, in update_config
    routes_map = routing.make_map()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/routing.py", line 159, in make_map
    'search'
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/routes/mapper.py", line 201, in connect
    return self.obj.connect(*newargs, **newkargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/routing.py", line 49, in connect
    out = _Mapper.connect(self, *args, **kw)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/routes/mapper.py", line 531, in connect
    route = self.make_route(*args, **kargs)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/routes/mapper.py", line 500, in make_route
    return Route(*args, **kargs)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/routes/route.py", line 84, in __init__
    if routepath.startswith('/') and self.minimization:
AttributeError: 'NoneType' object has no attribute 'startswith'

```

pip list
```
(default) -bash-4.2$ pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package                  Version  
------------------------ ---------
alabaster                0.7.12   
Babel                    2.3.4    
Beaker                   1.9.0    
beautifulsoup4           4.5.1    
bleach                   2.1.3    
blinker                  1.4      
certifi                  2019.9.11
cffi                     1.13.2   
ckan                     2.8.3    
click                    6.7      
coverage                 4.5.4    
coveralls                1.8.2    
cryptography             2.8      
decorator                4.2.1    
docopt                   0.6.2    
docutils                 0.12     
enum34                   1.1.6    
extras                   1.0.0    
factory-boy              2.1.1    
fanstatic                0.12     
first                    2.0.2    
fixtures                 3.0.0    
Flask                    0.12.4   
Flask-Babel              0.11.2   
Flask-DebugToolbar       0.10.1   
FormEncode               1.3.1    
funcsigs                 1.0.2    
html5lib                 1.0.1    
httpretty                0.8.3    
idna                     2.8      
imagesize                1.1.0    
ipaddress                1.0.23   
itsdangerous             0.24     
Jinja2                   2.8      
linecache2               1.0.0    
Mako                     1.0.7    
Markdown                 2.6.7    
MarkupSafe               1.0      
mock                     2.0.0    
mox3                     0.28.0   
nose                     1.3.7    
ofs                      0.4.2    
packaging                19.2     
Pairtree                 0.7.1-T  
passlib                  1.6.5    
Paste                    1.7.5.1  
PasteDeploy              1.5.2    
PasteScript              2.0.2    
pbr                      1.10.0   
pip                      19.3.1   
pip-tools                1.7.0    
polib                    1.0.7    
psycopg2                 2.7.3.2  
pycodestyle              2.2.0    
pycparser                2.19     
pyfakefs                 2.9      
Pygments                 2.2.0    
Pylons                   0.9.7    
pyOpenSSL                19.0.0   
pyparsing                2.4.2    
pysolr                   3.6.0    
python-dateutil          1.5      
python-magic             0.4.15   
python-mimeparse         1.6.0    
pytz                     2016.7   
pyutilib.component.core  4.6.4    
redis                    2.10.6   
repoze.lru               0.7      
repoze.who               2.3      
repoze.who-friendlyform  1.0.8    
requests                 2.11.1   
Routes                   1.13     
rq                       0.6.0    
setuptools               36.1.0   
simplejson               3.10.0   
six                      1.11.0   
snowballstemmer          2.0.0    
Sphinx                   1.7.1    
sphinx-rtd-theme         0.3.1    
sphinxcontrib-websupport 1.1.2    
SQLAlchemy               1.1.11   
sqlalchemy-migrate       0.10.0   
sqlparse                 0.2.2    
Tempita                  0.5.2    
testtools                2.3.0    
traceback2               1.4.0    
typing                   3.7.4.1  
tzlocal                  1.3      
unicodecsv               0.14.1   
unittest2                1.1.0    
urllib3                  1.25.6   
vdm                      0.14     
webencodings             0.5.1    
WebError                 0.13.1   
WebHelpers               1.3      
WebOb                    1.0.8    
WebTest                  1.4.3    
Werkzeug                 0.14.1   
wheel                    0.29.0   
zope.interface           4.3.2   

```

**Comment by smotornyuk** [comment]
After swithcing to 2.8.3, have you:
1. removed all `*.pyc` files
2. reinstalled requirements - `pip install -r requirements.txt`
3. reinstalled CKAN itself - `python setup.py develop` 
?

**Comment by Akshay-Hegde** [comment]
@smotornyuk I could install with the help of ckan gitter channel 3 days before, I had to reinstall it, I raised one more issue which is on rest api please help.
