### ISSUE TITLE
cli.py does not support non-ascii characters

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#5052]
### CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
Get the user list from command line.

### Please describe the actual behaviour
```
Users:
count = 6
name=default
name=francesco.frassinelli@nina.no display=Francesco Frassinelli
Traceback (most recent call last):
  File "/usr/local/bin/ckan-paster", line 10, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 885, in command
    self.list()
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 901, in list
    print(self.get_user_str(user))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 47: ordinal not in range(128)
```

### What steps can be taken to reproduce the issue? 
1. Add a user with non-ascii character
2. Run `ckan-paster --plugin=ckan user list -c /etc/ckan/production.ini`

I am using `ckanext-oauth2`.

It looks similar to #1244

**Comment by amercader** [comment]
We are moving to the new [Click](https://click.palletsprojects.com/en/7.x/) based CLI (see https://github.com/ckan/ckan/issues/4639). Among many improvements it has the `echo()` function that deals with this kind of errors.

**Comment by frafra** [comment]
Nice, but should I suppose that 2.8 will not get the fix?
