### ISSUE TITLE
Intermittent 500s from index page

### ISSUE THREAD

**Issue by davidmsibley** [ckan/ckan#5105]
I've been having an intermittent "Internal Server Error" being served as the index page. It seems to happen on the first call to the server after a while, and then when you refresh immediately, you get the normal index page. It doesn't get logged via the normal logging levels. I upped the logging levels and was able to capture some logs of it happening.

### CKAN Version if known (or site URL)
2.8.3 running via docker

### Please describe the expected behaviour
Visiting the index page will respond with a success every time

Normal response logs:
```
2019-11-27 20:46:39,441 DEBUG [ckan.config.middleware.flask_app] Flask route match, endpoint: home.index, args: {}, origin: core
2019-11-27 20:46:39,443 DEBUG [ckan.config.middleware] Route support answers for GET /: [(True, 'flask_app', 'core'), (False, 'pylons_app')]
2019-11-27 20:46:39,444 DEBUG [ckan.config.middleware] Serving request via flask_app app
2019-11-27 20:46:39,445 INFO  [repoze.who] request classification: browser
2019-11-27 20:46:39,446 INFO  [repoze.who] -- repoze.who request started (/) --
2019-11-27 20:46:39,447 INFO  [repoze.who] no identities found, not authenticating
2019-11-27 20:46:39,464 DEBUG [ckan.logic] check access OK - site_read user=
2019-11-27 20:46:39,465 DEBUG [ckan.logic] check access OK - package_search user=
2019-11-27 20:46:39,466 DEBUG [ckan.lib.search.query] Package query: {u'sort': u'view_recent desc', u'fq': [u'+capacity:public capacity:"public"', u'+site_id:"default"', '+state:active', u'+permission_labels:("public")'], 'facet.mincount': 1, u'rows': 5, u'facet.field': [u'organization', u'groups', u'tags', u'res_format', u'license_id'], 'facet.limit': '50', 'facet': 'true', u'q': u'*:*', u'start': 4, 'wt': 'json', 'fl': 'id validated_data_dict'}
2019-11-27 20:46:39,470 INFO  [requests.packages.urllib3.connectionpool] Starting new HTTP connection (1): solr
2019-11-27 20:46:39,519 INFO  [pysolr] Finished 'http://solr:8983/solr/ckan/select/?sort=view_recent+desc&fq=%2Bcapacity%3Apublic+capacity%3A%22public%22&fq=%2Bsite_id%3A%22default%22&fq=%2Bstate%3Aactive&fq=%2Bpermission_labels%3A%28%22public%22%29&facet.mincount=1&rows=5&facet.field=organization&facet.field=groups&facet.field=tags&facet.field=res_format&facet.field=license_id&facet.limit=50&facet=true&q=%2A%3A%2A&start=4&wt=json&fl=id+validated_data_dict' (get) with body '' in 0.052 seconds, with status 200
2019-11-27 20:46:39,527 DEBUG [ckan.logic] check access OK - user_create user=
2019-11-27 20:46:39,544 DEBUG [ckan.logic] check access OK - group_list user=
2019-11-27 20:46:39,549 DEBUG [ckan.logic] check access OK - organization_list user=
2019-11-27 20:46:39,557 INFO  [repoze.who] no challenge required
2019-11-27 20:46:39,557 INFO  [repoze.who] -- repoze.who request ended (/) --
```

### Please describe the actual behaviour
Visiting the index page sometimes responds with a 500, but will usually respond normally with repeated usage.

500 response logs:
```
2019-11-27 20:52:32,340 DEBUG [ckan.config.middleware.flask_app] Flask route match, endpoint: home.index, args: {}, origin: core
2019-11-27 20:52:32,342 DEBUG [ckan.config.middleware] Route support answers for GET /: [(True, 'flask_app', 'core'), (False, 'pylons_app')]
2019-11-27 20:52:32,343 DEBUG [ckan.config.middleware] Serving request via flask_app app
2019-11-27 20:52:32,344 INFO  [repoze.who] request classification: browser
2019-11-27 20:52:32,344 INFO  [repoze.who] -- repoze.who request started (/) --
2019-11-27 20:52:32,344 INFO  [repoze.who] no identities found, not authenticating
2019-11-27 20:52:32,355 DEBUG [ckan.logic] check access OK - user_create user=
2019-11-27 20:52:32,369 INFO  [repoze.who] no challenge required
2019-11-27 20:52:32,369 INFO  [repoze.who] -- repoze.who request ended (/) --
```

### What steps can be taken to reproduce the issue? 
`curl http://ckan:5000`

logger configuration:
```
## Logging configuration
[loggers]
keys = root, ckan, ckanext

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_ckan]
level = DEBUG
handlers = console
qualname = ckan
propagate = 0

[logger_ckanext]
level = DEBUG
handlers = console
qualname = ckanext
propagate = 0

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
```

**Comment by davidmsibley** [comment]
I started running the server in debug mode, and was able to get a stack trace:
```
2019-12-20 19:55:08,375 DEBUG [ckan.config.middleware.flask_app] Flask route match, endpoint: home.index, args: {}, origin: core
2019-12-20 19:55:08,417 DEBUG [ckan.config.middleware] Route support answers for GET /: [(True, 'flask_app', 'core'), (False, 'pylons_app')]
2019-12-20 19:55:08,417 DEBUG [ckan.config.middleware] Serving request via flask_app app
2019-12-20 19:55:08,418 INFO  [repoze.who] request classification: browser
2019-12-20 19:55:08,418 INFO  [repoze.who] -- repoze.who request started (/) --
2019-12-20 19:55:08,418 INFO  [repoze.who] no identities found, not authenticating
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
    self.wsgi_execute()
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
    self.wsgi_start_response)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
    return self.apps[app_name](environ, start_response)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
    return request.get_response(self.app)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
    response = request.get_response(self.app)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 282, in ckan_before_request
    app_globals.app_globals._check_uptodate()
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/app_globals.py", line 202, in _check_uptodate
    value = model.get_system_info('ckan.config_update')
  File "/usr/lib/ckan/venv/src/ckan/ckan/model/system_info.py", line 59, in get_system_info
    obj = meta.Session.query(SystemInfo).filter_by(key=key).first()
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2755, in first
    ret = list(self[0:1])
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
    return list(res)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
     This probably means the server terminated abnormally
     before or while processing the request.
 [SQL: 'SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state, system_info.revision_id AS system_info_revision_id \nFROM system_info \nWHERE system_info.key = %(key_1)s \n LIMIT %(param_1)s'] [parameters: {'key_1': 'ckan.config_update', 'param_1': 1}]
```

I'm not sure if this is exactly the same failure I was seeing in non-debug mode, but it was achieved the same way: by visiting the front page after a long period of inactivity.

**Comment by davidmsibley** [comment]
This looks like maybe the TCP connection to Postgres is closed due inactivity, then when the python code tries to use what it considers an active database connection, it errors out.

**Comment by davidmsibley** [comment]
I think I found it. Key bit of information is that I'm trying to run CKAN using Docker Swarm. 

https://forums.docker.com/t/tcp-timeout-that-occurs-only-in-docker-swarm-not-simple-docker-run/58179
Looks like the Docker Swarm IPVS cuts connections at 15 minutes, rather than 2 hours which is normally the default.

One solution to this is to set `endpoint_mode: dnsrr` on the db service.
https://success.docker.com/article/ipvs-connection-timeout-issue

This solves the issue as long as you don't need to access the database from outside the stack. However, you cannot map an ingress port to a service that is using `dnsrr`. So instead, I'm setting `tcp_keepalives_idle=600` in the postgres configuration.

This is briefly mentioned in the postgres documentation: https://github.com/docker-library/postgres/issues/538
