### ISSUE TITLE
ckan database installation error

### ISSUE THREAD

**Issue by Rakhibatra** [ckan/ckan#5106]
I am trying to install CKAN on windows 10 by following instructions from below link:
https://github.com/ckan/ckan/wiki/How-to-Install-CKAN-2.5.2-on-Windows-7

But I am getting below error while executing this command (13th command) "C:\src\ckan>paster db init -c development.ini" 

Error loading 'pyutilib.component' entry points: 'type object 'PluginGlobals' has no attribute 'add_env''
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Rakhi\Envs\ckan\Scripts\paster.exe\__main__.py", line 7, in <module>
  File "c:\users\rakhi\envs\ckan\lib\site-packages\paste\script\command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "c:\users\rakhi\envs\ckan\lib\site-packages\paste\script\command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "c:\users\rakhi\envs\ckan\lib\site-packages\paste\script\command.py", line 236, in run
    result = self.command()
  File "c:\src\ckan\ckan\lib\cli.py", line 205, in command
    self._load_config(cmd!='upgrade')
  File "c:\src\ckan\ckan\lib\cli.py", line 147, in _load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "c:\src\ckan\ckan\config\environment.py", line 232, in load_environment
    p.load_all(config)
  File "c:\src\ckan\ckan\plugins\core.py", line 124, in load_all
    unload_all()
  File "c:\src\ckan\ckan\plugins\core.py", line 181, in unload_all
    unload(*reversed(_PLUGINS))
  File "c:\src\ckan\ckan\plugins\core.py", line 209, in unload
    plugins_update()
  File "c:\src\ckan\ckan\plugins\core.py", line 116, in plugins_update
    environment.update_config()
  File "c:\src\ckan\ckan\config\environment.py", line 416, in update_config
    logic.get_action('get_site_user')({'ignore_auth': True}, None)
  File "c:\src\ckan\ckan\logic\__init__.py", line 416, in wrapped
    result = _action(context, data_dict, **kw)
  File "c:\src\ckan\ckan\logic\action\get.py", line 2450, in get_site_user
    user = model.User.get(site_id)
  File "c:\src\ckan\ckan\model\user.py", line 64, in get
    return query.first()
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\orm\query.py", line 2334, in first
    ret = list(self[0:1])
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\orm\query.py", line 2201, in __getitem__
    return list(res)
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\orm\query.py", line 2405, in __iter__
    return self._execute_and_instances(context)
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\orm\query.py", line 2420, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\engine\base.py", line 727, in execute
    return meth(self, multiparams, params)
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\sql\elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\engine\base.py", line 824, in _execute_clauseelement
    compiled_sql, distilled_params
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\engine\base.py", line 954, in _execute_context
    context)
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\engine\base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\util\compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\engine\base.py", line 947, in _execute_context
    context)
  File "c:\users\rakhi\envs\ckan\lib\site-packages\sqlalchemy\engine\default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DBAPIError: (UndefinedTable) relation "user" does not exist
LINE 2: FROM "user"
             ^
 'SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".openid AS user_openid, "user".fullname AS user_fullname, "user".email AS user_email, "user".apikey AS user_apikey, "user".created AS user_created, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".activity_streams_email_notifications AS user_activity_streams_email_notifications, "user".sysadmin AS user_sysadmin, "user".state AS user_state \nFROM "user" \nWHERE "user".name = %(name_1)s OR "user".openid = %(openid_1)s OR "user".id = %(id_1)s ORDER BY "user".name \n LIMIT %(param_1)s' {'id_1': 'default', 'name_1': 'default', 'param_1': 1, 'openid_1': 'default'}

Can someone guide how to solve this? Thank you

**Comment by tino097** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow as we dont have support for Windows yet.

You can also try on the Gitter [#ckan](https://gitter.im/ckan/chat) channel, where other developers may be able to help you.

Thanks!
