### ISSUE TITLE
is_flask_request() returns error

### ISSUE THREAD

**Issue by boykoc** [ckan/ckan#5118]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.8.2

### Please describe the expected behaviour
`def is_flask_request()` should return boolean value.

### Please describe the actual behaviour
In some circumstances `def is_flask_request()` returns an error that can evaluate to falsey. 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 325, in getMessage
    msg = str(self.msg)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/werkzeug/local.py", line 366, in <lambda>
    __str__ = lambda x: str(x._get_current_object())
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
Logged from file base.py, line 123
```

### What steps can be taken to reproduce the issue? 

One way is to print the output of `is_flask_request()` to a log file (thats how I got the above by printing it from where it's called in `ckan/lib/base.py` in `def render()`.

But this might cause issues when someone is using it to check the type of request like:

`if not is_flask_request():` 

in [`ckan/lib/base.py`](https://github.com/ckan/ckan/blob/8c40f3908369d340e57689268ba811616021cbc3/ckan/lib/base.py#L141). This evaluates to `True` even though an error is being raised and `False` isn't being returned.

#### Sample of pages/routes affected:

- user profile edit form returns `True` (/user/edit/<user>)
- Dataset page returns error (/dataset)
- new dataset form  returns error  (/dataset/new)
- organization page returns error  (/organization)

**Comment by boykoc** [comment]
_**While creating issue I found the "fix", so I'm creating this issue to leave as documentation for others.**_

This is fixed based on issue # 4431 and setting [`streaming=False`](https://github.com/ckan/ckan/issues/4431#issuecomment-463938811).

This was fixed in CKAN in PR #4657 

After setting `streaming=False` the error went away and boolean values were returned.
