### ISSUE TITLE
CKAN Installation issue in FIPS enabled EC2 Instance (ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips)

### ISSUE THREAD

**Issue by marikanti** [ckan/ckan#5205]
CKAN Version - 2.8.3 (Latest)

Installing CKAN on Federal Cloud AWS Instance on RHEL 7.7
 
During the installation process while initializing Database using this command
"paster db init -c /etc/ckan/default/development.ini"

[FIPS Issue ](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards)

I'm getting the below error :
(default) [root@ip-x-x-x-x ckan]# paster db init -c /etc/ckan/default/development.ini
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 101, in run
    command = commands[command_name].load()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/ckan/lib/default/src/ckan/ckan/lib/cli.py", line 32, in <module>
    from ckan.config.middleware import make_app
  File "/root/ckan/lib/default/src/ckan/ckan/config/middleware/__init__.py", line 13, in <module>
    from ckan.config.middleware.flask_app import make_flask_stack
  File "/root/ckan/lib/default/src/ckan/ckan/config/middleware/flask_app.py", line 18, in <module>
    from beaker.middleware import SessionMiddleware
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py", line 11, in <module>
    from beaker.cache import CacheManager
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/cache.py", line 23, in <module>
    import beaker.ext.mongodb as mongodb
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/ext/mongodb.py", line 102, in <module>
    class MongoSynchronizer(SynchronizerImpl):
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/ext/mongodb.py", line 106, in MongoSynchronizer
    MACHINE_ID = machine_identifier()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/util.py", line 489, in machine_identifier
    machine_hash = hashlib.md5()
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips

Someone had this error ? How to resolve this issue ?

We cannot disable [FIPS](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards) as its security issue.

**Comment by wardi** [comment]
Most ckan users don't have to run under FIPS, have you tried asking the data.gov folks https://github.com/GSA/ckanext-geodatagov ? Maybe they can share the changes they are using.
