### ISSUE TITLE
Problems installing CKAN in Debian

### ISSUE THREAD

**Issue by AlmuHS** [ckan/ckan#5209]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
latest

### Please describe the expected behaviour
https://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#create-database-tables
`paster db init -c /etc/ckan/default/development.ini`

`Initialising DB: SUCCESS`

### Please describe the actual behaviour
(default) pruebas@debian:/usr/lib/ckan/default/src/ckan$ paster db init -c /etc/ckan/default/development.ini 
Please specify a ckan.storage_path in your config
                         for your uploads
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/lib/python3.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/lib/python3.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/lib/python3.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 309, in command
    self._load_config(cmd != 'upgrade')
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 286, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 200, in load_config
    flask_app = app.apps['flask_app']._wsgi_app
AttributeError: 'I18nMiddleware' object has no attribute 'apps'

**Comment by smotornyuk** [comment]
You are using `latest` version of docs - it's currently not stable and there are a bunch of pending updates to it(for example, we are migrating away from paster, and instead of installing `pastescript`, it would be much better to use `ckan -c config.ini db init`). In your case, just switch to 2.8 release - https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html and it should work.

**Comment by AlmuHS** [comment]
Using `ckan -c /etc/ckan/default/development.ini db init` appears another problem

```
(default) pruebas@debian:~$ ckan -c /etc/ckan/default/development.ini db init
Please specify a ckan.storage_path in your config
                         for your uploads
(psycopg2.errors.InvalidTableDefinition) no se permiten múltiples llaves primarias para la tabla «package_extra_revision»

[SQL: ALTER TABLE package_extra_revision ADD CONSTRAINT package_extra_revision_pkey PRIMARY KEY (id, revision_id)]
(Background on this error at: http://sqlalche.me/e/f405)
```

> In your case, just switch to 2.8 release - https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html and it should work.

In 2.8 version I had another similar problems. I will put a new issue about them
