### ISSUE TITLE
Testing extensions gives who.ini error

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#5211]
I'm getting an issue running tests in an extension:
```
(default) vagrant@ubuntu-bionic:/vagrant/src/ckanext-dcat$ pytest --ckan-ini=test.ini
Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/common.py", line 61, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
pysolr.SolrError: Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
Problems were found while connecting to the SOLR server
Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/common.py", line 61, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
pysolr.SolrError: Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
Problems were found while connecting to the SOLR server
Please specify a ckan.storage_path in your config
                         for your uploads
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.6/site-packages/_pytest/main.py", line 204, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/vagrant/src/ckan/ckan/tests/pytest_ckan/ckan_setup.py", line 27, in pytest_sessionstart
INTERNALERROR>     app = make_app(conf.global_conf, **conf.local_conf)
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 58, in make_app
INTERNALERROR>     flask_app = make_flask_stack(conf, **app_conf)
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 286, in make_flask_stack
INTERNALERROR>     who_parser.parse(open(app_conf['who.config_file']))
INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: '/vagrant/src/ckanext-dcat/who.ini'
```
I believe this is related to the new CKANConfigLoader https://github.com/ckan/ckan/pull/5135 from @pdelboca 

It is looking for who.ini in the extension directory, when it should look in core ckan's directory. test.ini has `use = config:../ckan/test-core.ini` which in turn has `who.config_file = %(here)s/who.ini`, and the problem is that the value of `here` is the set by ckanext-dcat/test.ini, rather than ckan/test-core.ini - see https://github.com/ckan/ckan/pull/5135/files#diff-1aee1cf6e7f57da5372718f53a9836adR21

I wonder since this area is fresh in mind, if @pdelboca might suggest how best to adjust `here` when reading these ini files referenced by `use = config:`?

### CKAN Version if known (or site URL)
master

### Reproducing

Running the tests for @amercader 's ckanext-dcat py3 branch: https://github.com/ckan/ckanext-dcat/pull/174 with the latest ckan master.

**Comment by amercader** [comment]
@davidread I also noticed this while working on the py3 harvest tests and discussed the issue on #5204, check my last comment there

**Comment by pdelboca** [comment]
I updated #5204 to fix this issue, should be ready as soon as it is merged. Any feedback or testing using that branch will be appreciated!

**Comment by davidread** [comment]
Many thanks @pdelboca and @amercader !
