### ISSUE TITLE
Problems installing CKAN 2.8 in Debian 19

### ISSUE THREAD

**Issue by AlmuHS** [ckan/ckan#5214]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.8

### Please describe the expected behaviour
```
cd /usr/lib/ckan/default/src/ckan
paster db init -c /etc/ckan/default/development.ini
```
`Initialising DB: SUCCESS`

### Please describe the actual behaviour

```
(default) pruebas@debian:/usr/lib/ckan/default/src/ckan$ paster db init -c /etc/ckan/default/development.ini
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 357, in command
    self._load_config(cmd!='upgrade')
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 330, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 261, in load_config
    site_user = logic.get_action('get_site_user')({'ignore_auth': True}, {})
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 464, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 2377, in get_site_user
    user = model.User.get(site_id)
  File "/usr/lib/ckan/default/src/ckan/ckan/model/user.py", line 56, in get
    return query.first()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2755, in first
    ret = list(self[0:1])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
    return list(res)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) no existe la columna user.password
LINE 1: SELECT "user".password AS user_password, "user".id AS user_i...
               ^
 [SQL: 'SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".fullname AS user_fullname, "user".email AS user_email, "user".apikey AS user_apikey, "user".created AS user_created, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".activity_streams_email_notifications AS user_activity_streams_email_notifications, "user".sysadmin AS user_sysadmin, "user".state AS user_state \nFROM "user" \nWHERE "user".name = %(name_1)s OR "user".id = %(id_1)s ORDER BY "user".name \n LIMIT %(param_1)s'] [parameters: {'name_1': 'default', 'param_1': 1, 'id_1': 'default'}]
```

### What steps can be taken to reproduce the issue? 
```
sudo apt-get install python-dev postgresql libpq-dev python-pip python-virtualenv git-core solr-jetty openjdk-11-jdk redis-server
sudo mkdir -p /usr/lib/ckan/default
sudo chown `whoami` /usr/lib/ckan/default
virtualenv --no-site-packages /usr/lib/ckan/default
 . /usr/lib/ckan/default/bin/activate
python --version
pip install setuptools==36.1
pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.8.2#egg=ckan'
pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt
deactivate 
 . /usr/lib/ckan/default/bin/activate
 sudo mkdir -p /etc/ckan/default
 sudo chown -R `whoami` /etc/ckan/
 sudo chown -R `whoami` ~/ckan/etc
 paster make-config ckan /etc/ckan/default/development.ini
 sudo nano /etc/ckan/default/development.ini
 sudo nano /etc/default/jetty9 
 sudo service jetty9 start
 sudo mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak
 sudo ln -s /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml
 sudo service jetty9 start
 sudo nano /etc/default/jetty9 
 sudo nano /etc/ckan/default/development.ini
 cd /usr/lib/ckan/default/src/ckan
 paster db init -c /etc/ckan/default/development.ini
```

**Comment by Zharktas** [comment]
You have not created the database for ckan to access as per instructions https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html#setup-a-postgresql-database

**Comment by AlmuHS** [comment]
> You have not created the database for ckan to access as per instructions https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html#setup-a-postgresql-database

I have created previously in another installation

**Comment by joshiraez** [comment]
Same here. Database created, role created. It even creates all the default info, but still is not creating the table user alright.

**Comment by joshiraez** [comment]
Is working fine for me in 2.8.1 but I'm getting conflicting reports. I'll keep checking

**Comment by ThrawnCA** [comment]
@joshiraez The scripts in `ckan/migration/versions/` create the tables; 003 creates the user table, and 030 adds the password field.

**Comment by wardi** [comment]
Possibly unrelated, but I ran into the same error with an older ckan that was fixed by using `psycopg2==2.7.7` instead of `psycopg2==2.8.2` which I was using to test master.

**Comment by espirado** [comment]
I am having an issue with ckan 2.8.4 on ubuntu 18. when i ran the 
`` 
cd /usr/lib/ckan/default/src/ckan
``
``
paster db init -c /etc/ckan/default/development.ini
``

output 
`` Initialising DB: SUCCESS ``

After deploying to apache2 am getting the default apache page and looking at the error logs i get 
``[Mon Jun 15 09:33:33.189207 2020] [wsgi:error] [pid 109480] [remote 127.0.0.1:48720]     reraise(type(exception), exception, tb=exc_tb, cause=cause)
``
`` [Mon Jun 15 09:33:33.189212 2020] [wsgi:error] [pid 109480] [remote 127.0.0.1:48720]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
``
``[Mon Jun 15 09:33:33.189219 2020] [wsgi:error] [pid 109480] [remote 127.0.0.1:48720]     context)
``
``[Mon Jun 15 09:33:33.189223 2020] [wsgi:error] [pid 109480] [remote 127.0.0.1:48720]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
``
``[Mon Jun 15 09:33:33.189231 2020] [wsgi:error] [pid 109480] [remote 127.0.0.1:48720]     cursor.execute(statement, parameters)
``
``[Mon Jun 15 09:33:33.189271 2020] [wsgi:error] [pid 109480] [remote 127.0.0.1:48720] ProgrammingError: (psycopg2.errors.UndefinedColumn) column cons.consrc does not exist
``
``[Mon Jun 15 09:33:33.189276 2020] [wsgi:error] [pid 109480] [remote 127.0.0.1:48720] LINE 4:                 cons.consrc as src
``
``[Mon Jun 15 09:33:33.189278 2020] [wsgi:error] [pid 109480] [remote 127.0.0.1:48720]                         ^
``
``[Mon Jun 15 09:33:33.189281 2020] [wsgi:error] [pid 109480] [remote 127.0.0.1:48720] HINT:  Perhaps you meant to reference the column "cons.conkey" or the column "cons.conbin".
``
``[Mon Jun 15 09:33:33.189284 2020] [wsgi:error] [pid 109480] [remote 127.0.0.1:48720]  [SQL: "\\n            SELECT\\n                cons.conname as name,\\n                cons.consrc as src\\n            FROM\\n                pg_catalog.pg_constraint cons\\n            WHERE\\n                cons.conrelid = %(table_oid)s AND\\n                cons.contype = 'c'\\n        "] [parameters: {'table_oid': 17942}]
``


Trying to update 
`` sudo pip install --upgrade sqlalchemy ``

I get 

``Requirement already up-to-date: sqlalchemy``

How can i work around this?

**Comment by linforestzhang** [comment]
Same Problem with the user table:
CentOS 7.8; POSTGRESQL 10; Solr-5.5.5

Babel (2.3.4)
Beaker (1.9.0)
bleach (2.1.3)
ckan (2.8.5)
click (6.7)
decorator (4.2.1)
fanstatic (0.12)
Flask (0.12.4)
Flask-Babel (0.11.2)
FormEncode (1.3.1)
funcsigs (1.0.2)
html5lib (1.0.1)
itsdangerous (0.24)
Jinja2 (2.8)
Mako (1.0.7)
Markdown (2.6.7)
MarkupSafe (1.0)
nose (1.3.7)
ofs (0.4.2)
Pairtree (0.7.1-T)
passlib (1.6.5)
Paste (1.7.5.1)
PasteDeploy (1.5.2)
PasteScript (2.0.2)
pbr (1.10.0)
pip (20.2.2)
polib (1.0.7)
psycopg2 (2.7.3.2)
Pygments (2.2.0)
Pylons (0.9.7)
pysolr (3.6.0)
python-dateutil (1.5)
python-magic (0.4.15)
pytz (2016.7)
pyutilib.component.core (4.6.4)
redis (2.10.6)
repoze.lru (0.7)
repoze.who (2.3)
repoze.who-friendlyform (1.0.8)
requests (2.11.1)
Routes (1.13)
rq (0.6.0)
setuptools (36.1.0)
simplejson (3.10.0)
six (1.11.0)
SQLAlchemy (1.1.11)
sqlalchemy-migrate (0.10.0)
sqlparse (0.2.2)
Tempita (0.5.2)
tzlocal (1.3)
unicodecsv (0.14.1)
vdm (0.14)
webencodings (0.5.1)
WebError (0.13.1)
WebHelpers (1.3)
WebOb (1.0.8)
WebTest (1.4.3)
Werkzeug (0.14.1)
wheel (0.29.0)
zope.interface (4.3.2)

**Comment by shribrainium** [comment]
> @joshiraez The scripts in `ckan/migration/versions/` create the tables; 003 creates the user table, and 030 adds the password field.

I have created the migration file 
edited the migration file
def upgrade() -> None:
    op.add_column('group', sa.Column('organization_places', sa.String(50)))
now can you please tell me the command to commit the migration. or how can I add the column to table
