### ISSUE TITLE
Running werkzeug run on a different host results in KeyError

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#5237]
### CKAN Version if known (or site URL)
master

### Please describe the expected behaviour
Running  
```
ckan -c ckan.ini run -H some_ip_address 
``` 
should start ckan listening in given ip address.

### Please describe the actual behaviour
Server crashes with following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 1018, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/vagrant/ckan/cli/cli.py", line 56, in _init_ckan_config
    ctx.obj = CkanCommand(value)
  File "/vagrant/ckan/cli/cli.py", line 46, in __init__
    self.app = make_app(self.config)
  File "/vagrant/ckan/config/middleware/__init__.py", line 58, in make_app
    flask_app = make_flask_stack(conf)
  File "/vagrant/ckan/config/middleware/flask_app.py", line 285, in make_flask_stack
    who_parser.parse(open(conf['who.config_file']))
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/repoze/who/config.py", line 86, in parse
    obj = self._makePlugin(name, IPlugin, options)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/repoze/who/config.py", line 40, in _makePlugin
    obj = _resolve(name)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/repoze/who/config.py", line 23, in _resolve
    return EntryPoint.parse('x=%s' % name).resolve()
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/vagrant/ckan/lib/repoze_plugins/auth_tkt.py", line 23, in <module>
    _ckan_userid_type_decoders.pop('unicode')
KeyError: 'unicode'
```

### What steps can be taken to reproduce the issue? 
Run ckan dev server on different ip address.

**Comment by Zharktas** [comment]
Apparently fixed already, should have tested with actual master.
