### ISSUE TITLE
ckan installed with docker can't connect to solr

### ISSUE THREAD

**Issue by tugn0x** [ckan/ckan#5270]
### CKAN Version if known (or site URL)
same behaviour with latest (master) and 2.8.2

### Please describe the expected behaviour
CKAN should connect to solr

### Please describe the actual behaviour
CKAN can't connect to SOLR

```
020-03-09 11:05:45,532 ERROR [pysolr] Failed to connect to server at 'http://solr:8983/solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json', are you sure that URL is correct? Checking it in a browser might help: HTTPConnectionPool(host='solr', port=8983): Max retries exceeded with url: /solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9758688d10>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pysolr.py", line 366, in _send_request
    timeout=self.timeout)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='solr', port=8983): Max retries exceeded with url: /solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9758688d10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-03-09 11:05:45,532 ERROR [ckan.lib.search.common] Failed to connect to server at 'http://solr:8983/solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json', are you sure that URL is correct? Checking it in a browser might help: HTTPConnectionPool(host='solr', port=8983): Max retries exceeded with url: /solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9758688d10>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/search/common.py", line 61, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pysolr.py", line 375, in _send_request
    raise SolrError(error_message % params)
SolrError: Failed to connect to server at 'http://solr:8983/solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json', are you sure that URL is correct? Checking it in a browser might help: HTTPConnectionPool(host='solr', port=8983): Max retries exceeded with url: /solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9758688d10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-03-09 11:05:45,533 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
```
But Solr is up and running
```
Starting Solr 6.6.5
2020-03-09 11:05:42.987 INFO  (main) [   ] o.e.j.s.Server jetty-9.3.14.v20161028
2020-03-09 11:05:43.936 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter  ___      _       Welcome to Apache Solr™ version 6.6.5
2020-03-09 11:05:43.937 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter / __| ___| |_ _   Starting in standalone mode on port 8983
2020-03-09 11:05:43.937 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter \__ \/ _ \ | '_|  Install dir: /opt/solr
2020-03-09 11:05:43.978 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter |___/\___/_|_|    Start time: 2020-03-09T11:05:43.940Z
2020-03-09 11:05:44.018 INFO  (main) [   ] o.a.s.c.SolrResourceLoader Using system property solr.solr.home: /opt/solr/server/solr
2020-03-09 11:05:44.028 INFO  (main) [   ] o.a.s.c.SolrXmlConfig Loading container configuration from /opt/solr/server/solr/solr.xml
2020-03-09 11:05:44.283 INFO  (main) [   ] o.a.s.c.SolrResourceLoader [null] Added 0 libs to classloader, from paths: []
2020-03-09 11:05:45.170 INFO  (main) [   ] o.a.s.u.UpdateShardHandler Creating UpdateShardHandler HTTP client with params: socketTimeout=600000&connTimeout=60000&retry=true
2020-03-09 11:05:45.537 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 1 core definitions underneath /opt/solr/server/solr
2020-03-09 11:05:45.538 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Cores are: [ckan]
2020-03-09 11:05:45.548 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.TransientSolrCoreCacheDefault Allocating transient cache for 2147483647 transient cores
2020-03-09 11:05:45.741 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.c.SolrResourceLoader [ckan] Added 53 libs to classloader, from paths: [/opt/solr/contrib/clustering/lib, /opt/solr/contrib/extraction/lib, /opt/solr/contrib/langid/lib, /opt/solr/contrib/velocity/lib, /opt/solr/dist]
2020-03-09 11:05:45.804 INFO  (main) [   ] o.e.j.s.Server Started @4159ms
2020-03-09 11:05:45.869 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.c.SolrConfig Using Lucene MatchVersion: 6.0.0
2020-03-09 11:05:46.015 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.s.ManagedIndexSchemaFactory The schema is configured as managed, but managed schema resource managed-schema not found - loading non-managed schema schema.xml instead
2020-03-09 11:05:46.078 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.s.IndexSchema [ckan] Schema name=ckan
2020-03-09 11:05:46.224 WARN  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.c.SolrResourceLoader Solr loaded a deprecated plugin/analysis class [solr.SynonymFilterFactory]. Please consult documentation how to replace it accordingly.
2020-03-09 11:05:46.231 WARN  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.c.SolrResourceLoader Solr loaded a deprecated plugin/analysis class [solr.WordDelimiterFilterFactory]. Please consult documentation how to replace it accordingly.
2020-03-09 11:05:46.276 WARN  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.s.IndexSchema 'defaultSearchField' is deprecated, please use 'df' on request instead.
2020-03-09 11:05:46.276 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.s.IndexSchema [ckan] default search field in schema is text.
2020-03-09 11:05:46.279 WARN  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.s.IndexSchema [ckan] query parser default operator is AND. WARNING: Deprecated, please use 'q.op' on request instead. Will not work from Solr 7
2020-03-09 11:05:46.446 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.s.IndexSchema Loaded schema ckan/2.9 with uniqueid field index_id
2020-03-09 11:05:46.479 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.s.ManagedIndexSchema Upgraded to managed schema at /opt/solr/server/solr/ckan/conf/managed-schema
2020-03-09 11:05:46.486 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.s.ManagedIndexSchemaFactory After upgrading to managed schema, renamed the non-managed schema /opt/solr/server/solr/ckan/conf/schema.xml to /opt/solr/server/solr/ckan/conf/schema.xml.bak
2020-03-09 11:05:46.486 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.c.CoreContainer Creating SolrCore 'ckan' using configuration from instancedir /opt/solr/server/solr/ckan, trusted=true
2020-03-09 11:05:46.560 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.c.SolrCore solr.RecoveryStrategy.Builder
2020-03-09 11:05:46.567 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.c.SolrCore [[ckan] ] Opening new SolrCore at [/opt/solr/server/solr/ckan], dataDir=[/opt/solr/server/solr/ckan/data/]
2020-03-09 11:05:46.676 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.r.XSLTResponseWriter xsltCacheLifetimeSeconds=5
2020-03-09 11:05:47.223 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.u.UpdateHandler Using UpdateLog implementation: org.apache.solr.update.UpdateLog
2020-03-09 11:05:47.224 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.u.UpdateLog Initializing UpdateLog: dataDir= defaultSyncLevel=FLUSH numRecordsToKeep=100 maxNumLogsToKeep=10 numVersionBuckets=65536
2020-03-09 11:05:47.236 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.u.CommitTracker Hard AutoCommit: if uncommited for 15000ms; 
2020-03-09 11:05:47.236 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.u.CommitTracker Soft AutoCommit: disabled
2020-03-09 11:05:47.311 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.s.SolrIndexSearcher Opening [Searcher@10d5fb21[ckan] main]
2020-03-09 11:05:47.328 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.r.ManagedResourceStorage File-based storage initialized to use dir: /opt/solr/server/solr/ckan/conf
2020-03-09 11:05:47.351 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.h.c.SpellCheckComponent Initializing spell checkers
2020-03-09 11:05:47.361 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.s.DirectSolrSpellChecker init: {name=default,field=_text_,classname=solr.DirectSolrSpellChecker,distanceMeasure=internal,accuracy=0.5,maxEdits=2,minPrefix=1,maxInspections=5,minQueryLength=4,maxQueryFrequency=0.01}
2020-03-09 11:05:47.365 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.h.c.QueryElevationComponent Loading QueryElevation from: /opt/solr/server/solr/ckan/conf/elevate.xml
2020-03-09 11:05:47.381 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.h.ReplicationHandler Commits will be reserved for  10000
2020-03-09 11:05:47.430 INFO  (searcherExecutor-7-thread-1-processing-x:ckan) [   x:ckan] o.a.s.c.QuerySenderListener QuerySenderListener sending requests to Searcher@10d5fb21[ckan] main{ExitableDirectoryReader(UninvertingDirectoryReader())}
2020-03-09 11:05:47.430 INFO  (searcherExecutor-7-thread-1-processing-x:ckan) [   x:ckan] o.a.s.c.QuerySenderListener QuerySenderListener done.
2020-03-09 11:05:47.431 INFO  (coreLoadExecutor-6-thread-1) [   x:ckan] o.a.s.u.UpdateLog Could not find max version in index or recent updates, using new clock 1660684282029408256
2020-03-09 11:05:47.431 INFO  (searcherExecutor-7-thread-1-processing-x:ckan) [   x:ckan] o.a.s.h.c.SpellCheckComponent Loading spell index for spellchecker: default
2020-03-09 11:05:47.439 INFO  (searcherExecutor-7-thread-1-processing-x:ckan) [   x:ckan] o.a.s.c.SolrCore [ckan] Registered new searcher Searcher@10d5fb21[ckan] main{ExitableDirectoryReader(UninvertingDirectoryReader())}
```

### What steps can be taken to reproduce the issue? 
docker-compose up

**Comment by stirlingv** [comment]
I was able to resolve this issue by deleting all the ckan volumes `docker volume rm [volume name]`, deleting the docker images `docker-compose down` `docker rmi -f docker_ckan docker_db` and then rebuilding  from the contrib/docker folder running`docker-compose build` `docker-compose up`

**Comment by tugn0x** [comment]
Thank you @stirlingv 
I've done all steps you suggested without issue but now, 
I started ckan with `docker-compose up` and I see that ckan connect to solr but ckan container died at boot with `ckan exit with code 1` as reported below.

`ckan          | db:5432 - accepting connections
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 8, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 101, in run
ckan          |     command = commands[command_name].load()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2305, in load
ckan          |     return self.resolve()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
ckan          |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 32, in <module>
ckan          |     from ckan.cli import load_config as _get_config
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/__init__.py", line 8, in <module>
ckan          |     from configparser import ConfigParser
ckan          | ImportError: No module named configparser
`
So i still leave open this issue
thanks in advance
bye

**Comment by tugn0x** [comment]
I've succeeded by using tags/ckan-2.8.3 and destroying all images and volumes and rebuilding everything. I noticed that solr takes time to start so ckan can't always connect to solr at the first boot time, so after running all container you need to restart ckan again by `docker-compose restart ckan` and it connects to solr without problem.
I close this issue
Thanks

**Comment by stirlingv** [comment]
@tugn0x I should have updated my issue to let you know that I too used tags/ckan-2.8.3 and destroyed/rebuilt everything. Confirmed this works, and issue can be closed! Thanks!
