### ISSUE TITLE
Enabling debugging causes HTTP 500 ("ImportError: No module named flask_debugtoolbar")

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5326]
### Please describe the expected behaviour
When [the _debug_ configuration option](https://docs.ckan.org/en/latest/maintaining/configuration.html#debug) is enabled, some debugging features should be added, such as the "Debug x" footer.

### Please describe the actual behaviour
CKAN responses become HTTP 500 errors. Apache's log reveals that the flask_debugtoolbar development dependency is missing:
> [Fri Apr 03 10:17:18.803649 2020] [wsgi:error] [pid 17690:tid 140014413039360] 2020-04-03 10:17:18,803 INFO  [ckan.config.environment] Loading templates from /srv/www/acrigeo/apps/ckan/default/src/ckan/ckan/templates
> [Fri Apr 03 10:17:19.075678 2020] [wsgi:error] [pid 17690:tid 140014413039360] 2020-04-03 10:17:19,075 INFO  [ckan.config.environment] Loading templates from /srv/www/acrigeo/apps/ckan/default/src/ckan/ckan/templates
> [Fri Apr 03 10:17:19.239397 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496] mod_wsgi (pid=17690): Target WSGI script '/srv/www/acrigeo/apps/ckan/etc/ckan/apache.wsgi' cannot be loaded as Python module.
> [Fri Apr 03 10:17:19.239420 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496] mod_wsgi (pid=17690): Exception occurred processing WSGI script '/srv/www/acrigeo/apps/ckan/etc/ckan/apache.wsgi'.
> [Fri Apr 03 10:17:19.239437 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496] Traceback (most recent call last):
> [Fri Apr 03 10:17:19.239454 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]   File "/srv/www/acrigeo/apps/ckan/etc/ckan/apache.wsgi", line 10, in <module>
> [Fri Apr 03 10:17:19.239477 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]     application = loadapp('config:%s' % config_filepath)
> [Fri Apr 03 10:17:19.239486 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]   File "/srv/www/acrigeo/apps/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
> [Fri Apr 03 10:17:19.239500 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]     return loadobj(APP, uri, name=name, **kw)
> [Fri Apr 03 10:17:19.239507 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]   File "/srv/www/acrigeo/apps/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
> [Fri Apr 03 10:17:19.239517 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]     return context.create()
> [Fri Apr 03 10:17:19.239523 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]   File "/srv/www/acrigeo/apps/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
> [Fri Apr 03 10:17:19.239532 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]     return self.object_type.invoke(self)
> [Fri Apr 03 10:17:19.239538 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]   File "/srv/www/acrigeo/apps/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
> [Fri Apr 03 10:17:19.239548 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]     return fix_call(context.object, context.global_conf, **context.local_conf)
> [Fri Apr 03 10:17:19.239568 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]   File "/srv/www/acrigeo/apps/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
> [Fri Apr 03 10:17:19.239580 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]     val = callable(*args, **kw)
> [Fri Apr 03 10:17:19.239586 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]   File "/srv/www/acrigeo/apps/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 59, in make_app
> [Fri Apr 03 10:17:19.239597 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]     flask_app = make_flask_stack(conf, **app_conf)
> [Fri Apr 03 10:17:19.239603 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]   File "/srv/www/acrigeo/apps/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 104, in make_flask_stack
> [Fri Apr 03 10:17:19.239747 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496]     from flask_debugtoolbar import DebugToolbarExtension
> [Fri Apr 03 10:17:19.239765 2020] [wsgi:error] [pid 17690:tid 140014413039360] [client 10.102.27.189:64496] ImportError: No module named flask_debugtoolbar
> [Fri Apr 03 10:17:19.636140 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497] mod_wsgi (pid=17690): Target WSGI script '/srv/www/acrigeo/apps/ckan/etc/ckan/apache.wsgi' cannot be loaded as Python module.
> [Fri Apr 03 10:17:19.636184 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497] mod_wsgi (pid=17690): Exception occurred processing WSGI script '/srv/www/acrigeo/apps/ckan/etc/ckan/apache.wsgi'.
> [Fri Apr 03 10:17:19.636213 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497] Traceback (most recent call last):
> [Fri Apr 03 10:17:19.636241 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]   File "/srv/www/acrigeo/apps/ckan/etc/ckan/apache.wsgi", line 10, in <module>
> [Fri Apr 03 10:17:19.636277 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]     application = loadapp('config:%s' % config_filepath)
> [Fri Apr 03 10:17:19.636291 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]   File "/srv/www/acrigeo/apps/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
> [Fri Apr 03 10:17:19.636316 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]     return loadobj(APP, uri, name=name, **kw)
> [Fri Apr 03 10:17:19.636332 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]   File "/srv/www/acrigeo/apps/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
> [Fri Apr 03 10:17:19.636353 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]     return context.create()
> [Fri Apr 03 10:17:19.636363 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]   File "/srv/www/acrigeo/apps/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
> [Fri Apr 03 10:17:19.636378 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]     return self.object_type.invoke(self)
> [Fri Apr 03 10:17:19.636387 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]   File "/srv/www/acrigeo/apps/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
> [Fri Apr 03 10:17:19.636403 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]     return fix_call(context.object, context.global_conf, **context.local_conf)
> [Fri Apr 03 10:17:19.636413 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]   File "/srv/www/acrigeo/apps/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
> [Fri Apr 03 10:17:19.636429 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]     val = callable(*args, **kw)
> [Fri Apr 03 10:17:19.636465 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]   File "/srv/www/acrigeo/apps/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 59, in make_app
> [Fri Apr 03 10:17:19.636484 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]     flask_app = make_flask_stack(conf, **app_conf)
> [Fri Apr 03 10:17:19.636494 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]   File "/srv/www/acrigeo/apps/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 104, in make_flask_stack
> [Fri Apr 03 10:17:19.636509 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497]     from flask_debugtoolbar import DebugToolbarExtension
> [Fri Apr 03 10:17:19.636530 2020] [wsgi:error] [pid 17690:tid 140014345881344] [client 10.102.27.189:64497] ImportError: No module named flask_debugtoolbar

### What steps can be taken to reproduce the issue? 
1. Replace "False" with "True" at the _debug_ line in CKAN .ini file.
1. Restart Apache
1. Load any CKAN page

---

This used to affect all installations without flask_debugtoolbar, but following ticket #3520, only those in debugging mode are affected. This could be solved by moving flash_debugtoolbar from dev-requirements to requirements, but this would obviously increase CKAN's standard footprint.

---
### Wokaround
This can be worked around by installing flask-debugtoolbar. As of CKAN 2.8.3, the recommended version is 0.10.1, so the following commands should work:
$ . bin/activate
$ pip install flask_debugtoolbar==0.10.1

Note that you are likely to step on issue #5252 after working around this one.

**Comment by Chealer** [comment]
Thank you for fixing @davidread and @amercader 
I suggest also adding a note in the stock configuration file's comment about the debug option:

> \# WARNING: *THIS SETTING MUST BE SET TO FALSE ON A PUBLIC ENVIRONMENT*
> \# With debug mode enabled, a visitor to your site could execute malicious commands.
> debug = false
