### ISSUE TITLE
Problem in load ckan-admin

### ISSUE THREAD

**Issue by mohammad-chavoshipor** [ckan/ckan#5344]
### Please describe the expected behaviour
Hello
Difficulty loading the admin page
Error registered:
```
ckan          | 2020-04-15T10:03:04.741820713Z UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 0: ordinal not in range(128)
ckan          | 2020-04-15T10:03:07.407507411Z 2020-04-15 10:03:07,407 INFO  [ckan.lib.helpers] Route name "about" is deprecated and will be removed.                Please update calls to use "home.about" instead
ckan          | 2020-04-15T10:03:07.409421317Z 2020-04-15 10:03:07,409 INFO  [ckan.lib.helpers] Route name "about" is deprecated and will be removed.                Please update calls to use "home.about" instead
ckan          | 2020-04-15T10:03:07.411164660Z 2020-04-15 10:03:07,410 INFO  [ckan.lib.helpers] Route name "home" is deprecated and will be removed.                Please update calls to use "home.index" instead
ckan          | 2020-04-15T10:03:07.417899751Z Traceback (most recent call last):
ckan          | 2020-04-15T10:03:07.418302959Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
ckan          | 2020-04-15T10:03:07.418670921Z     self.finish_request(request, client_address)
ckan          | 2020-04-15T10:03:07.418957929Z   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
ckan          | 2020-04-15T10:03:07.419283414Z     self.RequestHandlerClass(request, client_address, self)
ckan          | 2020-04-15T10:03:07.419455154Z   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
ckan          | 2020-04-15T10:03:07.421463101Z     self.handle()
ckan          | 2020-04-15T10:03:07.421557908Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
ckan          | 2020-04-15T10:03:07.421568109Z     BaseHTTPRequestHandler.handle(self)
ckan          | 2020-04-15T10:03:07.421575424Z   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
ckan          | 2020-04-15T10:03:07.421655338Z     self.handle_one_request()
ckan          | 2020-04-15T10:03:07.421671884Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
ckan          | 2020-04-15T10:03:07.421723195Z     self.wsgi_execute()
ckan          | 2020-04-15T10:03:07.421744857Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
ckan          | 2020-04-15T10:03:07.421752472Z     self.wsgi_start_response)
ckan          | 2020-04-15T10:03:07.421759305Z   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
ckan          | 2020-04-15T10:03:07.421767250Z     return self.apps[app_name](environ, start_response)
ckan          | 2020-04-15T10:03:07.421774551Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
ckan          | 2020-04-15T10:03:07.421806358Z     app_iter = app(environ, wrapper.wrap_start_response)
ckan          | 2020-04-15T10:03:07.421813788Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
ckan          | 2020-04-15T10:03:07.421821317Z     resp = self.call_func(req, *args, **self.kwargs)
ckan          | 2020-04-15T10:03:07.421828581Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
ckan          | 2020-04-15T10:03:07.421835819Z     return self.func(req, *args, **kwargs)
ckan          | 2020-04-15T10:03:07.421842624Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
ckan          | 2020-04-15T10:03:07.421849830Z     return request.get_response(self.app)
ckan          | 2020-04-15T10:03:07.421856669Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
ckan          | 2020-04-15T10:03:07.421885938Z     application, catch_exc_info=False)
ckan          | 2020-04-15T10:03:07.421893176Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
ckan          | 2020-04-15T10:03:07.421912926Z     app_iter = application(self.environ, start_response)
ckan          | 2020-04-15T10:03:07.421920027Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
ckan          | 2020-04-15T10:03:07.421926809Z     resp = self.call_func(req, *args, **self.kwargs)
ckan          | 2020-04-15T10:03:07.421933231Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
ckan          | 2020-04-15T10:03:07.421939898Z     return self.func(req, *args, **kwargs)
ckan          | 2020-04-15T10:03:07.421946101Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
ckan          | 2020-04-15T10:03:07.422012426Z     response = request.get_response(self.app)
ckan          | 2020-04-15T10:03:07.422092965Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
ckan          | 2020-04-15T10:03:07.422102099Z     application, catch_exc_info=False)
ckan          | 2020-04-15T10:03:07.422108600Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
ckan          | 2020-04-15T10:03:07.422190671Z     app_iter = application(self.environ, start_response)
ckan          | 2020-04-15T10:03:07.422210102Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
ckan          | 2020-04-15T10:03:07.422224041Z     return self.wsgi_app(environ, start_response)
ckan          | 2020-04-15T10:03:07.422239439Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
ckan          | 2020-04-15T10:03:07.422296372Z     return self.wrap_app(environ, session_start_response)
ckan          | 2020-04-15T10:03:07.422323285Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
ckan          | 2020-04-15T10:03:07.422375066Z     response = self.handle_exception(e)
ckan          | 2020-04-15T10:03:07.422399683Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
ckan          | 2020-04-15T10:03:07.422407385Z     reraise(exc_type, exc_value, tb)
ckan          | 2020-04-15T10:03:07.422414329Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
ckan          | 2020-04-15T10:03:07.422421805Z     response = self.full_dispatch_request()
ckan          | 2020-04-15T10:03:07.422428795Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
ckan          | 2020-04-15T10:03:07.422436171Z     rv = self.handle_user_exception(e)
ckan          | 2020-04-15T10:03:07.422465328Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
ckan          | 2020-04-15T10:03:07.422485528Z     return self.handle_http_exception(e)
ckan          | 2020-04-15T10:03:07.422510508Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
ckan          | 2020-04-15T10:03:07.422524055Z     return handler(e)
ckan          | 2020-04-15T10:03:07.422570605Z   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 437, in error_handler
ckan          | 2020-04-15T10:03:07.422583059Z     u'error_document_template.html', extra_vars), e.code
ckan          | 2020-04-15T10:03:07.422589849Z   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/base.py", line 127, in render
ckan          | 2020-04-15T10:03:07.422596445Z     return flask_render_template(template_name, **extra_vars)
ckan          | 2020-04-15T10:03:07.422602869Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
ckan          | 2020-04-15T10:03:07.422609435Z     context, ctx.app)
ckan          | 2020-04-15T10:03:07.422615667Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
ckan          | 2020-04-15T10:03:07.422624237Z     rv = template.render(context)
ckan          | 2020-04-15T10:03:07.423004352Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
ckan          | 2020-04-15T10:03:07.424653034Z     return self.environment.handle_exception(exc_info, True)
ckan          | 2020-04-15T10:03:07.424674305Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
ckan          | 2020-04-15T10:03:07.424741388Z     reraise(exc_type, exc_value, tb)
ckan          | 2020-04-15T10:03:07.424758817Z   File "/usr/lib/ckan/venv/src/ckan/ckan/templates/error_document_template.html", line 1, in top-level template code
ckan          | 2020-04-15T10:03:07.424773961Z     {% extends "page.html" %}
ckan          | 2020-04-15T10:03:07.424828597Z   File "/usr/lib/ckan/venv/src/ckan/ckan/templates/page.html", line 1, in top-level template code
ckan          | 2020-04-15T10:03:07.424843827Z     {% extends "base.html" %}
ckan          | 2020-04-15T10:03:07.424856230Z   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/ckanext/iod_theme/templates/base.html", line 1, in top-level template code
ckan          | 2020-04-15T10:03:07.424890011Z     {% ckan_extends %}
ckan          | 2020-04-15T10:03:07.424899783Z   File "/usr/lib/ckan/venv/src/ckanext-googleanalytics/ckanext/googleanalytics/templates/base.html", line 1, in top-level template code
ckan          | 2020-04-15T10:03:07.424906899Z     {% ckan_extends %}
ckan          | 2020-04-15T10:03:07.424925316Z   File "/usr/lib/ckan/venv/src/ckan/ckan/templates/base.html", line 101, in top-level template code
ckan          | 2020-04-15T10:03:07.424933870Z     {%- block page %}{% endblock -%}
ckan          | 2020-04-15T10:03:07.424940696Z   File "/usr/lib/ckan/venv/src/ckan/ckan/templates/page.html", line 19, in block "page"
ckan          | 2020-04-15T10:03:07.424948098Z     {%- block content %}
ckan          | 2020-04-15T10:03:07.424954884Z   File "/usr/lib/ckan/venv/src/ckan/ckan/templates/page.html", line 22, in block "content"
ckan          | 2020-04-15T10:03:07.424980380Z     {% block main_content %}
ckan          | 2020-04-15T10:03:07.424999324Z   File "/usr/lib/ckan/venv/src/ckan/ckan/templates/page.html", line 74, in block "main_content"
ckan          | 2020-04-15T10:03:07.425028559Z     {% block primary %}
ckan          | 2020-04-15T10:03:07.425093169Z   File "/usr/lib/ckan/venv/src/ckan/ckan/templates/error_document_template.html", line 8, in block "primary"
ckan          | 2020-04-15T10:03:07.425112678Z     {{ content }}
ckan          | 2020-04-15T10:03:07.425127112Z UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 0: ordinal not in range(128)

```

**Comment by Zharktas** [comment]
This has already been fixed in master https://github.com/ckan/ckan/pull/4829, too bad it was missed from the new patch releases.
