### ISSUE TITLE
'Latest' Docs need updating to clarify which versions work with python 3

### ISSUE THREAD

**Issue by wood-chris** [ckan/ckan#5366]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.8.4

### Please describe the expected behaviour

It's not made clear on https://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html that 2.8.4 is not python 3 compatible. Section 1 installs python 3, and Section 2c advises 2.8.4 to be installed (unless for dev work).

### Please describe the actual behaviour

```
(default) chris@chris:~$ pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.8.4#egg=ckan'
Obtaining ckan from git+https://github.com/ckan/ckan.git@ckan-2.8.4#egg=ckan
  Cloning https://github.com/ckan/ckan.git (to revision ckan-2.8.4) to /usr/lib/ckan/default/src/ckan
  Running command git clone -q https://github.com/ckan/ckan.git /usr/lib/ckan/default/src/ckan
  Running command git checkout -q 7900935de6270ee80ec64a5378251dafedf3a0e4
    ERROR: Command errored out with exit status 1:
     command: /usr/lib/ckan/default/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/usr/lib/ckan/default/src/ckan/setup.py'"'"'; __file__='"'"'/usr/lib/ckan/default/src/ckan/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-phyybh7t
         cwd: /usr/lib/ckan/default/src/ckan/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/ckan/default/src/ckan/setup.py", line 34, in <module>
        if parse_version(setuptools_version) < min_setuptools_version:
    TypeError: '<' not supported between instances of 'map' and 'map'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

2.9 installs successfully

```
(default) chris@chris:~$ pip install -e 'git+https://github.com/ckan/ckan.git#egg=ckan'
Obtaining ckan from git+https://github.com/ckan/ckan.git#egg=ckan
  Updating /usr/lib/ckan/default/src/ckan clone
  Running command git fetch -q --tags
  Running command git reset --hard -q 6130cc17629dda73577efed36dae41ae6b447ac7
Could not build wheels for ckan, since package 'wheel' is not installed.
Installing collected packages: ckan
  Running setup.py develop for ckan
Successfully installed ckan
```

**Comment by kowh-ai** [comment]
Hey @wood-chris - I'll create a PR for this - thanks
