### ISSUE TITLE
No ability to modify dashboard_organizations.html

### ISSUE THREAD

**Issue by wood-chris** [ckan/ckan#5455]
### CKAN Version if known (or site URL)

2.8.3

### Please describe the expected behaviour

I have no other extensions installed.

Creating the file ckanext-myextension/ckanext/myextension/templates/user/dashboard_organizations.html with the only content being `{% ckan_extends %}` and going to http://myckan/dashboard/organizations should show the same information as core ckan

### Please describe the actual behaviour

http://myckan/dashboard/organizations shows

`Internal Server Error`

The stacktrace returned is:

```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
    self.wsgi_execute()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
    self.wsgi_start_response)
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
    return self.apps[app_name](environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
    return request.get_response(self.app)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
    response = request.get_response(self.app)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/views/dashboard.py", line 128, in organizations
    return base.render(u'user/dashboard_organizations.html', extra_vars)
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/lib/base.py", line 127, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 748, in handle_exception
    traceback = _make_traceback(exc_info, source_hint)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/debug.py", line 140, in make_traceback
    return translate_exception(exc_info, initial_skip)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/debug.py", line 182, in translate_exception
    lineno = template.get_corresponding_lineno(tb.tb_lineno)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 1056, in get_corresponding_lineno
    for template_line, code_line in reversed(self.debug_info):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 1072, in debug_info
    self._debug_info.split('&')]
ValueError: invalid literal for int() with base 10: ''
```

**Comment by wood-chris** [comment]
I've tracked this down to having items in the `group` table that are use a custom schema (hint from https://github.com/ckan/ckan/issues/4777#issuecomment-492219282). However, _even when_ the relevant extra plugins are included, the issue persists. Even with my minimal example, if I change everything in `group` to be a standard ckan type, then `dashboard_organizations.html` acts as expected. If I make 1 item a custom type (defined in a schema json file) then I get the error reported

**Comment by wood-chris** [comment]
I've played around with this today. There are other related(?) issues too (if they aren't related, I can make them into new issues)

Even with all types being CKAN ones, creating a new URL (e.g. /dashboard/my_publishers) is not straightforward. My first attempt used the same approach as IATI - but got the error `UndefinedError: 'user_dict' is undefined`. I finally found out that this was because support for Pylons has been seemingly dropped (I found this: https://stackoverflow.com/a/59990871/889604). 

When I changed to `Blueprint`, I first attempted a minimal example for /templates/user/dashboard_publishers.html:

```
{% extends "user/dashboard.html" %}

{% set user_dict = g.userobj %}

{% block dashboard_activity_stream_context %}{% endblock %}
```

This generates an error

```
UndefinedError: 'dashboard_activity_stream_context' is undefined
```

but, if I use the all of `dashboard_organizations.html` then the URL does work! 

This leads to a couple of (more) questions:

1. If I don't include the `{% set user_dict = g.userobj %}` then I get `UndefinedError: 'user_dict' is undefined` - even though this isn't in the file I'm extending. Why is this?

2. Maybe I missed it, but it might be helpful for there to a more prominent message in the docs that the Flask method should always be used now

3. Why does the `'dashboard_activity_stream_context' is undefined` error occur unless I include the whole code in my dashboard_publishers.html?!

**Comment by wood-chris** [comment]
Finally - just to clarify, even using the Flask method, I still need to use types that are in CKAN. I did track down the function that was raising the error. I don't really understand enough about flask to know why `FlaskRouteBuildError` (in `url_for`) gets thrown. 

However, the actual error occurs because the call to ` config.mapper._routenames.get(args[0])` returns `None` - it returns an object when CKAN types are used - printing the `args` and `kwargs` for a CKAN type and my custom type, and the return from that call:

```
(u'organization_read',)
{'action': 'read', 'id': u'nairobi'}
<routes.route.Route object at 0x7f53a39b74d0>
(u'publisher_read',)
{'action': 'read', 'id': u'pub_name_1'}
None
```

**Comment by wood-chris** [comment]
Slowly getting there:

I've realised that although _I'm_ using Blueprint, the fact that `FlaskRouteBuildError` is getting thrown means that `routes` needs the URL registering! Maybe this wasn't the easiest thing to delve into for my first serious CKAN experience, but the workaround is that I needed `get_blueprint` *and* `before_map` / `after_map`.

The next thing would be to understand why `FlaskRouteBuildError` gets thrown, so that I don't need `routes` at all

**Comment by wood-chris** [comment]
I think the fix needed is to change the `url_for` calls in `templates/organization/snippets/organization_list.html` to valid Flask ones.

I don't follow the guidance at https://github.com/ckan/ckan/blob/2.8/ckan/lib/helpers.py#L257 - why do the arguments end up in that order in the URL from the function args given?

**Comment by wood-chris** [comment]
So, finally, I created new custom routes in my `plugin.py` - I found I had to use _both_ flash and routes to get it all working:

```
    def get_blueprint(self):
        u'''Return a Flask Blueprint object to be registered by the app.'''

        group = GroupController()

        # Create Blueprint for plugin
        blueprint = Blueprint(self.name, self.__module__)
        blueprint.template_folder = u'templates'
        blueprint.add_url_rule(u'/dashboard/publishers', 'dashboard_publishers', view_func=self.dashboard_publishers)
        blueprint.add_url_rule(u'/dashboard/subjects', 'dashboard_subjects', view_func=self.dashboard_subjects)
        return blueprint

    def before_map(self, map):
    
        '''
           This is only needed because, at time of writing, CKAN only uses `routes` to check menu items. Once they update
            to use Flask, we can remove this function
        '''

        group = GroupController()

        map.connect('dashboard_publishers', '/dashboard/publishers', controller=self.name, action='dashboard_publishers') 
        map.connect('dashboard_subjects', '/dashboard/subjects', controller=self.name, action='dashboard_subjects') 
        return map
```

**Comment by wood-chris** [comment]
I _think_ this is also related: I want to change the "create organization" link on /dashboard/organizations from /organizations/new to /publishers/new. I thought that creating a new route and view would be enough, and changing the link from

    {% link_for _('Add Organization'), controller='organization', action='new', class_="btn btn-primary", icon="plus-square" %}

to

    {% link_for _('Add Publisher'), controller='ckanext.publishers.my_controllers:MyController', action='new_publisher', class_="btn btn-primary", icon="plus-square" %}

but this created an error:

    CkanUrlException: There is a broken url being created {'action': 'new_publisher', 'controller': 'ckanext.publishers.my_controllers:MyController'}

 but after lots of playing around I found the only solution that actually worked is

    {% link_for _('Add Publisher'), named_route='new_publisher', class_="btn btn-primary", icon="plus-square" %}

Just for my own sanity, can someone explain what's going on?!
