### ISSUE TITLE
Recurrent issue with Sqlalchemy migration

### ISSUE THREAD

**Issue by dmarteau** [ckan/ckan#5493]
**CKAN version**

ckan-2.8.4

**Describe the bug**

Database initialization failed when running  ckan-paster --plugin=ckan db init -c /etc/ckan/production.ini

Stacktrace:
```
...
 File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 366, in _migrate
schema.runchange(ver, change, changeset.step)
File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/schema.py", line 93, in runchange
change.run(self.engine, step)
File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/script/py.py", line 148, in run
script_func(engine)
 File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/ckan/migration/versions/016_uuids_everywhere.py", line 69, in upgrade
drop_sequencies(migrate_engine)
File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/ckan/migration/versions/016_uuids_everywhere.py", line 186, in drop_sequencies
migrate_engine.execute('drop sequence %s_id_seq;' % sequence)
File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2064, in execute
return connection.execute(statement, *multiparams, **params)
File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 939, in execute
return self._execute_text(object, multiparams, params)
statement, parameters
File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
context)
File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
exc_info
File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
context)
 File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) ERREUR:  la séquence « package_extra_revision_id_seq » n'existe pas
 [SQL: 'drop sequence package_extra_revision_id_seq;']
```

**Steps to reproduce**d
Execute: ```ckan-paster --plugin=ckan db init -c /etc/ckan/production.ini```

This error has been reported multiple time with no satisfactory answers:

- https://lists-archive.okfn.org/pipermail/ckan-dev/2018-November/022967.html
- https://stackoverflow.com/questions/53346147/how-can-i-initialize-db-ini-on-ckan
- https://discuss.okfn.org/t/installing-ckan-on-debian-9-5-stretch-from-source-some-issues-for-a-begginer/7093
- https://lists-archive.okfn.org/pipermail/ckan-dev/2019-April/023149.html

and so on...

It must be noted that the probleme may occurs also with a Docker image using  external database (i.e not in docker-compose stack).   The same image was running without problems in on one configuration and failed systematically with the error  above, on another host - same postgresql version,  starting from newly created database. 

That dismiss any relation to inadequate version of python package - same docker image in both cases - or ckan installation specific issue.  

The only difference in our test cases seems to be the databases, configuration are similar and we have no clue why it is failing in one situation and not in the other. It looks like that SqlAlchemy performe only partial migration processes when failing.

Since it seems to be a somewhat recurrent issue it would be nice to investigate the situation or at least to give some clues for identifying the problem.

Thanks.

**Comment by mdouchin** [comment]
Full PostgreSQL 11 log attached It seems the `public.package_extra_revision` is created without any sequence (no "serial" or "create sequence" found. 
[postgresql_11.log](https://github.com/ckan/ckan/files/4895827/postgresql_11.log)

**Comment by mdouchin** [comment]
I just tested with a fresh debian buster VM with vagrant, and could not reproduce the issue.

**Comment by mdouchin** [comment]
I tested on a fresh Debian buster 10, with a PostgreSQL 11
`PostgreSQL 11.8 (Debian 11.8-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit`

Databases have been created (or re-created after first failure, to start from scratch) with

```bash
sudo -iu postgres
dropdb -p 5432 -e ckan
dropdb -p 5432 -e datastore
psql -d template1 -p 5432 -c "DROP ROLE IF EXISTS datastore_ro; DROP ROLE IF EXISTS ckan;"
psql -d template1 -p 5432 -c "CREATE ROLE datastore_ro WITH LOGIN password '*****';CREATE ROLE ckan WITH LOGIN password '******';"
createdb -p 5432 -O ckan ckan
createdb -p 5432 -O ckan datastore
psql -d ckan -p 5432 -c "GRANT ALL PRIVILEGES ON DATABASE ckan TO ckan;create extension postgis;ALTER VIEW geometry_columns OWNER TO ckan;ALTER TABLE spatial_ref_sys OWNER TO ckan;"
psql -d datastore -p 5432 -c "GRANT ALL PRIVILEGES ON DATABASE datastore TO ckan;create extension postgis;ALTER VIEW geometry_columns OWNER TO ckan;ALTER TABLE spatial_ref_sys OWNER TO ckan;"
exit
```

We use docker to run ckan, solr, etc. We can give the full procedure if needed.

Note that I successfully ran the exact same stack on a Debian buster created from scratch **as a VM with vagrant** ! 
I looked at the logs, and the versions, both for PostgreSQL and Python packages are completely identical between the functionnal vagrant box and the "normal" Debian server with reported bug

I really does not understand what is going on.

Log

````
============================
====  Python packages  =====
============================
+ [[ DEBUG == \D\E\B\U\G ]]
+ echo ============================
+ echo '====  Python packages  ====='
+ echo ============================
+ ckan-pip list

Package                 Version
----------------------- -------
Babel                   2.3.4
Beaker                  1.9.0
bleach                  2.1.3
ckan                    2.8.4
ckanext-geoview         0.0.16
ckanext-spatial         0.2
ckantoolkit             0.0.4
click                   6.7
decorator               4.2.1
fanstatic               0.12
Flask                   0.12.4
Flask-Babel             0.11.2
FormEncode              1.3.1
funcsigs                1.0.2
GeoAlchemy              0.7.2
GeoAlchemy2             0.5.0
html5lib                1.0.1
itsdangerous            0.24
Jinja2                  2.8
lxml                    4.5.1
Mako                    1.0.7
Markdown                2.6.7
MarkupSafe              1.0
nose                    1.3.7
ofs                     0.4.2
OWSLib                  0.8.6
Pairtree                0.7.1-T
passlib                 1.6.5
Paste                   1.7.5.1
PasteDeploy             1.5.2
PasteScript             2.0.2
pbr                     1.10.0
pip                     20.1.1
pkg-resources           0.0.0
polib                   1.0.7
psycopg2                2.7.3.2
Pygments                2.2.0
Pylons                  0.9.7
pyparsing               2.4.7
pysolr                  3.6.0
python-dateutil         1.5
python-magic            0.4.15
pytz                    2016.7
pyutilib.component.core 4.6.4
redis                   2.10.6
repoze.lru              0.7
repoze.who              2.3
repoze.who-friendlyform 1.0.8
requests                2.11.1
Routes                  1.13
rq                      0.6.0
setuptools              36.1.0
Shapely                 1.7.0
simplejson              3.10.0
six                     1.11.0
SQLAlchemy              1.1.11
sqlalchemy-migrate      0.10.0
sqlparse                0.2.2
Tempita                 0.5.2
tzlocal                 1.3
unicodecsv              0.14.1
vdm                     0.14
webencodings            0.5.1
WebError                0.13.1
WebHelpers              1.3
WebOb                   1.0.8
WebTest                 1.4.3
Werkzeug                0.14.1
wheel                   0.34.2
zope.interface          4.3.2
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/lib/ckan/venv/bin/python2 -m pip install --upgrade pip' command.
+ ckan-paster make-config --no-interactive ckan /etc/ckan/production.ini
Distribution already installed:
  ckan 2.8.4 from /usr/lib/ckan/venv/lib/python2.7/site-packages
Creating /etc/ckan/production.ini
Now you should edit the config files
  /etc/ckan/production.ini
+ '[' '!' -z LOGGING_LEVEL ']'
+ ckan-configure -s logger_ckan -k level -c /etc/ckan/production.ini DEBUG
+ set_environment
+ export CKAN_SITE_ID=default
+ CKAN_SITE_ID=default
+ export CKAN_SITE_URL=http://srw-sigckan:80
+ CKAN_SITE_URL=http://srw-sigckan:80
+ export 'CKAN_SQLALCHEMY_URL=postgresql:///?service=ckan'
+ CKAN_SQLALCHEMY_URL='postgresql:///?service=ckan'
+ export CKAN_SOLR_URL=http://solr:8983/solr/ckan
+ CKAN_SOLR_URL=http://solr:8983/solr/ckan
+ export CKAN_REDIS_URL=http://redis:6379/1
+ CKAN_REDIS_URL=http://redis:6379/1
+ export CKAN_STORAGE_PATH=/var/lib/ckan
+ CKAN_STORAGE_PATH=/var/lib/ckan
+ export CKAN_DATAPUSHER_URL=http://datapusher:8800
+ CKAN_DATAPUSHER_URL=http://datapusher:8800
+ export 'CKAN_DATASTORE_WRITE_URL=postgresql:///?service=ckan_ds'
+ CKAN_DATASTORE_WRITE_URL='postgresql:///?service=ckan_ds'
+ export 'CKAN_DATASTORE_READ_URL=postgresql:///?service=ckan_ds_ro'
+ CKAN_DATASTORE_READ_URL='postgresql:///?service=ckan_ds_ro'
+ export CKAN_SMTP_SERVER=
+ CKAN_SMTP_SERVER=
+ export CKAN_SMTP_STARTTLS=
+ CKAN_SMTP_STARTTLS=
+ export CKAN_SMTP_USER=
+ CKAN_SMTP_USER=
+ export CKAN_SMTP_PASSWORD=
+ CKAN_SMTP_PASSWORD=
+ export CKAN_SMTP_MAIL_FROM=
+ CKAN_SMTP_MAIL_FROM=
+ export CKAN_MAX_UPLOAD_SIZE_MB=
+ CKAN_MAX_UPLOAD_SIZE_MB=
+ ckan-paster --plugin=ckan db init -c /etc/ckan/production.ini

Traceback (most recent call last):
  File "/usr/local/bin/ckan-paster", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/ckan/lib/cli.py", line 363, in command
    model.repo.init_db()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/ckan/model/__init__.py", line 188, in init_db
    self.upgrade_db()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/ckan/model/__init__.py", line 266, in upgrade_db
    mig.upgrade(self.metadata.bind, self.migrate_repository, version=version)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "<decorator-gen-16>", line 2, in _migrate
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 160, in with_engine
    return f(*a, **kw)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 366, in _migrate
    schema.runchange(ver, change, changeset.step)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/schema.py", line 93, in runchange
    change.run(self.engine, step)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/script/py.py", line 148, in run
    script_func(engine)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/ckan/migration/versions/016_uuids_everywhere.py", line 69, in upgrade
    drop_sequencies(migrate_engine)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/ckan/migration/versions/016_uuids_everywhere.py", line 186, in drop_sequencies
    migrate_engine.execute('drop sequence %s_id_seq;' % sequence)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2064, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) ERREUR:  la séquence « package_extra_revision_id_seq » n'existe pas
 [SQL: 'drop sequence package_extra_revision_id_seq;']

```

**Comment by mhartlauer** [comment]
We get the same error while installing ckan 2.8 (from source). However, it is not possible to execute the paster db init command successfully.


sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) FEHLER:  Sequenz »package_extra_revision_id_seq« existiert nicht
 [SQL: 'drop sequence package_extra_revision_id_seq;']


Does anyone have any idea how to solve this problem or is there any workaround for it to install ckan 2.8 from source successfully?

**Comment by guibos** [comment]
I installed a CKAN from .deb in a docker environment and I changed database cluster to test and executed ckan db init:

- [x] Postgis docker 11-3.0 (postgres 11.9) (https://registry.hub.docker.com/r/postgis/postgis/)
- [x] Aurora Postgres 11.9
- [ ] Redhat enviroment. 

Currently I am debugging what is happening.

**Comment by guibos** [comment]
In Postgis docker 11-3.0 I checked that CKAN no create this sequence but not raises any error. I don not understand why this happens.

**Comment by guibos** [comment]
Problem is here:
https://github.com/ckan/ckan/blob/eca78d5df65414249c5a76620c1acae1ddc76cc3/ckan/migration/versions/016_uuids_everywhere.py#L188
