### ISSUE TITLE
check_metadata_changes error when viewing changes

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5562]
**CKAN version**
2.9

**Describe the bug**
`check_metadata_changes` errors out when trying to compare old values that do not exist for the old package when trying to view changes.
It assumes that several keys always have old values (e.g. owner_org, maintainer, maintainer_email, author, author_email, etc).

https://github.com/ckan/ckan/blob/6d3453396359c9fc401e4f60383ee1b7f9e05885/ckan/lib/changes.py#L298

**Steps to reproduce**
1. Create a minimal package using `package_create`, specifying just the required fields.
2. Update the package using the CKAN UI.
3. Try to view changes in Activity stream

**Expected behavior**
`check_metadata_changes` should handle `KeyErrors` gracefully when old values do not exist.

**Additional details**

```
2020-08-27 06:00:08,776 DEBUG [ckan.logic] check access OK - user_show user=jqnatividad
2020-08-27 06:00:08,779 DEBUG [ckan.logic] check access OK - dashboard_new_activities_count user=jqnatividad
2020-08-27 06:00:08,779 DEBUG [ckan.logic] check access OK - dashboard_activity_list user=jqnatividad
2020-08-27 06:00:08,829 DEBUG [ckan.logic] check access OK - user_show user=jqnatividad
2020-08-27 06:00:08,832 ERROR [ckan.config.middleware.flask_app] 'maintainer'
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/views/dataset.py", line 1153, in changes
    u'dataset_type': current_pkg_dict[u'type'],
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/lib/base.py", line 151, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/templates/package/changes.html", line 1, in top-level template code
    {% extends "package/base.html" %}
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/templates/package/base.html", line 4, in top-level template code
    {% set dataset_type = dataset_type or pkg.type or 'dataset' %}
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/templates/base.html", line 106, in top-level template code
    {%- block page %}{% endblock -%}
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/templates/page.html", line 19, in block "page"
    {%- block content %}
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/templates/page.html", line 22, in block "content"
    {% block main_content %}
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/templates/page.html", line 74, in block "main_content"
    {% block primary %}
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/templates/package/changes.html", line 43, in block "primary"
    {% snippet "package/snippets/change_item.html", activity_diff=activity_diffs[i], pkg_dict=pkg_dict %}
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/lib/jinja_extensions.py", line 274, in _call
    return base.render_snippet(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/lib/base.py", line 95, in render_snippet
    output = render(template_name, extra_vars=kw)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/lib/base.py", line 151, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/templates/package/snippets/change_item.html", line 3, in top-level template code
    {% set changes = h.compare_pkg_dicts(activity_diff.activities[0].data.package, activity_diff.activities[1].data.package, activity_diff.activities[0].id) %}
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/lib/helpers.py", line 2849, in compare_pkg_dicts
    check_metadata_changes(change_list, old, new)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckan-2.9.0-py2.7.egg/ckan/lib/changes.py", line 312, in check_metadata_changes
    if old['maintainer'] != new['maintainer']:
KeyError: 'maintainer'
```

**Comment by jqnatividad** [comment]
**WORKAROUND:**
Was originally calling ``package_create`` using the ``ckanapi`` with the following parameters:

```
       package=catalogSite.action.package_create(
            name=tableName,
            maintainer='databot',
            maintainer_email='',
            owner_org='test-org',
            groups=[{'name': 'testgroup'}]
        )
```
Got around the problem by setting optional parameters to an empty string:
```
        package=catalogSite.action.package_create(
            name=tableName,
            maintainer='databot',
            maintainer_email='',
            groups=[{'name': 'testgroup'}],
            notes='',
            author='',
            author_email='',
            url=''
        )
```

**Comment by Zharktas** [comment]
Minimum fix for these would be to change all indexes to get call so it would not fail to KeyError. Proper fix should contain handling for all the custom schemas as the developer might have added or removed fields from the schema. There is handling for extra fields but I'm not completely sure if the parameters are in extra fields after validation in custom schema

**Comment by jqnatividad** [comment]
Hi @Zharktas,  Just wanted to confirm that I was using a custom schema using scheming.  For now, doing the minimum fix would be great!
