### ISSUE TITLE
Not session when replace a file

### ISSUE THREAD

**Issue by guibos** [ckan/ckan#5563]
**CKAN version: 2.9**

**Describe the bug**

When I try to replace a file in CKAN:

```
2020-08-27 14:05:06,602 DEBUG [ckanext.datapusher.plugin] Submitting resource a7ce5617-562a-4e04-b7e5-59289c26c1df to DataPusher
2020-08-27 14:05:06,634 DEBUG [ckanext.datapusher.plugin] Skipping DataPusher submission for resource a7ce5617-562a-4e04-b7e5-59289c26c1df
2020-08-27 14:05:06,748 ERROR [ckan.config.middleware.flask_app] 'NoneType' object has no attribute 'transaction'
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/resource.py", line 367, in post
    get_action(u'resource_update')(context, data)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/update.py", line 104, in resource_update
    updated_pkg_dict = _get_action('package_update')(context, pkg_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/update.py", line 344, in package_update
    model.repo.commit()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 464, in _prepare_impl
    stx = self.session.transaction
AttributeError: 'NoneType' object has no attribute 'transaction'
```

File and metadata is replaced.

**Steps to reproduce**
Replace a file. If metadata is replaced previous error is not raised.

**Expected behavior**
Not return "Internal server error"

**Additional details**
Datapusher is in a Docker Container. I have this plugins activated: datastore datapusher.

**Comment by jonathansberry** [comment]
I'm interested in this as well as I'm seeing a similar stack trace raised by ckanext-validation when patching the resource with the validation_status raised when calling the 'package_update' 

https://github.com/frictionlessdata/ckanext-validation/blob/23dd8a50edb974d1253361d89620aff06ba3906c/ckanext/validation/jobs.py#L111

The patch action ultimately ends up in the same place, calling the package_update action and throwing this same AttributeError:

```
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
ckan          |     response = self.handle_exception(e)
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
ckan          |     reraise(exc_type, exc_value, tb)
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
ckan          |     response = self.full_dispatch_request()
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
ckan          |     rv = self.handle_user_exception(e)
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
ckan          |     reraise(exc_type, exc_value, tb)
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
ckan          |     rv = self.dispatch_request()
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
ckan          |     return view_func(**req.view_args)
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
ckan          |     return self.dispatch_request(*args, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/views.py", line 163, in dispatch_request
ckan          |     return meth(*args, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/views/resource.py", line 248, in post
ckan          |     get_action(u'resource_create')(context, data)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
ckan          |     result = _action(context, data_dict, **kw)
ckan          |   File "/usr/lib/adx/ckanext-validation/ckanext/validation/logic.py", line 495, in resource_create
ckan          |     resource_id, local_upload=is_local_upload, new_resource=True)
ckan          |   File "/usr/lib/adx/ckanext-validation/ckanext/validation/logic.py", line 631, in _run_sync_validation
ckan          |     u'schema': schema})
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
ckan          |     result = _action(context, data_dict, **kw)
ckan          |   File "/usr/lib/adx/ckanext-validation/ckanext/validation/logic.py", line 137, in resource_validation_run
ckan          |     run_validation_job(resource)
ckan          |   File "/usr/lib/adx/ckanext-validation/ckanext/validation/jobs.py", line 187, in run_validation_job
ckan          |     'validation_timestamp': validation.finished.isoformat()})
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
ckan          |     result = _action(context, data_dict, **kw)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/logic/action/patch.py", line 80, in resource_patch
ckan          |     return _update.resource_update(context, patched)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/logic/action/update.py", line 104, in resource_update
ckan          |     updated_pkg_dict = _get_action('package_update')(context, pkg_dict)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
ckan          |     result = _action(context, data_dict, **kw)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/logic/action/update.py", line 345, in package_update
ckan          |     model.repo.commit()
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
ckan          |     return getattr(self.registry(), name)(*args, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
ckan          |     self.transaction.commit()
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
ckan          |     self._prepare_impl()
ckan          |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 464, in _prepare_impl
ckan          |     stx = self.session.transaction
ckan          | AttributeError: 'NoneType' object has no attribute 'transaction'
```
