### ISSUE TITLE
Cannot clean db with custom configuration options (http://sqlalche.me/e/f405)

### ISSUE THREAD

**Issue by paulmueller** [ckan/ckan#5580]
**CKAN version**
2.9

**Describe the bug**
When I have [custom configuration options](https://docs.ckan.org/en/2.9/extensions/remote-config-update.html?highlight=custom%20configuration) enabled, then the command ``ckan db clean`` fails:

**Steps to reproduce**
Here is the relevant code in [my plugin](https://github.com/DCOR-dev/ckanext-dcor_schemas/blob/master/ckanext/dcor_schemas/plugin.py#L57-L81):
```python
    # IConfigurer
    def update_config(self, config):
        # [...]
        # Set licenses path
        here = pathlib.Path(__file__).parent
        license_loc = "file://{}".format(here / "licenses.json")
        # When I uncomment the following, then `ckan db clean` works.
        toolkit.get_action('config_option_update')(
            context={'ignore_auth': True, 'user': None},
            data_dict={'licenses_group_url': license_loc}
            )

    def update_config_schema(self, schema):
        ignore_missing = toolkit.get_validator('ignore_missing')
        schema.update({
            # This is an existing CKAN core configuration option, we are just
            # making it available to be editable at runtime
            'licenses_group_url': [ignore_missing],
        })

        return schema
```

**Expected behavior**
Cleaning the db should work independently of custom configuration options.

**Additional details**
```
ckan db clean --yes
2020-09-04 09:06:47,681 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2020-09-04 09:06:47,681 INFO  [ckan.config.environment] Loading static files from public
2020-09-04 09:06:47,715 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "system_info" does not exist
LINE 2: FROM system_info 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 90, in _init_ckan_config
    ctx.obj = CkanCommand(value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 46, in __init__
    self.app = make_app(self.config)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 123, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 140, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 168, in load
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 122, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 177, in update_config
    plugin.update_config(config)
  File "/dcor-repos/ckanext-dcor_schemas/ckanext/dcor_schemas/plugin.py", line 70, in update_config
    toolkit.get_action('config_option_update')(
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/update.py", line 1380, in config_option_update
    model.set_system_info(key, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/model/system_info.py", line 67, in set_system_info
    obj = meta.Session.query(SystemInfo).filter_by(key=key).first()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3222, in first
    ret = list(self[0:1])
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3012, in __getitem__
    return list(res)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3324, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3349, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "system_info" does not exist
LINE 2: FROM system_info 
             ^

[SQL: SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
FROM system_info 
WHERE system_info.key = %(key_1)s 
 LIMIT %(param_1)s]
[parameters: {'key_1': 'licenses_group_url', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by pdelboca** [comment]
This is a problem of the database not being initialized correctly at the moment the command is executed since the error is `config_option_update` trying to update a table that doesn't exist in the database. Are you trying to execute the clean several times? Do you have a workflow that requires cleaning, initializing the database several times? If you make sure CKAN's database is correctly initialized before executing any cleaning will fix the issue. This is a buggy behaviour that I will try to explain.


### What's happening

Workflow to reproduce similar errors:
- Created a new extension, 
- Implement a custom configuration as described (or any)
- `ckan db clean --yes` execute correctly the first time
- It fails when trying to execute again with the error described in the ticket
- Trying to run `ckan db init` will fail with the same error. `# root cause of the error` 

The problem can be described as follows: `ckan db` commands depends on `ckan.config.middleware.make_app` to be executed correctly. Due `make_app` depends -in some cases- on the database being initialized we cannot **safely** run db commands without the database being initialized, even if the command is itself `ckan db init`. 

With a clean database (like the one after `ckan db clean --yes`) if I execute `ckan db init` **and there** are plugins loaded with IConfigurer implemented, they will try to [update the `system_info` table](https://github.com/ckan/ckan/blob/d2916b05f04784bac5ba3ba04a5255d3140fc647/ckan/logic/action/update.py#L1391) before `ckan db init` command can actually execute the [database initialization](https://github.com/ckan/ckan/blob/d2916b05f04784bac5ba3ba04a5255d3140fc647/ckan/cli/db.py#L34).

### Possible solution

I'm a little bit lost in the pipeline but there is a problem with `ckan db init` being a CKAN Command since CKAN Commands depends on the database being initialized to run properly. Probably we can make this database command to not depend on CKAN app but I'm not sure how that can impact on plugins accesing this command.

cc @amercader @smotornyuk

**Comment by amercader** [comment]
After discussion it was agreed that for some commands like `ckan db init` it doesn't make sense to load the whole application environment, specially loading all plugins, which might lead to issues like the one described here.

We could explore skipping the [initialization of the app](https://github.com/ckan/ckan/blob/d2916b05f04784bac5ba3ba04a5255d3140fc647/ckan/cli/cli.py#L52) with a `__init__()` param like `initialize_app=False` for specific commands like `ckan db init` (Although this is done at the class level, and I'm not sure if all `ckan db *` commands will be fine with this).

This would be related that what we discussed in https://github.com/ckan/ckan/pull/5629, about having a decorator to ensure that the database is initialized before running a command
