### ISSUE TITLE
Extension generator post_gen_project hook script error

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5610]
**CKAN version**
2.9

**Describe the bug**
Following the [Creating a new extension](https://docs.ckan.org/en/2.9/extensions/tutorial.html#creating-a-new-extension) procedure results in an error.

**Steps to reproduce**
Follow "Creating a new extension" after a source install.

**Expected behavior**
Extension generator works for both approaches - using either `cookiecutter` or `ckan generate extension`

**Additional details**
From `/usr/lib/ckan/default/src`, invoking either `cookiecutter` or `ckan generate extension` results in this error

```
Traceback (most recent call last):
  File "/tmp/tmpXZ_tLi.py", line 93, in <module>
    recut()
  File "/tmp/tmpXZ_tLi.py", line 76, in recut
    env=env)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 166, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: setup.py
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by fahazhussain** [comment]
were you able to solve it?

**Comment by Gauravp-NEC** [comment]
@jqnatividad @smotornyuk , I am working on this issue. I have tried to create new extension using both the approach i.e., "cookiecutter"  and "ckan generate extension".  The "ckan genarate extension" is working fine and no error have occurred while creating a new extension. The errors are occurring while using "cookiecutter" approach for creating a new extension. However in cookiecutter appraoch if we remove the "post_gen_project.py" in hooks (https://github.com/ckan/ckan/tree/master/contrib/cookiecutter/ckan_extension/hooks) the issue gets resolve and extensions are created. Please let me know your opinion.

**Comment by smotornyuk** [comment]
Post hook runs only when an extension created using the `cookiecutter` command directly. It checks/generates correct keywords, names, etc, and generally does the same things that `ckan generate extension` does. So we can't remove it.

Exception raised when cookiecutter tries to rewrite `setup.py`. It cannot find the source dir of the extension's template, because when the extension is created, the current working directory is changed temporarily to the extension's root. 
Thus we have to do two things:

1. Updapdate documentation and add explicit mention that `cookiecutter /path/to/template` form MUST use absolute path to the template folder
2. Update post_get_hook and put correct path to the template folder into the code. 

Roughly, it can be done in following way:

```diff
diff --git a/contrib/cookiecutter/ckan_extension/hooks/post_gen_project.py b/contrib/cookiecutter/ckan_extens
ion/hooks/post_gen_project.py
index 429450aa4..63b60654e 100644
--- a/contrib/cookiecutter/ckan_extension/hooks/post_gen_project.py
+++ b/contrib/cookiecutter/ckan_extension/hooks/post_gen_project.py
@@ -18,7 +18,7 @@ def recut():
     # template location
     try:
         # cutting cookie from directory with template
-        temp_dir = find.find_template('..')
+        temp_dir = find.find_template('{{cookiecutter._template}}')
     except NonTemplatedInputDirException as e:
         # template coming from Github
         # Hooks are passed through jinja2. raw will
diff --git a/doc/extensions/tutorial.rst b/doc/extensions/tutorial.rst
index 4a21703e4..40a56c6de 100644
--- a/doc/extensions/tutorial.rst
+++ b/doc/extensions/tutorial.rst
@@ -69,7 +69,7 @@ environment:
 
 Now run ``cookiecutter`` to create your extension::
 
-    cookiecutter ckan/contrib/cookiecutter/ckan_extension/
+    cookiecutter $PWD/ckan/contrib/cookiecutter/ckan_extension/
 
 .. topic:: CLI Command
 ```

**Comment by Gauravp-NEC** [comment]
@smotornyuk , I have keep the post_gen_hook script and use your patch, but the issue is not resolved and extensions are not created.

I have modified the patch and now ckan extension are created. But I am facing another issue of 'collections.OrderedDict object' has no attribute '_project'

![image](https://user-images.githubusercontent.com/66116382/100317318-26807800-2fe2-11eb-9e1e-c3d370200295.png)

**Comment by smotornyuk** [comment]
What exact error you've got with my initial patch? I've suggested using [variable set by cookiecutter itself](https://github.com/cookiecutter/cookiecutter/blob/591779157a62bafbb0655b32d8e86e6b3a32e869/cookiecutter/main.py#L99). This `_template` points to the original location of the template, that is used for the new extension. 
As for your `_project`, just as the error says, there is no such item inside the context. Where did you found it?

**Comment by Gauravp-NEC** [comment]
@smotornyuk , I have revert back the change "_project" to " _template" in your patch but I am getting the same error as mentioned in https://github.com/ckan/ckan/issues/5610#issuecomment-734113254. 

So I have applied your patch in a fresh setup of 2.9.1 in which extensions are created with the below error:

Traceback (most recent call last):
  File "/usr/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==1.3.0', 'console_scripts', 'cookiecutter')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/cli.py", line 100, in main
    config_file=user_config
  File "/usr/lib/python2.7/dist-packages/cookiecutter/main.py", line 140, in cookiecutter
    output_dir=output_dir
  File "/usr/lib/python2.7/dist-packages/cookiecutter/generate.py", line 329, in generate_files
    _run_hook_from_repo_dir(repo_dir, 'post_gen_project', project_dir, context)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/generate.py", line 232, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/hooks.py", line 114, in run_hook
    run_script_with_context(script, project_dir, context)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/hooks.py", line 96, in run_script_with_context
    output = Template(contents).render(**context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 926, in __new__
    return env.from_string(source, template_class=cls)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 38, in template
jinja2.exceptions.TemplateAssertionError: no filter named 'jsonify'

**Comment by smotornyuk** [comment]
First line of your traceback: 
```
File "/usr/bin/cookiecutter", line 9, in
```

You are using a global cookiecutter, not one from CKAN's virtual environment. So you probably messed with dependencies versions.

Activate venv, install dev-requirements ( `pip install -U -r dev-requirements.txt`) and verify that `cookiecutter` links to venv's executable ( `which cookiecutter`). And then it should work. I've just checked it on master branch

**Comment by gg2** [comment]
I found the fix by smotornyuk to work. Ran cookiecutter pip-installed beneath the CKAN virtualenv. Thank you!

**Comment by frafra** [comment]
Still not working for me. I have isntalled cookiecutter inside the venv, I used full paths, but I still get:

```
Traceback (most recent call last):
  File "/tmp/tmp_TCrZM.py", line 93, in <module>
    recut()
  File "/tmp/tmp_TCrZM.py", line 76, in recut
    env=env)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 169, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: setup.py
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```
