### ISSUE TITLE
docker compose ckan running error: KeyError: 'pylons.app_globals' 

### ISSUE THREAD

**Issue by hqman** [ckan/ckan#5724]
HI all:

I installed ckan followed by [doc](https://docs.ckan.org/en/latest/maintaining/installing/install-from-docker-compose.html)  more than 10 times ,all failed.

**CKAN version**
2.9.1 

**Describe the bug**
 Attaching to ckan
ckan          | db:5432 - accepting connections
ckan          | 2020-11-07 09:18:52,193 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
ckan          | 2020-11-07 09:18:52,194 INFO  [ckan.config.environment] Loading static files from public
ckan          | 2020-11-07 09:18:52,626 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan", line 11, in <module>
ckan          |     load_entry_point('ckan', 'console_scripts', 'ckan')()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
ckan          |     return self.main(*args, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 781, in main
ckan          |     with self.make_context(prog_name, args, **extra) as ctx:
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 700, in make_context
ckan          |     self.parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1212, in parse_args
ckan          |     rest = Command.parse_args(self, ctx, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1048, in parse_args
ckan          |     value, args = param.handle_parse_result(ctx, opts, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1630, in handle_parse_result
ckan          |     value = invoke_param_callback(self.callback, ctx, self, value)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 123, in invoke_param_callback
ckan          |     return callback(ctx, param, value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 102, in _init_ckan_config
ckan          |     ctx.obj = CkanCommand(value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 52, in __init__
ckan          |     self.app = make_app(self.config)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
ckan          |     load_environment(conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 122, in load_environment
ckan          |     p.load_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 130, in load_all
ckan          |     unload_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 183, in unload_all
ckan          |     unload(*reversed(_PLUGINS))
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 211, in unload
ckan          |     plugins_update()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 122, in plugins_update
ckan          |     environment.update_config()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 282, in update_config
ckan          |     config['pylons.app_globals'].jinja_env = env
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/common.py", line 98, in __getitem__
ckan          |     return self.store[key]
ckan          | KeyError: 'pylons.app_globals'
ckan exited with code 1

**Comment by kowh-ai** [comment]
@hqman - Can you stop all the containers and remove everything (containers, volumes, images, networks) before starting again. You may need to run prune commands too (https://docs.docker.com/config/pruning/)...good luck

**Comment by stiort91** [comment]
> @hqman - Can you stop all the containers and remove everything (containers, volumes, images, networks) before starting again. You may need to run prune commands too (https://docs.docker.com/config/pruning/)...good luck

It doesn't work. I try pruning but show the same error.

ckan | environment.update_config()
ckan | File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 282, in update_config
ckan | config['pylons.app_globals'].jinja_env = env
ckan | File "/usr/lib/ckan/venv/src/ckan/ckan/common.py", line 98, in getitem
ckan | return self.store[key]
ckan | KeyError: 'pylons.app_globals'
ckan exited with code 1

**Comment by leu2tm** [comment]
@stiort91 did you figure it out yet?

I currently also experience this error running on latest [master](https://github.com/ckan/ckan/commit/1d90c23ef5f72afb127dc94d390cc4014a5a11f2)

I also did a clean prune of docker environment.

System Software Overview:
      System Version: macOS 11.0.1 (20B29)
      Kernel Version: Darwin 20.1.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

      Docker version 19.03.13, build 4484c46d9d
      docker-compose version 1.27.4, build 40524192

```
ckan          | db:5432 - accepting connections
ckan          | 2020-12-07 16:21:35,446 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
ckan          | 2020-12-07 16:21:35,447 INFO  [ckan.config.environment] Loading static files from public
ckan          | 2020-12-07 16:21:35,537 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan", line 11, in <module>
ckan          |     load_entry_point('ckan', 'console_scripts', 'ckan')()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
ckan          |     return self.main(*args, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 781, in main
ckan          |     with self.make_context(prog_name, args, **extra) as ctx:
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 700, in make_context
ckan          |     self.parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1212, in parse_args
ckan          |     rest = Command.parse_args(self, ctx, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1048, in parse_args
ckan          |     value, args = param.handle_parse_result(ctx, opts, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1630, in handle_parse_result
ckan          |     value = invoke_param_callback(self.callback, ctx, self, value)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 123, in invoke_param_callback
ckan          |     return callback(ctx, param, value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 102, in _init_ckan_config
ckan          |     ctx.obj = CkanCommand(value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 52, in __init__
ckan          |     self.app = make_app(self.config)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
ckan          |     load_environment(conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 122, in load_environment
ckan          |     p.load_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 145, in load_all
ckan          |     unload_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 198, in unload_all
ckan          |     unload(*reversed(_PLUGINS))
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 226, in unload
ckan          |     plugins_update()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 137, in plugins_update
ckan          |     environment.update_config()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 282, in update_config
ckan          |     config['pylons.app_globals'].jinja_env = env
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/common.py", line 98, in __getitem__
ckan          |     return self.store[key]
ckan          | KeyError: 'pylons.app_globals'
```

**Comment by leu2tm** [comment]
@kowh-ai There was a commit where docker-compose worked [https://github.com/ckan/ckan/commit/9abeaa1b7d2f6539ade946cc3f407878f49950eb](https://github.com/ckan/ckan/commit/9abeaa1b7d2f6539ade946cc3f407878f49950eb)
But it's no longer working the latest master, nor ckan-2.9.1


Do you know when the fix will be working again in master?

**Comment by kowh-ai** [comment]
@leu2tm - Hey I brought this up at the Dev Core meeting this afternoon...This commit will be included in the **CKAN 2.9.2** patch release which will be released soon...It looks like it missed the **CKAN 2.9.0** and **2.9.1** tags....I checked master and it's definitely in there

**Comment by leu2tm** [comment]
@kowh-ai - Alright thanks! 👍

**Comment by amikrop** [comment]
Is the release date of 2.9.2 known? Are there any temporary fixes until that date? Thanks.

**Comment by kowh-ai** [comment]
@amikrop - Patch release can be tracked here: https://github.com/ckan/ckan/issues/5783

**Comment by amikrop** [comment]
> @amikrop - Patch release can be tracked here: #5783

Thank you.

**Comment by vicding-mi** [comment]
Hi all, I am having the same `KeyError: 'pylons.app_globals'` with `master` branch. I checked the files, all the aforementioned patches were included. It seems like this is introduced after version `2.9.1`. 

When working with branch 2.9.1 and patch [`9abeaa1`](https://github.com/ckan/ckan/commit/9abeaa1b7d2f6539ade946cc3f407878f49950eb), ckan will up and run.

**Comment by kowh-ai** [comment]
@amikrop - CKAN 2.9.2 should be out tomorrow (Wed 10th Feb)...

**Comment by YukunYangNPF** [comment]
Hi, I'm using the master branch and this problem still persists. Should I just use another version?

**Comment by vicding-mi** [comment]
> Hi, I'm using the master branch and this problem still persists. Should I just use another version?

both `master` and `2.9.1` have issues, especially when using docker, to be specific. 
The working combi I am using is `2.9.1` and patch [9abeaa1](https://github.com/ckan/ckan/commit/9abeaa1b7d2f6539ade946cc3f407878f49950eb)

**Comment by kowh-ai** [comment]
As @vicding-mi mentions, CKAN **2.9.1** with Mark Stuarts PR mentioned. I'll try to see what has happened to the master branch when I get some time

**Comment by YukunYangNPF** [comment]
I tried to checkout 2.9.1 and then merge with 9abeaa1

Still the same problem.

I've taken down the previous docker and prune the system before I did this. 

Is there something wrong I've done with it?

**Comment by kowh-ai** [comment]
yeah that _should_ work...it does for me every time....

**Comment by vicding-mi** [comment]
> I tried to checkout 2.9.1 and then merge with [9abeaa1](https://github.com/ckan/ckan/commit/9abeaa1b7d2f6539ade946cc3f407878f49950eb)
> 
> Still the same problem.
> 
> I've taken down the previous docker and prune the system before I did this.
> 
> Is there something wrong I've done with it?

Remove all the related docker images, all the volumes, networks and do a clean build.

**Comment by wilberth915** [comment]
Is now working? I tried in Centos7 and Ubuntu 16.04 and is not working, master and 2.9.1 9abeaa1

**Comment by YukunYangNPF** [comment]
I did a thorough prune of docker and checkout 9abeaa1 one, and it worked. However, I still face some difficulties installing other's extensions. Don't know it's more like the docker issue or the version issue.

**Comment by vicding-mi** [comment]
> Is now working? I tried in Centos7 and Ubuntu 16.04 and is not working, master and 2.9.1 [9abeaa1](https://github.com/ckan/ckan/commit/9abeaa1b7d2f6539ade946cc3f407878f49950eb)

We are talking about running in docker specifically. the docker environment is quite different than the stock centos or another other distribution. I've never installed CKAN directly on any OS, can you give docker/docker-compose a try?

**Comment by vicding-mi** [comment]
> I did a thorough prune of docker and checkout [9abeaa1](https://github.com/ckan/ckan/commit/9abeaa1b7d2f6539ade946cc3f407878f49950eb) one, and it worked. However, I still face some difficulties installing other's extensions. Don't know it's more like the docker issue or the version issue.

Yeah, this is quite troublesome. There are versions of Python, PIP, CKAN installed on the system, and they have different requirements and dependencies. Sometime, it can go circular.... Depending on the extension you are going to install, there will be specific requirements, specifically, on CKAN and Python/PIP. Which extension and version are you going to install? In some cases, the extension could be too old.

**Comment by YukunYangNPF** [comment]
> > I did a thorough prune of docker and checkout [9abeaa1](https://github.com/ckan/ckan/commit/9abeaa1b7d2f6539ade946cc3f407878f49950eb) one, and it worked. However, I still face some difficulties installing other's extensions. Don't know it's more like the docker issue or the version issue.
> 
> Yeah, this is quite troublesome. There are versions of Python, PIP, CKAN installed on the system, and they have different requirements and dependencies. Sometime, it can go circular.... Depending on the extension you are going to install, there will be specific requirements, specifically, on CKAN and Python/PIP. Which extension and version are you going to install? In some cases, the extension could be too old.

I'm installing ckan on the was server from package. Now a lot of the extensions are not working properly, e.g. pdf_view. Also, almost all the ckan themes extensions I can search on Github cannot work.

I'm also looking at this, and it did show me a lot of the extensions have not migrated to py3.
https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions
