### ISSUE TITLE
datapusher guesses wrong type for decimal number

### ISSUE THREAD

**Issue by wrinklenose** [ckan/ckan#5769]
**CKAN version**
2.8.4

**Describe the bug**
datapusher should guess decimals correctly respecting the locale configuration

**Steps to reproduce**
- make sure you're testing in a german locale environment
- upload a csv file with the following content to ckan
`id; timestamp; value
3; 4; 1,200`
- make sure the datapusher processed the file
- check the datapusher log or the resource details which types were guessed.

**Expected behavior**
the datapusher guesses the following types:
`[{'type': u'numeric', 'id': u'id'}, {'type': u'numeric', 'id': u'timestamp'}, {'type': u'numeric', 'id': u'value'}]`

**Additional details**
datapusher guesses:
`[{'type': u'numeric', 'id': u'id'}, {'type': u'numeric', 'id': u'timestamp'}, {'type': u'text', 'id': u'value'}]`

I've tried to track down this issue which leads me to messytables, which seems to be used for type guessing and parsing of csv data.
The type guessing seems to happen here: https://github.com/okfn/messytables/blob/51b736892a48e420ab313675f54901c77b446dec/messytables/types.py
and seems to happen locale specific. (I think the magic happens in line 100:
`value = locale.atof(value)`

Unfortunately python recognizes a dot as decimal point even if a german locale is set, which I could reproduce in my local environment:
`>>> locale.getlocale()
('de_DE', 'cp1252')
>>> locale.atof('1,200')

Traceback (most recent call last):
  File "<pyshell#35>", line 1, in <module>
    locale.atof('1,200')
  File "C:\Program Files\Python27\lib\locale.py", line 318, in atof
    return func(string)
ValueError: invalid literal for float(): 1,200
>>> locale.localeconv()
{'mon_decimal_point': '', 'int_frac_digits': 127, 'p_sep_by_space': 127, 'frac_digits': 127, 'thousands_sep': '', 'n_sign_posn': 127, 'decimal_point': '.', 'int_curr_symbol': '', 'n_cs_precedes': 127, 'p_sign_posn': 127, 'mon_thousands_sep': '', 'negative_sign': '', 'currency_symbol': '', 'n_sep_by_space': 127, 'mon_grouping': [], 'p_cs_precedes': 127, 'positive_sign': '', 'grouping': []}`

**Comment by wardi** [comment]
after uploading you should be able to set a type override in the data dictionary form, however you'll still run into the problem you mentioned with converting a number with a `,` instead of a `.`. Would it be better to fix this in messytables?

**Comment by wrinklenose** [comment]
ACK - if opened https://github.com/okfn/messytables/issues/190

**Comment by duttonw** [comment]
@wrinklenose  have you tried migrating to xloader and seeing how that handles it? 

It follows a different approach in that first upload sets the data dictionary to text and then once you change it it will stick to it.

The @qldgovau team have made improvements to it to allow migration of data dictionary conversion. see readme https://github.com/ckan/ckanext-xloader#upgrading-from-datapusher

**Comment by rhabbachi** [comment]
@wrinklenose Would be very interesting to know if you hear if you managed to workaround / solve this issue. I'm running into a similar situation and was not able to find a suitable solution yet.
