### ISSUE TITLE
Adding new user with existing email address causes 500 error

### ISSUE THREAD

**Issue by joelwigley** [ckan/ckan#5820]
**CKAN version**

2.9.1

**Describe the bug**

On the "Add Member" screen for an Organisation, entering an email address of an existing user into the "New User" field to invite a new user generates a 500 Internal Server Error.

**Steps to reproduce**
1. Go to an Organisation
2. Click Manage
3. Click the Members tab
4. Click Add Member
5. In the "New User" section, enter an email address already in use by an existing user
6. Click Add Member

**Expected behavior**

A user-friendly error should appear to say the email address is already in use. It could even link to the user with that address.

**Additional details**
```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/group.py", line 1091, in post
    user_dict = _action(u'user_invite')(context, user_data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 1152, in user_invite
    user_dict = _get_action('user_create')(context, data)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 1047, in user_create
    raise ValidationError(errors)
ckan.logic.ValidationError: None - {'email': ["The email address 'xxx@xxx.com' belongs to a registered user."]}
```

**Comment by dawnh223** [comment]
This error takes place even if you drop a user or change the email address so you can create a new user with it.  CKAN doesn't lose the association with the original  user.
