### ISSUE TITLE
Corrupted my 'ckan.ini' file, and ckan won't come up with Docker

### ISSUE THREAD

**Issue by infracritical** [ckan/ckan#5833]
I added some plugins manually within the '/etc/ckan/production.ini' file that was created by the 'docker-compose' utility.  As a result of my f'up, the ckan container won't come up.

I can't seem to get into the volume to fix the problem.

How do I fix the bad entry within the 'production.ini' file so I can bring up the ckan container?

TIA.  -rad

The error message is shown below:

root@srvr2028:/usr/local/ckan# docker logs -f ckan
db:5432 - accepting connections
2021-01-18 04:15:06,290 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
2021-01-18 04:15:06,290 INFO  [ckan.config.environment] Loading static files from public
2021-01-18 04:15:07,013 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/local/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1018, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 102, in _init_ckan_config
    ctx.obj = CkanCommand(value)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 52, in __init__
    self.app = make_app(self.config)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 123, in load_environment
    p.load_all()
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 140, in load_all
    load(*plugins)
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 154, in load
    service = _get_service(plugin)
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 257, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: ckan

**Comment by thehappycheese** [comment]
Annoyed to find this closed. A minor error in the production.ini has locked me out of the build. As a docker n00b this creates a seriously difficult situation to fix the ini.

**Comment by kowh-ai** [comment]
Other than deleting all containers, images, networks and volumes plus running docker-compose again to build everything, another option is to set up a bind mount for the `production.ini` file. You could make changes to the "local" file and back out anything that causes the CKAN container to not run

**Comment by crunchingnumbers** [comment]
Just use docker cp to copy the file out of the container, edit it and copy it back . 
docker cp 748ed0feebaaxxxxxxxxxxxxxxxxxxxxxxxxxxx:etc/ckan/production.ini production.ini . 
replace xxxxxxxx etc. with your container id by running docker ps -a
