### ISSUE TITLE
Ckan installation via using docker on ubuntu failed due to OS error (Python version confliction)

### ISSUE THREAD

**Issue by Ajaysamdyan** [ckan/ckan#5874]
**CKAN version**
Ckan 2.9.0 and 2.9.1
**Description of the bug**

An error has been faced via ckan-docker installation, it seen that docker build operation failed at the end.

It shows the below mentioned error code:
Cmd: docker-compose up -d --build

Error_code: “”TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2375, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 992, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 922, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 817, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /usr/lib/ckan/venv/bin/python2 - setuptools pkg_resources pip wheel failed with error code 2
Running virtualenv with interpreter /usr/bin/python2
ERROR: Service 'ckan' failed to build: The command '/bin/sh -c mkdir -p $CKAN_VENV $CKAN_CONFIG $CKAN_STORAGE_PATH &&     virtualenv $CKAN_VENV &&     ln -s $CKAN_VENV/bin/pip /usr/local/bin/ckan-pip &&    ln -s $CKAN_VENV/bin/paster /usr/local/bin/ckan-paster' returned a non-zero code: 1

It shows that venv creation failed setup.

We tried the below cmd to resolve this error:
1.	apt-get install python3-venv
2.	python3 -m venv venv
3.	pipenv shell

But still facing error like:

[pipenv.exceptions.VirtualenvCreationException]: Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.5/dist-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/usr/local/lib/python3.5/dist-packages/virtualenv/run/__init__.py", line 13, in <module>
    from .plugin.activators import ActivationSelector
  File "/usr/local/lib/python3.5/dist-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/usr/local/lib/python3.5/dist-packages/virtualenv/run/plugin/base.py", line 9, in <module>
    from importlib_metadata import entry_points
  File "/usr/local/lib/python3.5/dist-packages/importlib_metadata/__init__.py", line 88
    dist: Optional['Distribution'] = None
        ^
SyntaxError: invalid syntax

It seems that this is an issue with ckan setup via using docker.

Please help us to resolve this bug.

**Steps to reproduce**
link: https://docs.ckan.org/en/2.9/maintaining/installing/install-from-docker-compose.html

**Comment by kowh-ai** [comment]
I suggest you delete/clean up the docker environment (prune containers, images, volumes and network) and try again

`docker container prune`
`docker volume prune`
`docker network prune`
`docker system prune`

and then run `docker-compose up --build`

**Comment by kowh-ai** [comment]
...And after the cleanup you should install CKAN **2.9.1** and apply this PR https://github.com/ckan/ckan/pull/5381
