### ISSUE TITLE
Docker Install KeyError: 'pylons.app_globals'

### ISSUE THREAD

**Issue by YukunYangNPF** [ckan/ckan#5896]
**CKAN version**
2.9.2
**Describe the bug**
Docker build failed with logs showing KeyError: 'pylons.app_globals'

```
ckan          | 2021-02-11 22:13:09,574 ERROR [ckan.lib.search.common] Failed to connect to server at 'http://solr:8983/solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json', are you sure that URL is correct? Checking it in a browser might help: HTTPConnectionPool(host='solr', port=8983): Max retries exceeded with url: /solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f809dfc6fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/search/common.py", line 61, in is_available
ckan          |     conn.search(q="*:*", rows=1)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pysolr.py", line 720, in search
ckan          |     response = self._select(params, handler=search_handler)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pysolr.py", line 418, in _select
ckan          |     return self._send_request('get', path)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pysolr.py", line 375, in _send_request
ckan          |     raise SolrError(error_message % params)
ckan          | SolrError: Failed to connect to server at 'http://solr:8983/solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json', are you sure that URL is correct? Checking it in a browser might help: HTTPConnectionPool(host='solr', port=8983): Max retries exceeded with url: /solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f809dfc6fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ckan          | 2021-02-11 22:13:09,576 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
ckan          | 2021-02-11 22:13:09,576 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan", line 11, in <module>
ckan          |     load_entry_point('ckan', 'console_scripts', 'ckan')()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
ckan          |     return self.main(*args, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 781, in main
ckan          |     with self.make_context(prog_name, args, **extra) as ctx:
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 700, in make_context
ckan          |     self.parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1212, in parse_args
ckan          |     rest = Command.parse_args(self, ctx, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1048, in parse_args
ckan          |     value, args = param.handle_parse_result(ctx, opts, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1630, in handle_parse_result
ckan          |     value = invoke_param_callback(self.callback, ctx, self, value)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 123, in invoke_param_callback
ckan          |     return callback(ctx, param, value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 102, in _init_ckan_config
ckan          |     ctx.obj = CkanCommand(value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 52, in __init__
ckan          |     self.app = make_app(self.config)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
ckan          |     load_environment(conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 122, in load_environment
ckan          |     p.load_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 145, in load_all
ckan          |     unload_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 198, in unload_all
ckan          |     unload(*reversed(_PLUGINS))
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 226, in unload
ckan          |     plugins_update()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 137, in plugins_update
ckan          |     environment.update_config()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 282, in update_config
ckan          |     config['pylons.app_globals'].jinja_env = env
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/common.py", line 98, in __getitem__
ckan          |     return self.store[key]
ckan          | KeyError: 'pylons.app_globals'`
```

**Steps to reproduce**
Steps to reproduce the behavior: docker install procedures

**Expected behavior**

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by kowh-ai** [comment]
@amercader -  Seems to have occurred on master _after_ the **2.9.1** release - Would the best option be to update the Docker CKAN build to use Python3 rather than continue with Python2? _or_ best to move to finishing up the clan-docker repo? (https://github.com/ckan/ckan-docker)
