### ISSUE TITLE
Datasets not listed on the Dataset view

### ISSUE THREAD

**Issue by wood-chris** [ckan/ckan#5906]
**CKAN version**
2.9

**Describe the bug**
Datasets don't get listed in the dataset view

**Steps to reproduce**
With a vanilla 2.9 install:

 - create a new organization
 - create a new dataset associated with this organization

There are no extensions installed in this instance and the dataset is of type `dataset`. Solr has been reindexed using `search-index rebuild`

**Expected behavior**

The new dataset should be listed at both `http://localhost:5000/dataset` and `http://localhost:5000/organization/<my-org>`, but isn't. It *is* listed in the activity stream: `http://localhost:5000/organization/activity/<my-org>/0`

**Additional details: Screenshots**

Dataset exists!

![Screenshot 2021-02-19 at 17 47 45](https://user-images.githubusercontent.com/10977677/108542872-32778f80-72dc-11eb-84e8-a8d765adaa68.png)

Dataset listed in the activity stream

![Screenshot 2021-02-19 at 17 47 29](https://user-images.githubusercontent.com/10977677/108542910-3efbe800-72dc-11eb-9710-159cf9855bbb.png)

Dataset not listed in the Organization's Dataset list

![Screenshot 2021-02-19 at 17 48 09](https://user-images.githubusercontent.com/10977677/108542940-48855000-72dc-11eb-9f6c-168011e5ab1a.png)

Dataset not listed in the overall Dataset list

![Screenshot 2021-02-19 at 17 48 18](https://user-images.githubusercontent.com/10977677/108542956-4cb16d80-72dc-11eb-80a1-5894958cabdd.png)

**Comment by amercader** [comment]
@wood-chris I can't reproduce this on a standard 2.9 install so it's likely an environment issue.

Things to check (or double check)
* No plugins are loaded (see /api/action/status_show)
* Datasets are of type "dataset"
* Datasets have "state=active" (not draft, deleted, or anything else)
* No weird (non-default) [search settings](https://docs.ckan.org/en/latest/maintaining/configuration.html#search-settings) on the ini file
* Does the package_show action return something? can you paste the package_show JSON dict for the dataset you created
* What's the output of `ckan -c /etc/ckan/default/development.ini search-index rebuild`?
* What's the output of `ckan -c /etc/ckan/default/development.ini show <dataset-name>`?

**Comment by wood-chris** [comment]
Hi @amercader - thanks for the pointers!

1. http://localhost:5000/api/3/action/status_show returns:

```
{"help": "http://localhost:5000/api/3/action/help_show?name=status_show", "error": {"__type": "Internal Server Error", "message": "Internal Server Error"}, "success": false}
```

with the error being

```
Traceback (most recent call last):
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/config/middleware/../../views/api.py", line 291, in action
    result = function(context, request_data)
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/logic/action/get.py", line 2424, in status_show
    'extensions': config.get('ckan.plugins').split(),
AttributeError: 'NoneType' object has no attribute 'split'
```

[I think this is a bug - no extensions are returned, which returns None rather than an empty dictionary, so can't be `split`]

2. from the `ckan_default database`:

```
ckan_default=# select id, title, type, state from package where state = 'active';
                  id                  |        title        |  type   | state  
--------------------------------------+---------------------+---------+--------
 3abbfd25-570a-46f3-bd2e-f0433dfb4509 | test                | dataset | active
 f9815ae1-b985-4495-939b-6d2a7bf6dab3 | test 2              | dataset | active
 f858fe64-db82-45ec-8645-2e8df427a8e0 | my first test       | dataset | active
 5f1c5d36-f9f8-4db5-a1a5-9fe05de4641c | my new data         | dataset | active
(5 rows)
```
3. nothing strange in search settings:

```
(default) ckan@ckan:~$ grep ckan.search ckan/etc/default/development.ini 
#ckan.search.show_all_types = true
(default) ckan@ckan:~$ grep solr ckan/etc/default/development.ini
solr_url = http://127.0.0.1:8983/solr
```

4. package_list:

http://localhost:5000/api/3/action/package_list

```
{"help": "http://localhost:5000/api/3/action/help_show?name=package_list", "success": true, "result": ["my-first-test", "my-new-data", "test-2", "test2"]}
```

http://localhost:5000/api/3/action/package_show?id=5f1c5d36-f9f8-4db5-a1a5-9fe05de4641c

```
{"help": "http://localhost:5000/api/3/action/help_show?name=package_show", "success": true, "result": {"author": "chris", "author_email": "chris@localhost", "creator_user_id": "41d60cdd-1153-4bff-9a70-e2250e5f7baf", "id": "5f1c5d36-f9f8-4db5-a1a5-9fe05de4641c", "isopen": true, "license_id": "other-pd", "license_title": "Other (Public Domain)", "maintainer": "", "maintainer_email": "", "metadata_created": "2021-02-19T17:36:00.479237", "metadata_modified": "2021-02-19T17:39:17.860151", "name": "my-new-data", "notes": "", "num_resources": 1, "num_tags": 1, "organization": {"id": "6254df30-9d68-4334-bbe0-d20f847c2bef", "name": "my-new-org", "title": "My new org", "type": "organization", "description": "", "image_url": "", "created": "2021-02-19T17:35:41.804939", "is_organization": true, "approval_status": "approved", "state": "active"}, "owner_org": "6254df30-9d68-4334-bbe0-d20f847c2bef", "private": false, "state": "active", "title": "my new data", "type": "dataset", "url": "", "version": "", "groups": [{"description": "", "display_name": "my new group", "id": "8e4ae8e3-9e81-452a-a391-4f9b465b7912", "image_display_url": "", "name": "my-new-group", "title": "my new group"}], "resources": [{"cache_last_updated": null, "cache_url": null, "created": "2021-02-19T17:36:09.900006", "description": "", "format": "CSV", "hash": "", "id": "b4f83045-49b0-4542-92f7-f375d43bc050", "last_modified": "2021-02-19T17:36:09.882517", "metadata_modified": "2021-02-19T17:36:09.895146", "mimetype": "text/csv", "mimetype_inner": null, "name": "test_data.csv", "package_id": "5f1c5d36-f9f8-4db5-a1a5-9fe05de4641c", "position": 0, "resource_type": null, "size": 18, "state": "active", "url": "http://localhost:5000/dataset/5f1c5d36-f9f8-4db5-a1a5-9fe05de4641c/resource/b4f83045-49b0-4542-92f7-f375d43bc050/download/test_data.csv", "url_type": "upload"}], "tags": [{"display_name": "testing", "id": "c33ae35b-aaea-430b-b74a-95cba19302d8", "name": "testing", "state": "active", "vocabulary_id": null}], "extras": [], "relationships_as_subject": [], "relationships_as_object": []}}
```

5.

```
(default) ckan@ckan:~$ ckan -c /etc/ckan/default/development.ini search-index rebuild
2021-02-23 17:48:09,900 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-23 17:48:09,901 INFO  [ckan.config.environment] Loading static files from public
2021-02-23 17:48:09,939 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-23 17:48:10,108 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-23 17:48:10,390 INFO  [ckan.lib.search] Rebuilding search index...
2021-02-23 17:48:10,392 INFO  [ckan.lib.search] Rebuilding the whole index...
Indexing dataset 9/92021-02-23 17:48:10,810 INFO  [ckan.lib.search] Finished rebuilding search index.
2021-02-23 17:48:10,939 INFO  [ckan.lib.search] Commited pending changes on the search index
```

```
(default) ckan@ckan:~$ ckan -c /etc/ckan/default/development.ini dataset show 5f1c5d36-f9f8-4db5-a1a5-9fe05de4641c
2021-02-23 17:55:58,229 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-23 17:55:58,230 INFO  [ckan.config.environment] Loading static files from public
2021-02-23 17:55:58,264 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-23 17:55:58,410 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
OrderedDict([('id', '5f1c5d36-f9f8-4db5-a1a5-9fe05de4641c'),
             ('name', 'my-new-data'),
             ('title', 'my new data'),
             ('version', ''),
             ('url', ''),
             ('author', 'chris'),
             ('author_email', 'chris@localhost'),
             ('maintainer', ''),
             ('maintainer_email', ''),
             ('notes', ''),
             ('license_id', 'other-pd'),
             ('type', 'dataset'),
             ('owner_org', '6254df30-9d68-4334-bbe0-d20f847c2bef'),
             ('creator_user_id', '41d60cdd-1153-4bff-9a70-e2250e5f7baf'),
             ('metadata_created', '2021-02-19T17:36:00.479237'),
             ('metadata_modified', '2021-02-19T17:39:17.860151'),
             ('private', False),
             ('state', 'active'),
             ('license', 'Other (Public Domain)'),
             ('isopen', True),
             ('tags', ['testing']),
             ('groups', ['my-new-group', 'my-new-org']),
             ('extras', {}),
             ('ratings_average', None),
             ('ratings_count', 0),
             ('resources',
              [OrderedDict([('id', 'b4f83045-49b0-4542-92f7-f375d43bc050'),
                            ('url', 'test_data.csv'),
                            ('format', 'CSV'),
                            ('description', ''),
                            ('hash', ''),
                            ('name', 'test_data.csv'),
                            ('resource_type', None),
                            ('mimetype', 'text/csv'),
                            ('mimetype_inner', None),
                            ('size', 18),
                            ('created', '2021-02-19T17:36:09.900006'),
                            ('last_modified', '2021-02-19T17:36:09.882517'),
                            ('metadata_modified', '2021-02-19T17:36:09.895146'),
                            ('cache_url', None),
                            ('cache_last_updated', None),
                            ('url_type', 'upload'),
                            ('position', 0),
                            ('package_id',
                             '5f1c5d36-f9f8-4db5-a1a5-9fe05de4641c')])]),
             ('ckan_url', 'http://localhost:5000/dataset/my-new-data'),
             ('relationships', []),
             ('notes_rendered', '')])
 ```

**Comment by amercader** [comment]
Apologies @wood-chris , for point 5 I meant `ckan -c /etc/ckan/default/development.ini search-index show <dataset-name>`

**Comment by wood-chris** [comment]
@amercader that's ok:

```
(default) ckan@ckan:/usr/lib/ckan/default/src/ckan$ ckan -c /etc/ckan/default/development.ini search-index show my-new-data
2021-02-24 01:05:16,083 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-24 01:05:16,084 INFO  [ckan.config.environment] Loading static files from public
2021-02-24 01:05:16,203 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 01:05:16,430 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 33, in <module>
    sys.exit(load_entry_point('ckan', 'console_scripts', 'ckan')())
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/cli/search_index.py", line 62, in show
    index = show(dataset_name)
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/lib/search/__init__.py", line 239, in show
    return package_query.get_index(package_reference)
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/lib/search/query.py", line 288, in get_index
    raise SearchError('Dataset not found in the search index: %s' % reference)
ckan.lib.search.common.SearchError: Dataset not found in the search index: my-new-data
```

I had meant to add I did wonder if this is related to what I asked on gitter about none of my packages being shown as being indexed when I run `(default) ckan@ckan:/usr/lib/ckan/default/src/ckan$ ckan -c /etc/ckan/default/development.ini search-index check`

```
2021-02-24 01:06:47,857 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-24 01:06:47,858 INFO  [ckan.config.environment] Loading static files from public
2021-02-24 01:06:47,916 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 01:06:48,088 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
Packages not indexed = 4 out of 4
('2021-02-18', 'test-2')
('2021-02-18', 'my-first-test')
('2021-02-22', 'test2')
('2021-02-19', 'my-new-data')
```

What do you think?

**Comment by amercader** [comment]
Interesting. So `ckan search-index rebuild` is lying when it says "Indexing dataset 9/9"... Or something is clearing the index immediately afterwards.

That discrepancy in the number of datasets (9 != 4) could be a clue (or could be nothing, `check` queries for `active` datasets, so `rebuild` could be using an additional 5 drafts)

This is a bit puzzling. The only thing I can think of is around multiple sites using the same index (or database) and this somehow creating an issue. Can you check that the site you are testing has a unique database and a unique `ckan.site_id`?

**Comment by wood-chris** [comment]
Yes, there are non-active datasets:

```
ckan_default=# select id, state, type from package;
                  id                  | state  |  type   
--------------------------------------+--------+---------
 7a92a51a-1de6-4f69-b917-c3ac9bd97b5c | draft  | dataset
 3abbfd25-570a-46f3-bd2e-f0433dfb4509 | active | dataset
 f9815ae1-b985-4495-939b-6d2a7bf6dab3 | active | dataset
 f858fe64-db82-45ec-8645-2e8df427a8e0 | active | dataset
 e33aec81-bded-46d3-a684-70eb4b457a32 | active | dataset
 5f1c5d36-f9f8-4db5-a1a5-9fe05de4641c | active | dataset
 dce1447a-53de-426d-bc82-08f60e21288b | draft  | dataset
 8d0ef4e0-2560-477a-8d5c-c22d9d5da1ee | draft  | dataset
 60d0d0bd-c9be-4e5b-bdbc-9d4344b9adf5 | draft  | dataset
(9 rows)
```

this is on a VM with a single CKAN instance (a VM spun up _just for_ CKAN dev / testing)

```
(default) ckan@ckan:/etc/ckan/default$ sudo -u postgres psql
psql (10.15 (Ubuntu 10.15-0ubuntu0.18.04.1))
Type "help" for help.

postgres=# \l
                                         List of databases
       Name        |    Owner     | Encoding | Collate |  Ctype  |        Access privileges         
-------------------+--------------+----------+---------+---------+----------------------------------
 ckan_default      | ckan_default | UTF8     | C.UTF-8 | C.UTF-8 | =Tc/ckan_default                +
                   |              |          |         |         | ckan_default=CTc/ckan_default
 datastore_default | ckan_default | UTF8     | C.UTF-8 | C.UTF-8 | =Tc/ckan_default                +
                   |              |          |         |         | ckan_default=CTc/ckan_default   +
                   |              |          |         |         | datastore_default=c/ckan_default
 postgres          | postgres     | UTF8     | C.UTF-8 | C.UTF-8 | 
 template0         | postgres     | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres                     +
                   |              |          |         |         | postgres=CTc/postgres
 template1         | postgres     | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres                     +
                   |              |          |         |         | postgres=CTc/postgres
(5 rows)

postgres=# 
```

Totally changing `ckan.site_id` makes no difference, nor does removing `/tmp/%(ckan.site_id)s/`

**Comment by wood-chris** [comment]
Ahhh! I've tracked it down 🎉 

It happens if the value of `ckan.site_id` is surrounded by quotes.

```
(default) ckan@ckan:/etc/ckan/default$ grep ^ckan.site_id development.ini 
ckan.site_id = "My Site"
(default) ckan@ckan:/etc/ckan/default$ ckan -c /etc/ckan/default/development.ini search-index clear
2021-02-24 14:36:35,681 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-24 14:36:35,682 INFO  [ckan.config.environment] Loading static files from public
2021-02-24 14:36:35,713 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 14:36:35,931 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
(default) ckan@ckan:/etc/ckan/default$ ckan -c /etc/ckan/default/development.ini search-index check
2021-02-24 14:36:44,273 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-24 14:36:44,274 INFO  [ckan.config.environment] Loading static files from public
2021-02-24 14:36:44,304 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 14:36:44,422 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
Packages not indexed = 4 out of 4
('2021-02-18', 'my-first-test')
('2021-02-18', 'test-2')
('2021-02-22', 'test2')
('2021-02-19', 'my-new-data')
(default) ckan@ckan:/etc/ckan/default$ ckan -c /etc/ckan/default/development.ini search-index rebuild
2021-02-24 14:36:49,987 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-24 14:36:49,988 INFO  [ckan.config.environment] Loading static files from public
2021-02-24 14:36:50,024 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 14:36:50,169 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 14:36:50,440 INFO  [ckan.lib.search] Rebuilding search index...
2021-02-24 14:36:50,443 INFO  [ckan.lib.search] Rebuilding the whole index...
Indexing dataset 9/92021-02-24 14:36:50,725 INFO  [ckan.lib.search] Finished rebuilding search index.
2021-02-24 14:36:50,806 INFO  [ckan.lib.search] Commited pending changes on the search index
(default) ckan@ckan:/etc/ckan/default$ ckan -c /etc/ckan/default/development.ini search-index check
2021-02-24 14:36:57,975 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-24 14:36:57,975 INFO  [ckan.config.environment] Loading static files from public
2021-02-24 14:36:58,010 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 14:36:58,170 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
Packages not indexed = 4 out of 4
('2021-02-18', 'test-2')
('2021-02-19', 'my-new-data')
('2021-02-18', 'my-first-test')
('2021-02-22', 'test2')
```

if we remove the quotes, even if the site id has spaces in, then the packages **are** indexed:

```
(default) ckan@ckan:/etc/ckan/default$ grep ^ckan.site_id development.ini 
ckan.site_id = My Site
(default) ckan@ckan:/etc/ckan/default$ ckan -c /etc/ckan/default/development.ini search-index clear
2021-02-24 15:05:18,180 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-24 15:05:18,181 INFO  [ckan.config.environment] Loading static files from public
2021-02-24 15:05:18,211 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 15:05:18,341 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
(default) ckan@ckan:/etc/ckan/default$ ckan -c /etc/ckan/default/development.ini search-index check
2021-02-24 15:05:27,629 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-24 15:05:27,630 INFO  [ckan.config.environment] Loading static files from public
2021-02-24 15:05:27,661 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 15:05:27,781 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
Packages not indexed = 4 out of 4
('2021-02-19', 'my-new-data')
('2021-02-18', 'my-first-test')
('2021-02-22', 'test2')
('2021-02-18', 'test-2')
(default) ckan@ckan:/etc/ckan/default$ ckan -c /etc/ckan/default/development.ini search-index rebuild
2021-02-24 15:06:43,689 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-24 15:06:43,689 INFO  [ckan.config.environment] Loading static files from public
2021-02-24 15:06:43,721 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 15:06:43,865 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 15:06:44,134 INFO  [ckan.lib.search] Rebuilding search index...
2021-02-24 15:06:44,137 INFO  [ckan.lib.search] Rebuilding the whole index...
Indexing dataset 9/92021-02-24 15:06:44,413 INFO  [ckan.lib.search] Finished rebuilding search index.
2021-02-24 15:06:44,482 INFO  [ckan.lib.search] Commited pending changes on the search index
(default) ckan@ckan:/etc/ckan/default$ ckan -c /etc/ckan/default/development.ini search-index check
2021-02-24 15:06:49,513 INFO  [ckan.cli] Using configuration file /etc/ckan/default/development.ini
2021-02-24 15:06:49,514 INFO  [ckan.config.environment] Loading static files from public
2021-02-24 15:06:49,548 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
2021-02-24 15:06:49,688 INFO  [ckan.config.environment] Loading templates from /home/ckan/ckan/lib/default/src/ckan/ckan/templates
Packages not indexed = 0 out of 5
```

I'll leave it up to you to decide if this is an actual bug, or something that is by design but should be documented :)

**Comment by amercader** [comment]
Success! :tada: 

This makes sense, I was suspecting it was something related to `ckan.site_id` but couldn't figure what.

The reason this is happening is that when *querying* we are removing the double quotes from the string [here](https://github.com/ckan/ckan/blob/6a77d2895e219e13fb38dd7f3ff33687f4609505/ckan/lib/search/query.py#L336) using `solr_literal()`:

https://github.com/ckan/ckan/blob/6a77d2895e219e13fb38dd7f3ff33687f4609505/ckan/lib/search/query.py#L420-L427

So if you have your `ckan.site_id` quoted, your datasets are indexed with:

```
{ "site_id": "\"default\""}
```

But when we are querying datasets , we are filtering with `fq:+site_id:"default"` which is the same as `site_id=default`, ie a different site_id so no datasets are found.

@wardi IIUC we introduced the `solr_literal` filter to avoid problems with potentially dangerous characters so should we just not allow quotes on `site_id` and document it? Maybe with a startup check [here](https://github.com/ckan/ckan/blob/6a77d2895e219e13fb38dd7f3ff33687f4609505/ckan/config/environment.py#L217)
