### ISSUE TITLE
Docker CKAN version 2.8.7 - build failure

### ISSUE THREAD

**Issue by gamesbook** [ckan/ckan#5925]
**CKAN version 2.8.7**

**Describe the bug**

The Docker fails to build:
```
Traceback (most recent call last):
  File "/usr/local/bin/ckan-pip", line 9, in <module>
    load_entry_point('pip==21.0.1', 'console_scripts', 'pip')()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
ERROR: Service 'ckan' failed to build: The command '/bin/sh -c ckan-pip install -U pip &&     ckan-pip install --upgrade --no-cache-dir -r $CKAN_VENV/src/ckan/requirement-setuptools.txt &&     ckan-pip install --upgrade --no-cache-dir -r $CKAN_VENV/src/ckan/requirements.txt &&     ckan-pip install -e $CKAN_VENV/src/ckan/ &&     ln -s $CKAN_VENV/src/ckan/ckan/config/who.ini $CKAN_CONFIG/who.ini &&     cp -v $CKAN_VENV/src/ckan/contrib/docker/ckan-entrypoint.sh /ckan-entrypoint.sh &&     chmod +x /ckan-entrypoint.sh &&     chown -R ckan:ckan $CKAN_HOME $CKAN_VENV $CKAN_CONFIG $CKAN_STORAGE_PATH' returned a non-zero code: 1
```

**Steps to reproduce**

Checkout the 2.8.7 version and run the Docker build process.

**Expected behavior**

Container should build with no errors.

**Additional details**

None.

**Comment by Zharktas** [comment]
Pip 21 dropped support for python2 and will cause errors. As CKAN 2.8.x is only supporting python2, pip should be pinned to max 20.x versions.

**Comment by gamesbook** [comment]
I assume that means a patch is required for the 2.8 Docker script(s)?
