### ISSUE TITLE
Cannot upload several files through uWSGI + nginx and multiple uWSGI workers

### ISSUE THREAD

**Issue by markpilkku** [ckan/ckan#5959]
**CKAN version**
CKAN: v.2.9.2
PostgreSQL: 12.6 (Ubuntu 12.6-0ubuntu0.20.10.1)
psycopg2: 2.8.2 (dt dec pq3 ext lo64)
uWSGI: 2.0.19.1
nginx: 1.18.0 (Ubuntu)

Other modules used but imo irrelevant regarding the bug: datapusher, datastore, ckanext-blob-storage, giftless

**Describe the bug**
When CKAN is used with uWSGI+Nginx and uWSGI is configured to use several [workers](https://uwsgi-docs.readthedocs.io/en/latest/Options.html#workers), uploading multiple files is not working. Say, when uploading for instance three files, only one of them will be uploaded, the rest will be lost.

In the console CKAN outputs an error:

2021-03-12 11:38:11,148 ERROR [ckan.views.api] (psycopg2.OperationalError) SSL error: decryption failed or bad record mac

[SQL: SELECT alias_of FROM "_table_metadata" WHERE name = %(id)s]
[parameters: {'id': 'b92bdbfa-7e07-4f21-ac45-7a33be8b6f55'}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL error: decryption failed or bad record mac

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mark/ckan/lib/default/src/ckan/ckan/config/middleware/../../views/api.py", line 291, in action
    result = function(context, request_data)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/mark/ckan/lib/default/src/ckan/ckanext/datastore/logic/action.py", line 503, in datastore_search
    res_exists, real_id = backend.resource_id_from_alias(res_id)
  File "/home/mark/ckan/lib/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1966, in resource_id_from_alias
    results = self._get_read_engine().execute(resources_sql, id=alias)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL error: decryption failed or bad record mac

[SQL: SELECT alias_of FROM "_table_metadata" WHERE name = %(id)s]
[parameters: {'id': 'b92bdbfa-7e07-4f21-ac45-7a33be8b6f55'}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

I think this also somehow related to [#4576](https://github.com/ckan/ckan/issues/4576), because after starting CKAN I get the same error, but it goes away after refreshing the page:

2021-03-12 12:01:09,793 ERROR [ckan.config.middleware.flask_app] Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 2267, in process_response
    response = handler(response)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/config/middleware/flask_app.py", line 400, in ckan_after_request
    r_time = time.time() - g.__timer
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/config/middleware/flask_app.py", line 444, in __getattr__
    return getattr(app_globals.app_globals, name)
AttributeError: '_Globals' object has no attribute '__timer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 2267, in process_response
    response = handler(response)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/config/middleware/flask_app.py", line 400, in ckan_after_request
    r_time = time.time() - g.__timer
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/config/middleware/flask_app.py", line 444, in __getattr__
    return getattr(app_globals.app_globals, name)
AttributeError: '_Globals' object has no attribute '__timer'

**Steps to reproduce**
Follow the [instructions](https://docs.ckan.org/en/2.9/maintaining/installing/deployment.html) without a Supervisor) for a production deployment. Insert `workers  =  10` inside ckan-uwsgi.ini. Try to upload several files.

**Expected behavior**
CKAN should be able to upload several files at once when configured with uWSGI and several workers in it.

**Comment by Zharktas** [comment]
_table_metadata is used in datastore, so datapusher and datastore are probably related to this. Could you disable datapusher and see if the error still pops up ?

Are you uploading the files to different datasets or the same one ? Uploading multiple files to single dataset is not supported in the UI.

**Comment by markpilkku** [comment]
> Are you uploading the files to different datasets or the same one ? Uploading multiple files to single dataset is not supported in the UI.

True! A very important detail I forgot to mention. There is custom plugin written in React which enables multi-file upload. In the screenshot below I attached two files for the same dataset and then pressed upload. For the second file uploading failed:

![network](https://user-images.githubusercontent.com/79199982/110936280-522d3100-8339-11eb-8f95-c17747e0b4b0.png)

> _table_metadata is used in datastore, so datapusher and datastore are probably related to this. Could you disable datapusher and see if the error still pops up ?

If disable I am not able to upload files at all. CKAN prints an error:

2021-03-12 13:36:28,442 ERROR [ckan.views.api] Object of type FileStorage is not JSON serializable
Traceback (most recent call last):
  File "/home/mark/ckan/lib/default/src/ckan/ckan/config/middleware/../../views/api.py", line 291, in action
    result = function(context, request_data)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/logic/action/create.py", line 319, in resource_create
    _get_action('package_update')(context, pkg_dict)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/logic/action/update.py", line 294, in package_update
    data, errors = lib_plugins.plugin_validate(
  File "/home/mark/ckan/lib/default/src/ckan/ckan/lib/plugins.py", line 306, in plugin_validate
    return toolkit.navl_validate(data_dict, schema, context)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 273, in validate
    converted_data, errors = _validate(flattened, schema, validators_context)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 323, in _validate
    convert(converter, key, converted_data, errors, context)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 249, in convert
    value = converter(converted_data.get(key), context)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/logic/validators.py", line 973, in extras_valid_json
    json.dumps(value)
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type FileStorage is not JSON serializable

**Comment by Zharktas** [comment]
Due to technical reasons if you call multiple `resource_create` functions in parallel, only one of the resources will remain in dataset. You should use the new  `package_revise` api instead, see https://github.com/ckan/ckan/pull/4618 for more details.

The error you are getting, is not probably related to that though.

**Comment by markpilkku** [comment]
@Zharktas, thanks! I will give a try to `package_revise` with multiple files. However, if I use a single worker in uWSGI and send several `resource_create` I get these files uploaded successfully to the same dataset:

![network2](https://user-images.githubusercontent.com/79199982/110940053-fb2a5a80-833e-11eb-8da8-0fd258a3d1bb.png)

**Comment by Zharktas** [comment]
If the `resource_create` calls start and finish in the same order, it probably won't create a problem. Technically every time `resource_create` finishes it calls `package_update` to add newly created resource to the dataset. If multiple `resource_create` calls finish about the same time, the `package_update` might be called in a state where one or multiple of the new resources do not exist and they are therefore deleted.

**Comment by markpilkku** [comment]
@Zharktas I think we have here two separate problems:

1) `resource_create` is not concurrency safe as stated in #4618 and you should either use it once (not multi-file upload as I did) or use alternative concurrency safe methods (such as you mentioned `package_revise`).

2) There is still a deeper concurrency issue even if you call `resource_create` once i.e. upload only a single file. As long as `workers` are set to 1 in uWSGI configuration file, everything works fine. When I increase it say to 10, I start to get four different exceptions when trying to upload a single file. The bad thing that they are not deterministic, sometimes they come sometimes don't. Here they are:

**First:**
`2021-03-17 14:04:28,512 ERROR [ckan.views.api] (psycopg2.OperationalError) SSL SYSCALL error: EOF detected
[SQL: SELECT alias_of FROM "_table_metadata" WHERE name = %(id)s]
[parameters: {'id': '9a56ef8e-13a7-4eae-98bc-081313d09f13'}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/mark/ckan/lib/default/src/ckan/ckan/config/middleware/../../views/api.py", line 291, in action
    result = function(context, request_data)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/mark/ckan/lib/default/src/ckan/ckanext/datastore/logic/action.py", line 503, in datastore_search
    res_exists, real_id = backend.resource_id_from_alias(res_id)
  File "/home/mark/ckan/lib/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1966, in resource_id_from_alias
    results = self._get_read_engine().execute(resources_sql, id=alias)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected
[SQL: SELECT alias_of FROM "_table_metadata" WHERE name = %(id)s]
[parameters: {'id': '9a56ef8e-13a7-4eae-98bc-081313d09f13'}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)`

**Second:**
`2021-03-17 13:44:30,455 ERROR [ckan.views.api] (psycopg2.OperationalError) SSL error: decryption failed or bad record mac
[SQL: SET LOCAL statement_timeout TO 60000]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL error: decryption failed or bad record mac
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/mark/ckan/lib/default/src/ckan/ckan/config/middleware/../../views/api.py", line 291, in action
    result = function(context, request_data)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/mark/ckan/lib/default/src/ckan/ckanext/datastore/logic/action.py", line 158, in datastore_create
    result = backend.create(context, data_dict)
  File "/home/mark/ckan/lib/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1884, in create
    context['connection'].execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL error: decryption failed or bad record mac
[SQL: SET LOCAL statement_timeout TO 60000]`


**Third:**
`2021-03-17 13:38:16,070 ERROR [ckan.views.api] (psycopg2.OperationalError) SSL error: decryption failed or bad record mac
[SQL: SELECT oid, typname FROM pg_type;]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL error: decryption failed or bad record mac
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/mark/ckan/lib/default/src/ckan/ckan/config/middleware/../../views/api.py", line 291, in action
    result = function(context, request_data)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/mark/ckan/lib/default/src/ckan/ckanext/datastore/logic/action.py", line 158, in datastore_create
    result = backend.create(context, data_dict)
  File "/home/mark/ckan/lib/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1877, in create
    _cache_types(context['connection'])
  File "/home/mark/ckan/lib/default/src/ckan/ckanext/datastore/backend/postgres.py", line 300, in _cache_types
    results = connection.execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL error: decryption failed or bad record mac
[SQL: SELECT oid, typname FROM pg_type;]`


**Fourth:**
`2021-03-17 13:56:55,073 ERROR [ckan.views.api] 'NoneType' object has no attribute 'transaction'
Traceback (most recent call last):
  File "/home/mark/ckan/lib/default/src/ckan/ckan/config/middleware/../../views/api.py", line 291, in action
    result = function(context, request_data)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/mark/ckan/lib/default/src/ckan/ckan/logic/action/create.py", line 332, in resource_create
    model.repo.commit()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 474, in _prepare_impl
    stx = self.session.transaction
AttributeError: 'NoneType' object has no attribute 'transaction'`


And you were right about datastore+datapusher involvement. These happen only when I upload tabular data for instance csv-files. Uploading other files, say pictures, that doesn't call datastore works fine.

**Comment by aitormagan** [comment]
Hi! Have you been able to fix this issue? We are at the same situation and trying to find a solution :(

**Comment by wardi** [comment]
This should be pretty easy to fix: #6420
