### ISSUE TITLE
Custom validator args (value, context) not as described in docs (not schema value, not session details)

### ISSUE THREAD

**Issue by reedv** [ckan/ckan#5992]
**CKAN version**
2.9.1

**Describe the bug**
Attempting to create a dataset field extension plugin as described in the docs (https://docs.ckan.org/en/2.9/extensions/adding-custom-fields.html#validator-value-context) and seeing that for my custom validator...

1) it appears the `value` and `context` objects are in swapped positions to how they are described in the docs ( https://docs.ckan.org/en/2.9/extensions/adding-custom-fields.html#validator-value-context ) (ie. when logging, I see value=someFunctionObject and context=someunicodeString) and
2) even if I were to switch them around the `context` object is just my own plugin <Plugin MyPlugin 'myplugin'> and the `value` object is the schema field name (not the schema value entered by the user).

...whereas in the docs (https://docs.ckan.org/en/2.9/extensions/adding-custom-fields.html#validator-value-context) it describes that the `context` object should be a `dict` with into about the user and session, etc and `value` should be the value of the field of the schema.

Could anyone help with this? Am I doing something wrong here?

**Steps to reproduce**
- Create a dataset extension plugin as described in the extension guide (see https://docs.ckan.org/en/2.9/extensions/adding-custom-fields.html#cleaning-up-the-code). My exact code is provided in the detail section below. 
- Attempt to update a dataset from Private to Public in the CKAN web UI

**Expected behavior**
I should be able to access the user info via the `context` param in the validator

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.
My code is mainly based on the extension tutorial (https://docs.ckan.org/en/2.9/extensions/adding-custom-fields.html#cleaning-up-the-code) and looks like...
```python
import ckan.plugins as plugins
import ckan.plugins.toolkit as toolkit
import logging

from ckan import model


class PublicrestrictiondatasetsPlugin(plugins.SingletonPlugin, toolkit.DefaultDatasetForm):
    plugins.implements(plugins.IConfigurer)
    plugins.implements(plugins.IDatasetForm)

    # IConfigurer
   # This was already here; generated when first running the cookiecutter command
    def update_config(self, config_):
        toolkit.add_template_directory(config_, 'templates')
        toolkit.add_public_directory(config_, 'public')
        toolkit.add_resource('fanstatic',
            'publicrestrictiondatasets')


    # IDatasetForm

    def _sysadmins_only(value, context):
        # ensure that only sysadmins are setting a dataset to public
        log = logging.getLogger(__name__)
       
        log.info('\n=====publicrestrictiondatasets:_sysadmins_only(value, context)=====')
        log.info(value)
        log.info(type(value))
        log.info([m for m in dir(value) if not m.startswith('__')])
        log.info(context)
        log.info(type(context))
        log.info([m for m in dir(context) if not m.startswith('__')])
       
        username = context.get('user')
        user = model.User.get(username)
        private = value
        if (not private) and (not user.sysadmin):
            raise toolkit.Invalid('Only sysadmin users may set datasets as public')
        else:
            return value

    def _modify_package_schema(self, schema):
        log = logging.getLogger(__name__)
        log.info('\n=====publicrestrictiondatasets:_modify_package_schema(self, schema)=====')
        log.info(schema)

        schema.update({
            'private': [self._sysadmins_only] + schema['private']  #[toolkit.get_validator('ignore_not_sysadmin')]
        })
        return schema

    def create_package_schema(self):
        # let's grab the default schema in our plugin
        schema = super(PublicrestrictiondatasetsPlugin, self).create_package_schema()
       
        schema = self._modify_package_schema(schema)
        return schema

    def update_package_schema(self):
        schema = super(PublicrestrictiondatasetsPlugin, self).update_package_schema()
       
        schema = self._modify_package_schema(schema)
        return schema

    def is_fallback(self):
        # Return True to register this plugin as the default handler for
        # package types not handled by any other IDatasetForm plugin.
        return True

    def package_types(self):
        # This plugin doesn't handle any special package types, it just
        # registers itself as the default (above).
        return []
```
and when attempting to update a Private dataset to Public (as a non-sysadmin user) in the CKAN web UI, I get a "Internal server error" and the relevant logs show...
```
=====publicrestrictiondatasets:_modify_package_schema(self, schema)=====
{'__before': [<function duplicate_extras_key at 0x7f578ddd9ad0>, <function ignore at 0x7f578dcf7d50>], 'maintainer': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], '__extras': [<function ignore at 0x7f578dcf7d50>], 'relationships_as_object': {'comment': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'object': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'state': [<function ignore at 0x7f578dcf7d50>], 'type': [<function not_empty at 0x7f578dcf7b50>, <function callable at 0x7f578bfcb050>], 'id': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'subject': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>]}, 'tag_string': [<function ignore_missing at 0x7f578dcf7ed0>, <function tag_string_convert at 0x7f578ddd9d50>], 'private': [<function ignore_missing at 0x7f578dcf7ed0>, <function boolean_validator at 0x7f578ddd9250>, <function datasets_with_no_organization_cannot_be_private at 0x7f578db73750>], 'maintainer_email': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>, <function email_validator at 0x7f578db73bd0>], '__junk': [<function empty at 0x7f578dcf7cd0>], 'id': [<function ignore_missing at 0x7f578dcf7ed0>, <function package_id_not_changed at 0x7f578ddd9050>], 'owner_org': [<function ignore_missing at 0x7f578dcf7ed0>, <function owner_org_validator at 0x7f578db68f50>, <function unicode_safe at 0x7f578dcfc150>], 'title': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'author_email': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>, <function email_validator at 0x7f578db73bd0>], 'state': [<function ignore_not_package_admin at 0x7f578ddd9e50>, <function ignore_missing at 0x7f578dcf7ed0>], 'version': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>, <function package_version_validator at 0x7f578ddd9a50>], 'license_id': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'save': [<function ignore at 0x7f578dcf7d50>], 'type': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'resources': {'mimetype': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'cache_url': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], '__extras': [<function ignore_missing at 0x7f578dcf7ed0>, <function extras_valid_json at 0x7f578db73ed0>, <function keep_extras at 0x7f578dcf7a50>], 'tracking_summary': [<function ignore_missing at 0x7f578dcf7ed0>], 'hash': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'description': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'last_modified': [<function ignore_missing at 0x7f578dcf7ed0>, <function isodate at 0x7f578ddd92d0>], 'format': [<function if_empty_guess_format at 0x7f578db73850>, <function ignore_missing at 0x7f578dcf7ed0>, <function clean_format at 0x7f578db738d0>, <function unicode_safe at 0x7f578dcfc150>], 'url': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>, <function remove_whitespace at 0x7f578db833d0>], 'created': [<function ignore_missing at 0x7f578dcf7ed0>, <function isodate at 0x7f578ddd92d0>], 'state': [<function ignore at 0x7f578dcf7d50>], 'cache_last_updated': [<function ignore_missing at 0x7f578dcf7ed0>, <function isodate at 0x7f578ddd92d0>], 'package_id': [<function ignore at 0x7f578dcf7d50>], 'mimetype_inner': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'url_type': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'position': [<function ignore at 0x7f578dcf7d50>], 'size': [<function ignore_missing at 0x7f578dcf7ed0>, <function int_validator at 0x7f578ddd90d0>], 'datastore_active': [<function ignore_missing at 0x7f578dcf7ed0>], 'id': [<function ignore_empty at 0x7f578dcf7f50>, <function unicode_safe at 0x7f578dcfc150>], 'resource_type': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'name': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>]}, 'tags': {'revision_timestamp': [<function ignore at 0x7f578dcf7d50>], 'vocabulary_id': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>, <function vocabulary_id_exists at 0x7f578db73450>], 'state': [<function ignore at 0x7f578dcf7d50>], 'display_name': [<function ignore at 0x7f578dcf7d50>], 'name': [<function not_missing at 0x7f578dcf7ad0>, <function not_empty at 0x7f578dcf7b50>, <function unicode_safe at 0x7f578dcfc150>, <function tag_length_validator at 0x7f578ddd9bd0>, <function tag_name_validator at 0x7f578ddd9c50>]}, 'groups': {'__extras': [<function ignore at 0x7f578dcf7d50>], 'title': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'id': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'name': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>]}, 'log_message': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>, <function no_http at 0x7f578ddd9350>], 'return_to': [<function ignore at 0x7f578dcf7d50>], 'relationships_as_subject': {'comment': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'object': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'state': [<function ignore at 0x7f578dcf7d50>], 'type': [<function not_empty at 0x7f578dcf7b50>, <function callable at 0x7f5787c6e750>], 'id': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'subject': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>]}, 'name': [<function ignore_missing at 0x7f578dcf7ed0>, <function name_validator at 0x7f578ddd9950>, <function package_name_validator at 0x7f578ddd99d0>, <function unicode_safe at 0x7f578dcfc150>], 'url': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'notes': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'author': [<function ignore_missing at 0x7f578dcf7ed0>, <function unicode_safe at 0x7f578dcfc150>], 'extras': {'__extras': [<function ignore at 0x7f578dcf7d50>], 'deleted': [<function ignore_missing at 0x7f578dcf7ed0>], 'value': [<function not_missing at 0x7f578dcf7ad0>], 'revision_timestamp': [<function ignore at 0x7f578dcf7d50>], 'state': [<function ignore at 0x7f578dcf7d50>], 'key': [<function not_empty at 0x7f578dcf7b50>, <function extra_key_not_in_root_schema at 0x7f578db73ad0>, <function unicode_safe at 0x7f578dcfc150>], 'id': [<function ignore at 0x7f578dcf7d50>]}}
.
.
.
=====publicrestrictiondatasets:_sysadmins_only(value, context)=====
2021-03-25 16:44:27,856 INFO  [ckanext.publicrestrictiondatasets.plugin] <Plugin PublicrestrictiondatasetsPlugin 'publicrestrictiondatasets'>
2021-03-25 16:44:27,856 INFO  [ckanext.publicrestrictiondatasets.plugin] <class 'ckanext.publicrestrictiondatasets.plugin.PublicrestrictiondatasetsPlugin'>
2021-03-25 16:44:27,856 INFO  [ckanext.publicrestrictiondatasets.plugin] ['_enable', '_id', '_id_env', '_implements', '_modify_package_schema', '_service', '_sysadmins_only', 'activate', 'alias', 'create_package_schema', 'deactivate', 'disable', 'edit_template', 'enable', 'enabled', 'history_template', 'implements', 'is_fallback', 'name', 'new_template', 'package_form', 'package_types', 'read_template', 'resource_form', 'resource_template', 'search_template', 'setup_template_variables', 'show_package_schema', 'update_config', 'update_package_schema']
2021-03-25 16:44:27,856 INFO  [ckanext.publicrestrictiondatasets.plugin] False
2021-03-25 16:44:27,856 INFO  [ckanext.publicrestrictiondatasets.plugin] <type 'unicode'>
2021-03-25 16:44:27,856 INFO  [ckanext.publicrestrictiondatasets.plugin] ['_formatter_field_name_split', '_formatter_parser', 'capitalize', 'center', 'count', 'decode', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'islower', 'isnumeric', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
2021-03-25 16:44:27,856 ERROR [ckan.config.middleware.flask_app] 'unicode' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/views/dataset.py", line 734, in post
    pkg_dict = get_action(u'package_update')(context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/update.py", line 295, in package_update
    package_plugin, context, data_dict, schema, 'package_update')
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/plugins.py", line 306, in plugin_validate
    return toolkit.navl_validate(data_dict, schema, context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 273, in validate
    converted_data, errors = _validate(flattened, schema, validators_context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 314, in _validate
    convert(converter, key, converted_data, errors, context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 224, in convert
    value = converter(converted_data.get(key))
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicrestrictiondatasets-0.0.1-py2.7.egg/ckanext/publicrestrictiondatasets/plugin.py", line 35, in _sysadmins_only
    username = context.get('user')
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by reedv** [comment]
Oddly, if I change the function a 3-parameter signature, like...
```python
    def _sysadmins_only(value, data, context):
        # ensure that only sysadmins are setting a dataset to public
        log = logging.getLogger(__name__)

        log.info('\n=====publicrestrictiondatasets:_sysadmins_only(value, context)=====')
        log.info(value)
        log.info(type(value))
        log.info([m for m in dir(value) if not m.startswith('__')])
        log.info(data)
        log.info(type(data))
        log.info([m for m in dir(data) if not m.startswith('__')])
        log.info(context)
        log.info(type(context))
        log.info([m for m in dir(context) if not m.startswith('__')])
```
I do actually see a `dict` get passed:
```
=====publicrestrictiondatasets:_sysadmins_only(value, context)=====
2021-03-25 18:56:07,387 INFO  [ckanext.publicrestrictiondatasets.plugin] <Plugin PublicrestrictiondatasetsPlugin 'publicrestrictiondatasets'>
2021-03-25 18:56:07,387 INFO  [ckanext.publicrestrictiondatasets.plugin] <class 'ckanext.publicrestrictiondatasets.plugin.PublicrestrictiondatasetsPlugin'>
2021-03-25 18:56:07,387 INFO  [ckanext.publicrestrictiondatasets.plugin] ['_enable', '_id', '_id_env', '_implements', '_modify_package_schema', '_service', '_sysadmins_only', 'activate', 'alias', 'create_package_schema', 'deactivate', 'disable', 'edit_template', 'enable', 'enabled', 'history_template', 'implements', 'is_fallback', 'name', 'new_template', 'package_form', 'package_types', 'read_template', 'resource_form', 'resource_template', 'search_template', 'setup_template_variables', 'show_package_schema', 'update_config', 'update_package_schema']
2021-03-25 18:56:07,387 INFO  [ckanext.publicrestrictiondatasets.plugin] False
2021-03-25 18:56:07,387 INFO  [ckanext.publicrestrictiondatasets.plugin] <type 'unicode'>
2021-03-25 18:56:07,387 INFO  [ckanext.publicrestrictiondatasets.plugin] ['_formatter_field_name_split', '_formatter_parser', 'capitalize', 'center', 'count', 'decode', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'islower', 'isnumeric', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
2021-03-25 18:56:07,387 INFO  [ckanext.publicrestrictiondatasets.plugin] {u'allow_partial_update': True, 'package': <Package id=c32f08e8-3afe-4d78-bd6a-0d20c3832b2e name=publictest-001 title=publictest 001 version= url= author= author_email= maintainer= maintainer_email= notes=init=public license_id= type=dataset owner_org=e05e8bca-b9fb-4c77-8bbe-a526b5a1fee8 creator_user_id=1f52555a-852d-4b4f-b940-844ed3235339 metadata_created=2021-03-25 06:54:32.049850 metadata_modified=2021-03-25 06:54:40.917108 private=True state=active>, 'schema_keys': ['__before', 'maintainer', '__extras', 'relationships_as_object', 'tag_string', 'private', 'maintainer_email', '__junk', 'id', 'owner_org', 'title', 'author_email', 'state', 'version', 'license_id', 'save', 'type', 'resources', 'tags', 'groups', 'log_message', 'return_to', 'relationships_as_subject', 'name', 'url', 'notes', 'author', 'extras'], u'auth_user_obj': <User id=1f52555a-852d-4b4f-b940-844ed3235339 name=myuser password=$pbkdf2-sha512$25000$cC5ljBFiDOH8H6MUQgih1A$MZVPwcrgxdhjG/.CgO6b6K/Txa0kPuCFbkUUSPJLPt5x07F6GE2mLzeCr936zG5UjHl6XpabpWWoL/ZJSEUPgA fullname=None email=myuser@myorg.org apikey=None created=2021-02-19 01:34:19.791162 reset_key=None about=None activity_streams_email_notifications=False sysadmin=False state=active image_url=None plugin_extras=None>, '__auth_user_obj_checked': True, u'session': <sqlalchemy.orm.scoping.scoped_session object at 0x7f3fd7cff610>, u'user': u'myuser', '__auth_audit': [], u'model': <module 'ckan.model' from '/usr/lib/ckan/default/src/ckan/ckan/model/__init__.pyc'>, u'save': True, u'message': u''}
2021-03-25 18:56:07,387 INFO  [ckanext.publicrestrictiondatasets.plugin] <type 'dict'>
2021-03-25 18:56:07,387 INFO  [ckanext.publicrestrictiondatasets.plugin] ['clear', 'copy', 'fromkeys', 'get', 'has_key', 'items', 'iteritems', 'iterkeys', 'itervalues', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values', 'viewitems', 'viewkeys', 'viewvalues']
```
But, if I use the 4-parameter signature (one that is actually described in the docs (https://docs.ckan.org/en/2.9/extensions/adding-custom-fields.html#validator-key-flattened-data-errors-context) unlike the 3-param version I use above), I get an args-mismatch error:
```
2021-03-25 18:51:50,966 ERROR [ckan.config.middleware.flask_app] _sysadmins_only() takes exactly 4 arguments (3 given)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/views/dataset.py", line 734, in post
    pkg_dict = get_action(u'package_update')(context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/update.py", line 295, in package_update
    package_plugin, context, data_dict, schema, 'package_update')
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/plugins.py", line 306, in plugin_validate
    return toolkit.navl_validate(data_dict, schema, context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 273, in validate
    converted_data, errors = _validate(flattened, schema, validators_context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 314, in _validate
    convert(converter, key, converted_data, errors, context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 249, in convert
    value = converter(converted_data.get(key), context)
TypeError: _sysadmins_only() takes exactly 4 arguments (3 given)
```

**Comment by reedv** [comment]
I think I understand what's going on. Because I'm defining my custom validator within my plugin class...
```python
class PublicrestrictiondatasetsPlugin(plugins.SingletonPlugin, toolkit.DefaultDatasetForm):
    plugins.implements(plugins.IConfigurer)
    plugins.implements(plugins.IDatasetForm)

    # IConfigurer
   # This was already here; generated when first running the cookiecutter command
    def update_config(self, config_):
        toolkit.add_template_directory(config_, 'templates')
        toolkit.add_public_directory(config_, 'public')
        toolkit.add_resource('fanstatic',
            'publicrestrictiondatasets')


    # IDatasetForm

    def _sysadmins_only(value, context):
    ...
```
...the `self` object is getting passed in as the first arg. That is why when I print the first object in the logs, I see `<Plugin PublicrestrictiondatasetsPlugin 'publicrestrictiondatasets'>`; it's the `self` object.

Editing the function signature to look like...
```python
    def _sysadmins_only(self, value, context):
    ...
```
...then the fact that the 3-param function signature (as shown in my other post) does make sense.

(**Still don't understand why using a 4-param signature does not work though** (I would think the schema would see the signature param count and pass the right number of args. Is that not how it works? Else how? That was my interpretation of the docs))
