### ISSUE TITLE
WSGI server is not starting up

### ISSUE THREAD

**Issue by ddazal** [ckan/ckan#6050]
**CKAN version**
2.9.2

I followed the steps to install CKAN from source successfully in a server with Ubuntu 20.04.2 LTS installed. That is, I can see the demo homepage on port 5000 whenever I run the server. However, after finishing step number 7 of the [deploying a source install page](https://docs.ckan.org/en/latest/maintaining/installing/deployment.html) all I see in the browser is `Internal Server Error`.

At first I thought that Nginx wasn't proxying properly to the upstream. So, I stopped the `supervisor` process an created a catch-all server with python running on port 8080 and it worked. Then, I looked at the logs generated when the command `sudo supervisorctl restart ckan-uwsgi:*` is executed. Results are show below.

**Additional details**
This is the error log output when I execute `sudo supervisorctl restart ckan-uwsgi:*`
```
[uWSGI] getting INI configuration from /etc/ckan/default/ckan-uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Apr 27 23:07:18 2021] ***
compiled with version: 9.3.0 on 27 April 2021 21:08:51
os: Linux-5.4.0-1038-aws #40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021
nodename: ip-172-31-49-149
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
writing pidfile to /tmp/ckan-uwsgi.pid
detected binary path: /home/ubuntu/ckan/lib/default/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setuid() to 33
your processes number limit is 3869
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8080 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:33567 (port auto-assigned) fd 3
Python version: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
PEP 405 virtualenv detected: /usr/lib/ckan/default
Set PythonHome to /usr/lib/ckan/default
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5595466c81b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 203152 bytes (198 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/home/ubuntu/ckan/lib/default/src/ckan/wsgi.py", line 10, in <module>
    loggingFileConfig(config_filepath)
  File "/usr/lib/python3.8/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python3.8/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
unable to load app 0 (mountpoint='') (callable not found or import error)
Traceback (most recent call last):
  File "/etc/ckan/default/wsgi.py", line 10, in <module>
    loggingFileConfig(config_filepath)
  File "/usr/lib/python3.8/logging/config.py", line 69, in fileConfig
    cp.read(fname)
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.8/configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/etc/ckan/default/ckan.ini', line: 1
'w#\n'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
spawned uWSGI master process (pid: 45914)
spawned uWSGI worker 1 (pid: 45917, cores: 1)
spawned uWSGI http 1 (pid: 45918)
```
I can't figure out why is this happening.

**Comment by kowh-ai** [comment]
Can you please run a `cat -vet /etc/ckan/default/ckan.ini` and post the output - thanks!

**Comment by ddazal** [comment]
HI @kowh-ai this is the full output

```
#$
# CKAN - Pylons configuration$
#$
# These are some of the configuration options available for your CKAN$
# instance. Check the documentation in 'doc/configuration.rst' or at the$
# following URL for a description of what they do and the full list of$
# available options:$
#$
# http://docs.ckan.org/en/latest/maintaining/configuration.html$
#$
# The %(here)s variable will be replaced with the parent directory of this file$
#$
$
[DEFAULT]$
$
# WARNING: *THIS SETTING MUST BE SET TO FALSE ON A PUBLIC ENVIRONMENT*$
# With debug mode enabled, a visitor to your site could execute malicious commands.$
debug = true$
$
[server:main]$
use = egg:Paste#http$
host = 0.0.0.0$
port = 5000$
$
[app:main]$
use = egg:ckan$
full_stack = true$
cache_dir = /tmp/%(ckan.site_id)s/$
beaker.session.key = ckan$
$
# This is the secret token that the beaker library uses to hash the cookie sent$
# to the client. `ckan generate config` generates a unique value for this each$
# time it generates a config file.$
beaker.session.secret = uxKM39cEJMbyiv-0aQZ0RtO2K$
$
# `ckan generate config` generates a unique value for this each time it generates$
# a config file.$
app_instance_uuid = b13fef3c-9596-42f9-a7a0-2a54c11b9a08$
$
# repoze.who config$
who.config_file = %(here)s/who.ini$
who.log_level = warning$
who.log_file = %(cache_dir)s/who_log.ini$
# Session timeout (user logged out after period of inactivity, in seconds).$
# Inactive by default, so the session doesn't expire.$
# who.timeout = 86400$
$
## Database Settings$
sqlalchemy.url = postgresql://ckan_default:ckan_default@localhost/ckan_default$
$
ckan.datastore.write_url = postgresql://ckan_default:ckan_default@localhost/datastore_default$
ckan.datastore.read_url = postgresql://datastore_default:datastore_default@localhost/datastore_default$
$
# PostgreSQL' full-text search parameters$
ckan.datastore.default_fts_lang = english$
ckan.datastore.default_fts_index_method = gist$
$
$
## Site Settings$
$
ckan.site_url = http://source.ckan.datasketch.co$
#ckan.use_pylons_response_cleanup_middleware = true$
$
## Authorization Settings$
$
ckan.auth.anon_create_dataset = false$
ckan.auth.create_unowned_dataset = false$
ckan.auth.create_dataset_if_not_in_organization = false$
ckan.auth.user_create_groups = false$
ckan.auth.user_create_organizations = false$
ckan.auth.user_delete_groups = true$
ckan.auth.user_delete_organizations = true$
ckan.auth.create_user_via_api = false$
ckan.auth.create_user_via_web = true$
ckan.auth.roles_that_cascade_to_sub_groups = admin$
ckan.auth.public_user_details = true$
ckan.auth.public_activity_stream_detail = true$
ckan.auth.allow_dataset_collaborators = false$
ckan.auth.create_default_api_keys = false$
$
## API Token Settings$
api_token.nbytes = 60$
api_token.jwt.encode.secret = string:uxKM39cEJMbyiv-0aQZ0RtO2K$
api_token.jwt.decode.secret = string:uxKM39cEJMbyiv-0aQZ0RtO2K$
api_token.jwt.algorithm = HS256$
$
## API Token: expire_api_token plugin$
expire_api_token.default_lifetime = 3600$
$
## Search Settings$
$
ckan.site_id = default$
solr_url = http://127.0.0.1:8983/solr$
$
$
## Redis Settings$
$
# URL to your Redis instance, including the database to be used.$
#ckan.redis.url = redis://localhost:6379/0$
$
$
## CORS Settings$
$
# If cors.origin_allow_all is true, all origins are allowed.$
# If false, the cors.origin_whitelist is used.$
# ckan.cors.origin_allow_all = true$
# cors.origin_whitelist is a space separated list of allowed domains.$
# ckan.cors.origin_whitelist = http://example1.com http://example2.com$
$
$
## Plugins Settings$
$
# Note: Add ``datastore`` to enable the CKAN DataStore$
#       Add ``datapusher`` to enable DataPusher$
#^I^IAdd ``resource_proxy`` to enable resorce proxying and get around the$
#^I^Isame origin policy$
ckan.plugins = stats text_view image_view recline_view datastore pdae_theme datapusher$
$
# Define which views should be created by default$
# (plugins must be loaded in ckan.plugins)$
ckan.views.default_views = image_view text_view recline_view$
$
# Customize which text formats the text_view plugin will show$
#ckan.preview.json_formats = json$
#ckan.preview.xml_formats = xml rdf rdf+xml owl+xml atom rss$
#ckan.preview.text_formats = text plain text/plain$
$
# Customize which image formats the image_view plugin will show$
#ckan.preview.image_formats = png jpeg jpg gif$
$
## Front-End Settings$
$
ckan.site_title = Portal de datos abiertos de Ecuador$
ckan.site_logo = /base/images/ckan-logo.png$
ckan.site_description =$
ckan.favicon = /base/images/ckan.ico$
ckan.gravatar_default = identicon$
ckan.preview.direct = png jpg gif$
ckan.preview.loadable = html htm rdf+xml owl+xml xml n3 n-triples turtle plain atom csv tsv rss txt json$
ckan.display_timezone = server$
$
# package_hide_extras = for_search_index_only$
#package_edit_return_url = http://another.frontend/dataset/<NAME>$
#package_new_return_url = http://another.frontend/dataset/<NAME>$
#ckan.recaptcha.publickey =$
#ckan.recaptcha.privatekey =$
#licenses_group_url = http://licenses.opendefinition.org/licenses/groups/ckan.json$
# ckan.template_footer_end =$
$
$
## Internationalisation Settings$
ckan.locale_default = en$
ckan.locale_order = en pt_BR ja it cs_CZ ca es fr el sv sr sr@latin no sk fi ru de pl nl bg ko_KR hu sa sl lv$
ckan.locales_offered =$
ckan.locales_filtered_out = en_GB$
$
## Feeds Settings$
$
ckan.feeds.authority_name =$
ckan.feeds.date =$
ckan.feeds.author_name =$
ckan.feeds.author_link =$
$
## Storage Settings$
$
ckan.storage_path = /var/lib/ckan/default$
#ckan.max_resource_size = 10$
#ckan.max_image_size = 2$
$
## Webassets Settings$
#ckan.webassets.use_x_sendfile = false$
#ckan.webassets.path = /var/lib/ckan/webassets$
$
$
## Datapusher settings$
$
# Make sure you have set up the DataStore$
$
ckan.datapusher.formats = csv xls xlsx tsv application/csv application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet$
ckan.datapusher.url = http://127.0.0.1:8800/$
#ckan.datapusher.assume_task_stale_after = 3600$
$
# Resource Proxy settings$
# Preview size limit, default: 1MB$
#ckan.resource_proxy.max_file_size = 1048576$
# Size of chunks to read/write.$
#ckan.resource_proxy.chunk_size = 4096$
$
## Activity Streams Settings$
$
#ckan.activity_streams_enabled = true$
#ckan.activity_list_limit = 31$
#ckan.activity_streams_email_notifications = true$
#ckan.email_notifications_since = 2 days$
ckan.hide_activity_from_users = %(ckan.site_id)s$
$
$
## Email settings$
$
#email_to = errors@example.com$
#error_email_from = ckan-errors@example.com$
#smtp.server = localhost$
#smtp.starttls = False$
#smtp.user = username@example.com$
#smtp.password = your_password$
#smtp.mail_from =$
#smtp.reply_to =$
$
## Background Job Settings$
ckan.jobs.timeout = 180$
$
## Logging configuration$
[loggers]$
keys = root, ckan, ckanext, werkzeug$
$
[handlers]$
keys = console$
$
[formatters]$
keys = generic$
$
[logger_root]$
level = WARNING$
handlers = console$
$
[logger_werkzeug]$
level = WARNING$
handlers = console$
qualname = werkzeug$
propagate = 0$
$
[logger_ckan]$
level = INFO$
handlers = console$
qualname = ckan$
propagate = 0$
$
[logger_ckanext]$
level = DEBUG$
handlers = console$
qualname = ckanext$
propagate = 0$
$
[handler_console]$
class = StreamHandler$
args = (sys.stderr,)$
level = NOTSET$
formatter = generic$
$
[formatter_generic]$
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s$

```

**Comment by ajddba** [comment]
did you ever work this out?

**Comment by ddazal** [comment]
@ajddba No, I ended up installing ckan from the package https://docs.ckan.org/en/2.9/maintaining/installing/install-from-package.html

**Comment by ajddba** [comment]
@ddazal cheers - unfortunately i cant install from package as its for centos

**Comment by BainMcKay** [comment]
We installed on Ubuntu 20.04 on Digital Ocean. The only issue I was having is [urllib3] http handler to SOLR. it complained about version mismatch. Manual changing the version number did not help. I replaced it with [python3-requests], which resolved that connection issue. It effected Datapusher fetching of csv files from FileStore. Now I get the csv fetched in [Upload to DataStore], parsing of CSV and mapping of proper types to sqlLite table fields, but it does not import the rows. Sill complained about urllib3 version issue, so may go to Conda to resolve. Once that's working, we have fully workingCKAN on Digital Ocean Ubuntu 20.04. Hopefully only one more library mismatch to resolve.

**Comment by sfirke** [comment]
I was getting `ckan-uwsgi:ckan-uwsgi-00 FATAL Exited too quickly (process log may have details)` when I ran `sudo supervisorctl status` and, like the first post here, had `!!! no internal routing support, rebuild with pcre support !!!` in my log files.

I ran `sudo apt-get install libpcre3 libpcre3-dev` when installing packages in the first steps of the CKAN installation from package guide and that fixed it for me.  Credit to [this StackOverflow post](https://stackoverflow.com/a/22645915/4470365).  Not sure why it was necessary for me, I'm running CKAN on an Azure Gov Cloud Virtual Machine in case that is relevant.
