### ISSUE TITLE
DataTables view does not work when a resource does not have resource.size defined

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#6060]
**CKAN version**
master

**Describe the bug**
DataTables view shows some resource metadata as a tooltip.

![Screenshot from 2021-05-01 11-54-00](https://user-images.githubusercontent.com/1980690/116787844-83da9280-aa74-11eb-96fa-7ce6f7ddc69d.png)

However, when the resource's `size` attribute (the "**( 3.9 k)**" on the last line of the tooltip in the screenshot above) is undefined, you get an error:
```
2021-05-01 11:06:29,297 ERROR [ckan.config.middleware.flask_app] int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/resource.py", line 611, in view
    return h.rendered_resource_view(view, resource, package, embed=True)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 2532, in rendered_resource_view
    return literal(base.render(template, extra_vars=data_dict))
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 151, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datatablesview/templates/datatables/datatables_view.html", line 1, in <module>
    {% extends "base.html" %}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/base.html", line 106, in <module>
    {%- block page %}{% endblock -%}
  File "/usr/lib/ckan/default/src/ckan/ckanext/datatablesview/templates/datatables/datatables_view.html", line 91, in <module>
    {{- res.format or res.mimetype_inner or res.mimetype or _('unknown') }} ( {{ h.SI_number_span(res.size)|striptags }} )&#10;"
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 2643, in SI_number_span
    number = int(number)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Steps to reproduce**
1. Use `datastore_create` to create a resource.
2. Define a datatables resource view on the created resource

**Expected behavior**
If the resource's `size` attribute is undefined, datatables view should still work.

**Additional details**
A resource's `size` attribute is automatically defined when a file is uploaded to CKAN.  If a datastore resource is created without uploading a file, the `size` attribute is undefined.

**Comment by ThrawnCA** [comment]
This still doesn't work for us. For resources with no size we get a stack trace similar to:

      File "/mnt/local_data/ckan_venv/src/ckan/ckan/templates/base.html", line 108, in top-level template code
        {%- block page %}{% endblock -%}
      File "/mnt/local_data/ckan_venv/src/ckan/ckanext/datatablesview/templates/datatables/datatables_view.html", line 93, in block 'page'
        {%- if res.size|int != 0 -%}
      File "/usr/lib/ckan/default/lib64/python3.7/site-packages/jinja2/filters.py", line 971, in do_int
        return int(value)
    jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'size'

I think the condition should be `if res.size and res.size|int != 0`.
