### ISSUE TITLE
Language translation: Error in re-extracting message when updating translation file 

### ISSUE THREAD

**Issue by chenxj2020** [ckan/ckan#6215]
**CKAN version**: ckan 2.9 with python 3.8

**Describe the bug**
In order to update my translation file, firstly I re-extract the messages by running the command:
python setup.py extract_messages

But there is error in the extracting process, it interrupts with:

File "/usr/lib/ckan/default/lib/python3.8/site-packages/jinja2/lexer.py", line 381, in expect
    raise TemplateSyntaxError("expected token %r, got %r" %
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'old_link'

Do you know how to solve this problem? Appreciate for any reply.

**Comment by kowh-ai** [comment]
@chenxj2020 - does this error occur before any files are parsed?

**Comment by steveoni** [comment]
@kowh-ai i'm having the same error when i run `python setup.py extract_messages`, ckan 2.9.4 python 3

here is the output error

```
extracting messages from ckanext/fcscopendata/templates/snippets/changes/extension_fields.html
extracting messages from ckanext/fcscopendata/templates/snippets/changes/extra_fields.html
extracting messages from ckanext/fcscopendata/templates/snippets/changes/license.html
extracting messages from ckanext/fcscopendata/templates/snippets/changes/maintainer.html
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/site-packages/babel/messages/frontend.py", line 481, in run
    for filename, lineno, message, comments, context in extracted:
  File "/usr/lib/python3.8/site-packages/babel/messages/extract.py", line 149, in extract_from_dir
    for message_tuple in check_and_call_extract_file(
  File "/usr/lib/python3.8/site-packages/babel/messages/extract.py", line 207, in check_and_call_extract_file
    for message_tuple in extract_from_file(
  File "/usr/lib/python3.8/site-packages/babel/messages/extract.py", line 243, in extract_from_file
    return list(extract(method, fileobj, keywords, comment_tags,
  File "/usr/lib/python3.8/site-packages/babel/messages/extract.py", line 325, in extract
    for lineno, funcname, messages, comments in results:
  File "/usr/lib/python3.8/site-packages/jinja2/ext.py", line 609, in babel_extract
    node = environment.parse(source)
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 493, in parse
    self.handle_exception(exc_info, source_hint=source)
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 5, in <module>
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 212, in parse_if
    node.body = self.parse_statements(('name:elif', 'name:else',
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 620, in parse_tuple
    args.append(parse())
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 547, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 676, in parse_postfix
    node = self.parse_call(node)
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 789, in parse_call
    ensure(not kwargs)
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 762, in ensure
    self.fail('invalid syntax for function call expression',
  File "/usr/lib/python3.8/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: invalid syntax for function call expression
```

**Comment by kowh-ai** [comment]
@steveoni - I think this was fixed in https://github.com/ckan/ckan/pull/6258 - I updated mine and the `/ckan/i18n/ckan.pot` file was successfully created

**Comment by steveoni** [comment]
@kowh-ai my bad! I did a mistake of not including the plug-in interface to my extension.

now fixed.
Thanks
