### ISSUE TITLE
Refactor model to support SQLAlchemy 1.4

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#6243]
Our current usage of SQLAlchemy prevents us from upgrading to [version 1.4](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html).

* We use the [`SessionExtension`](https://github.com/ckan/ckan/blob/94194d43667d122bc5a55a45e16b07b4430f3405/ckan/model/meta.py#L13) and [`MapperExtension`](https://github.com/ckan/ckan/blob/94194d43667d122bc5a55a45e16b07b4430f3405/ckan/model/extension.py#L27) classes, which are deprecated in 1.3 and removed in 1.4. They need to be replaced by the [event listener system](https://docs.sqlalchemy.org/en/14/core/event.html). Might be a good opportunity to assess if these extensions are actually used.
* The dictization functions use [`RowProxy`](https://github.com/ckan/ckan/blob/94194d43667d122bc5a55a45e16b07b4430f3405/ckan/lib/dictization/__init__.py#L13) which is not available on 1.4 ([`Row`](https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.Row) seems to be a potential replacement).
* `mapper()` no longer supports `order_by` (eg [here](https://github.com/ckan/ckan/blob/94194d43667d122bc5a55a45e16b07b4430f3405/ckan/model/tag.py#L285)) or `extension` (eg [here](https://github.com/ckan/ckan/blob/94194d43667d122bc5a55a45e16b07b4430f3405/ckan/model/package.py#L553))
* A couple of warnings coming up:
```
/home/adria/dev/pyenvs/ckan-py3/src/ckan/ckan/model/user.py:62: SAWarning: relationship 'Package.package_tag_all' will copy column package.id to column package_tag.package_id, which conflicts with relationship(s): 'Package.package_tags' (copies package.id to package_tag.package_id), 'PackageTag.package' (copies package.id to package_tag.package_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="package,package_tags"' to the 'Package.package_tag_all' relationship.
  query = meta.Session.query(cls).autoflush(False)
/home/adria/dev/pyenvs/ckan-py3/src/ckan/ckan/model/user.py:62: SAWarning: relationship 'PackageTag.pkg' will copy column package.id to column package_tag.package_id, which conflicts with relationship(s): 'Package.package_tags' (copies package.id to package_tag.package_id), 'PackageTag.package' (copies package.id to package_tag.package_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="package,package_tags"' to the 'PackageTag.pkg' relationship.
  query = meta.Session.query(cls).autoflush(False)
```

```
/home/adria/dev/pyenvs/ckan-py3/src/ckan/ckan/model/activity.py:130: SAWarning: TypeDecorator JsonDictType() will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
  return _activities_limit(q, limit, offset).all()
```

**Comment by pdelboca** [comment]
I have been debugging the first point and cleaned one of the SQLAlchemy extensions that depends on SessionExtension: #6331 

Related CkanSessionExtension:

https://github.com/ckan/ckan/blob/94194d43667d122bc5a55a45e16b07b4430f3405/ckan/model/meta.py#L33-L62

The whole purpose of this extension is to create a cache object inside Session object to trigger the index of the Package into Solr.

It has two flaws in it's design:
 1. Session objects should not be used as cache. ([Is the Session a cache?](https://docs.sqlalchemy.org/en/14/orm/session_basics.html#is-the-session-a-cache)). And related to this, the extension is trying to hack what is avoided by design: get the ID of the object when is still not commited to the database. (Hence the whole labyrinth of commit/flush hooks) 
 2. [Indexing depends on `package_show`](https://github.com/ckan/ckan/blob/94194d43667d122bc5a55a45e16b07b4430f3405/ckan/lib/search/__init__.py#L117-L138) that depends on the Package being stored in the database. Hooking the index logic into `before_commit` will never be possible if not for dirty hacks.

Sadly `Package.as_dict()` also depends on it to be available in the DB since internally it queries for relationships. So except for some dictization function, there is no clean way to index a package before the commit.

I'm gonna try to see how easy is to keep our current system using SQLAlchemy events listeners as suggested and leave this refactor for other issue.

**Comment by pdelboca** [comment]
I had some time to keep working on this issue. The next step is to refactor all uses of `SessionExtension` which can be tricky to do.

The problem I'm facing is that the SQLAlchemy the paradigm shifted from `SessionExtension` plugins to EventListeners registration. This means that instead of adding an extension to the Session object, we need to register the events upon initialization.

We need to go from this:
```python
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm.interfaces import SessionExtension

class MySessionExtension(SessionExtension):
    def before_commit(self, session):
        print "before commit!"

Session = sessionmaker(extension=MySessionExtension())
```

To this:
```python
from sqlalchemy import event
from sqlalchemy.orm import sessionmaker

def my_before_commit(session):
    print("before commit!")

Session = sessionmaker()

event.listen(Session, "before_commit", my_before_commit)
```

To keep compatibility with current Implementations we need to find a way to iterate over all the plugins implementing `ISession` and add the events to our sessions object.

While testing implementations I'm facing some errors like circular imports. Some simple code like this one:

```python
Session = orm.scoped_session(orm.sessionmaker(
    autoflush=False,
    autocommit=False,
    expire_on_commit=False
))

for plugin in plugins.PluginsImplementation(plugins.ISession):
    events.listen(Session, 'before_commit', plugin.before_commit)

```

Will throw an error since `load_environment` -> `model -> `meta` -> `plugins` -> `model` and finally:
```
ImportError: Error importing plugin "ckan.tests.pytest_ckan.ckan_setup": cannot import name 'PackageRelationship' from partially initialized module 'ckan.model' (most likely due to a circular import)

So I will keep working on figuring our a solution for this plugin implementation.
```

**Comment by pdelboca** [comment]
@amercader this ticket is not finished yet. I'm still working on some of the cleanup like the MapperExtensions.

I would suggest to keep it open :)

**Comment by Namwanza** [comment]
The error seems to surface with SessionExtension, I have tried all the other options but can't get it resolved, how did you @pdelboca solve this ??

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 33, in <module>
    sys.exit(load_entry_point('ckan', 'console_scripts', 'ckan')())
  File "/usr/lib/ckan/default/bin/ckan", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/home-directory/ckan/lib/default/src/ckan/ckan/cli/cli.py", line 13, in <module>
    from ckan.config.middleware import make_app
  File "/home/home-directory/ckan/lib/default/src/ckan/ckan/config/middleware/__init__.py", line 11, in <module>
    from ckan.config.environment import load_environment
  File "/home/home-directory/ckan/lib/default/src/ckan/ckan/config/environment.py", line 15, in <module>
    import ckan.model as model
  File "/home/home-directory/ckan/lib/default/src/ckan/ckan/model/__init__.py", line 20, in <module>
    from ckan.model import meta
  File "/home/home-directory/ckan/lib/default/src/ckan/ckan/model/meta.py", line 11, in <module>
    from sqlalchemy.orm.interfaces import SessionExtension
ImportError: cannot import name 'SessionExtension' from 'sqlalchemy.orm.interfaces' (/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/orm/interfaces.py)

**Comment by pdelboca** [comment]
Hello @Namwanza !

What version of CKAN are you using? SQLAlchemy 1.4 has support only in `CKAN 2.10`.

`SessionExtension` has been deprecated in SQLAlchemy 1.4 and therefore we had to refactor it from core. Your traceback points to `meta.py` line 11 having a call to `SessionExtension` which have been removed in `CKAN 2.10`. Note that if you are running CKAN 2.9 you will not be able to run SQLAlchemy 1.4.

Bests!

**Comment by markstuart** [comment]
Hi @pdelboca, I'm trying to upgrade an existing CKAN install from 2.9.8 to 2.10.1, and noticing a lot of warnings in the logs that seem to be relevant to this issue:
```
ckan  | /ckan_repo_code/src/ckan-core/ckanext/activity/model/activity.py:713: SAWarning: TypeDecorator JsonDictType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
ckan  |   results = q.all()
ckan  | /ckan_repo_code/src/ckan-core/ckanext/datastore/logic/action.py:646: SAWarning: TypeDecorator JsonDictType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
ckan  |   q.update({'extras': extras}, synchronize_session=False)
```
Any ideas of how to remove those warnings?

**Comment by pdelboca** [comment]
Hello @markstuart , it is necessary to do some work on the models to remove those warnings.

Hi @markstuart , thanks for raising this.

We need to revisit some of our models and add the `cache_ok` attribute. Both `datastore` and `activity` plugins are raising the same warning.

I will create a ticket to do a follow up of this. (PR are wellcome!)

More info: https://docs.sqlalchemy.org/en/14/faq/performance.html#why-is-my-application-slow-after-upgrading-to-1-4-and-or-2-x
