### ISSUE TITLE
"Internal server error" when colleague tries to create a Dataset

### ISSUE THREAD

**Issue by maxclac** [ckan/ckan#6291]
**CKAN version**

2.9.2

**Describe the bug**
I am running a CKAN 2.9.2 instance on an Ubuntu 20 server. I am a admin and I can create and edit datasets without problems, but a colleague of mine, who is also an admin user, got an "Internal server error" message while simply trying to create a dataset. To be more precise, it happens when he clicks "Add data". I really puzzles me that I cannot reproduce that.

**Steps to reproduce**
Simply trying to create a dataset on the UI

**Expected behavior**
I should have no internal error

**Additional details**

I found this on `/var/log/ckan/ckan-uwsgi.stderr.log`. I hope it helps.

```
2021-07-26 11:45:57,856 DEBUG [ckan.logic] check access OK - user_create user=
2021-07-26 11:45:58,737 DEBUG [ckan.views] No valid session data - deleting session
2021-07-26 11:45:58,737 DEBUG [ckan.views] Session: dict_items([('_domain', None), ('_path', '/'), ('_accessed_time', 1627299957.6847792), ('_creation_time', 1627299956.0832794)])
2021-07-26 11:45:58,738 ERROR [ckan.config.middleware.flask_app] Exception on /organization/archipelago [GET]
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 2266, in process_response
    response = handler(response)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 400, in ckan_after_request
    r_time = time.time() - g.__timer
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 444, in __getattr__
    return getattr(app_globals.app_globals, name)
AttributeError: '_Globals' object has no attribute '__timer'
2021-07-26 11:45:58,739 ERROR [ckan.config.middleware.flask_app] 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 2266, in process_response
    response = handler(response)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 400, in ckan_after_request
    r_time = time.time() - g.__timer
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 444, in __getattr__
    return getattr(app_globals.app_globals, name)
AttributeError: '_Globals' object has no attribute '__timer'


```

**Comment by smotornyuk** [comment]
I saw similar error in environments that are setting up multiple uWSGI processes. Can you post your `ckan-uwsgi.ini`? Or, if you understand, how it works, check whether you are using more than one process. If so, make sure you've enabled `lazy-apps` option

**Comment by maxclac** [comment]
Thank you @smotornyuk for your reply, it sounds very useful! Actually, I found that my problem was a misconfiguration of my config file. I will anyway pay attention to uWSGI processes in the future.
