### ISSUE TITLE
CKAN won't start if properties have accents in the ini config file

### ISSUE THREAD

**Issue by quinoescobar** [ckan/ckan#6336]
**CKAN version**
2.9.3

**Describe the bug**
Ckan won't start if is set ckan.title or ckan.description has accents.

**Steps to reproduce**

1. In the ckan.ini configuration file set ckan.title = "Catálogo de datos abiertos"
2. Restart/Reload Apache
3. Try to access the ckan web page --> Server Error 500
4. Take a look to the log output

**Expected behavior**
CKAN will start independent of the text set in the ckan.title and ckan.description.

**Additional details**

I think the error comes from this library in the Apache WSGI config file:
`from logging.config import fileConfig as loggingFileConfig
`

Log output:

> Traceback (most recent call last):
  File "/..path../ckan/default/apache.wsgi", line 17, in <module>
    loggingFileConfig(config_path)
  File "/usr/lib/python3.6/logging/config.py", line 74, in fileConfig
    cp.read(fname)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 564: ordinal not in range(128)

**Comment by amercader** [comment]
Try to open the file with the correct encoding in the line linked

**Comment by quinoescobar** [comment]
It can't be apply right now, the parameter encoding in the logging.config.fileConfig it's not present for the versions of python currently fully supported by CKAN, Python 3 (<= 3.8).
Only starting from Python 3 version >= 3.10 the encoding parameter its implemented

"**_New in version 3.10: The encoding parameter is added._**"

https://docs.python.org/3.10/library/logging.config.html#logging.config.fileConfig
