### ISSUE TITLE
internal server error while running ckan (ckan.config.middleware.flask_app error)

### ISSUE THREAD

**Issue by flopdaisies** [ckan/ckan#6365]
**CKAN version**
2.9.3 on MacOS

**Expected behavior**
There's no internal server error when opening main page and dataset.

**Additional details**
2021-09-06 09:32:14,398 ERROR [ckan.config.middleware.flask_app] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/dataset.py", line 316, in search
    query = get_action(u'package_search')(context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 1869, in package_search
    query.run(data_dict, permission_labels=labels)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/query.py", line 378, in run
    solr_response = conn.search(**query)
  File "/usr/lib/ckan/default/lib/python3.7/site-packages/pysolr.py", line 721, in search
    decoded = self.decoder.decode(response)
  File "/usr/lib/ckan/default/lib/python3.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/ckan/default/lib/python3.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kowh-ai** [comment]
CKAN on MacOS is unsupported. I'd recommend using Ubuntu 20.04...Using VirtualBox 6.1 on MacOS to create a virtual server (Ubuntu 20.04) is pretty painless
