### ISSUE TITLE
Removal of ckan.lib.base.render_jinja2 breaks harvester plugin

### ISSUE THREAD

**Issue by thebe14** [ckan/ckan#6393]
**Describe the bug**
The CKAN master branch no longer contains `render_jinja2` in module `ckan.lib.base`, which is required by the plugin. 

**Steps to reproduce**

- Install CKAN using Docker compose, from the master branch.
- Add the [harvest](https://github.com/ckan/ckanext-harvest/issues/455) plugin, which bricks my CKAN container. 

**Expected behavior**

Installation of the latest CKAN and the latest harvest plugin should work out of the box.

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

$ sudo docker logs ckan
db:5432 - accepting connections
Set environment variables
Initialize CKAN database
2021-09-14 11:13:51,115 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
2021-09-14 11:13:51,116 INFO  [ckan.config.environment] Loading static files from public
2021-09-14 11:13:51,187 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
2021-09-14 11:13:51,570 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
2021-09-14 11:13:51,613 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2021-09-14 11:13:51,615 DEBUG [ckanext.harvest.model] Harvest table creation deferred
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/bin/ckan", line 33, in <module>
    sys.exit(load_entry_point('ckan', 'console_scripts', 'ckan')())
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 113, in parse_args
    result = super().parse_args(ctx, args)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 123, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 132, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 54, in __init__
    self.app = make_app(self.config)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 23, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 75, in load_environment
    p.load_all()
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 166, in load_all
    load(*plugins)
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 195, in load
    plugins_update()
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 154, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 252, in update_config
    logic.get_action('get_site_user')({'ignore_auth': True}, None)
  File "/usr/lib/ckan/venv/src/ckan/ckan/logic/__init__.py", line 445, in get_action
    for name, action_function in plugin.get_actions().items():
  File "/usr/lib/ckan/venv/src/ckanext-harvest/ckanext/harvest/plugin/__init__.py", line 272, in get_actions
    action_functions = _get_logic_functions(module_root)
  File "/usr/lib/ckan/venv/src/ckanext-harvest/ckanext/harvest/plugin/__init__.py", line 334, in _get_logic_functions
    module = __import__(module_path)
  File "/usr/lib/ckan/venv/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 19, in <module>
    from ckan.lib.base import render_jinja2
ImportError: cannot import name 'render_jinja2' from 'ckan.lib.base' (/usr/lib/ckan/venv/src/ckan/ckan/lib/base.py)

**Comment by Zharktas** [comment]
Fixed inn ckan/ckanext-harvest#459
