### ISSUE TITLE
While updating CKAN from 2.7.2 to v2.9.3(via docker image), Facing many issues

### ISSUE THREAD

**Issue by ArqamFarooqui110719** [ckan/ckan#6413]
**CKAN version**
Updating to 2.9.3(docker)

**Describe the bug**
I have updated CKAN 2.9.3, and currently CKAN container is UP and successfully running. But when I'm trying to access CKAN GUI, actual CKAN page is not being loaded it is giving below page with `404 Not found` error:

![CKAN GUI error 2 9 3](https://user-images.githubusercontent.com/55977298/133730671-853a2b03-6b3e-4a90-a862-a60d24b8a916.png)

**Why this error is occurring or why CKAN page is not being loaded? Can anyone Please suggest that, Thank you:)**

And below error is occurring in CKAN logs when I'm accessing CKAN GUI:

```
2021-09-17 01:39:29,291 DEBUG [ckan.logic] check access NotAuthorized - user_create user= "Not authorized to create users"
2021-09-17 01:39:29,292 DEBUG [ckan.lib.helpers] Humanize group_type of type group for main nav
2021-09-17 01:39:29,301 INFO  [ckan.config.middleware.flask_app]  /ckan/webassets/base/7a2a1fbc_ckan.js render time 0.015 seconds
2021-09-17 01:39:29,302 INFO  [werkzeug] 192.168.11.115 - - [17/Sep/2021 01:39:29] "GET /ckan/webassets/base/7a2a1fbc_ckan.js HTTP/1.0" 404 -
2021-09-17 01:39:29,321 ERROR [ckan.config.middleware.flask_app] 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask_multistatic.py", line 96, in send_static_file
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

```

**Steps to reproduce**

1. Initially we pull the CKAN image(v2.9.3) from docker hub.
2. Then we have changed the `docker-compose.yml` file as per latest CKAN. (for example: image name, tag, volume etc.)
3. And we have also made some changes in `production.ini` file as per latest CKAN.
4. Meanwhile we have faced many integration issues with PostgreSQL, SOLR and REDIS, we have resolved that. And we have also faced many error like `SOLR schema version not supported` and `ERROR:  relation "user" does not exist at character 515` etc., we also resolved these errors.

**Expected behavior**
CKAN GUI should be loaded/visible, as expected.

**Additional details**
PostgreSQL: 9.6
SOLR: 6.0.0

**Comment by ArqamFarooqui110719** [comment]
I'm also trying to add ckanext-oauth2 extension(0.7.0) in this updated CKAN. For that I have installed ckanext-oauth2 but when I'm adding oauth2 plugin in the `producition.ini`, it is giving below error:
```
ModuleNotFoundError: No module named 'urlparse'
```

I have resolved the above error by updating the file /usr/lib/ckan/venv/src/ckan/ckanext-oauth2/ckanext/oauth2/plugin.py from from urlparse import urlparse to from urllib.parse import urlparse.

But after that I'm getting another error i.e.:
```
AttributeError: module 'oauth2' has no attribute 'OAuth2Helper'
```
how can I resolve the above error?
