### ISSUE TITLE
 Installing from source on Centos7 failed on zope requirement.

### ISSUE THREAD

**Issue by 4estone** [ckan/ckan#6427]
**CKAN 2.9.3**

**Describe the bug**
Installing from source on Centos7 failed on  zope requirement.
```
Running setup.py install for zope.interface ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/lib/ckan/default/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k3rzaoup/zope-interface_2cf763c975914a25ad0c836998a18727/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k3rzaoup/zope-interface_2cf763c975914a25ad0c836998a18727/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1i3vl1zu/install-record.txt --single-version-externally-managed --compile --install-headers /usr/lib/ckan/default/include/site/python3.6/zope.interface
         cwd: /tmp/pip-install-k3rzaoup/zope-interface_2cf763c975914a25ad0c836998a18727/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k3rzaoup/zope-interface_2cf763c975914a25ad0c836998a18727/setup.py", line 26, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/lib/ckan/default/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k3rzaoup/zope-interface_2cf763c975914a25ad0c836998a18727/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k3rzaoup/zope-interface_2cf763c975914a25ad0c836998a18727/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1i3vl1zu/install-record.txt --single-version-externally-managed --compile --install-headers /usr/lib/ckan/default/include/site/python3.6/zope.interface Check the logs for full command output.
```
It seems to be related to [zope.interface<5.0.0 relies on a deprecated API from setuptools](https://stackoverflow.com/questions/67784206/python-dependency-satisfied-but-pip-still-complains-for-zope-interface-4-6-0)

Is there any plan to upgrade requirements.txt with zope.interface==5.0.0 or later wich seems to solve issue when I do it?
Thanks
Sylvain

**Comment by Zharktas** [comment]
You need to install our pinned setuptools version from https://github.com/ckan/ckan/blob/master/requirement-setuptools.txt which currently is version 44.1.0. We do need to upgrade dependencies but those updates are not usually added to patch releases as testing resources are limited.

**Comment by ChristianF88** [comment]
I am experiencing the same issue on Debian. Install **CKAN 2.9.8** from source. I am using the correct version of setuptools (44.1.0) and the latest version of pip. Running `pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.9.8#egg=ckan[requirements]'` results in:

```sh
Collecting zope.interface==4.3.2 (from ckan[requirements])
  Using cached zope.interface-4.3.2.tar.gz (143 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/ckan/default/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/ckan/default/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/ckan/default/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-gt1i5xn2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-gt1i5xn2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-gt1i5xn2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-gt1i5xn2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 26, in <module>
      ImportError: cannot import name 'Feature' from 'setuptools' (/tmp/pip-build-env-gt1i5xn2/overlay/lib/python3.9/site-packages/setuptools/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I am using **Python 3.9.13**.

**Comment by ChristianF88** [comment]
**Not** upgrading pip works for me. I am using **pip 22.0.4**.

**Comment by spwoodcock** [comment]
The fix is pinning `setuptools==45`.

I think that pinning `pip==22.0.4` may inadvertently do that, but the actual issue is with setuptools.

**Comment by knudmoeller** [comment]
I had the same issue following the [Install from Source](https://docs.ckan.org/en/2.9/maintaining/installing/install-from-source.html) instructions for 2.9.10 on Ubuntu 20.04.

Pinning `setuptools==45` didn't help, but

`pip install pip==22.0.4`

did.

Should this be reflected in the documentation? Either remove/replace the `pip install --upgrade pip` command, or add an entry to the "Source install troubleshooting" section? I could do a PR, if someone could suggest which approach would be better.

**Comment by dboc** [comment]
@knudmoeller Thanks!
This issue still there.... I installed version 2.9.11 in Ubuntu 22.04 and i had to set `pip install pip=22.0.4` .

I ask the same question:
"Should this be reflected in the documentation? Either remove/replace the pip install --upgrade pip command, or add an entry to the "Source install troubleshooting" section? I could do a PR, if someone could suggest which approach would be better."
