### ISSUE TITLE
ImportError: cannot import name 'render_jinja2' from 'ckan.lib.base'

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#6450]
**CKAN version**
master, ad405b580332e5f73e933da8db6ed36a90adfcdf

**Describe the bug**

```
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/lib/ckan/venv/bin/ckan", line 33, in <module>
ckan          |     sys.exit(load_entry_point('ckan', 'console_scripts', 'ckan')())
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
ckan          |     return self.main(*args, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1061, in main
ckan          |     with self.make_context(prog_name, args, **extra) as ctx:
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 923, in make_context
ckan          |     self.parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 113, in parse_args
ckan          |     result = super().parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1624, in parse_args
ckan          |     rest = super().parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1379, in parse_args
ckan          |     value, args = param.handle_parse_result(ctx, opts, args)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2364, in handle_parse_result
ckan          |     value = self.process_value(ctx, value)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2326, in process_value
ckan          |     value = self.callback(ctx, self, value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 123, in _init_ckan_config
ckan          |     _add_ctx_object(ctx, value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 132, in _add_ctx_object
ckan          |     ctx.obj = CtxObject(path)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 54, in __init__
ckan          |     self.app = make_app(self.config)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 23, in make_app
ckan          |     load_environment(conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 75, in load_environment
ckan          |     p.load_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 166, in load_all
ckan          |     load(*plugins)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 195, in load
ckan          |     plugins_update()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 154, in plugins_update
ckan          |     environment.update_config()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 246, in update_config
ckan          |     logic.get_action('get_site_user')({'ignore_auth': True}, None)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/logic/__init__.py", line 442, in get_action
ckan          |     for name, action_function in plugin.get_actions().items():
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/ckanext/harvest/plugin/__init__.py", line 272, in get_actions
ckan          |     action_functions = _get_logic_functions(module_root)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/ckanext/harvest/plugin/__init__.py", line 334, in _get_logic_functions
ckan          |     module = __import__(module_path)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/ckanext/harvest/logic/action/update.py", line 19, in <module>
ckan          |     from ckan.lib.base import render_jinja2
ckan          | ImportError: cannot import name 'render_jinja2' from 'ckan.lib.base' (/usr/lib/ckan/venv/src/ckan/ckan/lib/base.py)
```

**Steps to reproduce**
Steps to reproduce the behavior: `cd contrib/docker && docker-compose down -v && docker-compose up --build`

**Expected behavior**
CKAN starts.

**Comment by kowh-ai** [comment]
Looks like `render_jinja2` was removed in https://github.com/ckan/ckan/commit/d19b2ca1bd7118068c749f773a7cd80cda8c85efharvest was updated on Sep. 22

**Comment by frafra** [comment]
Thank you!
