### ISSUE TITLE
TypeError: 'ScriptInfo' object is not subscriptable

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#6452]
I tried to start CKAN using Flask, for debugging purposes in PyCharm.

This is a command line equivalent of what PyCharm tries to do when debugging a Flask app in Docker:
```docker-compose run -e CKAN_INI=/etc/ckan/production.ini ckan python3 -m flask run```

...which fails badly:

```
Traceback (most recent call last):
2021-10-04T14:40:10.250688142Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
2021-10-04T14:40:10.251175580Z     rv = self.invoke(ctx)
2021-10-04T14:40:10.251179400Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
2021-10-04T14:40:10.251182175Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-10-04T14:40:10.251184175Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
2021-10-04T14:40:10.251186213Z     return ctx.invoke(self.callback, **ctx.params)
2021-10-04T14:40:10.251188110Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
2021-10-04T14:40:10.251227566Z     return __callback(*args, **kwargs)
2021-10-04T14:40:10.251231344Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
2021-10-04T14:40:10.251308438Z     return ctx.invoke(f, obj, *args, **kwargs)
2021-10-04T14:40:10.251312984Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
2021-10-04T14:40:10.251535644Z     return __callback(*args, **kwargs)
2021-10-04T14:40:10.251538485Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/cli.py", line 845, in run_command
2021-10-04T14:40:10.251540929Z     app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
2021-10-04T14:40:10.251552568Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/cli.py", line 321, in __init__
2021-10-04T14:40:10.251554690Z     self._load_unlocked()
2021-10-04T14:40:10.251556534Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/cli.py", line 346, in _load_unlocked
2021-10-04T14:40:10.251598292Z     self._app = rv = self.loader()
2021-10-04T14:40:10.251625468Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/cli.py", line 406, in load_app
2021-10-04T14:40:10.251654503Z     app = locate_app(self, import_name, None, raise_if_not_found=False)
2021-10-04T14:40:10.251679427Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/cli.py", line 273, in locate_app
2021-10-04T14:40:10.251827713Z     return find_best_app(script_info, module)
2021-10-04T14:40:10.251832303Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/cli.py", line 68, in find_best_app
2021-10-04T14:40:10.251834434Z     app = call_factory(script_info, app_factory)
2021-10-04T14:40:10.251836243Z   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/cli.py", line 119, in call_factory
2021-10-04T14:40:10.251838117Z     return app_factory(*args, **kwargs)
2021-10-04T14:40:10.251839870Z   File "/opt/project/ckan/config/middleware/__init__.py", line 23, in make_app
2021-10-04T14:40:10.251841807Z     load_environment(conf)
2021-10-04T14:40:10.251843550Z   File "/opt/project/ckan/config/environment.py", line 41, in load_environment
2021-10-04T14:40:10.251845393Z     os.environ['CKAN_CONFIG'] = conf['__file__']
2021-10-04T14:40:10.251847363Z TypeError: 'ScriptInfo' object is not subscriptable
```

https://github.com/ckan/ckan/blob/ad405b580332e5f73e933da8db6ed36a90adfcdf/ckan/config/environment.py#L41

**Comment by amercader** [comment]
The entrypoints are written to be used using the `ckan run` command. Running `flask run` will probably pass different parameters to the app factory (a `ScriptInfo` object instead of a `dict`). Can you configure PyCharm to run the expected CKAN command (`ckan run`)?
