### ISSUE TITLE
Docker entrypoint does not generate /etc/ckan/production.ini correctly

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#6464]
**CKAN version**
CKAN 2.8.3, CKAN 2.9.4, CKAN master

**Describe the bug**
Docker entrypoint does not generate `production.ini` correctly.

**Steps to reproduce**
```
cd contrib/docker
cp .env.template .env
docker-compose down -v
docker-compose build ckan

docker-compose run --rm ckan grep 'ckan.site_url' /etc/ckan/production.ini
```

**Expected behavior**
`ckan.site_url` should be set using `CKAN_SITE_URL` environmental variable.

**Additional details**
```
# echo $CKAN_SITE_URL
http://localhost:5000
# rm /etc/ckan/production.ini 
# ckan generate config /etc/ckan/production.ini 
# grep ckan.site_url /etc/ckan/production.ini
ckan.site_url =
/# ckan -c /etc/ckan/production.ini run
2021-10-12 12:32:47,343 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
2021-10-12 12:32:47,344 INFO  [ckan.config.environment] Loading static files from public
2021-10-12 12:32:47,386 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
2021-10-12 12:32:47,565 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
2021-10-12 12:32:47,764 INFO  [ckan.cli.server] Running CKAN on http://localhost:5000
2021-10-12 12:32:48,476 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
2021-10-12 12:32:48,476 INFO  [ckan.config.environment] Loading static files from public
2021-10-12 12:32:48,516 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
2021-10-12 12:32:48,694 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
2021-10-12 12:32:48,884 INFO  [ckan.cli.server] Running CKAN on http://localhost:5000
^C# unset CKAN_SITE_URL
# ckan -c /etc/ckan/production.ini run
2021-10-12 12:33:16,941 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
2021-10-12 12:33:16,941 INFO  [ckan.config.environment] Loading static files from public
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/bin/ckan", line 33, in <module>
    sys.exit(load_entry_point('ckan', 'console_scripts', 'ckan')())
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1061, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 113, in parse_args
    result = super().parse_args(ctx, args)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1624, in parse_args
    rest = super().parse_args(ctx, args)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2326, in process_value
    value = self.callback(ctx, self, value)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 123, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 132, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 54, in __init__
    self.app = make_app(self.config)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 23, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 75, in load_environment
    p.load_all()
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 162, in load_all
    unload_all()
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 210, in unload_all
    unload(*reversed(_PLUGINS))
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 242, in unload
    plugins_update()
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 154, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 150, in update_config
    raise RuntimeError(
RuntimeError: ckan.site_url is not configured and it must have a value. Please amend your .ini file.
```

**Comment by dynamicmonkeys** [comment]
Some extra keywords to help people pushing their Google-fu...
If you're trying to build the setup via Docker on a Mac running macOS Monterey, without any tinkering then port 5000 is used by default by the ControlCenter.app.

Due to this issue, even if you change:
https://github.com/ckan/ckan/blob/ad8d27e504391f504012bfcce79a7cd29c62046c/contrib/docker/docker-compose.yml#L24
to:
`      - "0.0.0.0:${CKAN_PORT}:5001"`

then this won't work fully as per the notes above.

As well as this change, you need to do the tweak as @kowh-ai describes above as well:
https://github.com/ckan/ckan/blob/ad8d27e504391f504012bfcce79a7cd29c62046c/Dockerfile#L78
to:
`CMD ["ckan","-c","/etc/ckan/production.ini", "run", "--host", "0.0.0.0", "--port", "5001"]`

**Comment by categulario** [comment]
Just faced this issue. Not only with `SITE_URL` but also `SQLALCHEMY_URL`.

**Comment by categulario** [comment]
It is not enough, because `update_config` itself requires `site_url` to be set.
