### ISSUE TITLE
TypeError: str cannot be used as validator because it is not a user-defined function

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#6488]
**CKAN version**
master

**Describe the bug**
Adding a CKAN harvester raises an internal server error.

**Steps to reproduce**
Add a CKAN harvest with ckanext-harvest.

**Expected behavior**
No internal server error.

**Additional details**
```
2021-10-21 13:19:34,408 ERROR [ckan.config.middleware.flask_app] str cannot be used as validator because it is not a user-defined function
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/navl/dictization_functions.py", line 222, in convert
    nargs = converter.__code__.co_argcount
AttributeError: type object 'str' has no attribute '__code__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/views.py", line 83, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/flask/views.py", line 157, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/../../views/dataset.py", line 600, in post
    pkg_dict = get_action(u'package_create')(context, data_dict)
  File "/usr/lib/ckan/venv/src/ckan/ckan/logic/__init__.py", line 496, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/venv/src/ckan/ckan/logic/action/create.py", line 174, in package_create
    data, errors = lib_plugins.plugin_validate(
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/plugins.py", line 313, in plugin_validate
    return toolkit.navl_validate(data_dict, schema, context)
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/navl/dictization_functions.py", line 278, in validate
    converted_data, errors = _validate(flattened, schema, validators_context)
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/navl/dictization_functions.py", line 328, in _validate
    convert(converter, key, converted_data, errors, context)
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/navl/dictization_functions.py", line 224, in convert
    raise TypeError(
TypeError: str cannot be used as validator because it is not a user-defined function
```

I post here since it looks a CKAN issue from the traceback, and not a ckanext-harvest error, but I could be wrong

**Comment by ChristianF88** [comment]
Did you every figure out how to fix this? I am running into the same error, when trying to add a test organization.

```sh
root@ckan-2-10:~# /usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini generate fake-data organization
2023-03-21 08:24:19,911 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2023-03-21 08:24:19,912 INFO  [ckan.config.environment] Loading static files from public
2023-03-21 08:24:20,178 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2023-03-21 08:24:21,016 WARNI [ckanext.reclineview.plugin] The Recline-based views are deprecated andwill be removed in future versions
2023-03-21 08:24:21,047 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2023-03-21 08:24:21,457 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 246, in convert
    nargs = converter.__code__.co_argcount
AttributeError: type object 'str' has no attribute '__code__'. Did you mean: '__mod__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 33, in <module>
    sys.exit(load_entry_point('ckan', 'console_scripts', 'ckan')())
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/generate.py", line 308, in fake_data
    for entity in factory.create_batch(fake_count, **extras):
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/base.py", line 540, in create_batch
    return [cls.create(**kwargs) for _ in range(size)]
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/base.py", line 540, in <listcomp>
    return [cls.create(**kwargs) for _ in range(size)]
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/base.py", line 528, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/alchemy.py", line 51, in _generate
    return super()._generate(strategy, params)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/base.py", line 465, in _generate
    return step.build()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/builder.py", line 262, in build
    instance = self.factory_meta.instantiate(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/base.py", line 317, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/tests/factories.py", line 214, in _create
    return cls.api_create(kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/tests/factories.py", line 197, in api_create
    result = helpers.call_action(cls._meta.action, **data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/tests/helpers.py", line 128, in call_action
    return logic.get_action(action_name)(context, kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 943, in organization_create
    return _group_or_org_create(context, data_dict, is_org=True)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 753, in _group_or_org_create
    data, errors = lib_plugins.plugin_validate(
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/plugins.py", line 327, in plugin_validate
    result = plugin.validate(context, data_dict, schema, action)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/scheming/plugins.py", line 191, in validate
    return navl_validate(data_dict, schema, context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 305, in validate
    flat_data, errors = _validate(flattened, schema, validators_context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 356, in _validate
    convert(converter, key, converted_data, errors, context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 248, in convert
    raise TypeError(
TypeError: str cannot be used as validator because it is not a user-defined function

```

**Comment by frafra** [comment]
@ChristianF88 sorry, I do not have this problem any more, since I began avoiding using ckanext-harvester and I just push/synchronize datasets using CKAN API. Way easier to fix issues and to maintain, in my opinion. See: https://gitlab.com/GISdevio/geonetwork2ckan.

**Comment by ChristianF88** [comment]
@frafra thanks for the swift response. I do not use **ckanext-harvest**, so the cause must be outside that library. I created a new issue for this and linked it here. Cheers
