### ISSUE TITLE
Cannot upload organizations with logo via API

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#6575]
**CKAN version**
2.9.4

**Describe the bug**
Cannot upload organizations with logos using ckanapi any more, because of strict typing.

**Steps to reproduce**
Upload an organization with ckanapi using `--upload-logo`, like this:
```
ckanapi load organizations --upload-logo -r $dst_url -a$dst_key
```

The `--upload-logo` makes ckanapi send the data as `multipart/form-data` instead of JSON and CKAN fails because `is_organization` is a string and not a boolean.

**Expected behavior**
It should just work like the previous versions.

**Additional details**
```
2021-12-06 16:57:17,410 ERROR [ckan.views.api] (exceptions.TypeError) Not a boolean value: u'true'
[SQL: UPDATE "group" SET image_url=%(image_url)s, is_organization=%(is_organization)s WHERE "group".id = %(group_id)s]
[parameters: [{'is_organization': u'true', 'group_id': u'40b5eee0-506e-426e-a368-c5b593db2452', 'image_url': u'2021-12-06-165717.397966Arcticfoxmodule.png'}]]
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/src/ckan/ckan/views/api.py", line 291, in action
    result = function(context, request_data)
  File "/usr/lib/ckan/venv/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/venv/src/ckan/ckan/logic/action/update.py", line 783, in group_update
    return _group_or_org_update(context, data_dict)
  File "/usr/lib/ckan/venv/src/ckan/ckan/logic/action/update.py", line 752, in _group_or_org_update
    model.repo.commit()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 462, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 297, in __call__
    fn(*args, **kw)
  File "/usr/lib/ckan/venv/src/ckan/ckan/model/meta.py", line 54, in before_commit
    session.flush()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 733, in _init_compiled
    for key in compiled_params
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 733, in <genexpr>
    for key in compiled_params
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1782, in process
    value = _strict_as_bool(value)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1757, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % value)
StatementError: (exceptions.TypeError) Not a boolean value: u'true'
[SQL: UPDATE "group" SET image_url=%(image_url)s, is_organization=%(is_organization)s WHERE "group".id = %(group_id)s]
[parameters: [{'is_organization': u'true', 'group_id': u'40b5eee0-506e-426e-a368-c5b593db2452', 'image_url': u'2021-12-06-165717.397966Arcticfoxmodule.png'}]]
```

**Comment by Sunny-NEC** [comment]
@tino097  I am interested to work in this issue.

**Comment by Sunny-NEC** [comment]
I am unable  to reproduce this issue in my local machine. it would be great if you provide some other information to reproduce this issue.

**Comment by frafra** [comment]
@Sunny-NEC 
1. Create an organization with a logo
2. Dump the organization using `ckanapi dump organizations --all -r "$SRC_URL" -a"$SRC_KEY" > organizations.jsonl`
3. Load the organization using `ckanapi load organizations -r "$DST_URL" -a"$DST_KEY" --upload-logo < organizations.jsonl`

The problem appears with both Python 2 and Python 3. Even if the value `is_organization` is boolean, it gets cast to a string when using `--upload-logo`, as the organization gets send using `multipart/form-data` instead of a regular typed JSON.

**Comment by hussnainwithss** [comment]
@tino097 can i take a go at this. i have been reporting issues previously and would like to start contributing the actual code base. this seems like the best issue for me to fix and start contributing more regularly.

**Comment by tino097** [comment]
@Sunny-NEC @hussnainwithss go on, no need to ask for permission to contribute

**Comment by robin-NEC** [comment]
Hi @frafra  I would like to work on this issue. Please let me know if someone working on it.

**Comment by frafra** [comment]
@robin-NEC feel free to go after it.

**Comment by robin-NEC** [comment]
@frafra  I'm trying to reproduce the issue by following the steps you mentioned, but I'm getting a different error. 
```
2022-03-14 14:47:35,199 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2022-03-14 14:47:35,199 INFO  [ckan.config.environment] Loading static files from public
2022-03-14 14:47:35,238 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-03-14 14:47:35,512 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
Usage: ckan [OPTIONS] COMMAND [ARGS]...

Error: No such command 'api'.
```
Are the variables `"$SRC_URL"` & `"$SRC_KEY"` that you've mentioned environment specific or do i need to provide them myself? 
What exactly are these variable?
I just want to make sure that I'm going in the right direction with this.

**Comment by frafra** [comment]
The command is `ckanapi`, not `ckan`, which triggers such CKAN bug.
The variables depend on your CKAN setup (URL and API key generated by your user).

**Comment by tino097** [comment]
@robin-NEC as @frafra mentioned the command is `ckanapi` and you will need to install this [package](https://github.com/ckan/ckanapi) in your local virtual environment

**Comment by robin-NEC** [comment]
I'm able to dump the organization but getting a different error while loading them.
```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckanapi", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/ckanapi/cli/main.py", line 141, in main
    return load_things(ckan, thing[0], arguments)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/ckanapi/cli/load.py", line 47, in load_things
    return load_things_worker(ckan, thing, arguments)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/ckanapi/cli/load.py", line 222, in load_things_worker
    obj = _upload_logo(ckan,obj)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/ckanapi/cli/load.py", line 311, in _upload_logo
    ckan.action.group_update(**obj)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/ckanapi/common.py", line 48, in action
    return self._ckan.call_action(name,
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/ckanapi/remoteckan.py", line 93, in call_action
    return reverse_apicontroller_action(url, status, response)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/ckanapi/common.py", line 133, in reverse_apicontroller_action
    raise CKANAPIError(repr([url, status, response]))
ckanapi.errors.CKANAPIError: ['http://localhost:5000/api/action/group_update', 500, '{"help": "http://127.0.0.1:5000/api/3/action/help_show?name=group_update", "error": {"__type": "Internal Server Error", "message": "Internal Server Error"}, "success": false}']
```
Can you provide any lead for this?

**Comment by frafra** [comment]
@robin-NEC CKAN fails, which is what this bug report is about. You can have a look at CKAN logs to see if it fails for the same reasons.

**Comment by robin-NEC** [comment]
Hi @frafra , on investigation I'm not sure how and where the `parameters` are being passed? 
Can you provide any guidance on this?

**Comment by frafra** [comment]
@robin-NEC you can see the CKAN traceback in the first post, which also explains as the request is sent as `multipart/form-data` when the logo is updated, which is not typed and makes CKAN fail.
One option would be to try to convert the argument which require a boolean from strings when needed.
