### ISSUE TITLE
AttributeError: 'module' object has no attribute 'base'

### ISSUE THREAD

**Issue by jbspeakr** [ckan/ckan#663]
1 Forked and cloned master
2 Set up environment according to "Testing for Developers"
3 Run nosetests --ckan ckan

```
ckan.model.modification: ERROR: 'module' object has no attribute 'base'
Traceback (most recent call last):
  File "/home/jbspeakr/.virtualenvs/ckan/src/ckan/ckan/model/modification.py", line 68, in notify
    observer.notify(entity, operation)
  File "/home/jbspeakr/.virtualenvs/ckan/src/ckan/ckan/lib/search/__init__.py", line 125, in notify
    logic.get_action('package_show')(
  File "/home/jbspeakr/.virtualenvs/ckan/src/ckan/ckan/logic/__init__.py", line 276, in get_action
    module = __import__(module_path)
  File "/home/jbspeakr/Dev/Repos/ckan/ckan/logic/__init__.py", line 8, in <module>
    import ckan.lib.base as base
AttributeError: 'module' object has no attribute 'base'
```

**Comment by marcdubois71450** [comment]
I had the same problem, be careful that your file does not also name it milter.py. Your script must not have the same name as an import
