### ISSUE TITLE
Cannot import core blueprint modules

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#6678]
**CKAN version**

2.9

**Describe the bug**

Attempting to import the core blueprint modules sometimes results in an ImportError. Importing at plugin load time works, but lazy-loading at the time of actually creating a blueprint does not.

**Steps to reproduce**

https://github.com/ThrawnCA/ckanext-import-example contains a minimal plugin that, when installed, will recreate the error. Going to any dataset view page should be sufficient.

**Additional details**

Stack trace for the example plugin is similar to:

    [Mon Jan 31 09:58:03.557953 2022] [:error] [pid 11776] [remote 10.40.0.253:60] Traceback (most recent call last):
    [Mon Jan 31 09:58:03.557965 2022] [:error] [pid 11776] [remote 10.40.0.253:60]   File "/etc/ckan/default/apache.wsgi", line 22, in <module>
    [Mon Jan 31 09:58:03.557987 2022] [:error] [pid 11776] [remote 10.40.0.253:60]     application = make_app(config)
    [Mon Jan 31 09:58:03.557993 2022] [:error] [pid 11776] [remote 10.40.0.253:60]   File "/mnt/local_data/ckan_venv/src/ckan/ckan/config/middleware/__init__.py", line 58, in make_app
    [Mon Jan 31 09:58:03.558004 2022] [:error] [pid 11776] [remote 10.40.0.253:60]     flask_app = make_flask_stack(conf)
    [Mon Jan 31 09:58:03.558009 2022] [:error] [pid 11776] [remote 10.40.0.253:60]   File "/mnt/local_data/ckan_venv/src/ckan/ckan/config/middleware/flask_app.py", line 241, in make_flask_stack
    [Mon Jan 31 09:58:03.558130 2022] [:error] [pid 11776] [remote 10.40.0.253:60]     plugin_blueprints = plugin.get_blueprint()
    [Mon Jan 31 09:58:03.558136 2022] [:error] [pid 11776] [remote 10.40.0.253:60]   File "/mnt/local_data/ckan_venv/src/ckanext-import-example/ckanext/import_example/plugin.py", line 13, in get_blueprint
    [Mon Jan 31 09:58:03.558159 2022] [:error] [pid 11776] [remote 10.40.0.253:60]     import dataset
    [Mon Jan 31 09:58:03.558163 2022] [:error] [pid 11776] [remote 10.40.0.253:60]   File "/mnt/local_data/ckan_venv/src/ckanext-import-example/ckanext/import_example/dataset.py", line 1, in <module>
    [Mon Jan 31 09:58:03.558182 2022] [:error] [pid 11776] [remote 10.40.0.253:60]     from ckan.views import dataset
    [Mon Jan 31 09:58:03.558195 2022] [:error] [pid 11776] [remote 10.40.0.253:60] ImportError: cannot import name dataset

**Comment by ThrawnCA** [comment]
Adding an import at plugin load time (eg at the top of `plugin.py`) also prevents the error from occurring later. We may be able to use this as a workaround...
