### ISSUE TITLE
error [500] - internal server error when trying to download dataset resource as json

### ISSUE THREAD

**Issue by tgurr** [ckan/ckan#6713]
**CKAN version**
2.9.5

**Describe the bug**
While downloading as json works for other resources on other datasets on the same system, it fails on a specific one with "Error [500] - Internal server error".

**Steps to reproduce**
* Dataset with csv: [2022_02_06-oberbuergermeisterwahl-stadt-heilbronn-heilbronner-stadtteile.csv](https://github.com/ckan/ckan/files/8108382/2022_02_06-oberbuergermeisterwahl-stadt-heilbronn-heilbronner-stadtteile.csv)
* Click download
* Choose JSON
* See error

**Expected behavior**
Export/Download as JSON without error.

**Additional details**
I couldn't find anything in the logs, if you can give me any hint I'll gladly attach any information needed to identify the issue. DataStore processing Log view under the DataStore tab on the dataset in the webinterface doesn't show any problem, everything green.

Screenshot of the error:
![ckan_error500](https://user-images.githubusercontent.com/414984/154937371-d8a1e7d7-f855-4144-a88e-11d14d6143b3.png)

**Comment by TomeCirun** [comment]
@kowh-ai @tgurr, I tried with the resource you attached, instead of 500 I get AssertionError, I didn't have much time to deal with the problem, but I will do it by the end of the week.

**Comment by visla-xugeng** [comment]
@TomeCirun any update on this issue? 
We got the similar 500 Internal Server Error, when we tried to download with **JSON Flat**. 
![image](https://user-images.githubusercontent.com/88679609/162581388-53de3009-e5f3-40fe-80df-bb4965926362.png)

**Comment by hylkevdveen** [comment]
@tgurr @kowh-ai @TomeCirun is there a solution for this problem yet? I am running into the exact same issue. I can provide more details if necessary.

**Comment by Nisha-1212** [comment]
I am working on this issue.

**Comment by Nisha-1212** [comment]
Hi @tgurr 

I am successfully able to download the above mentioned csv file "https://github.com/ckan/ckan/files/8108382/2022_02_06-oberbuergermeisterwahl-stadt-heilbronn-heilbronner-stadtteile.csv" as json format.

You can also check both the log file  datapusher_error.log  and ckan_http.error.log  as well. Might be you are able to understand the reason of 500 internal server error in error log.

**Comment by kowh-ai** [comment]
I'm not sure why the original (problem) CSV file: [2022_02_06-oberbuergermeisterwahl-stadt-heilbronn-heilbronner-stadtteile.csv](https://github.com/ckan/ckan/files/8108382/2022_02_06-oberbuergermeisterwahl-stadt-heilbronn-heilbronner-stadtteile.csv) seems to work now (I've just tested with a new CKAN 2.9.5 install and it works fine) but I will keep this issue open as it can be used in conjunction with PR https://github.com/ckan/ckan/pull/7063

**Comment by tgurr** [comment]
I'm still having this problem with the dataset in question after updating to ckan 2.10.0, error thrown is slightly different but:

```
2023-02-21 14:58:31,972 ERROR [ckan.config.middleware.flask_app] 
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/blueprint.py", line 74, in dump
    dump_to(
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/blueprint.py", line 223, in dump_to
    if len(records) < paginate_by:
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/lazyjson.py", line 46, in method
    return getattr(self._loads(), name)(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/lazyjson.py", line 24, in _loads
    assert self._json_string is not None
AssertionError
```

**Comment by KatiRG** [comment]
I get the same error as well with this test file. It is because of column containing all nulls (col `gebiet-nr`). Deleting this column and re-uploading the CSV allows the JSON to be successfully returned.

This is the error when the null column is included:
```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/blueprint.py", line 71, in dump
    dump_to(
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/blueprint.py", line 217, in dump_to
    if len(records) < paginate_by:
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/lazyjson.py", line 43, in method
    return getattr(self._loads(), name)(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/lazyjson.py", line 22, in _loads
    self._json_dict = loads(self._json_string)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/simplejson/decoder.py", line 396, in raw_decode
    raise TypeError("Input string must be text, not bytes")
TypeError: Input string must be text, not bytes

```
