### ISSUE TITLE
Problem with extension installation

### ISSUE THREAD

**Issue by derw0lf** [ckan/ckan#6728]
**CKAN version**
Verison 2.9.5 (package installation) on Ubuntu 20.04

**Describe the bug**
While extension installation there ist always the follwoing error coming up:
_ImportError: cannot import name 'appdirs' from 'pip._vendor'_

**Steps to reproduce**
Activate virtual environment (source /usr/lib/ckan/default/bin/activate)
Install extension with pip (pip install EXTENSION-NAME)

**Expected behavior**
Extenstion schould be installed

**Additional details**
-

**Comment by frafra** [comment]
It seems that you have problem with your pip. Try to reinstall it.
You can try this if you installed it without your package manager: `python3 -m pip install --upgrade pip`

**Comment by derw0lf** [comment]
Thanks for your help.
I was able to install the ckanext-geoview extension but I had to add it manually directly from git because I got a syntax error when starting the one from repository.
Now I added the ""geojson_view" plugin in the ckan.ini but nothing happens to my geojson-file.
Any Idea?

**Comment by derw0lf** [comment]
So I tried a fresh install of CKAN on Ubuntu 20.04 directly with the official documentation (http://docs.ckan.org/en/2.9/maintaining/installing/install-from-package.html)
Directly after the installation of CKAN (everything up and running) I tried to install the extension "ckanext-geoview" and the following output appears while trying to execute "pip install ckanext-geoview":
`Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 25, in <module>
    from pip._internal.locations import USER_CACHE_DIR, get_src_prefix
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/locations.py", line 19, in <module>
    from pip._internal.utils import appdirs
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/utils/appdirs.py", line 13, in <module>
    from pip._vendor import appdirs as _appdirs
ImportError: cannot import name 'appdirs' from 'pip._vendor' (/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_vendor/__init__.py)`

This seems to be a general problem, isn't it?

**Comment by frafra** [comment]
Have you tried to upgrade pip as suggested?

**Comment by mattsouth** [comment]
Ive hit this issue.  If I try to run the pip upgrade I see:

```
matt@testckan:~$ python3 -m pip install --upgrade pip
/usr/bin/python3: No module named pip
matt@testckan:~$ source /usr/lib/ckan/default/bin/activate
(default) matt@testckan:~$ python3 -m pip install --upgrade pip
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 25, in <module>
    from pip._internal.locations import USER_CACHE_DIR, get_src_prefix
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/locations.py", line 19, in <module>
    from pip._internal.utils import appdirs
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_internal/utils/appdirs.py", line 13, in <module>
    from pip._vendor import appdirs as _appdirs
ImportError: cannot import name 'appdirs' from 'pip._vendor' (/usr/lib/ckan/default/lib/python3.8/site-packages/pip/_vendor/__init__.py)
(default) matt@testckan:~$ deactivate
```

**Comment by Anrecky** [comment]
# **May 18 2022**

In my case, It appears pip not installed or broken in your's server try to install pip on your server (in my case i ran (already in root, sudo)) `apt install python3-pip`. 
After that i did activate my virtual env (`source /usr/lib/ckan/default/bin/activate`), and then i ran `pip install <ckan-extension>` but it gave me an error  `error: invalid command 'bdist_wheel'`. 
So, to fix this 'bdist_wheel' i ran `pip install wheel` and to make sure i did run `pip install --force-reinstall <ckan-extension>`. And it was succeeded!!

Hopefully, if you try these steps you can make it works!


I ran these commands below, and it works:

**Comment by mattsouth** [comment]
Yes this has indeed worked for me.  Many thanks @Anrecky

**Comment by S-mardii** [comment]
`python3 setup.py develop` failed with the error of `https://setuptools.pypa.io/en/latest/deprecated/easy_install.html`

By the way, I get the extension installed with `python3 -m pip install --user -e .`
