### ISSUE TITLE
Error starting CKAN database

### ISSUE THREAD

**Issue by rogermsarmento** [ckan/ckan#6824]
**CKAN version**: 2.9
**Ubuntu version**: 20.04
**Python version**: 3.8.10

**Describe the bug**
I installed 2.9 from package and every time i run the "sudo ckan db init" i get the following error below:

```
dgti@dgti-VirtualBox:/etc/ckan/default$ sudo ckan db init
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 115, in parse_args
    result = super(ExtendableGroup, self).parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 125, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 134, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 55, in __init__
    self.config = ckan_cli.load_config(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/__init__.py", line 120, in load_config
    config_loader = CKANConfigLoader(filename)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/__init__.py", line 24, in __init__
    self._create_config_object()
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/__init__.py", line 52, in _create_config_object
    self._update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/__init__.py", line 36, in _update_config
    options = self.parser.options(self.section)
  File "/usr/lib/python3.8/configparser.py", line 675, in options
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'app:main'
```
Whats happening?
It errors, and I wonder how can I solve this:

**Comment by TomeCirun** [comment]
@rogermsarmento do you have `[app:main]`  in your `.ini` file ?

![image](https://user-images.githubusercontent.com/72216462/165525753-f4ae23e7-2f89-490a-9599-c33630201392.png)

**Comment by rogermsarmento** [comment]
Hi, @TomeCirun 

/etc/ckan/default/ckan.ini was never created. 
Inside the default folder there were these files:

![image](https://user-images.githubusercontent.com/40036396/165527700-26ae6d35-4a04-4bc7-b004-adb950c3471a.png)



ckan.ini is a copy of ckan-uwsgi.ini with some changes.

![image](https://user-images.githubusercontent.com/40036396/165528628-48b75cee-41af-44d1-9f6a-2cb64d16780f.png)



Any idea?
