### ISSUE TITLE
Action status_show has no corresponding auth function

### ISSUE THREAD

**Issue by knudmoeller** [ckan/ckan#6833]
**CKAN version**

2.9.5

**Describe the bug**
The Action-API function `status_show` does not call a corresponding auth function (there is none). This means that, if a plugin _does_ register an auth function for `status_show`, there will be an error when the action is called.

**Steps to reproduce**
* Implement IAuthFunctions in a plugin and add `status_show` to `get_auth_functions()`.
* Call `status_show` as a non-sysadmin user.
* This leads to the exception above.

**Expected behavior**
If a plugin _does_ registers an auth function for `status_show`, I expect it to be called when the action is called.

**Additional details**
Stacktrace:

```
2022-04-28 08:06:19,368 ERROR [ckan.views.api] Action function status_show did not call its auth function
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/api.py", line 292, in action
    result = function(context, request_data)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 511, in wrapped
    raise Exception(
Exception: Action function status_show did not call its auth function
```

Action function:
https://github.com/ckan/ckan/blob/ca537ad25e13320b6fbf91f41031eadc30500f12/ckan/logic/action/get.py#L2406

**Comment by knudmoeller** [comment]
I created a pull request for this: https://github.com/ckan/ckan/pull/6836
