### ISSUE TITLE
Very slow page render when metadata > 2000 words

### ISSUE THREAD

**Issue by atanikan** [ckan/ckan#6842]
**CKAN version**
2.9.5

**System Used**

OS version : Ubuntu 20.04.4 LTS
RAM:    16G RAM
Cores/cpu: 4 CPU single core
Docker Version:          20.10.14

**Describe the bug**

Our requirement is to track the metadata (path of the file and its size) of all files generated through all our projects. We generate ~10k files for each project. This information is captured in the notes section of the dataset using ckanapi.action.resource_create api. 

If the word count is ~3100 words and the number of records/datasets is > 50 the dataset page and all records pages renders at ~ 20-25 seconds.
For >100 records with ~3k words each the application crashes

**Steps to reproduce**

1. git clone git@github.com:ckan/ckan.git
2. git checkout tags/ckan-2.9.5
3. cp contrib/docker/.env.template .env
4. cd contrib/docker
5. docker-compose up -d --build
6. Upload 100 records with 20 file uploads each and ~3000 words in notes

**Expected behavior**
Page renders more quickly

**Additional details**

**Comment by smotornyuk** [comment]
Do you mean, that every page takes around half a minute to load?

**Comment by smotornyuk** [comment]
Here are my results:

CKAN: fresh 2.9.5, no extra plugins
Test data: 100 datasets, each containing 20 resources with 1KB binary upload and 3000 words in the description
Solr: 5.5
PostgreSQL: 11.2

OS version: Arch on v5.17.5 kernel
RAM: 8G RAM
Cores/CPU: Intel i5-8400, 6 cores, 2.8GHz
Docker Version: no docker, running on the host.

Load time:

Homepage(`/`): **174 ms**
Search page(`/dataset`): **344 ms**
Dataset details(`/dataset/<ID>`): **402 ms**
Resource details(`/dataset/<ID>/resource/<ID>`): **106 ms**


The fact that I'm using a host machine and have a different CPU shouldn't make such a big difference. So I suspect that you have problems with your environment or plugins

**Comment by atanikan** [comment]
Yes, I meant every page takes around half a minute. I am using the docker build which comes with the package can you please try it out with that. I am not using any additional plugins other than those which come with the source.

**Comment by atanikan** [comment]
Hello, I missed mentioning that I followed the first 4 steps laid out in the link below. So I do include datapusher and  datastore 

http://docs.ckan.org/en/2.9/maintaining/installing/install-from-docker-compose.html

Thank You once again for helping me with this

**Comment by Zharktas** [comment]
If you are using datapusher and adding your resources one after the other within a short period of time, the container will run out of memory as the datapusher downloads all the files in memory.

**Comment by Zharktas** [comment]
Could you try disabling datapusher to see if it has any affect on performance pin point the actual bottleneck ?

**Comment by atanikan** [comment]
Hello, 

No dice :(
I tried disabling datapusher for ckan 2.9.5 and my new results for 30k words with 5382561 letters in the "notes" field are as bad as before i.e. ~ 25 seconds for page load.

I also tried to scale to 300k words with 48442153 letter in the "notes" field, but the application crashes with java.lang.OutOfMemoryError: Java heap space error 
in solr logs:

```
2022-05-16 05:51:42.137 INFO  (qtp736709391-20) [   x:ckan] o.a.s.u.p.LogUpdateProcessorFactory [ckan]  webapp=/solr path=/update params={commit=true}{} 0 1397
2022-05-16 05:51:42.139 ERROR (qtp736709391-20) [   x:ckan] o.a.s.s.HttpSolrCall null:java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
	at org.apache.solr.servlet.HttpSolrCall.sendError(HttpSolrCall.java:676)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:544)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:361)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:305)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at org.apache.solr.handler.loader.XMLLoader.readDoc(XMLLoader.java:435)
	at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:260)
	at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:188)
	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:68)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:723)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:529)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:361)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:305)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)

2022-05-16 05:51:42.141 WARN  (qtp736709391-20) [   x:ckan] o.e.j.s.ServletHandler Error for /solr/ckan/update/
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at org.apache.solr.handler.loader.XMLLoader.readDoc(XMLLoader.java:435)
	at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:260)
	at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:188)
	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:68)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:723)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:529)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:361)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:305)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
```

Also, I'd really appreciate it if someone can test ckan 2.9.5's solr image updated to the latest version or version 9. Version 6.6.5 has log4shell CVE vulnerabilities. Just updating the base image led to several issues.

**Comment by Zharktas** [comment]
Are every page slow ? Even those which have nothing to do with datasets ? If its only pages which display datasets, you could remove markdown rendering from notes field which is bound to be slow on a large content.  If it's solr that is causing the slowdowns, then you need to build infrastructure for large indexes which is out of scope of core ckan development.
