### ISSUE TITLE
CKAN crashing when adding datastore to ckan.plugins 

### ISSUE THREAD

**Issue by Perla-Al-Haddad** [ckan/ckan#6854]
**CKAN version**
version 2.9.5

**Describe the bug**
I am setting up CKAN with a package install on my Windows 10 using WSL 2.
I ran into a few problems since I was using WSL (mainly setting up solr), but was able to resolve them. Now CKAN is running successfully on http://localhost:5000/. I am able to login as a sysadmin user and add new datasets.

I now want to enable datastore. I am following the steps specified here: https://docs.ckan.org/en/2.8/maintaining/datastore.html#enable-the-plugin

When adding datastore to ckan.plugins
`ckan.plugins = datastore`

ckan crashes and displays the following error:
```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 115, in parse_args
    result = super(ExtendableGroup, self).parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 125, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 134, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 56, in __init__
    self.app = make_app(self.config)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 123, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 165, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 193, in load
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 153, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 177, in update_config
    plugin.update_config(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/plugin.py", line 71, in update_config
    DatastoreBackend.set_active_backend(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/__init__.py", line 90, in set_active_backend
    schema = config.get(u'ckan.datastore.write_url').split(u':')[0]
AttributeError: 'NoneType' object has no attribute 'split'

```
**Steps to reproduce**
Follow the steps described here: 

> https://docs.ckan.org/en/2.9/maintaining/installing/install-from-package.html#installing-ckan-from-package

On a Windows 10 system using WSL 2 with Ubuntu 20.04.

And try to enable datastore by adding datastore to the ckan.plugins in the ckan.ini config file.

ckan.site_url here is set to http://localhost:5000/ and not http://demo.ckan.org.

If installing solr using the following command:
`sudo apt install -y solr-tomcat`
results in this error: 
`System has not been booted with systemd as init system (PID 1). Can't operate.`

systemd must be enabled on WSL.

**Expected behavior**
The ckan process should not crash after we add datastore to ckan.plugins in the ckan.ini config file.
And should not keep crashing wherever we try to run the process again.

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by kowh-ai** [comment]
@Perla-Al-Haddad - Have the *_DATASTORE_* entries in the ini file been updated?

**Comment by Perla-Al-Haddad** [comment]
```
ckan.datastore.write_url = postgresql://ckan_default:pass@localhost/datastore_default
ckan.datastore.read_url = postgresql://datastore_default:pass@localhost/datastore_default
```
I'm guessing you mean those lines, and yes, I ended up following the rest of the instructions even though CKAN was crashing. And once the datastore database was set up, adding datastore to the plugins stopped crashing CKAN. 

The [documentation](https://docs.ckan.org/en/2.9/maintaining/datastore.html) seems to instruct to add datastore to the plugins before setting up the database, and since it was crashing immediately I thought the problem was coming from me getting some of the previous instructions wrong. 

Thank you for your help!
