### ISSUE TITLE
Group page in Basque langugage causes an internal server error

### ISSUE THREAD

**Issue by seitenbau-govdata** [ckan/ckan#6895]
**CKAN version**
2.8.7 and 2.9.5

**Describe the bug**
It looks like the translation for the Basque language has a bug, because the group page in Basque shows an "500 internal server" error.

**Steps to reproduce**
1. Select the language Basque (language key `eu`)
2. Go to the group page (/eu/group)

Link to the demo instance: https://demo.ckan.org/eu/group/

**Expected behavior**
Displays the group page in Basque without causing an error.

**Additional details**

    2022-06-02 17:28:27,848 ERROR [ckan.config.middleware.flask_app] 'izena'
    Traceback (most recent call last):
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/config/middleware/../../views/group.py", line 211, in index
        _get_group_template(u'index_template', group_type), extra_vars)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/lib/base.py", line 151, in render
        return flask_render_template(template_name, **extra_vars)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
        ctx.app,
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
        rv = template.render(context)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
        return original_render(self, *args, **kwargs)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/group/index.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/page.html", line 1, in top-level template code
        {% extends "base.html" %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckanext/harvest/plugin/../templates/base.html", line 1, in top-level template code
        {% ckan_extends %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/base.html", line 106, in top-level template code
        {%- block page %}{% endblock -%}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/page.html", line 19, in block "page"
        {%- block content %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/page.html", line 22, in block "content"
        {% block main_content %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/page.html", line 74, in block "main_content"
        {% block primary %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/page.html", line 87, in block "primary"
        {% block primary_content %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/page.html", line 107, in block "primary_content"
        {% block primary_content_inner %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/group/index.html", line 22, in block "primary_content_inner"
        {% block groups_list %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/group/index.html", line 25, in block "groups_list"
        {% snippet "group/snippets/group_list.html", groups=page.items %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/lib/jinja_extensions.py", line 274, in _call
        return base.render_snippet(*args, **kwargs)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/lib/base.py", line 95, in render_snippet
        output = render(template_name, extra_vars=kw)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/lib/base.py", line 151, in render
        return flask_render_template(template_name, **extra_vars)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
        ctx.app,
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
        rv = template.render(context)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
        return original_render(self, *args, **kwargs)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/group/snippets/group_list.html", line 11, in top-level template code
        {% block group_list %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/group/snippets/group_list.html", line 13, in block "group_list"
        {% block group_list_inner %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/group/snippets/group_list.html", line 15, in block "group_list_inner"
        {% snippet "group/snippets/group_item.html", group=group, position=loop.index %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/lib/jinja_extensions.py", line 274, in _call
        return base.render_snippet(*args, **kwargs)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/lib/base.py", line 95, in render_snippet
        output = render(template_name, extra_vars=kw)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/lib/base.py", line 151, in render
        return flask_render_template(template_name, **extra_vars)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
        ctx.app,
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
        rv = template.render(context)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
        return original_render(self, *args, **kwargs)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/group/snippets/group_item.html", line 16, in top-level template code
        {% block item %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/group/snippets/group_item.html", line 18, in block "item"
        {% block item_inner %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/group/snippets/group_item.html", line 37, in block "item_inner"
        {% block link %}
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/ckan/templates/group/snippets/group_item.html", line 38, in block "link"
        <a href="{{ url }}" title="{{ _('View {name}').format(name=group.display_name) }}" class="media-view">
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/markupsafe/__init__.py", line 213, in format
        return self.__class__(formatter.vformat(self, args, kwargs))
      File "/usr/lib/python3.6/string.py", line 194, in vformat
        result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
      File "/usr/lib/python3.6/string.py", line 234, in _vformat
        obj, arg_used = self.get_field(field_name, args, kwargs)
      File "/usr/lib/python3.6/string.py", line 299, in get_field
        obj = self.get_value(first, args, kwargs)
      File "/usr/lib/python3.6/string.py", line 256, in get_value
        return kwargs[key]
      File "/usr/lib/ckan/env/lib/python3.6/site-packages/markupsafe/__init__.py", line 249, in __getitem__
        return self._kwargs[key]
    KeyError: 'izena'

**Comment by TomeCirun** [comment]
I can't reproduce the error... works fine on both `CKAN 2.9.5 / 2.10`
<img width="840" alt="image" src="https://user-images.githubusercontent.com/72216462/172120849-d3931059-f828-43c5-9e33-50f15514cd73.png">
@seitenbau-govdata

**Comment by amercader** [comment]
@TomeCirun You need to have a group create to replicate the issue.

This is caused by this bad substitution (var names should not be translated): https://github.com/ckan/ckan/blob/c7e946c0b144c1de7157b0cc3f6414ec8927e4c8/ckan/i18n/eu/LC_MESSAGES/ckan.po#L3108 (and there's another one [here](https://github.com/ckan/ckan/blob/c7e946c0b144c1de7157b0cc3f6414ec8927e4c8/ckan/i18n/eu/LC_MESSAGES/ckan.po#L3453))

@seitenbau-govdata I've updated these on Transifex so it will be fixed in the next patch releases when we pull the latest translations.

We use to have a test (or maybe it's the check-po-files command) to flag issues like these, maybe they stopped working
