### ISSUE TITLE
Changing maintainer causes template error on activity stream 'Changes' link

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#6931]
**CKAN version**

2.9

**Describe the bug**

Changing the Maintainer of a dataset will result in a template syntax error when the activity stream is viewed and the 'Changes' link is followed. This is caused by erroneous double commas in `ckan/templates/snippets/changes/maintainer.html`.

**Steps to reproduce**

- Create a public dataset.
- Edit the dataset and change the Maintainer field.
- View the activity stream for the dataset.
- Click the 'Changes' link for the most recent change. This will result in an Internal Server Error

**Additional details**

Stack trace:

    [Thu Jun 23 16:32:48.698225 2022] [:error] [pid 11681] 16:32:48,696 ERROR [ckan.config.middleware.flask_app] invalid syntax for function call expression
    [Thu Jun 23 16:32:48.698244 2022] [:error] [pid 11681] Traceback (most recent call last):
    [Thu Jun 23 16:32:48.698246 2022] [:error] [pid 11681]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    [Thu Jun 23 16:32:48.698249 2022] [:error] [pid 11681]     rv = self.dispatch_request()
    [Thu Jun 23 16:32:48.698251 2022] [:error] [pid 11681]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    [Thu Jun 23 16:32:48.698254 2022] [:error] [pid 11681]     return self.view_functions[rule.endpoint](**req.view_args)
    [Thu Jun 23 16:32:48.698257 2022] [:error] [pid 11681]   File "/mnt/local_data/ckan_venv/src/ckan/ckan/views/dataset.py", line 1154, in changes
    [Thu Jun 23 16:32:48.698259 2022] [:error] [pid 11681]     u'dataset_type': current_pkg_dict[u'type'],
    [Thu Jun 23 16:32:48.698261 2022] [:error] [pid 11681]   File "/mnt/local_data/ckan_venv/src/ckan/ckan/lib/base.py", line 151, in render
    [Thu Jun 23 16:32:48.698264 2022] [:error] [pid 11681]     return flask_render_template(template_name, **extra_vars)
    [Thu Jun 23 16:32:48.698266 2022] [:error] [pid 11681]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/templating.py", line 140, in render_template
    [Thu Jun 23 16:32:48.698269 2022] [:error] [pid 11681]     ctx.app,
    [Thu Jun 23 16:32:48.698271 2022] [:error] [pid 11681]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/templating.py", line 120, in _render
    [Thu Jun 23 16:32:48.698273 2022] [:error] [pid 11681]     rv = template.render(context)
    [Thu Jun 23 16:32:48.698281 2022] [:error] [pid 11681]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    [Thu Jun 23 16:32:48.698283 2022] [:error] [pid 11681]     return self.environment.handle_exception(exc_info, True)
    [Thu Jun 23 16:32:48.698285 2022] [:error] [pid 11681]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    [Thu Jun 23 16:32:48.698288 2022] [:error] [pid 11681]     reraise(exc_type, exc_value, tb)
    [Thu Jun 23 16:32:48.698290 2022] [:error] [pid 11681]   File "/mnt/local_data/ckan_venv/src/ckan/ckan/templates/snippets/changes/maintainer.html", line 5, in template
    [Thu Jun 23 16:32:48.698292 2022] [:error] [pid 11681]     {{ _('Set maintainer of {pkg_link} to {new_maintainer} (previously {old_maintainer})').format(
    [Thu Jun 23 16:32:48.698295 2022] [:error] [pid 11681] TemplateSyntaxError: invalid syntax for function call expression

**Comment by ThrawnCA** [comment]
This appears to be resolved on master by https://github.com/ckan/ckan/commit/fb27f2a42cd9b579e1989271f5ecf1a3f4c4e35d but should be back-ported to 2.9.
