### ISSUE TITLE
USWGI fails to serve app due to circular import

### ISSUE THREAD

**Issue by JVickery-TBS** [ckan/ckan#6976]
**CKAN version**
2.10 / master branch

**Describe the bug**
Serving the app with uwsgi fails due to circular import of ckan.model.user

**Steps to reproduce**
Using the wsgi.py file provided in master, serve the app with uwsgi:
```
uwsgi --master --log-master --http :5001 --socket :8080 --single-interpreter --uid ckan --gid ckan --wsgi-file /path/to/wsgi.py --stats :1717;
```

**Expected behavior**
UWSGI loads the ckan app via the provided wsgi.py script. The ckan app is then accessible from the above http port (5001)

**Additional details**
```
og-ckan-registry | Traceback (most recent call last):
og-ckan-registry |   File "/srv/app/ckan/registry/wsgi.py", line 6, in <module>
og-ckan-registry |     from ckan.config.middleware import make_app
og-ckan-registry |   File "/srv/app/ckan/registry/src/ckan/ckan/config/middleware/__init__.py", line 10, in <module>
og-ckan-registry |     from ckan.config.environment import load_environment
og-ckan-registry |   File "/srv/app/ckan/registry/src/ckan/ckan/config/environment.py", line 14, in <module>
og-ckan-registry |     import ckan.model as model
og-ckan-registry |   File "/srv/app/ckan/registry/src/ckan/ckan/model/__init__.py", line 31, in <module>
og-ckan-registry |     from ckan.model.package import (
og-ckan-registry |   File "/srv/app/ckan/registry/src/ckan/ckan/model/package.py", line 488, in <module>
og-ckan-registry |     from ckan.model import tag
og-ckan-registry |   File "/srv/app/ckan/registry/src/ckan/ckan/model/tag.py", line 19, in <module>
og-ckan-registry |     import ckan.logic
og-ckan-registry |   File "/srv/app/ckan/registry/src/ckan/ckan/logic/__init__.py", line 22, in <module>
og-ckan-registry |     import ckan.authz as authz
og-ckan-registry |   File "/srv/app/ckan/registry/src/ckan/ckan/authz.py", line 15, in <module>
og-ckan-registry |     import ckan.plugins as p
og-ckan-registry |   File "/srv/app/ckan/registry/src/ckan/ckan/plugins/__init__.py", line 3, in <module>
og-ckan-registry |     from ckan.plugins.core import *  # noqa: re-export
og-ckan-registry |   File "/srv/app/ckan/registry/src/ckan/ckan/plugins/core.py", line 20, in <module>
og-ckan-registry |     import ckan.plugins.interfaces as interfaces
og-ckan-registry |   File "/srv/app/ckan/registry/src/ckan/ckan/plugins/interfaces.py", line 18, in <module>
og-ckan-registry |     from ckan.model import User
og-ckan-registry | ImportError: cannot import name 'User' from partially initialized module 'ckan.model' (most likely due to a circular import) (/srv/app/ckan/registry/src/ckan/ckan/model/__init__.py)
```

**Comment by kowh-ai** [comment]
@JVickery-TBS - I just tried this on a CKAN **2.9.5** version I had lying around and it worked fine. Are you able to try 2.9.5?

**Comment by JVickery-TBS** [comment]
@kowh-ai Yes, I do not have an issue with running the earlier releases.

It seems to be this line.
https://github.com/ckan/ckan/blob/master/ckan/plugins/interfaces.py#L18

Changing it from `from ckan.model import User` to `from ckan.model.user import User` has fixed it for me locally.

I am also running python 3.9.2, not sure if that would affect CKAN master?

**Comment by wardi** [comment]
@JVickery-TBS I get the same error when using okfn/docker-ckan against ckan master. Would you submit a PR for this fix?

**Comment by JVickery-TBS** [comment]
@wardi @kowh-ai PR created https://github.com/ckan/ckan/pull/7005

**Comment by kowh-ai** [comment]
PR: https://github.com/ckan/ckan/pull/7005 Merged
