### ISSUE TITLE
Trying to create a new resource for an existing dataset.

### ISSUE THREAD

**Issue by flaviofrancisco** [ckan/ckan#7002]
**CKAN version**
2.9.5

**Describe the bug**
Trying to create a new resource for an existing dataset.

**Steps to reproduce**
curl --location --request POST 'http://localhost/api/action/resource_create' \
--header 'Authorization: xxxxxxxxxxxxxxxxxxxxxxxxxx' \
--form 'package_id="dataset-from-api-ii"' \
--form 'upload=@"/C:/Users/User/Downloads/book.pdf"'

**Expected behavior**
Attach the resource to the existing dataset

**Additional details**
`
Traceback (most recent call last):
  File "/home/flavio/ckan/lib/default/src/ckan/ckan/config/middleware/../../views/api.py", line 292, in action
    result = function(context, request_data)
  File "/home/flavio/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/flavio/ckan/lib/default/src/ckan/ckan/logic/action/create.py", line 319, in resource_create
    _get_action('package_update')(context, pkg_dict)
  File "/home/flavio/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/flavio/ckan/lib/default/src/ckan/ckan/logic/action/update.py", line 337, in package_update
    item.after_update(context, data)
  File "/home/flavio/ckan/lib/default/src/ckanext-doi/ckanext/doi/plugin.py", line 68, in after_update
    xml_dict = build_xml_dict(metadata_dict)
  File "/home/flavio/ckan/lib/default/src/ckanext-doi/ckanext/doi/lib/metadata.py", line 266, in build_xml_dict
    xml_dict['creators'].append(xml_utils.create_contributor(**creator))
  File "/home/flavio/ckan/lib/default/src/ckanext-doi/ckanext/doi/lib/xml_utils.py", line 28, in create_contributor
    raise ValueError('Creator name must be supplied, either as full_name="FamilyName, '
ValueError: Creator name must be supplied, either as full_name="FamilyName, GivenName" or separately as family_name and given_name
2022-08-09 11:19:03,341 INFO  [ckan.config.middleware.flask_app]  500 /api/action/resource_create render time 0.249 seconds
`

**Comment by flaviofrancisco** [comment]
I found the problem. My dataset has no creator name as the error mentioned aboved.
