### ISSUE TITLE
Beaker - Cookie expires installation error on Mac

### ISSUE THREAD

**Issue by MoSHad91** [ckan/ckan#7092]
**CKAN version**
Latest version

**Describe the bug**
I tried to install the CKAN according to the [documentation with docker compose](https://docs.ckan.org/en/latest/maintaining/installing/install-from-docker-compose.html) on Mac and got the following error. 
Mac M1
Docker version 4.12.0

> ckan          | db:5432 - accepting connections
ckan          | Option ckan.requests.timeout is not declared
ckan          | Option ckan.requests.timeout is not declared
ckan          | 2022-09-21 14:56:44,289 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
ckan          | 2022-09-21 14:56:44,289 INFO  [ckan.config.environment] Loading static files from public
ckan          | 2022-09-21 14:56:44,374 WARNI [ckan.common] Option ckan.plugins is not declared
solr          | 2022-09-21 14:56:44.461 INFO  (qtp736709391-21) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={q=*:*&rows=1&wt=json} hits=0 status=0 QTime=2
solr          | 2022-09-21 14:56:44.473 INFO  (qtp736709391-12) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/schema params={wt=schema.xml} status=0 QTime=2
ckan          | 2022-09-21 14:56:44,479 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
db            | 2022-09-21 14:56:44.645 UTC [211] ERROR:  relation "user" does not exist at character 555
db            | 2022-09-21 14:56:44.645 UTC [211] STATEMENT:  SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".fullname AS user_fullname, "user".email AS user_email, "user".apikey AS user_apikey, "user".created AS user_created, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".last_active AS user_last_active, "user".activity_streams_email_notifications AS user_activity_streams_email_notifications, "user".sysadmin AS user_sysadmin, "user".state AS user_state, "user".image_url AS user_image_url, "user".plugin_extras AS user_plugin_extras 
db            | 	FROM "user" 
db            | 	WHERE "user".name = 'default' OR "user".id = 'default' 
db            | 	 LIMIT 1
solr          | 2022-09-21 14:56:44.835 INFO  (qtp736709391-20) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={q=*:*&rows=1&wt=json} hits=0 status=0 QTime=0
solr          | 2022-09-21 14:56:44.839 INFO  (qtp736709391-14) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/schema params={wt=schema.xml} status=0 QTime=0
ckan          | 2022-09-21 14:56:44,843 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
db            | 2022-09-21 14:56:44.937 UTC [213] ERROR:  relation "user" does not exist at character 555
db            | 2022-09-21 14:56:44.937 UTC [213] STATEMENT:  SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".fullname AS user_fullname, "user".email AS user_email, "user".apikey AS user_apikey, "user".created AS user_created, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".last_active AS user_last_active, "user".activity_streams_email_notifications AS user_activity_streams_email_notifications, "user".sysadmin AS user_sysadmin, "user".state AS user_state, "user".image_url AS user_image_url, "user".plugin_extras AS user_plugin_extras 
db            | 	FROM "user" 
db            | 	WHERE "user".name = 'default' OR "user".id = 'default' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:44.982 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:44.982 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.site_title' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:44.993 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:44.993 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.site_logo' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:44.994 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:44.994 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.site_url' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:44.997 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:44.997 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.site_description' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:44.998 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:44.998 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.site_about' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:45.000 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:45.000 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.site_intro_text' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:45.002 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:45.002 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.site_custom_css' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:45.004 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:45.004 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.main_css' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:45.007 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:45.007 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.homepage_style' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:45.009 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:45.009 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'logo_upload' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:45.011 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:45.011 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'clear_logo_upload' 
db            | 	 LIMIT 1
db            | 2022-09-21 14:56:45.013 UTC [215] ERROR:  relation "system_info" does not exist at character 163
db            | 2022-09-21 14:56:45.013 UTC [215] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.main_css' 
db            | 	 LIMIT 1
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/lib/ckan/venv/bin/ckan", line 8, in <module>
ckan          |     sys.exit(ckan())
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
ckan          |     return self.main(*args, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1054, in main
ckan          |     with self.make_context(prog_name, args, **extra) as ctx:
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 920, in make_context
ckan          |     self.parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 116, in parse_args
ckan          |     result = super().parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1613, in parse_args
ckan          |     rest = super().parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1378, in parse_args
ckan          |     value, args = param.handle_parse_result(ctx, opts, args)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2360, in handle_parse_result
ckan          |     value = self.process_value(ctx, value)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2322, in process_value
ckan          |     value = self.callback(ctx, self, value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 126, in _init_ckan_config
ckan          |     _add_ctx_object(ctx, value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 135, in _add_ctx_object
ckan          |     ctx.obj = CtxObject(path)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 56, in __init__
ckan          |     self.app = make_app(self.config)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 29, in make_app
ckan          |     flask_app = make_flask_stack(conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 214, in make_flask_stack
ckan          |     app.wsgi_app = SessionMiddleware(app.wsgi_app, session_opts)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/middleware.py", line 126, in __init__
ckan          |     coerce_session_params(self.options)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 318, in coerce_session_params
ckan          |     opts = verify_rules(params, rules)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 290, in verify_rules
ckan          |     params[key] = verify_options(params[key], types, message)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 281, in verify_options
ckan          |     raise Exception(error)
ckan          | Exception: Cookie expires was not a boolean, datetime, int, or timedelta instance.
ckan exited with code 1

**Steps to reproduce**
I tried **docker-compose up; docker-compose down** over and over again but it didn't work.

**Comment by MoSHad91** [comment]
Dear @kowh-ai,
I considered default as False for **key: beaker.session.cookie_expires**  in the **config_declaration.yaml**, and got another error:

> Option ckan.requests.timeout is not declared
Option ckan.requests.timeout is not declared
2022-09-22 14:01:18,970 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
2022-09-22 14:01:18,970 INFO  [ckan.config.environment] Loading static files from public
2022-09-22 14:01:19,060 WARNI [ckan.common] Option ckan.plugins is not declared
2022-09-22 14:01:19,145 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
2022-09-22 14:01:19,479 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 116, in parse_args
    result = super().parse_args(ctx, args)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 126, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 135, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 56, in __init__
    self.app = make_app(self.config)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 29, in make_app
    flask_app = make_flask_stack(conf)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 214, in make_flask_stack
    app.wsgi_app = SessionMiddleware(app.wsgi_app, session_opts)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/middleware.py", line 126, in __init__
    coerce_session_params(self.options)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 318, in coerce_session_params
    opts = verify_rules(params, rules)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 290, in verify_rules
    params[key] = verify_options(params[key], types, message)
  File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 283, in verify_options
    raise Exception("Empty strings are invalid for: %s" % error)
Exception: Empty strings are invalid for: Cookie domain must be a string.


However, I believe this issue began with the prior merge request: https://github.com/ckan/ckan/pull/7091
Because I changed **config_declaration.yaml** to its original version, I received another error( with False default in cookie_expires ):
> beaker.session.timeout should be an integer.


So in the **beaker.session.timeout** I defined type as int and set the default, 5. It worked, and the issue was addressed!
