### ISSUE TITLE
CKAN w/ docker-compose won't start

### ISSUE THREAD

**Issue by lbam** [ckan/ckan#7120]
**CKAN version**

d199d39d5e225ecbc4ee9c75418009226c7c8571

**Describe the bug**
CKAN fails to start when following the instructions from [Installing CKAN with Docker Compose](https://docs.ckan.org/en/2.9/maintaining/installing/install-from-docker-compose.html).

**Steps to reproduce**

From the installation instructions + the additional instructions listed in `contrib/docker/.env.template`:

```
cd contrib/docker
cp .env.template .env
docker-compose down
docker rmi -f docker_ckan docker_db
docker rmi $(docker images -f dangling=true -q)
docker-compose build
docker-compose up -d
docker-compose restart ckan
```

All containers start, but the `ckan` container runs into an exception and gets stuck in a restart loop.

**Expected behavior**
CKAN runs.

**Additional details**
This is what docker-compose spews out at regular intervals:

```
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/lib/ckan/venv/bin/ckan", line 8, in <module>
ckan          |     sys.exit(ckan())
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
ckan          |     return self.main(*args, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1054, in main
ckan          |     with self.make_context(prog_name, args, **extra) as ctx:
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 920, in make_context
ckan          |     self.parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 116, in parse_args
ckan          |     result = super().parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1613, in parse_args
ckan          |     rest = super().parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1378, in parse_args
ckan          |     value, args = param.handle_parse_result(ctx, opts, args)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2360, in handle_parse_result
ckan          |     value = self.process_value(ctx, value)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2322, in process_value
ckan          |     value = self.callback(ctx, self, value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 126, in _init_ckan_config
ckan          |     _add_ctx_object(ctx, value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 135, in _add_ctx_object
ckan          |     ctx.obj = CtxObject(path)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 56, in __init__
ckan          |     self.app = make_app(self.config)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 29, in make_app
ckan          |     flask_app = make_flask_stack(conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 214, in make_flask_stack
ckan          |     app.wsgi_app = SessionMiddleware(app.wsgi_app, session_opts)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/middleware.py", line 126, in __init__
ckan          |     coerce_session_params(self.options)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 318, in coerce_session_params
ckan          |     opts = verify_rules(params, rules)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 290, in verify_rules
ckan          |     params[key] = verify_options(params[key], types, message)
ckan          |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 281, in verify_options
ckan          |     raise Exception(error)
ckan          | Exception: Cookie expires was not a boolean, datetime, int, or timedelta instance.
ckan exited with code 1
```

**Comment by anthonymobile** [comment]
same here built on M1 mac (tho ckn is an AMD64 image)

**Comment by tino097** [comment]
Yes there is an issue with freshly created `ckan.ini` file

**Comment by anthonymobile** [comment]
i dont see ckan.ini anywhere in `/etc/ckan' (the `docker_ckan_config` volume) only `production.ini` and `who.ini` 


this is the stack log, things seem to start going wrong with the failed query, guessing the db schema never got initialized?

```
ckan        | db:5432 - accepting connections
ckan        | Option ckan.requests.timeout is not declared
ckan        | Option ckan.requests.timeout is not declared
ckan        | 2022-10-06 00:38:52,610 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
ckan        | 2022-10-06 00:38:52,612 INFO  [ckan.config.environment] Loading static files from public
ckan        | 2022-10-06 00:38:53,297 WARNI [ckan.common] Option ckan.plugins is not declared
solr        | 2022-10-06 00:38:53.997 INFO  (qtp736709391-20) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={q=*:*&rows=1&wt=json} hits=0 status=0 QTime=3
solr        | 2022-10-06 00:38:54.017 INFO  (qtp736709391-18) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/schema params={wt=schema.xml} status=0 QTime=4
ckan        | 2022-10-06 00:38:54,043 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
db          | 2022-10-06 00:38:54.370 UTC [199] ERROR:  relation "user" does not exist at character 555
db          | 2022-10-06 00:38:54.370 UTC [199] STATEMENT:  SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".fullname AS user_fullname, "user".email AS user_email, "user".apikey AS user_apikey, "user".created AS user_created, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".last_active AS user_last_active, "user".activity_streams_email_notifications AS user_activity_streams_email_notifications, "user".sysadmin AS user_sysadmin, "user".state AS user_state, "user".image_url AS user_image_url, "user".plugin_extras AS user_plugin_extras
db          | 	FROM "user"
db          | 	WHERE "user".name = 'default' OR "user".id = 'default'
db          | 	 LIMIT 1
solr        | 2022-10-06 00:38:55.678 INFO  (qtp736709391-13) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={q=*:*&rows=1&wt=json} hits=0 status=0 QTime=2
solr        | 2022-10-06 00:38:55.694 INFO  (qtp736709391-16) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/schema params={wt=schema.xml} status=0 QTime=1
ckan        | 2022-10-06 00:38:55,715 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
db          | 2022-10-06 00:38:55.804 UTC [212] ERROR:  relation "user" does not exist at character 555
db          | 2022-10-06 00:38:55.804 UTC [212] STATEMENT:  SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".fullname AS user_fullname, "user".email AS user_email, "user".apikey AS user_apikey, "user".created AS user_created, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".last_active AS user_last_active, "user".activity_streams_email_notifications AS user_activity_streams_email_notifications, "user".sysadmin AS user_sysadmin, "user".state AS user_state, "user".image_url AS user_image_url, "user".plugin_extras AS user_plugin_extras
db          | 	FROM "user"
db          | 	WHERE "user".name = 'default' OR "user".id = 'default'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.845 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.845 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'ckan.site_title'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.856 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.856 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'ckan.site_logo'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.859 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.859 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'ckan.site_url'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.862 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.862 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'ckan.site_description'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.865 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.865 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'ckan.site_about'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.867 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.867 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'ckan.site_intro_text'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.870 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.870 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'ckan.site_custom_css'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.872 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.872 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'ckan.theme'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.875 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.875 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'ckan.homepage_style'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.877 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.877 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'logo_upload'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.879 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.879 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'clear_logo_upload'
db          | 	 LIMIT 1
db          | 2022-10-06 00:38:55.882 UTC [214] ERROR:  relation "system_info" does not exist at character 163
db          | 2022-10-06 00:38:55.882 UTC [214] STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state
db          | 	FROM system_info
db          | 	WHERE system_info.key = 'ckan.theme'
db          | 	 LIMIT 1
ckan        | Traceback (most recent call last):
ckan        |   File "/usr/lib/ckan/venv/bin/ckan", line 8, in <module>
ckan        |     sys.exit(ckan())
ckan        |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
ckan        |     return self.main(*args, **kwargs)
ckan        |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1054, in main
ckan        |     with self.make_context(prog_name, args, **extra) as ctx:
ckan        |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 920, in make_context
ckan        |     self.parse_args(ctx, args)
ckan        |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 116, in parse_args
ckan        |     result = super().parse_args(ctx, args)
ckan        |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1613, in parse_args
ckan        |     rest = super().parse_args(ctx, args)
ckan        |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 1378, in parse_args
ckan        |     value, args = param.handle_parse_result(ctx, opts, args)
ckan        |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2360, in handle_parse_result
ckan        |     value = self.process_value(ctx, value)
ckan        |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/click/core.py", line 2322, in process_value
ckan        |     value = self.callback(ctx, self, value)
ckan        |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 126, in _init_ckan_config
ckan        |     _add_ctx_object(ctx, value)
ckan        |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 135, in _add_ctx_object
ckan        |     ctx.obj = CtxObject(path)
ckan        |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 56, in __init__
ckan        |     self.app = make_app(self.config)
ckan        |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 29, in make_app
ckan        |     flask_app = make_flask_stack(conf)
ckan        |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 214, in make_flask_stack
ckan        |     app.wsgi_app = SessionMiddleware(app.wsgi_app, session_opts)
ckan        |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/middleware.py", line 126, in __init__
ckan        |     coerce_session_params(self.options)
ckan        |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 318, in coerce_session_params
ckan        |     opts = verify_rules(params, rules)
ckan        |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 290, in verify_rules
ckan        |     params[key] = verify_options(params[key], types, message)
ckan        |   File "/usr/lib/ckan/venv/lib/python3.8/site-packages/beaker/util.py", line 281, in verify_options
ckan        |     raise Exception(error)
ckan        | Exception: Cookie expires was not a boolean, datetime, int, or timedelta instance.
ckan exited with code 1
```

**Comment by kowh-ai** [comment]
> is this whole install method out of date then? what creates `production.ini` / `ckan.ini` ? not sure where to start updating this

no, just broken at the moment. Same issue as installing CKAN (Master) from source

**Comment by kowh-ai** [comment]
> for anyone who ends here looking for an immediate solution to just test, suggest checking out earlier version (i went back to 2.9.5 and it worked fine) before building
> 
> ```
> git clone https://github.com/ckan/ckan.git
> git checkout tags/ckan-2.9.5
> docker compose up -d --build
> ```

Another workaround option is to create a pre-configured `production.ini` file and copy it into the CKAN image via the CKAN Dockerfile. The `ckan-entrypoint.sh` script won't override this file if it exists

…
`RUN cp -v $CKAN_VENV/src/ckan/contrib/docker/production.ini /etc/ckan/production.ini`
...
The Make sure the ckan config volume (docker_ckan_config)  has been deleted before running a new build

**Comment by djk2** [comment]
Hi. 
I had the same issue,  when I switched to `tags/ckan-2.9.5` now I have a problem with migrations. 
```
ckan_1        | ProgrammingError: (psycopg2.errors.UndefinedTable) relation "group" does not exist
ckan_1        | LINE 2: FROM "group" 
```
When I go to inside docker and run manually `ckan-entrypoint.sh`
I got 
```
postgres:5432 - accepting connections
2022-10-11 09:54:00,723 INFO  [ckan.cli] Using configuration file /etc/ckan/production.ini
2022-10-11 09:54:00,723 INFO  [ckan.config.environment] Loading static files from public
2022-10-11 09:54:00,754 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
2022-10-11 09:54:00,962 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
2022-10-11 09:54:01,122 INFO  [ckan.cli.db] Initialize the Database
Can't locate revision identified by 'deb4c9d4a4ef'
```
How I can solve the problem?
