### ISSUE TITLE
DataPusher URL required to run CKAN without DataPusher

### ISSUE THREAD

**Issue by stefina** [ckan/ckan#7214]
**CKAN version**
2.9.7

**Describe the bug**
We are running the default [docker-setup](https://github.com/okfn/docker-ckan) and disabled and removed datapusher from `ckan.plugins` because we are using xloader. 
We are getting this error when starting the app because we also removed it from the [.env](https://github.com/okfn/docker-ckan/blob/master/.env.example#L27):
```
Exception: Config option `ckan.datapusher.url` must be set to use the DataPusher.
```
After some debugging to see why it seems to be activated, though we don't want it to be, we found this:
https://github.com/ckan/ckan/blob/2.9/setup.py#L55

We saw that those lines are removed in master, but they seem to be moved here:
https://github.com/ckan/ckan/blob/master/setup.cfg#L47

We are guessing this is to be able to run datapusher via cli, but are wondering if it is planned to remove it from ckan-cli? I seems odd to us that it is required, even though the user is not using the plugin. Also giving us false hope being able to enable/disable it via `ckan.plugins` ;)

**Steps to reproduce**
- run CKAN with the default [docker-setup](https://github.com/okfn/docker-ckan)
- remove from [this line](https://github.com/okfn/docker-ckan/blob/master/.env.example#L27) from .env
- remove `datapusher` from [this line](https://github.com/okfn/docker-ckan/blob/master/.env.example#L44)

**Expected behavior**
CKAN starts up without errors

**Additional details**
```
Traceback (most recent call last):
  File "/usr/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python2.7/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/srv/app/src_extensions/ckan/ckan/cli/cli.py", line 115, in parse_args
    result = super(ExtendableGroup, self).parse_args(ctx, args)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/srv/app/src_extensions/ckan/ckan/cli/cli.py", line 125, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/srv/app/src_extensions/ckan/ckan/cli/cli.py", line 134, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/srv/app/src_extensions/ckan/ckan/cli/cli.py", line 56, in __init__
    self.app = make_app(self.config)
  File "/srv/app/src_extensions/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
    load_environment(conf)
  File "/srv/app/src_extensions/ckan/ckan/config/environment.py", line 123, in load_environment
    p.load_all()
  File "/srv/app/src_extensions/ckan/ckan/plugins/core.py", line 165, in load_all
    load(*plugins)
  File "/srv/app/src_extensions/ckan/ckan/plugins/core.py", line 193, in load
    plugins_update()
  File "/srv/app/src_extensions/ckan/ckan/plugins/core.py", line 153, in plugins_update
    environment.update_config()
  File "/srv/app/src_extensions/ckan/ckan/config/environment.py", line 309, in update_config
    plugin.configure(config)
  File "/srv/app/src_extensions/ckan/ckanext/datapusher/plugin.py", line 65, in configure
    format(config_option)
Exception: Config option `ckan.datapusher.url` must be set to use the DataPusher.
```

**Comment by kowh-ai** [comment]
@stefina The  [docker-setup](https://github.com/okfn/docker-ckan) you have used is not this CKAN repo. It's the OKFN repo. Are you able to post this issue there?

**Comment by stefina** [comment]
Thanks for getting back to me so quickly @kowh-ai !
Yes, the setup is from OKFN, but as far as our investigation went, we have not found a possibility to "fix" this from the OKFN-repo. The root, it looks for us, seems to be there:
https://github.com/ckan/ckan/blob/2.9/setup.py#L55
But if you see a way for us to configure this otherwise, we would be happy to hear it :)

**Comment by amercader** [comment]
@stefina this seems like an issue with the docker setup not refreshing the plugins configuration correctly rather than an issue with how Datapusher is registered.
The lines you point to in setup.py just register the click command, they don't activate the plugin.
This line:
```
  File "/srv/app/src_extensions/ckan/ckanext/datapusher/plugin.py", line 65, in configure
    format(config_option)
```
implies that the `datapusher` plugin is activated. Have you tried removing the container (`docker-compose rm ckan-dev`) after chaging the `.env` file?
I'll have a play myself to see if I can replicate it, but this definitely doesn't feel like a CKAN core issue

**Comment by kowh-ai** [comment]
@stefina - I have just installed CKAN via the OKFN repo (`docker-compose -f docker-compose.dev.yml up --build`) and I **don't** get the error. Have you tried removing the datapusher service from the compose yaml file? As a last resort are you able to try  removing all containers, images, volumes and network(s) plus pruning any dangling (unassigned) images?

**Comment by kowh-ai** [comment]
Sorry to hear that @stefina -- FYI: I used the Python3 image when testing
