### ISSUE TITLE
Error resetting password when ckan.auth.public_user_details is false

### ISSUE THREAD

**Issue by EricSoroos** [ckan/ckan#7264]
**CKAN version**
2.9.x

**Describe the bug**
If `ckan.auth.public_user_details` is false, users can't reset their password. 

```
2022-12-06 12:46:49,489 ERROR [ckan.config.middleware.flask_app] Action user_show requires an authenticated user
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/views/user.py", line 767, in get
    context, user_dict = self._prepare(id)
  File "/usr/lib/ckan/default/src/ckan/ckan/views/user.py", line 699, in _prepare
    user_dict = logic.get_action(u'user_show')(context, {u'id': id})
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 1422, in user_show
    _check_access('user_show', context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 313, in check_access
    raise NotAuthorized(msg)
NotAuthorized: Action user_show requires an authenticated user
```

**Steps to reproduce**

* Turn off ckan.auth.public_user_details
* Visit the reset password page, when not logged in, request a reset
* Follow the link. 500 error.

**Comment by sagargg** [comment]
This remains an issue, even in CKAN 2.10.1.

**Comment by markstuart** [comment]
There seem to be a number of Github issues around this, I've [commented here](https://github.com/ckan/ckan/issues/5185#issuecomment-1765365973) with what I've found when debugging this issue.
