### ISSUE TITLE
Activity new_resource.html snippet missing dataset_type and unable to build urls

### ISSUE THREAD

**Issue by pdekraker-epa** [ckan/ckan#7272]
**CKAN version**
master

**Describe the bug**
In the activity extension the snippets/changes/new_resource.html requires a `dataset_type` to generate proper urls. It crashes trying to _incorrectly_ build the url for endpoint `activity.read`. Looking at the snippet it tries to determine the `package_type` from `request.view_args.package_type`, but it does not contain the needed information and the `dataset_type` is then set to 'activity' leading to the exception.

**Steps to reproduce**

1. Create dataset
2. Add a resource to the dataset
3. View activity stream
4. click on Changes link corresponding to the change where the resource was added

**Expected behavior**
It should show the message that the resource was added, with the appropriate links to the resource and package

**Additional details**
I encountered this issue while using a variety of extensions including scheming, but do not believe they are a factor

```
  File "/mnt/c/Users/pdekraker.NVFEL/ckan_projects/ckan29/src/ckan/ckanext/activity/templates/package/snippets/change_item.html", line 6, in top-level template code
    {% snippet "snippets/changes/{}.html".format(
  File "/mnt/c/Users/pdekraker.NVFEL/ckan_projects/ckan29/src/ckan/ckan/lib/jinja_extensions.py", line 277, in _call
    return base.render_snippet(*args, **kwargs)
  File "/mnt/c/Users/pdekraker.NVFEL/ckan_projects/ckan29/src/ckan/ckan/lib/base.py", line 72, in render_snippet
    output = render(template_name, extra_vars=kw)
  File "/mnt/c/Users/pdekraker.NVFEL/ckan_projects/ckan29/src/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/pdekraker.NVFEL/ckan_projects/ckan29/src/ckan/ckanext/activity/templates/snippets/changes/new_resource.html", line 2, in top-level template code
    {% set pkg_url = h.url_for(dataset_type ~ '.read', id=change.pkg_id) %}
  File "/mnt/c/Users/pdekraker.NVFEL/ckan_projects/ckan29/src/ckan/ckan/lib/helpers.py", line 385, in url_for
    my_url = _url_for_flask(*args, **kw)
  File "/mnt/c/Users/pdekraker.NVFEL/ckan_projects/ckan29/src/ckan/ckan/lib/helpers.py", line 443, in _url_for_flask
    my_url = _flask_default_url_for(*args, **kw)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/usr/lib/ckan/default/lib/python3.9/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'activity.read' with values ['id']. Did you mean 'harvest.read' instead?
```

**Comment by pdekraker-epa** [comment]
I noticed that #7143 involves changes to the activity stream not sure if it will correct this issue as well

**Comment by paulmueller** [comment]
This issue is still present in CKAN 2.10.1:

<details>

```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/ckan/default/src/ckan/ckanext/activity/views.py", line 404, in package_changes
    return tk.render(
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/ckan/default/src/ckan/ckanext/activity/templates/package/changes.html", line 1, in top-level template code
    {% extends "package/base.html" %}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/package/base.html", line 4, in top-level template code
    {% set dataset_type = dataset_type or pkg.type or 'dataset' %}
  File "/usr/lib/ckan/default/src/ckan/ckanext/activity/templates/page.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/lib/ckan/default/src/ckan/ckanext/activity/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/ckanext/dcor_schemas/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/ckanext/dcor_theme/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/base.html", line 108, in top-level template code
    {%- block page %}{% endblock -%}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/page.html", line 19, in block 'page'
    {%- block content %}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/page.html", line 22, in block 'content'
    {% block main_content %}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/page.html", line 74, in block 'main_content'
    {% block primary %}
  File "/usr/lib/ckan/default/src/ckan/ckanext/activity/templates/package/changes.html", line 43, in block 'primary'
    {% snippet "package/snippets/change_item.html", activity_diff=activity_diffs[i], pkg_dict=pkg_dict %}
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/jinja_extensions.py", line 277, in _call
    return base.render_snippet(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 72, in render_snippet
    output = render(template_name, extra_vars=kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/ckan/default/src/ckan/ckanext/activity/templates/package/snippets/change_item.html", line 6, in top-level template code
    {% snippet "snippets/changes/{}.html".format(
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/jinja_extensions.py", line 277, in _call
    return base.render_snippet(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 72, in render_snippet
    output = render(template_name, extra_vars=kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/ckan/default/src/ckan/ckanext/activity/templates/snippets/changes/new_resource.html", line 2, in top-level template code
    {% set pkg_url = h.url_for(dataset_type ~ '.read', id=change.pkg_id) %}
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 385, in url_for
    my_url = _url_for_flask(*args, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 443, in _url_for_flask
    my_url = _flask_default_url_for(*args, **kw)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'activity.read' with values ['id']. Did you mean 'dataset.read' instead?
```

</details>
