### ISSUE TITLE
Webassets -> ValueError: Cannot determine url for

### ISSUE THREAD

**Issue by ChristianF88** [ckan/ckan#7369]
## CKAN version
2.9.7

**other versions of my source install:**

   "version_postgresql": "15",
   "version_postgis": "3",
   "version_solr": "8.11.2",
   "version_python": "3.9.13"

## Describe the bug
One of the extensions (https://github.com/eawag-rdm/ckanext-eaw_schema/tree/int_rel2) I use, is changing the schema and it is throwing an error, when trying to load the webpage. The webpage returns bad gateway, the stacktrace is below.

```ini
ckan.plugins = stats text_view image_view recline_view datastore xloader spatial_metadata spatial_query eaw_helpers eaw_theme eaw_schema scheming_datasets scheming_organizations hierarchy_display repeating
```

Curiously it used to work without any issues, it stopped working when I set up a new VM with the same installation procedure as before.

I checked the extension's code ([webassets.yaml](https://github.com/eawag-rdm/ckanext-eaw_schema/blob/int_rel2/ckanext/eaw_schema/assets/webassets.yml), .[add_resource in plugin](https://github.com/eawag-rdm/ckanext-eaw_schema/blob/06d0818026b37c64a9ddbaa3224caeff2018535f/ckanext/eaw_schema/plugin.py#L559), [asset in template](https://github.com/eawag-rdm/ckanext-eaw_schema/blob/06d0818026b37c64a9ddbaa3224caeff2018535f/ckanext/eaw_schema/templates/base.html#L5), project structure). Everything seems good to me. Does anyone have any ideas?

I have figured out that the webassets library (last function call in stacktrace) is not looking for the **assets** folder but for the **public** folder.  

### Steps to reproduce
Run a source install with all the plugins mentioned above.

### Expected behavior
Webassets should find the right folder, the website shouldn't crash... Everything ought to work.

### Additional details

**Stacktrace**
```
Jan 31 13:39:34 ckan bash[1418]: Traceback (most recent call last):
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
Jan 31 13:39:34 ckan bash[1418]:     rv = self.dispatch_request()
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
Jan 31 13:39:34 ckan bash[1418]:     return self.view_functions[rule.endpoint](**req.view_args)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/home.py", line 67, in index
Jan 31 13:39:34 ckan bash[1418]:     return base.render(u'home/index.html', extra_vars={})
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 151, in render
Jan 31 13:39:34 ckan bash[1418]:     return flask_render_template(template_name, **extra_vars)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
Jan 31 13:39:34 ckan bash[1418]:     return _render(
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
Jan 31 13:39:34 ckan bash[1418]:     rv = template.render(context)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/asyncsupport.py", line 76, in render
Jan 31 13:39:34 ckan bash[1418]:     return original_render(self, *args, **kwargs)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/environment.py", line 1008, in render
Jan 31 13:39:34 ckan bash[1418]:     return self.environment.handle_exception(exc_info, True)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/environment.py", line 780, in handle_exception
Jan 31 13:39:34 ckan bash[1418]:     reraise(exc_type, exc_value, tb)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/_compat.py", line 37, in reraise
Jan 31 13:39:34 ckan bash[1418]:     raise value.with_traceback(tb)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/templates/home/index.html", line 2, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% set homepage_style = ( g.homepage_style or '1' ) %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/templates/page.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% extends "base.html" %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_theme/ckanext/eaw_theme/templates/base.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% ckan_extends %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_schema/ckanext/eaw_schema/templates/base.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% ckan_extends %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/templates/base.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% ckan_extends %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/templates/base.html", line 68, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {%- block styles %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_theme/ckanext/eaw_theme/templates/base.html", line 6, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {{ super() }}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_schema/ckanext/eaw_schema/templates/base.html", line 5, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% asset 'eaw_schema_assets/eaw_schema-css' %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/lib/jinja_extensions.py", line 352, in _call
Jan 31 13:39:34 ckan bash[1418]:     h.include_asset(args[0])
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/lib/webassets_tools.py", line 109, in include_asset
Jan 31 13:39:34 ckan bash[1418]:     urls = [url_for_static_or_external(url) for url in bundle.urls()]
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 806, in urls
Jan 31 13:39:34 ckan bash[1418]:     urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 764, in _urls
Jan 31 13:39:34 ckan bash[1418]:     self._build(ctx, extra_filters=extra_filters, force=False,
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 617, in _build
Jan 31 13:39:34 ckan bash[1418]:     hunk = self._merge_and_apply(
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 542, in _merge_and_apply
Jan 31 13:39:34 ckan bash[1418]:     hunk = filtertool.apply(hunk, filters_to_run, 'input',
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/merge.py", line 276, in apply
Jan 31 13:39:34 ckan bash[1418]:     return self._wrap_cache(key, func)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/merge.py", line 218, in _wrap_cache
Jan 31 13:39:34 ckan bash[1418]:     content = func().getvalue()
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/merge.py", line 251, in func
Jan 31 13:39:34 ckan bash[1418]:     getattr(filter, type)(data, out, **kwargs_final)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/filter/cssrewrite/__init__.py", line 76, in input
Jan 31 13:39:34 ckan bash[1418]:     return super(CSSRewrite, self).input(_in, out, **kw)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/filter/cssrewrite/base.py", line 77, in input
Jan 31 13:39:34 ckan bash[1418]:     self.source_url = self.ctx.resolver.resolve_source_to_url(
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/env.py", line 279, in resolve_source_to_url
Jan 31 13:39:34 ckan bash[1418]:     return self.query_url_mapping(ctx, filepath)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/env.py", line 217, in query_url_mapping
Jan 31 13:39:34 ckan bash[1418]:     raise ValueError('Cannot determine url for %s' % filepath)
Jan 31 13:39:34 ckan bash[1418]: ValueError: Cannot determine url for /usr/lib/ckan/default/src/ckanext-eaw_schema/ckanext/eaw_schema/assets/css/eaw_schema.css
Jan 31 13:39:34 ckan bash[1418]: During handling of the above exception, another exception occurred:
Jan 31 13:39:34 ckan bash[1418]: Traceback (most recent call last):
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
Jan 31 13:39:34 ckan bash[1418]:     response = self.full_dispatch_request()
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
Jan 31 13:39:34 ckan bash[1418]:     rv = self.handle_user_exception(e)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
Jan 31 13:39:34 ckan bash[1418]:     return handler(e)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 568, in error_handler
Jan 31 13:39:34 ckan bash[1418]:     return base.render(u'error_document_template.html', extra_vars), 500
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 151, in render
Jan 31 13:39:34 ckan bash[1418]:     return flask_render_template(template_name, **extra_vars)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
Jan 31 13:39:34 ckan bash[1418]:     return _render(
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
Jan 31 13:39:34 ckan bash[1418]:     rv = template.render(context)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/asyncsupport.py", line 76, in render
Jan 31 13:39:34 ckan bash[1418]:     return original_render(self, *args, **kwargs)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/environment.py", line 1008, in render
Jan 31 13:39:34 ckan bash[1418]:     return self.environment.handle_exception(exc_info, True)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/environment.py", line 780, in handle_exception
Jan 31 13:39:34 ckan bash[1418]:     reraise(exc_type, exc_value, tb)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/_compat.py", line 37, in reraise
Jan 31 13:39:34 ckan bash[1418]:     raise value.with_traceback(tb)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/templates/error_document_template.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% extends "page.html" %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/templates/page.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% extends "base.html" %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_theme/ckanext/eaw_theme/templates/base.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% ckan_extends %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_schema/ckanext/eaw_schema/templates/base.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% ckan_extends %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/templates/base.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% ckan_extends %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/templates/base.html", line 68, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {%- block styles %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_theme/ckanext/eaw_theme/templates/base.html", line 6, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {{ super() }}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_schema/ckanext/eaw_schema/templates/base.html", line 5, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% asset 'eaw_schema_assets/eaw_schema-css' %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/lib/jinja_extensions.py", line 352, in _call
Jan 31 13:39:34 ckan bash[1418]:     h.include_asset(args[0])
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/lib/webassets_tools.py", line 109, in include_asset
Jan 31 13:39:34 ckan bash[1418]:     urls = [url_for_static_or_external(url) for url in bundle.urls()]
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 806, in urls
Jan 31 13:39:34 ckan bash[1418]:     urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 764, in _urls
Jan 31 13:39:34 ckan bash[1418]:     self._build(ctx, extra_filters=extra_filters, force=False,
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 617, in _build
Jan 31 13:39:34 ckan bash[1418]:     hunk = self._merge_and_apply(
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 542, in _merge_and_apply
Jan 31 13:39:34 ckan bash[1418]:     hunk = filtertool.apply(hunk, filters_to_run, 'input',
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/merge.py", line 276, in apply
Jan 31 13:39:34 ckan bash[1418]:     return self._wrap_cache(key, func)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/merge.py", line 218, in _wrap_cache
Jan 31 13:39:34 ckan bash[1418]:     content = func().getvalue()
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/merge.py", line 251, in func
Jan 31 13:39:34 ckan bash[1418]:     getattr(filter, type)(data, out, **kwargs_final)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/filter/cssrewrite/__init__.py", line 76, in input
Jan 31 13:39:34 ckan bash[1418]:     return super(CSSRewrite, self).input(_in, out, **kw)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/filter/cssrewrite/base.py", line 77, in input
Jan 31 13:39:34 ckan bash[1418]:     self.source_url = self.ctx.resolver.resolve_source_to_url(
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/env.py", line 279, in resolve_source_to_url
Jan 31 13:39:34 ckan bash[1418]:     return self.query_url_mapping(ctx, filepath)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/env.py", line 217, in query_url_mapping
Jan 31 13:39:34 ckan bash[1418]:     raise ValueError('Cannot determine url for %s' % filepath)
Jan 31 13:39:34 ckan bash[1418]: ValueError: Cannot determine url for /usr/lib/ckan/default/src/ckanext-eaw_schema/ckanext/eaw_schema/assets/css/eaw_schema.css
Jan 31 13:39:34 ckan bash[1418]: During handling of the above exception, another exception occurred:
Jan 31 13:39:34 ckan bash[1418]: Traceback (most recent call last):
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 66, in __call__
Jan 31 13:39:34 ckan bash[1418]:     return self.app(environ, start_response)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py", line 114, in __call__
Jan 31 13:39:34 ckan bash[1418]:     return self.app(environ, start_response)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/repoze/who/middleware.py", line 86, in __call__
Jan 31 13:39:34 ckan bash[1418]:     app_iter = app(environ, wrapper.wrap_start_response)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/fanstatic/publisher.py", line 224, in __call__
Jan 31 13:39:34 ckan bash[1418]:     return self.app(environ, start_response)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/fanstatic/injector.py", line 64, in __call__
Jan 31 13:39:34 ckan bash[1418]:     response = request.get_response(self.app)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webob/request.py", line 1313, in send
Jan 31 13:39:34 ckan bash[1418]:     status, headers, app_iter = self.call_application(
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webob/request.py", line 1278, in call_application
Jan 31 13:39:34 ckan bash[1418]:     app_iter = application(self.environ, start_response)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/app.py", line 2463, in __call__
Jan 31 13:39:34 ckan bash[1418]:     return self.wsgi_app(environ, start_response)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/beaker/middleware.py", line 156, in __call__
Jan 31 13:39:34 ckan bash[1418]:     return self.wrap_app(environ, session_start_response)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py", line 58, in __call__
Jan 31 13:39:34 ckan bash[1418]:     return self.app(environ, start_response)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/app.py", line 2449, in wsgi_app
Jan 31 13:39:34 ckan bash[1418]:     response = self.handle_exception(e)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/app.py", line 1878, in handle_exception
Jan 31 13:39:34 ckan bash[1418]:     server_error = handler(server_error)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 564, in error_handler
Jan 31 13:39:34 ckan bash[1418]:     return base.render(
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 151, in render
Jan 31 13:39:34 ckan bash[1418]:     return flask_render_template(template_name, **extra_vars)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
Jan 31 13:39:34 ckan bash[1418]:     return _render(
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
Jan 31 13:39:34 ckan bash[1418]:     rv = template.render(context)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/asyncsupport.py", line 76, in render
Jan 31 13:39:34 ckan bash[1418]:     return original_render(self, *args, **kwargs)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/environment.py", line 1008, in render
Jan 31 13:39:34 ckan bash[1418]:     return self.environment.handle_exception(exc_info, True)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/environment.py", line 780, in handle_exception
Jan 31 13:39:34 ckan bash[1418]:     reraise(exc_type, exc_value, tb)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/jinja2/_compat.py", line 37, in reraise
Jan 31 13:39:34 ckan bash[1418]:     raise value.with_traceback(tb)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/templates/error_document_template.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% extends "page.html" %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/templates/page.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% extends "base.html" %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_theme/ckanext/eaw_theme/templates/base.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% ckan_extends %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_schema/ckanext/eaw_schema/templates/base.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% ckan_extends %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/templates/base.html", line 1, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% ckan_extends %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/templates/base.html", line 68, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {%- block styles %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_theme/ckanext/eaw_theme/templates/base.html", line 6, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {{ super() }}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckanext-eaw_schema/ckanext/eaw_schema/templates/base.html", line 5, in <module>
Jan 31 13:39:34 ckan bash[1418]:     {% asset 'eaw_schema_assets/eaw_schema-css' %}
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/lib/jinja_extensions.py", line 352, in _call
Jan 31 13:39:34 ckan bash[1418]:     h.include_asset(args[0])
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/lib/webassets_tools.py", line 109, in include_asset
Jan 31 13:39:34 ckan bash[1418]:     urls = [url_for_static_or_external(url) for url in bundle.urls()]
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 806, in urls
Jan 31 13:39:34 ckan bash[1418]:     urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 764, in _urls
Jan 31 13:39:34 ckan bash[1418]:     self._build(ctx, extra_filters=extra_filters, force=False,
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 617, in _build
Jan 31 13:39:34 ckan bash[1418]:     hunk = self._merge_and_apply(
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/bundle.py", line 542, in _merge_and_apply
Jan 31 13:39:34 ckan bash[1418]:     hunk = filtertool.apply(hunk, filters_to_run, 'input',
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/merge.py", line 276, in apply
Jan 31 13:39:34 ckan bash[1418]:     return self._wrap_cache(key, func)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/merge.py", line 218, in _wrap_cache
Jan 31 13:39:34 ckan bash[1418]:     content = func().getvalue()
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/merge.py", line 251, in func
Jan 31 13:39:34 ckan bash[1418]:     getattr(filter, type)(data, out, **kwargs_final)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/filter/cssrewrite/__init__.py", line 76, in input
Jan 31 13:39:34 ckan bash[1418]:     return super(CSSRewrite, self).input(_in, out, **kw)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/filter/cssrewrite/base.py", line 77, in input
Jan 31 13:39:34 ckan bash[1418]:     self.source_url = self.ctx.resolver.resolve_source_to_url(
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/env.py", line 279, in resolve_source_to_url
Jan 31 13:39:34 ckan bash[1418]:     return self.query_url_mapping(ctx, filepath)
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/lib/python3.9/site-packages/webassets/env.py", line 217, in query_url_mapping
Jan 31 13:39:34 ckan bash[1418]:     raise ValueError('Cannot determine url for %s' % filepath)
Jan 31 13:39:34 ckan bash[1418]: ValueError: Cannot determine url for /usr/lib/ckan/default/src/ckanext-eaw_schema/ckanext/eaw_schema/assets/css/eaw_schema.css
Jan 31 13:39:34 ckan bash[1418]: [pid: 1418|app: 0|req: 23/23] 127.0.0.1 () {34 vars in 502 bytes} [Tue Jan 31 13:39:33 2023] GET / => generated 0 bytes in 97 msecs (HTTP/1.0 500) 0 headers in 0 bytes (0 switches on core 0)
```

**Comment by ChristianF88** [comment]
The bundle (part of the stacktrace) looks good also
```
Jan 31 13:39:34 ckan bash[1418]:   File "/usr/lib/ckan/default/src/ckan/ckan/lib/webassets_tools.py", line 109, in include_asset
Jan 31 13:39:34 ckan bash[1418]:     urls = [url_for_static_or_external(url) for url in bundle.urls()]
```

I added a `print(bundle)` before that list comprehension:

```
<Bundle output=eaw_schema_assets/%(version)s_eaw_schema.css, filters=[<webassets.filter.cssrewrite.CSSRewrite object at 0x7f4786b651c0>], contents=('css/eaw_schema.css',)>
```

**Comment by spwoodcock** [comment]
I can't reproduce the bad gateway error with your extension installed, but do see an errors logged on page load:
```
2023-02-02 04:30:37,571.571 [ERROR] ckan.lib.webassets_tools | include_asset:94 | Trying to include unknown asset: <eaw_schema_assets/eaw_schema-js>

2023-02-02 04:30:37,290.290 [ERROR] ckan.lib.webassets_tools | include_asset:94 | Trying to include unknown asset: <eaw_schema_assets/eaw_schema-css>
```

I feel the issue is somehow related to the MANIFEST.in in the root of your extension repo: https://github.com/eawag-rdm/ckanext-eaw_schema/blob/int_rel2/MANIFEST.in

Perhaps update it on the branch & try loading the extension again:
```
include README.rst
recursive-include ckanext *.html *.json *.js *.less *.css *.yaml *.yml *.png
```

**Comment by ChristianF88** [comment]
Thanks, for getting back straight away. Unfortunately, changing the `MANIFEST.in` didn't have any effect. I'll keep you up to date, once I manage to fix it.

**Comment by ChristianF88** [comment]
I ended up creating a new extension for the latest CKAN version 2.10.0, copy pasting my code and updating it where needed. now it works

**Comment by spwoodcock** [comment]
Funnily enough I am getting the same error for some older plugins we use on CKAN 2.9 (in particular ckanext-hierarchy).
I use a version of 2.9 frozen at commit 4b61dd17ad3edba41f4419737548363f8932db8e (Jan 2023).

```
2023-04-18 09:58:34,313.313 [ERROR] ckan.lib.webassets_tools | include_asset:94 | Trying to include unknown asset: <hierarchy/hierarchy_js>
2023-04-18 09:58:34,313.313 [ERROR] ckan.lib.webassets_tools | include_asset:94 | Trying to include unknown asset: <hierarchy/hierarchy_css>
```

This was working on previous versions of 2.9 (frozen at Jan 2022), so I'm wondering if something changed in a patch version of 2.9 to break this.

I will try updating the plugin as described above.

**Comment by NimeCy** [comment]
Were you able to fix the problem?
I am facing the same problem.
Adjusting the MANIFEST have not fixed the problem unfortunately.

**Comment by spwoodcock** [comment]
I use the CKAN API only, so missing the css and js hasn't impacted usage.

I'm not certain exactly what the issue is, so the quickest solution is probably to re-create the plugin for CKAN 2.10 and copy the code across.

**Comment by smotornyuk** [comment]
I wasn't able to reproduce the original problem, but I'm almost sure, that problem comes from `cssrewrite`. If you have `filters: cssrewrite` line in your webassets.yml, try removing it.

If the error is solved by this change, it means, in your CSS file you are referring to a static file(`background: url("../bg.png")`) that cannot be located by webassets. First of all, check if anything look broken in UI. It's possible that you don't even need `cssrewrite`

If something is missing, try registering assets folder as a public folder as well(and make sure that all images you are referring to are stored inside the assets folder):
```python
tk.add_resource("assets", "myext")
tk.add_public_directory(config, "assets")
```

**Comment by smotornyuk** [comment]
Fixed in #9300
