### ISSUE TITLE
Generating test data is broken

### ISSUE THREAD

**Issue by ChristianF88** [ckan/ckan#7480]
## Versions
CKAN -> 2.10
Python -> 3.10.10

## Describe the bug
Trying to generate fake-data as described in the [documentation](https://docs.ckan.org/en/2.10/maintaining/getting-started.html?highlight=fake-data#creating-test-data) on my dev box (source install) results in this error:
```sh
root@ckan-2-10:~# /usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini generate fake-data organization
2023-03-21 08:32:36,074 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2023-03-21 08:32:36,074 INFO  [ckan.config.environment] Loading static files from public
2023-03-21 08:32:36,322 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2023-03-21 08:32:37,142 WARNI [ckanext.reclineview.plugin] The Recline-based views are deprecated andwill be removed in future versions
2023-03-21 08:32:37,179 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2023-03-21 08:32:37,569 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 246, in convert
    nargs = converter.__code__.co_argcount
AttributeError: type object 'str' has no attribute '__code__'. Did you mean: '__mod__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 33, in <module>
    sys.exit(load_entry_point('ckan', 'console_scripts', 'ckan')())
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/generate.py", line 308, in fake_data
    for entity in factory.create_batch(fake_count, **extras):
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/base.py", line 540, in create_batch
    return [cls.create(**kwargs) for _ in range(size)]
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/base.py", line 540, in <listcomp>
    return [cls.create(**kwargs) for _ in range(size)]
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/base.py", line 528, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/alchemy.py", line 51, in _generate
    return super()._generate(strategy, params)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/base.py", line 465, in _generate
    return step.build()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/builder.py", line 262, in build
    instance = self.factory_meta.instantiate(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/factory/base.py", line 317, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/tests/factories.py", line 214, in _create
    return cls.api_create(kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/tests/factories.py", line 197, in api_create
    result = helpers.call_action(cls._meta.action, **data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/tests/helpers.py", line 128, in call_action
    return logic.get_action(action_name)(context, kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 943, in organization_create
    return _group_or_org_create(context, data_dict, is_org=True)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 753, in _group_or_org_create
    data, errors = lib_plugins.plugin_validate(
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/plugins.py", line 327, in plugin_validate
    result = plugin.validate(context, data_dict, schema, action)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/scheming/plugins.py", line 191, in validate
    return navl_validate(data_dict, schema, context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 305, in validate
    flat_data, errors = _validate(flattened, schema, validators_context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 356, in _validate
    convert(converter, key, converted_data, errors, context)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 248, in convert
    raise TypeError(
TypeError: str cannot be used as validator because it is not a user-defined function

```

### Additional details
This error has been reported before #6488 and seems to be linked to [#6048 ](https://github.com/ckan/ckan/pull/6048)

**Comment by ChristianF88** [comment]
I have been playing with this a bit more. It hast nothing to do with the generation of fake-data. Creating a new organization causes the error. 

![image](https://user-images.githubusercontent.com/9096348/226910798-f4caab2c-e993-441a-8401-26f4368373bf.png)

**Comment by ChristianF88** [comment]
The issue stems from https://github.com/ckan/ckanext-scheming/issues/298 .
