### ISSUE TITLE
config_declaration.yaml has non ASCII characters

### ISSUE THREAD

**Issue by BonaBeavis** [ckan/ckan#7521]
## CKAN version
2.10

## Describe the bug
```
Traceback (most recent call last):
  File "/srv/app/src/ckan/wsgi.py", line 20, in <module>
    application = make_app(config)
  File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 27, in make_app
    load_environment(conf)
  File "/srv/app/src/ckan/ckan/config/environment.py", line 69, in load_environment
    p.load_all()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 220, in load_all
    unload_all()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 270, in unload_all
    unload(*reversed(_PLUGINS))
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 302, in unload
    plugins_update()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 212, in plugins_update
    environment.update_config()
  File "/srv/app/src/ckan/ckan/config/environment.py", line 113, in update_config
    config_declaration.setup()
  File "/srv/app/src/ckan/ckan/config/declaration/__init__.py", line 114, in setup
    self.load_core_declaration()
  File "/srv/app/src/ckan/ckan/config/declaration/__init__.py", line 205, in load_core_declaration
    loader(self, "core")
  File "/srv/app/src/ckan/ckan/config/declaration/utils.py", line 52, in handle
    return handler(subject, *args, **kwargs)
  File "/srv/app/src/ckan/ckan/config/declaration/load.py", line 160, in load_core
    data = yaml.safe_load(stream)
  File "/usr/local/lib/python3.10/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.10/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.10/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.10/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.10/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.10/dist-packages/yaml/scanner.py", line 255, in fetch_more_tokens
    return self.fetch_plain()
  File "/usr/local/lib/python3.10/dist-packages/yaml/scanner.py", line 679, in fetch_plain
    self.tokens.append(self.scan_plain())
  File "/usr/local/lib/python3.10/dist-packages/yaml/scanner.py", line 1293, in scan_plain
    self.peek(length+1) in '\0 \t\r\n\x85\u2028\u2029'
  File "/usr/local/lib/python3.10/dist-packages/yaml/reader.py", line 91, in peek
    self.update(index+1)
  File "/usr/local/lib/python3.10/dist-packages/yaml/reader.py", line 153, in update
    self.update_raw()
  File "/usr/local/lib/python3.10/dist-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.10/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1538: ordinal not in range(128)
```

### Steps to reproduce
Deploy on Ubuntu 22.04 with uwsgi

### Expected behavior
config_declaration.yaml  should be parsed.

### Additional details

For identifying the offending characters:
```
❯ grep --color='auto' -P -n '[^\x00-\x7F]' config_declaration.yaml
691:          Also set to False if you want to use WTForms’s built-in messages directly, see more info here.
705:        description: The name of the cookie to store the “remember me” information in.
717:          If the “Remember Me” cookie should cross domains, set the domain value here
722:        description: Limits the “Remember Me” cookie to a certain path.
727:        description: Restricts the “Remember Me” cookie's scope to secure channels (typically HTTPS).
732:        description: Prevents the “Remember Me” cookie from being accessed by client-side scripts.
743:        description: Restricts the “Remember Me” cookie to first-party or same-site context.
```

**Comment by wardi** [comment]
@BonaBeavis try adding an `encoding='utf-8'` to the `open` call on this line https://github.com/ckan/ckan/blob/71d08f931db610faf8669c3a35cf184abec0d9d0/ckan/config/declaration/load.py#L159 and see if it fixes the issue. I'm assuming it's caused by your default system encoding not being UTF-8.

**Comment by BonaBeavis** [comment]
@wardi Yes the locale has to be set to UTF-8.

```Dockerfile
# Set locale to UTF-8 for python
RUN locale-gen de_DE.UTF-8 en_US.UTF-8
ENV LANG=de_DE.UTF-8
ENV LANGUAGE=de_DE.UTF-8
ENV LC_ALL=de_DE.UTF-8
```
