### ISSUE TITLE
ckan create views --yes fails

### ISSUE THREAD

**Issue by BonaBeavis** [ckan/ckan#7525]
I would guess the issue is, that ckan.plugins is not a string anymore, but a list.

https://github.com/ckan/ckan/blob/71d08f931db610faf8669c3a35cf184abec0d9d0/ckan/cli/views.py#L52

```
Traceback (most recent call last):
  File "/srv/app/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/srv/app/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/srv/app/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/srv/app/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/app/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/app/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/app/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/srv/app/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/app/src/ckan/ckan/cli/views.py", line 52, in create
    u"datastore" in config[u"ckan.plugins"].split()
AttributeError: 'list' object has no attribute 'split'
```

**Comment by amercader** [comment]
Fixed by #7526
