### ISSUE TITLE
Improper Auth Check Handling through `check_access` Helper

### ISSUE THREAD

**Issue by JVickery-TBS** [ckan/ckan#7560]
## CKAN version
2.8 (did not check if behavior is in current/master)

## Describe the bug
Using `ckan.lib.helpers.check_access` within an action method implemented via `get_actions` and `IActions` results in an exception of `Action function format_autocomplete did not call its auth function`.

However, using `ckan.logic.check_access` works fine.

### Steps to reproduce
Have a plugin implement `IActions` and its `get_actions` method. Override a core action method such as `package_show` and in your callback method use `ckan.lib.helpers.check_access` to call th check access of `package_show`.

### Expected behavior
The auth check passes and does not throw an exception.

### Additional details
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.
Example stack trace:
```
Traceback (most recent call last):
  File "/srv/app/ckan/registry/src/ckan/ckan/config/middleware/__init__.py", line 200, in __call__
    return self.apps[app_name](environ, start_response)
  File "/srv/app/ckan/registry/src/ckan/ckan/config/middleware/common_middleware.py", line 115, in __call__
    return self.app(environ, start_response)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
    return request.get_response(self.app)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
    response = request.get_response(self.app)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/srv/app/ckan/registry/src/ckanext-canada/ckanext/canada/plugins.py", line 635, in __call__
    return self.app(environ, _start_response)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/app/ckan/registry/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/srv/app/ckan/registry/src/ckan/ckan/views/api.py", line 410, in format_autocomplete
    formats = get_action(u'format_autocomplete')(context, data_dict)
  File "/srv/app/ckan/registry/src/ckan/ckan/logic/__init__.py", line 509, in wrapped
    .format(action_name))
Exception: Action function format_autocomplete did not call its auth function
```

**Comment by wardi** [comment]
Aside from the confusing two-different-ways-of-doing-auth-checks situation, I wonder if we want to enforce calling `check_access` for chained actions in plugins at all? Actions overridden from plugins don't have this check enforced.

**Comment by wardi** [comment]
There was some agreement to remove the `check_access` enforcement from `ckan/logic/__init__.py` because this kind of thing is better done from tests than on every call to every action on every live site, and because edge cases aren't handled well, e.g. chained actions from plugins
