### ISSUE TITLE
Function is dropped in CKAN 2.10 despite deprecation info

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#7579]
## CKAN version

2.10

## Describe the bug

The `authz.auth_is_loggedin_user` function is dropped in CKAN 2.10. However, in CKAN 2.9, there was a deprecation notice _recommending_ this function, and there doesn't appear to be a clear replacement.

### Steps to reproduce

- Install a plugin that calls `auth_is_loggedin_user` on CKAN 2.9, such as https://github.com/qld-gov-au/ckanext-ytp-comments/
- Update to CKAN 2.10
- Perform an operation that calls the function, such as flagging a comment for moderation

### Expected behavior

There should be a notice in the code and/or the changelog to indicate what replaces `auth_is_loggedin_user`.

### Additional details

    12:38:09,321 ERROR [ckan.config.middleware.flask_app] module 'ckan.authz' has no attribute 'auth_is_loggedin_user'
    Traceback (most recent call last):
      File "/usr/lib/ckan/default/lib64/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/lib/ckan/default/lib64/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
        return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
      File "/mnt/local_data/ckan_venv/src/ckanext-ytp-comments/ckanext/ytp/comments/controllers/__init__.py", line 276, in flag
        if authz.auth_is_loggedin_user():
    AttributeError: module 'ckan.authz' has no attribute 'auth_is_loggedin_user'

**Comment by Zharktas** [comment]
It was dropped as authentication was replaced to flask-login in https://github.com/ckan/ckan/pull/6560, its not optimal that there isn't a clear upgrade path though
