### ISSUE TITLE
Error while deleting a package with an extra field

### ISSUE THREAD

**Issue by pkernevez** [ckan/ckan#7592]
## CKAN version
2.10

## Describe the bug
When deleting a package with an extra field, the following exception is traced:
```
ckan  | 2023-05-16 13:05:12,630 ERROR [ckan.model.modification]
ckan  | Traceback (most recent call last):
ckan  |   File "/srv/app/src/ckan/ckan/model/modification.py", line 71, in notify
ckan  |     observer.notify(entity, operation)
ckan  |   File "/srv/app/src/ckan/ckan/lib/search/__init__.py", line 167, in notify
ckan  |     logic.get_action('package_show')(cast(
ckan  |   File "/srv/app/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
ckan  |     result = _action(context, data_dict, **kw)
ckan  |   File "/srv/app/src/ckan/ckan/logic/action/get.py", line 1018, in package_show
ckan  |     raise NotFound
ckan  | ckan.logic.NotFound
```

### Steps to reproduce
Create a schema with an extra field on a package.

Create an instance of this package, then delete it.
After the call of the deletion we have no changed nor new objects.
<img width="461" alt="image" src="https://github.com/ckan/ckan/assets/338699/b01c3cd5-b6a0-40b7-8b16-f074695719f5">

But right after in `modification.py` L58, ckan is going through all deleted object to notify a 'change' on their related packages 
<img width="640" alt="image" src="https://github.com/ckan/ckan/assets/338699/9abdd70a-0906-4c9a-bcae-cc6c99a15ee7">
But in this case the related package is the one that has been deleted
<img width="1191" alt="image" src="https://github.com/ckan/ckan/assets/338699/ac87ca50-60c6-44d6-87ab-9d68ae7cf39e">

### Expected behavior
Do not trace exception as the deletion is done.
Do not notifiy a package as changed when it is already deleted.

**Comment by Faldrian** [comment]
I have experienced the same behaviour when purging a package with a resource. In that case, the purging of the package will trigger purging of the resource. Purging the resource will trigger notification for the package which is deleted at that moment.
