### ISSUE TITLE
2.10.1 - fails to start with suggested beaker configuration from migration notes

### ISSUE THREAD

**Issue by tgurr** [ckan/ckan#7602]
## CKAN version
2.10.1

## Describe the bug
2.10.1 changelog: https://github.com/ckan/ckan/blob/2.10/CHANGELOG.rst#migration-notes mentions to change/add:

```
# ckan.ini
beaker.session.type = cookie
beaker.session.data_serializer = json
beaker.session.validate_key = CHANGE_ME
beaker.session.httponly = True
beaker.session.secure = True
beaker.session.samesite = Lax # or Strict, depending on your setup
```
First it would be nice to know what kind of string `CHANGE_ME` expects like the recommended lenght/format and maybe suggest a command to create the random string.

However the actual problem is with this change ckan 2.10.1 fails to start as it's lacking an AES library.

```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 82, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py", line 87, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py", line 31, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 615, in error_handler
    show_login_redirect_link = current_user.is_anonymous and type(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/werkzeug/local.py", line 436, in __get__
    obj = instance._get_current_object()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/werkzeug/local.py", line 565, in _get_current_object
    return self.__local()  # type: ignore
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask_login/utils.py", line 384, in _get_user
    current_app.login_manager._load_user()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask_login/login_manager.py", line 347, in _load_user
    if self._session_protection_failed():
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask_login/login_manager.py", line 388, in _session_protection_failed
    if sess and ident != sess.get("_id", None):
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/beaker/session.py", line 814, in __getattr__
    return getattr(self._session(), attr)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/beaker/session.py", line 810, in _session
    self.__dict__['_sess'] = session_cls(req, **params)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/beaker/session.py", line 622, in __init__
    raise InvalidCryptoBackendError("No AES library is installed, can't generate "
beaker.exceptions.InvalidCryptoBackendError: No AES library is installed, can't generate encrypted cookie-only Session.
```

CKAN has been installed/upgraded via `pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.10.1#egg=ckan[requirements]'` so the lacking python library should be added the the requirements as well.

### Steps to reproduce
1. Install CKAN `pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.10.1#egg=ckan[requirements]'`
2. Configure beaker like suggested
3. Observe error at `/etc/ckan/default/uwsgi.ERR`

### Expected behavior
Have everything CKAN uses availble/installed to be able to successfully run it with the recommended (and according to the changelog future default) configuration.

### Additional details
beaker documentation:

https://beaker.readthedocs.io/en/latest/configuration.html#encryption-options

```
crypto_type (optional, string)
Encryption backend to use. If default is used, one of the installed backends is picked.
Other valid choices are cryptography, nss, pycrypto.

Note: You may need to install additional libraries to use Beaker’s cookie-based session encryption. See the Encryption section for more information.

```

https://beaker.readthedocs.io/en/latest/sessions.html#encryption

```
Depending on the Python implementation used, Beaker may require an additional library to provide AES encryption.
On CPython (the regular Python), one of the following libraries is required:

The [python-nss](https://pypi.python.org/pypi/python-nss/) library
The [pycryptopp](https://pypi.python.org/pypi/pycryptopp/) library
The [cryptography](https://pypi.python.org/pypi/cryptography/) library
The [PyCrypto](https://pypi.python.org/pypi/pycrypto/) library
```

**Comment by amercader** [comment]
Thanks @tgurr , we've now added extra details to the CHANGELOG for 2.10.1 and 2.9.9:

https://docs.ckan.org/en/2.10/changelog.html#migration-notes

**Comment by mtearle** [comment]
I too saw this error.   I needed to set crypto_type manually as well.

My config:

```
beaker.session.validate_key = CHANGEME_TO_BEAKER_VALIDATE_KEY
beaker.session.encrypt_key = CHANGEME_TO_BEAKER_ENCRYPT_KEY
beaker.session.crypto_type = cryptography
```
