### ISSUE TITLE
Internal Server Error when trying to access a dataset with an active session

### ISSUE THREAD

**Issue by perecanet** [ckan/ckan#7621]
## CKAN version
2.10
## Describe the bug
I have deployed CKAN using Docker Compose and openknowledge/ckan-base:2.10 image, everything is working fine, but after logging in, I can no longer access any dataset. When trying to do so, an Internal Server Error occurs. The CKAN container logs show this message: 'ERROR [ckan.config.middleware.flask_app] Could not build URL for endpoint 'activity.package_activity' with values ['id']. Did you mean 'api.get_api' instead?'
....
File "/usr/lib/python3.10/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'activity.package_activity' with values ['id']. Did you mean 'api.get_api' instead?
2023-05-31 13:08:31,507 INFO  [ckan.config.middleware.flask_app]  500 /dataset/prueba render time 1.567 seconds

### Additional details
2023-05-31 13:08:31,194 ERROR [ckan.config.middleware.flask_app] Could not build url for endpoint 'activity.package_activity' with values ['id']. Did you mean 'api.get_api' instead?
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/srv/app/src/ckan/ckan/config/middleware/../../views/dataset.py", line 499, in read
    return base.render(
  File "/srv/app/src/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/srv/app/src_extensions/ckanext-scheming-master/ckanext/scheming/templates/scheming/package/read.html", line 3, in top-level template code
    {%- set schema = h.scheming_get_dataset_schema(dataset_type) -%}
  File "/srv/app/src_extensions/ckanext-stomallorca_theme/ckanext/stomallorca_theme/templates/package/read.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/srv/app/src/ckan/ckan/templates/package/read.html", line 1, in top-level template code
    {% extends "package/read_base.html" %}
  File "/srv/app/src_extensions/ckanext-stomallorca_theme/ckanext/stomallorca_theme/templates/package/read_base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/srv/app/src/ckan/ckan/templates/package/read_base.html", line 3, in top-level template code
    {% set default_group_type = h.default_group_type('group') %}
  File "/srv/app/src/ckan/ckan/templates/package/base.html", line 4, in top-level template code
    {% set dataset_type = dataset_type or pkg.type or 'dataset' %}
  File "/srv/app/src/ckan/ckan/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/srv/app/src_extensions/ckanext-scheming-master/ckanext/scheming/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/srv/app/src_extensions/ckanext-stomallorca_theme/ckanext/stomallorca_theme/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/srv/app/src/ckan/ckan/templates/base.html", line 108, in top-level template code
    {%- block page %}{% endblock -%}
  File "/srv/app/src/ckan/ckan/templates/page.html", line 19, in block 'page'
    {%- block content %}
    File "/srv/app/src/ckan/ckan/templates/page.html", line 22, in block 'content'
    {% block main_content %}
  File "/srv/app/src/ckan/ckan/templates/page.html", line 74, in block 'main_content'
    {% block primary %}
  File "/srv/app/src/ckan/ckan/templates/page.html", line 87, in block 'primary'
    {% block primary_content %}
  File "/srv/app/src/ckan/ckan/templates/page.html", line 89, in block 'primary_content'
    {% block page_header %}
  File "/srv/app/src/ckan/ckan/templates/page.html", line 97, in block 'page_header'
    {% block content_primary_nav %}{% endblock %}
  File "/srv/app/src_extensions/ckanext-stomallorca_theme/ckanext/stomallorca_theme/templates/package/read_base.html", line 7, in block 'content_primary_nav'        
    {{ h.build_nav_icon('activity.package_activity', _('Activity Stream'), id=pkg.id if is_activity_archive else pkg.name, icon='clock-o') }}
  File "/srv/app/src/ckan/ckan/lib/helpers.py", line 879, in build_nav_icon
    return _make_menu_item(menu_item, title, **kw)
  File "/srv/app/src/ckan/ckan/lib/helpers.py", line 964, in _make_menu_item
    link = _link_to(title, menu_item, suppress_active_class=True, **item)
  File "/srv/app/src/ckan/ckan/lib/helpers.py", line 780, in _link_to
    url_for(*args, **kwargs),
  File "/srv/app/src/ckan/ckan/lib/helpers.py", line 385, in url_for
    my_url = _url_for_flask(*args, **kw)
  File "/srv/app/src/ckan/ckan/lib/helpers.py", line 443, in _url_for_flask
    my_url = _flask_default_url_for(*args, **kw)
  File "/usr/lib/python3.10/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python3.10/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/usr/lib/python3.10/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'activity.package_activity' with values ['id']. Did you mean 'api.get_api' instead?
2023-05-31 13:08:31,507 INFO  [ckan.config.middleware.flask_app]  500 /dataset/prueba render time 1.567 seconds

**Comment by smotornyuk** [comment]
On line 7 of `ckanext-stomallorca_theme/ckanext/stomallorca_theme/templates/package/read_base.html` you are building a URL for the activity page. This page is available only when `activity` plugin is enabled. Make sure you have something like `ckan.plugins = ... activity` in the config file
