### ISSUE TITLE
[Error 500] Internal error, layout broken after restart ckan-uwsgi 

### ISSUE THREAD

**Issue by nmtoan91** [ckan/ckan#7660]
## Describe the bug
I installed ckan from 2.10.1 package, the website works fine on the first run. But when I try to restart the ckan-uwsgi, the page is broken.

### Additional details
```
2023-06-19 14:52:03,207 ERROR [ckan.config.middleware.flask_app] SOLR returned an error running query: {'facet': 'false', 'fq': ['+capacity:public +owner_org:"ed262aef-552e-4d7f-8b07-789a334d0edf" +state:(active)', '+site_id:"tanlab-test-ckan"'], 'rows': 3, 'df': 'text', 'sort': 'score desc, metadata_modified desc', 'fl': 'id validated_data_dict', 'q': '*:*', 'facet.limit': 50, 'facet.mincount': 1, 'wt': 'json', 'q.op': 'AND'} Error: SolrError('Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]')
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/query.py", line 414, in run
    solr_response = conn.search(**query)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/pysolr.py", line 827, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/pysolr.py", line 488, in _select
    return self._send_request("get", path)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/pysolr.py", line 463, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
pysolr.SolrError: Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/home.py", line 90, in index
    return base.render(u'home/index.html', extra_vars={})
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/home/index.html", line 2, in top-level template code
    {% set homepage_style = ( g.homepage_style or '1' ) %}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/base.html", line 108, in top-level template code
    {%- block page %}{% endblock -%}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/page.html", line 19, in block 'page'
    {%- block content %}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/home/index.html", line 14, in block 'content'
    {% block primary_content %}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/home/index.html", line 15, in block 'primary_content'
    {% snippet "home/layout{0}.html".format(homepage_style) %}
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/jinja_extensions.py", line 277, in _call
    return base.render_snippet(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 72, in render_snippet
    output = render(template_name, extra_vars=kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/home/layout1.html", line 33, in top-level template code
    {% block featured_organization %}
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/home/layout1.html", line 34, in block 'featured_organization'
    {% snippet 'home/snippets/featured_organization.html' %}
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/jinja_extensions.py", line 277, in _call
    return base.render_snippet(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 72, in render_snippet
    output = render(template_name, extra_vars=kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/home/snippets/featured_organization.html", line 1, in top-level template code
    {% set organizations = h.get_featured_organizations() %}
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 2420, in get_featured_organizations
    orgs = featured_group_org(get_action='organization_show',
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 2463, in featured_group_org
    group = get_group(group_name)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 2451, in get_group
    out = logic.get_action(get_action)(context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 1341, in organization_show
    return _group_or_org_show(context, data_dict, is_org=True)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 1232, in _group_or_org_show
    group_dict = model_dictize.group_dictize(group, context,
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/dictization/model_dictize.py", line 399, in group_dictize
    package_count, packages = get_packages_for_this_group(group)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/dictization/model_dictize.py", line 394, in get_packages_for_this_group
    search_results = logic.get_action('package_search')(
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 1941, in package_search
    query.run(data_dict, permission_labels=labels)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/query.py", line 425, in run
    raise SearchError('SOLR returned an error running query: %r Error: %r' %
ckan.lib.search.common.SearchError: SOLR returned an error running query: {'facet': 'false', 'fq': ['+capacity:public +owner_org:"ed262aef-552e-4d7f-8b07-789a334d0edf" +state:(active)', '+site_id:"tanlab-test-ckan"'], 'rows': 3, 'df': 'text', 'sort': 'score desc, metadata_modified desc', 'fl': 'id validated_data_dict', 'q': '*:*', 'facet.limit': 50, 'facet.mincount': 1, 'wt': 'json', 'q.op': 'AND'} Error: SolrError('Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]')
2023-06-19 14:52:03,639 INFO  [ckan.config.middleware.flask_app]  500 / render time 0.595 seconds
[pid: 5490|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 878 bytes} [Mon Jun 19 14:52:03 2023] GET / => generated 9878 bytes in 598 msecs (HTTP/1.1 500) 3 headers in 124 bytes (1 switches on core 0)
2023-06-19 14:52:03,667 INFO  [ckan.config.middleware.flask_app]  304 /webassets/vendor/f3b8236b_select2.css render time 0.010 seconds
[pid: 5490|app: 0|req: 2/2] 127.0.0.1 () {46 vars in 921 bytes} [Mon Jun 19 14:52:03 2023] GET /webassets/vendor/f3b8236b_select2.css => generated 0 bytes in 65 msecs (HTTP/1.1 304) 3 headers in 187 bytes (0 switches on core 0)
2023-06-19 14:52:03,726 INFO  [ckan.config.middleware.flask_app]  304 /webassets/vendor/d05bf0e7_fontawesome.css render time 0.004 seconds
[pid: 5490|app: 0|req: 3/3] 127.0.0.1 () {46 vars in 928 bytes} [Mon Jun 19 14:52:03 2023] GET /webassets/vendor/d05bf0e7_fontawesome.css => generated 0 bytes in 4 msecs (HTTP/1.1 304) 3 headers in 191 bytes (0 switches on core 0)
2023-06-19 14:52:03,731 INFO  [ckan.config.middleware.flask_app]  304 /webassets/vendor/8c3c143a_jquery.js render time 0.004 seconds
[pid: 5490|app: 0|req: 4/4] 127.0.0.1 () {46 vars in 902 bytes} [Mon Jun 19 14:52:03 2023] GET /webassets/vendor/8c3c143a_jquery.js => generated 0 bytes in 25 msecs (HTTP/1.1 304) 3 headers in 185 bytes (0 switches on core 0)
2023-06-19 14:52:03,758 INFO  [ckan.config.middleware.flask_app]  304 /webassets/vendor/5027b870_vendor.js render time 0.004 seconds
[pid: 5490|app: 0|req: 5/5] 127.0.0.1 () {46 vars in 902 bytes} [Mon Jun 19 14:52:03 2023] GET /webassets/vendor/5027b870_vendor.js => generated 0 bytes in 5 msecs (HTTP/1.1 304) 3 headers in 185 bytes (0 switches on core 0)
2023-06-19 14:52:03,763 INFO  [ckan.config.middleware.flask_app]  304 /webassets/vendor/6d1ad7e6_bootstrap.js render time 0.004 seconds
[pid: 5490|app: 0|req: 6/6] 127.0.0.1 () {46 vars in 908 bytes} [Mon Jun 19 14:52:03 2023] GET /webassets/vendor/6d1ad7e6_bootstrap.js => generated 0 bytes in 5 msecs (HTTP/1.1 304) 3 headers in 188 bytes (0 switches on core 0)
2023-06-19 14:52:03,768 INFO  [ckan.config.middleware.flask_app]  304 /webassets/base/ac37343e_main.js render time 0.004 seconds
[pid: 5490|app: 0|req: 7/7] 127.0.0.1 () {46 vars in 894 bytes} [Mon Jun 19 14:52:03 2023] GET /webassets/base/ac37343e_main.js => generated 0 bytes in 5 msecs (HTTP/1.1 304) 3 headers in 183 bytes (0 switches on core 0)
2023-06-19 14:52:03,773 INFO  [ckan.config.middleware.flask_app]  304 /webassets/base/ea40fb97_ckan.js render time 0.004 seconds
[pid: 5490|app: 0|req: 8/8] 127.0.0.1 () {46 vars in 894 bytes} [Mon Jun 19 14:52:03 2023] GET /webassets/base/ea40fb97_ckan.js => generated 0 bytes in 5 msecs (HTTP/1.1 304) 3 headers in 183 bytes (0 switches on core 0)
2023-06-19 14:52:03,782 INFO  [ckan.config.middleware.flask_app]  304 /base/images/ckan-logo.png render time 0.007 seconds
[pid: 5490|app: 0|req: 9/9] 127.0.0.1 () {46 vars in 904 bytes} [Mon Jun 19 14:52:03 2023] GET /base/images/ckan-logo.png => generated 0 bytes in 8 msecs (HTTP/1.1 304) 3 headers in 180 bytes (0 switches on core 0)
2023-06-19 14:52:03,790 INFO  [ckan.config.middleware.flask_app]  304 /base/images/od_80x15_blue.png render time 0.005 seconds
[pid: 5490|app: 0|req: 10/10] 127.0.0.1 () {46 vars in 912 bytes} [Mon Jun 19 14:52:03 2023] GET /base/images/od_80x15_blue.png => generated 0 bytes in 7 msecs (HTTP/1.1 304) 3 headers in 184 bytes (0 switches on core 0)
2023-06-19 14:52:03,843 INFO  [ckan.config.middleware.flask_app]  200 /api/i18n/en render time 0.003 seconds
[pid: 5490|app: 0|req: 11/11] 127.0.0.1 () {38 vars in 590 bytes} [Mon Jun 19 14:52:03 2023] GET /api/i18n/en => generated 2 bytes in 4 msecs (HTTP/1.0 200) 4 headers in 282 bytes (1 switches on core 0)
```

**Comment by kowh-ai** [comment]
Whats the value of the solr_url parameter in the CKAN config file? Are you able to access the Solr instance (http://127.0.0.1:8983/solr) using a browser?
