### ISSUE TITLE
SMTP connection problems and SMTP settings documentation

### ISSUE THREAD

**Issue by BWibo** [ckan/ckan#7666]
## CKAN version

- All CKAN versions

## Describe the bug
The documentation of the SMTP settings should be improved. As you can observe in this issue (tum-gis/sddi-ckan-k8s#4), we had severe trouble with that. It is unclear wether or not the port in the server string should be set. Furthermore it should be documented, that apparently the `startTls` option is required to enable TSL too. The config you see in the examples below, refers to the config of our Kubernetes SDDI CKAN Stack (see here: [tum-gis/sddi-ckan-k8s(https://github.com/tum-gis/sddi-ckan-k8s)). These settings are mapped to the CKAN settings documented here:
https://docs.ckan.org/en/latest/maintaining/configuration.html#email-settings

### Examples

- 
  ```yml
  ckan:
    smtp:
      server: "smtps.udag.de:465"
      user: "username"
      password: "pwd"
      mailFrom: "a@b.de"
      startTls: "True"
  ```
  - Port 465 set
  - STARTLS enabled
  - ==> Not working
  - Error after several seconds on console:
    ```shell
    2023-06-21 08:49:39,749 INFO  [ckan.views.user] Password reset requested for user "bruno"
    2023-06-21 08:49:39,757 INFO  [ckan.views.user] Emailing reset link to user: bruno
    2023-06-21 08:49:46,656 INFO  [ckan.config.middleware.flask_app]  200 /api/3/action/status_show render time 0.008 seconds
    # ...
    # ...
    2023-06-21 08:49:46,656 INFO  [ckan.config.middleware.flask_app]  200 /api/3/action/status_show render time 0.008 seconds
    2023-06-21 08:50:39,812 ERROR [ckan.lib.mailer] Connection unexpectedly closed
    Traceback (most recent call last):
      File "/srv/app/src/ckan/ckan/lib/mailer.py", line 82, in _mail_recipient
        smtp_connection = smtplib.SMTP(smtp_server)
      File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
        (code, msg) = self.connect(host, port)
      File "/usr/lib/python3.8/smtplib.py", line 341, in connect
        (code, msg) = self.getreply()
      File "/usr/lib/python3.8/smtplib.py", line 398, in getreply
        raise SMTPServerDisconnected("Connection unexpectedly closed")
    smtplib.SMTPServerDisconnected: Connection unexpectedly closed
    2023-06-21 08:50:39,812 ERROR [ckan.views.user] SMTP server could not be connected to: "smtps.udag.de:465" Connection unexpectedly closed
    Traceback (most recent call last):
      File "/srv/app/src/ckan/ckan/lib/mailer.py", line 82, in _mail_recipient
        smtp_connection = smtplib.SMTP(smtp_server)
      File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
        (code, msg) = self.connect(host, port)
      File "/usr/lib/python3.8/smtplib.py", line 341, in connect
        (code, msg) = self.getreply()
      File "/usr/lib/python3.8/smtplib.py", line 398, in getreply
        raise SMTPServerDisconnected("Connection unexpectedly closed")
    smtplib.SMTPServerDisconnected: Connection unexpectedly closed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/srv/app/src/ckan/ckan/config/middleware/../../views/user.py", line 662, in post
        mailer.send_reset_link(user_obj)
      File "/srv/app/src/ckan/ckan/lib/mailer.py", line 188, in send_reset_link
        mail_user(user, subject, body)
      File "/srv/app/src/ckan/ckan/lib/mailer.py", line 133, in mail_user
        mail_recipient(recipient.display_name, recipient.email, subject,
      File "/srv/app/src/ckan/ckan/lib/mailer.py", line 124, in mail_recipient
        return _mail_recipient(recipient_name, recipient_email,
      File "/srv/app/src/ckan/ckan/lib/mailer.py", line 85, in _mail_recipient
        raise MailerException('SMTP server could not be connected to: "%s" %s'
    ckan.lib.mailer.MailerException: SMTP server could not be connected to: "smtps.udag.de:465" Connection unexpectedly closed
    ```
- 
  ```yml
  ckan:
    smtp:
      server: "smtps.udag.de:465"
      user: "username"
      password: "pwd"
      mailFrom: "a@b.de"
      startTls: "False"
  ```
  - Port 465 set
  - STARTLS disabled
  - ==> Not working

- 
  ```yml
  ckan:
    smtp:
      server: "smtps.udag.de:465"
      user: "username"
      password: "pwd"
      mailFrom: "a@b.de"
      startTls: "False"
  ```
  - Not port set
  - STARTLS enabled
  - ==> This works. 🎉 🍺 

### Steps to reproduce
Try out some SMTP settings and e.g. try to receive a password reset email.

### Expected behavior
The documentation should help users to avoid trial and error to find the correct settings. The current documentation is not very intuitive in my opinion.

**Comment by hongjie123** [comment]
Hello, I also have the same problem. How can I solve it?
I added a new user to an organization and received an error stating "504 Gateway Time out" after entering my email. As shown in the following figure:
![image](https://github.com/ckan/ckan/assets/54384385/f2f70909-55a4-46d7-a2ad-78522e15c218)

At the beginning (first time), configure the following in the ckan configuration file:
'''
ckan:
  smtp:
    server: "smtp.126.com:465"
    user: "username"
    password: "pwd"
    mailFrom: "a@b.de"
    startTls: "True"
'''
There has been an error similar to the one mentioned above.

Now (the second time), I am using the following method without a port (465), but still reporting an error. 
'''
ckan:
  smtp:
    server: "smtp.126.com"
    user: "username"
    password: "pwd"
    mailFrom: "a@b.de"
    startTls: "True"
'''
The specific error is as follows:
'''
2024-01-15 15:25:24,411 DEBUG [ckanext.activity.logic.action] Created 'new user' activity
2024-01-15 15:29:46,373 ERROR [ckan.lib.mailer] [Errno 110] Connection timed out
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/mailer.py", line 100, in _mail_recipient
    smtp_connection = smtplib.SMTP(smtp_server)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
2024-01-15 15:29:46,384 ERROR [ckan.config.middleware.flask_app]
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/mailer.py", line 100, in _mail_recipient
    smtp_connection = smtplib.SMTP(smtp_server)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 1116, in user_invite
    mailer.send_invite(user, group_dict, data['role'])
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/mailer.py", line 281, in send_invite
    mail_user(user, subject, body)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/mailer.py", line 208, in mail_user
    mail_recipient(
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/mailer.py", line 183, in mail_recipient
    return _mail_recipient(
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/mailer.py", line 103, in _mail_recipient
    raise MailerException('SMTP server could not be connected to: "%s" %s'
ckan.lib.mailer.MailerException: SMTP server could not be connected to: "smtp.126.com" [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/group.py", line 1111, in post
    user_dict = _action(u'user_invite')(context, user_data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 1125, in user_invite
    raise ValidationError(message)
ckan.logic.ValidationError: None - {'message': 'Error sending the invite email, the user was not created: SMTP server could not be connected to: "smtp.126.com" [Errno 110] Connection timed out'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/group.py", line 1113, in post
    for error in e.error_summary.values():
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 150, in error_summary
    return summarise(self.error_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 144, in summarise
    assert isinstance(error, list)
AssertionError
2024-01-15 15:29:46,427 INFO  [ckan.config.middleware.flask_app]  500 /organization/member_new/8f35801e-48a4-4fac-a008-fc6e937cb486 render time 262.040 seconds

'''

**Comment by hongjie123** [comment]
I found that in version 2.10.2 of ckan.com, it is not possible to only modify the email configuration in the ckan.ini file. Also, it is necessary to modify the "smtp_connection=smtplib. SMTP (smtp_server)" in the ckan/ckan/lib/mailer. py file to "smtp_connection=smtplib. SMTP-SSL (smtp_server, 465)".
