### ISSUE TITLE
ckan.lib.search.common.SearchError: SOLR schema version not supported: 1.6. Supported versions are [2.8, 2.9, 2.10]

### ISSUE THREAD

**Issue by GlennTatum** [ckan/ckan#7688]
## CKAN version

2.10.1

## Describe the bug

The uWSGI server fails to start because the Solr schema version is reported to be incorrect.

### Steps to reproduce

From the installing CKAN from source guide:
https://docs.ckan.org/en/2.10/maintaining/installing/install-from-source.html#installing-solr-manually
```
sudo -u solr wget -O /var/solr/data/ckan/conf/managed-schema https://raw.githubusercontent.com/ckan/ckan/dev-v2.10/ckan/config/solr/schema.xml
```

### Expected behavior

The uWSGI server should successfully start.

### Additional details
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

Solr version: 8.11.2

**/etc/ckan/default/uwsgi.ERR** 
```
*** Starting uWSGI 2.0.21 (64bit) on [Sat Jul  1 22:39:47 2023] ***
compiled with version: 9.4.0 on 01 July 2023 21:56:18
os: Linux-5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023
nodename: ckan-ansible-3
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /tmp/ckan-uwsgi.pid
detected binary path: /usr/lib/ckan/default/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
your processes number limit is 31420
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8080 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:34067 (port auto-assigned) fd 3
Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0]
PEP 405 virtualenv detected: /usr/lib/ckan/default
Set PythonHome to /usr/lib/ckan/default
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55c912c798d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
2023-07-01 22:39:48,490 INFO  [ckan.config.environment] Loading static files from public
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/wsgi.py", line 20, in <module>
    application = make_app(config)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 27, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 69, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 220, in load_all
    unload_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 270, in unload_all
    unload(*reversed(_PLUGINS))
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 302, in unload
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 212, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 184, in update_config
    search.check_solr_schema_version()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 394, in check_solr_schema_version
    raise SearchError('SOLR schema version not supported: %s. Supported'
ckan.lib.search.common.SearchError: SOLR schema version not supported: 1.6. Supported versions are [2.8, 2.9, 2.10]
unable to load app 0 (mountpoint='') (callable not found or import error)
2023-07-01 22:39:48,897 INFO  [ckan.config.environment] Loading static files from public
Traceback (most recent call last):
  File "/etc/ckan/default/wsgi.py", line 12, in <module>
    application = make_app(config)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 27, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 69, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 220, in load_all
    unload_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 270, in unload_all
    unload(*reversed(_PLUGINS))
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 302, in unload
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 212, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 184, in update_config
    search.check_solr_schema_version()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 394, in check_solr_schema_version
    raise SearchError('SOLR schema version not supported: %s. Supported'
ckan.lib.search.common.SearchError: SOLR schema version not supported: 1.6. Supported versions are [2.8, 2.9, 2.10]
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
spawned uWSGI master process (pid: 24480)
spawned uWSGI worker 1 (pid: 24485, cores: 1)
spawned uWSGI http 1 (pid: 24486)
```

**Comment by GlennTatum** [comment]
For the Solr schema does CKAN look at

`/usr/lib/ckan/default/lib/python3.8/site-packages/ckan/config/solr/schema.xml`

or

`/var/solr/data/ckan/conf/managed-schema`

or does it query the Solr API for the schema version?

**Comment by kowh-ai** [comment]
`/var/solr/data/ckan/conf/managed-schema` on the solr server and  `/usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml` on the CKAN server should be the same...something looks a bit messed up. 

[Here](https://github.com/ckan/ckan/blob/2.10/ckan/lib/search/__init__.py#L378-L397) is the where the error comes from

**Comment by ChristianF88** [comment]
This bug is back. I'm using [ckan-docker](https://github.com/ckan/ckan-docker), with these images:
- `ckan/ckan-dev:2.10.6-py3.10`
- `ckan/ckan-solr:2.10-solr9`

But I tried all sorts of other versions for solr and ckan 2.10.6.

**Comment by ChristianF88** [comment]
I dug a little deeper and found out that the solr managed schema is initialized with ckan-2-11.
In the SOLR container:
```bash
solr@421aa972dd62:/opt/solr-9.7.0$ wget -O- http://localhost:8983/solr/ckan/schema?wt=schema.xml | grep version
...
<schema name="ckan-2.11" version="1.6">
...
```

Causes the error:
```bash
2025-01-30 10:04:31,812 INFO  [ckan.cli] Using configuration file /srv/app/ckan.ini
2025-01-30 10:04:31,812 INFO  [ckan.config.environment] Loading static files from public
Traceback (most recent call last):
  File "/usr/local/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/srv/app/src/ckan/ckan/cli/cli.py", line 121, in parse_args
    result = super().parse_args(ctx, args)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/srv/app/src/ckan/ckan/cli/cli.py", line 131, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/srv/app/src/ckan/ckan/cli/cli.py", line 140, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/srv/app/src/ckan/ckan/cli/cli.py", line 57, in __init__
    self.app = make_app(raw_config)
  File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 27, in make_app
    load_environment(conf)
  File "/srv/app/src/ckan/ckan/config/environment.py", line 69, in load_environment
    p.load_all()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 218, in load_all
    unload_all()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 268, in unload_all
    unload(*reversed(_PLUGINS))
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 300, in unload
    plugins_update()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 210, in plugins_update
    environment.update_config()
  File "/srv/app/src/ckan/ckan/config/environment.py", line 184, in update_config
    search.check_solr_schema_version()
  File "/srv/app/src/ckan/ckan/lib/search/__init__.py", line 395, in check_solr_schema_version
    raise SearchError('SOLR schema version not supported: %s. Supported'
ckan.lib.search.common.SearchError: SOLR schema version not supported: 2.11. Supported versions are [2.8, 2.9, 2.10]
```

The code responsible is here:
https://github.com/ckan/ckan/blob/6b42e2f222c1afcb6f0f72555e431010e2ba223c/ckan/lib/search/__init__.py#L332

**Comment by ChristianF88** [comment]
The issue seems to be caused by https://github.com/ckan/ckan-solr/issues/13.
