### ISSUE TITLE
psycopg2.errors.UndefinedTable relation "_table_metadata"

### ISSUE THREAD

**Issue by FlavorFlav** [ckan/ckan#7698]
## CKAN version
2.10

## Describe the bug
When submitting data to the Datapusher or Xloader extension, I get the following error message
```
2023-07-03 13:07:36,215 ERROR [ckanext.xloader.jobs] xloader error: (psycopg2.errors.UndefinedTable) relation "_table_metadata" does not exist
LINE 1: SELECT alias_of FROM "_table_metadata" WHERE name = '9705299...
                             ^

[SQL: SELECT alias_of FROM "_table_metadata" WHERE name = %(id)s]
[parameters: {'id': '9705299e-79cd-42a2-a1a4-13163a71f113'}]
(Background on this error at: https://sqlalche.me/e/14/f405), Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "_table_metadata" does not exist
LINE 1:    WHERE name = '9705299...
                             ^
```

### Steps to reproduce
I proceeded like described in the official CKAN documentation for installing CKAN 2.10 including all recommendations regarding production environments (Solr, PostgreSQL, etc.)

### Additional details
I suppose some statements to read the _table_metadata view are misinterpreted by the psycopg2 adapter yielding a PostgreSQL syntax error.

**Comment by FlavorFlav** [comment]
@smotornyuk 
I assume the double quotes are interpreted as part of the table name which, obviously, should not be the case.

**Comment by smotornyuk** [comment]
No, PostgreSQL uses double quotes for escaping table\column names. For example, you cannot use `SELECT * FROM user`, because `user` is a keyword in PostgreSQL, so you have to write `SELECT * FROM "user"`. Double-quotes are not affecting non-keyword names and the following query behaves identically with or without double-quotes: `SELECT * FROM "package"`.

It's more likely that you haven't setup DB permissions for the datastore properly. Can you run `ckan datastore set-permissions` and apply produced SQL to the database? Make sure you've got something similar to the following:
```
You are now connected to database "ckan_datastore" as user "postgres".
REVOKE
REVOKE
GRANT
GRANT
GRANT
GRANT
REVOKE
GRANT
GRANT
GRANT
ALTER DEFAULT PRIVILEGES
CREATE VIEW
ALTER VIEW
GRANT
CREATE FUNCTION
ALTER FUNCTION
DO
```
