### ISSUE TITLE
CKAN 2.9.9 (Red Hat 8) bug with markdown==3.4.1

### ISSUE THREAD

**Issue by carlosmartinezdelacasa** [ckan/ckan#7731]
## CKAN version
2.9.9
## Describe the bug
When installing CKAN version 2.9.9 on Red Hat 8 (with python 3.6.8) the following error occurs when validating the requirements:
<<..
ERROR: Could not find a version that satisfies the requirement markdown==3.4.1; extra == "requirements" (from ckan[requirements]) (from versions: 1.7, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.3, 2.3.1, 2.4, 2.4.1, 2.5, 2.5.1, 2.5.2, 2.6, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.6.9, 2.6.10, 2.6.11, 3.0, 3.0.1, 3.1, 3.1.1, 3.2, 3.2.1, 3.2.2, 3.3, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7)
ERROR: No matching distribution found for markdown==3.4.1; extra == "requirements"
..>>
### Steps to reproduce
install
pip3 install -e 'git+https://github.com/ckan/ckan.git@ckan-2.9.9#egg=ckan[requirements]'

### Additional details
Red Hat 8.8  python 3.6.8

**Comment by Pooya-Oladazimi** [comment]
I can confirm this issue. I installed ckan 2.9.9 on Debian 11
I solved it by editing the requirements.txt file and removing the markdown version.

**Comment by kowh-ai** [comment]
mmmm...OK.....CKAN 2.9.9 installs OK on Ubuntu 20.04 (after a slight problem with setuptools)

**Comment by Pooya-Oladazimi** [comment]
I put the error for markdown here just in case: (python 3.9 and Debian 11)
```Building wheel for markdown (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      <string>:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      Converting docs/cli.txt -> build/docs/cli.html
      Traceback (most recent call last):
        File "/usr/lib/ckan/default/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/ckan/default/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/ckan/default/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 234, in <module>
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-dm5qrmw4/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 184, in run
        File "<string>", line 116, in _get_context
        File "build/lib/markdown/__init__.py", line 375, in convert
          newRoot = treeprocessor.run(root)
        File "build/lib/markdown/treeprocessors.py", line 361, in run
          brs = root.getiterator('br')
      AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
      [end of output]
```
