### ISSUE TITLE
`RuntimeError: Working outside of request context` when specifying `email_to` in `ckan.ini`

### ISSUE THREAD

**Issue by paulmueller** [ckan/ckan#7802]
## Describe the bug
When I specify the `email_to` field in `ckan.ini`, I cannot start the app anymore and I get a cryptic `RuntimeError: Working outside of request context` error message.

### Steps to reproduce
Uncomment the email settings in `ckan.ini`:

```
email_to = errors@example.com
error_email_from = ckan-errors@example.com
smtp.server = localhost
#smtp.starttls = False
smtp.user = username@example.com
smtp.password = your_password
smtp.mail_from =
#smtp.reply_to =
```

### Expected behavior
CKAN should start and the `ckan` CLI command should work.

### Additional details
I initially thought that this was a logging issue, because when I removed "ckan" from the `[loggers]: key` configuration option, the error message went away. The issue also goes away when enabling debugging, which is because of a [case that excludes emails being set up in debugging mode](https://github.com/ckan/ckan/blob/ckan-2.10.1/ckan/config/middleware/flask_app.py#L633).

If I uncomment [this line](https://github.com/ckan/ckan/blob/ckan-2.10.1/ckan/config/middleware/flask_app.py#L679), the error message goes away (which is not what I want, just illustrating the issue).

I tried to fix this with a `with app.app_context()`-guard, but to no avail.

Are error emails broken in CKAN 2.10.1, or did I miss something? I noticed this while migrating from CKAN 2.9.5 to 2.10.1.

Full log message of a `ckan db upgrade` call:
<details>

```
2023-09-17 23:24:09,450 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2023-09-17 23:24:09,450 INFO  [ckan.config.environment] Loading static files from public
2023-09-17 23:24:09,641 WARNI [ckan.config.environment] Invalid value for solr_url (None): Missing value
2023-09-17 23:24:09,660 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2023-09-17 23:24:10,058 WARNI [ckanext.reclineview.plugin] The Recline-based views are deprecated andwill be removed in future versions
2023-09-17 23:24:10,072 WARNI [ckan.config.environment] Invalid value for solr_url (None): Missing value
2023-09-17 23:24:10,088 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 33, in <module>
    sys.exit(load_entry_point('ckan', 'console_scripts', 'ckan')())
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 121, in parse_args
    result = super().parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 131, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 140, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 57, in __init__
    self.app = make_app(raw_config)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 29, in make_app
    flask_app = make_flask_stack(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 276, in make_flask_stack
    log.warn(csrf_warn_extensions)
  File "/usr/lib/python3.8/logging/__init__.py", line 1463, in warn
    self.warning(msg, *args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1458, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1598, in handle
    if (not self.disabled) and self.filter(record):
  File "/usr/lib/python3.8/logging/__init__.py", line 811, in filter
    result = f.filter(record)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 644, in filter
    log_record.url = request.path
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 436, in __get__
    obj = instance._get_current_object()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 565, in _get_current_object
    return self.__local()  # type: ignore
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/globals.py", line 33, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

Since turning off email notifications is not an option for me, I am also looking for a quick fix (such ass the `app.app_context()` guard, which I do not fully understand and which maybe because of that did not work).

</details>

**Comment by Zharktas** [comment]
The error email handler tries to catch all errors caused by the end users so it tries to parse various information from the request, which obviously doesn't exist when the error originates from CLI command. Alternatives for this is to try to deduce if the error originate from cli and then not send the email or fix the error caused by the cli command. 

The error handler currently catches warnings as well which is the real cause for this stack trace.  Based on the stack trace it originates from here: https://github.com/ckan/ckan/blob/831ff5dcd74236d23d4fc0018baa71e9614332bf/ckan/config/middleware/flask_app.py#L242

**Comment by paulmueller** [comment]
@Zharktas thanks for your reply and thanks for the explanation. As far as I understand, properly setting up CSRF would be a workaround for this issue for me (which I planned to do anyway).

**Comment by zlobniyshurik** [comment]
Same problem on 2.10.3. 
If `email_to` or `error_email_from` are not empty, than I got
```
RuntimeError: Working outside of request context.
```
