### ISSUE TITLE
Error in button delete dataset

### ISSUE THREAD

**Issue by MiguelGuzmanDev** [ckan/ckan#7809]
## CKAN version
2.9

## Describe the bug
Deleting a dataset from the ckan button in the path mickan.com/dataset/namedataset/resource/id_resurce/edit does not generate any action.

I get this error in browser console:

```
Uncaught TypeError: element.modal is not a function
    at Module.createModal (b8576d9c_ckan.js:4:248)
    at Module.confirm (b8576d9c_ckan.js:3:1151)
    at Module._onClick (b8576d9c_ckan.js:5:74)
    at HTMLAnchorElement.proxy (d8ae4bed_jquery.js:672:57)
    at HTMLAnchorElement.dispatch (d8ae4bed_jquery.js:325:476)
    at elemData.handle (d8ae4bed_jquery.js:311:166)
```
my installation is from: [How to Install CKAN 2.9 on CentOS 7](https://github.com/ckan/ckan/wiki/How-to-Install-CKAN-2.9-on-CentOS-7)

### Steps to play
access a dataset mickan.com/dataset/namedataset/resource/id_resurce/edit and delete with the button

### Expected behavior
You must delete the dataset

### Additional details
We have only been able to delete it via url mickan.com/NAME_DATASET/resource/ID_RESOURCE/delete but this should work from the btn

**Comment by Zharktas** [comment]
It seems that your javascript has some fault in it, the core ckan itself has had working bootstrap modals for ages and the error is not coming from default install.

**Comment by MiguelGuzmanDev** [comment]
I can't understand your answer, on my CKan side, what should I do?

**Comment by wardi** [comment]
@MiguelGuzmanDev as far as we know this error doesn't happen on a default install. Is it possible it's caused by some customization on your instance?

**Comment by MiguelGuzmanDev** [comment]
My instance is not customized, the error is original, the error occurred in two instances installed from scratch, that is why I published it as an error.
