### ISSUE TITLE
KeyError: 'face_type'

### ISSUE THREAD

**Issue by PortarescuOctavian** [ckan/ckan#7870]
```
ckan   | Traceback (most recent call last):
ckan   |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
ckan   |     rv = self.dispatch_request()
ckan   |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
ckan   |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
ckan   |   File "/ckan/src/ckan/ckan/config/middleware/../../views/dataset.py", line 387, in search
ckan   |     return base.render(
ckan   |   File "/ckan/src/ckan/ckan/lib/base.py", line 107, in render
ckan   |     return flask_render_template(template_name, **extra_vars)
ckan   |   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
ckan   |     return _render(
ckan   |   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
ckan   |     rv = template.render(context)
ckan   |   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
ckan   |     self.environment.handle_exception()
ckan   |   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
ckan   |     raise rewrite_traceback_stack(source=source)
ckan   |   File "/ckan/src/ckan/ckan/templates/package/search.html", line 2, in top-level template code
ckan   |     {% import 'macros/form.html' as form %}
ckan   |   File "/ckan/src/ckan/ckan/templates/page.html", line 1, in top-level template code
ckan   |     {% extends "base.html" %}
ckan   |   File "/ckan/src_extensions/ckanext-dategovmd_theme/ckanext/dategovmd_theme/templates/base.html", line 1, in top-level template code
ckan   |     {% ckan_extends %}
ckan   |   File "/ckan/src/ckan/ckan/templates/base.html", line 108, in top-level template code
ckan   |     {%- block page %}{% endblock -%}
ckan   |   File "/ckan/src/ckan/ckan/templates/page.html", line 19, in block 'page'
ckan   |     {%- block content %}
ckan   |   File "/ckan/src/ckan/ckan/templates/page.html", line 22, in block 'content'
ckan   |     {% block main_content %}
ckan   |   File "/ckan/src/ckan/ckan/templates/page.html", line 48, in block 'main_content'
ckan   |     <div class="row wrapper{% block wrapper_class %}{% endblock %}{% if self.secondary()|trim == '' or c.action=='resource_read' %} no-nav{% endif %}">
ckan   |   File "/ckan/src/ckan/ckan/templates/page.html", line 70, in block 'secondary'
ckan   |     {% block secondary_content %}{% endblock %}
ckan   |   File "/ckan/src/ckan/ckan/templates/package/search.html", line 76, in block 'secondary_content'
ckan   |     {{ h.snippet('snippets/facet_list.html', title=facet_titles[facet], name=facet, search_facets=search_facets) }}
ckan   |   File "/ckan/src/ckan/ckan/lib/helpers.py", line 1776, in snippet
ckan   |     return base.render_snippet(template_name, **kw)
ckan   |   File "/ckan/src/ckan/ckan/lib/base.py", line 72, in render_snippet
ckan   |     output = render(template_name, extra_vars=kw)
ckan   |   File "/ckan/src/ckan/ckan/lib/base.py", line 107, in render
ckan   |     return flask_render_template(template_name, **extra_vars)
ckan   |   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
ckan   |     return _render(
ckan   |   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
ckan   |     rv = template.render(context)
ckan   |   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
ckan   |     self.environment.handle_exception()
ckan   |   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
ckan   |     raise rewrite_traceback_stack(source=source)
ckan   |   File "/ckan/src/ckan/ckan/templates/snippets/facet_list.html", line 39, in top-level template code
ckan   |     {% block facet_list %}
ckan   |   File "/ckan/src/ckan/ckan/templates/snippets/facet_list.html", line 43, in block 'facet_list'
ckan   |     {% block facet_list_item %}
ckan   |   File "/ckan/src/ckan/ckan/templates/snippets/facet_list.html", line 51, in block 'facet_list_item'
ckan   |     {% block facet_list_items %}
ckan   |   File "/ckan/src/ckan/ckan/templates/snippets/facet_list.html", line 76, in block 'facet_list_items'
ckan   |     <a href="{{ h.remove_url_param('_%s_limit' % name, replace=0, extras=extras, alternative_url=alternative_url) }}" class="read-more">{{ _('Show More {facet_type}').format(facet_type=title) }}</a>
ckan   |   File "/usr/lib/python3.10/site-packages/markupsafe/__init__.py", line 214, in format
ckan   |     return self.__class__(formatter.vformat(self, args, kwargs))
ckan   |   File "/usr/lib/python3.10/string.py", line 165, in vformat
ckan   |     result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
ckan   |   File "/usr/lib/python3.10/string.py", line 205, in _vformat
ckan   |     obj, arg_used = self.get_field(field_name, args, kwargs)
ckan   |   File "/usr/lib/python3.10/string.py", line 270, in get_field
ckan   |     obj = self.get_value(first, args, kwargs)
ckan   |   File "/usr/lib/python3.10/string.py", line 227, in get_value
ckan   |     return kwargs[key]
ckan   | KeyError: 'face_type'
```

Help me please on this issue.

**Comment by amercader** [comment]
Hi @PortarescuOctavian please provide a bit more details when you create an issue, like the CKAN version you are using or any specific customizations you've made.

In this case the error is caused because the `'Show More {facet_type}` string was translated incorrectly in one of the translation files (Probably changing the key to `{face_type}`. What language are you using on your CKAN site? Does changing the language solve the issue?
