### ISSUE TITLE
Python 3.12 support / Pyutillib replacement

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#7952]
Changes are needed for CKAN to run on Python 3.12
*  There are a couple of requirements listed in `requirements.txt` that are incompatible (`greenlet` needs to be bumped to 3.0.1 and lxml to 4.9.3)
* Pyutilib does not work on py3.12:
```
ckan generate config
Traceback (most recent call last):
  File "/home/adria/.pyenv/versions/ckan-ml/bin/ckan", line 5, in <module>
    from ckan.cli.cli import ckan
  File "/home/adria/dev/pyenvs/ckan-ml/ckan/ckan/cli/cli.py", line 12, in <module>
    import ckan.plugins as p
  File "/home/adria/dev/pyenvs/ckan-ml/ckan/ckan/plugins/__init__.py", line 3, in <module>
    from ckan.plugins.core import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adria/dev/pyenvs/ckan-ml/ckan/ckan/plugins/core.py", line 15, in <module>
    from pyutilib.component.core import PluginGlobals, implements
  File "/home/adria/.pyenv/versions/3.12.0/envs/ckan-ml/lib/python3.12/site-packages/pyutilib/component/__init__.py", line 18, in <module>
    from . import executables
  File "/home/adria/.pyenv/versions/3.12.0/envs/ckan-ml/lib/python3.12/site-packages/pyutilib/component/executables/__init__.py", line 13, in <module>
    from pyutilib.component.executables.executable import IExternalExecutable, ExternalExecutable
  File "/home/adria/.pyenv/versions/3.12.0/envs/ckan-ml/lib/python3.12/site-packages/pyutilib/component/executables/executable.py", line 10, in <module>
    import pyutilib.misc
  File "/home/adria/.pyenv/versions/3.12.0/envs/ckan-ml/lib/python3.12/site-packages/pyutilib/misc/__init__.py", line 21, in <module>
    from pyutilib.misc.import_file import import_file, run_file
  File "/home/adria/.pyenv/versions/3.12.0/envs/ckan-ml/lib/python3.12/site-packages/pyutilib/misc/import_file.py", line 11, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

```

The library seems unmaintained, this particular issue was raised [3 years ago](https://github.com/PyUtilib/pyutilib/issues/111), so it seems it's time to look for a replacement. Usage of pyutilib is restricted, but very critical, as it's the backend of the [plugins system](https://github.com/ckan/ckan/blob/b180fdbf1fa983a7b7ee111efd44568c606396ef/ckan/plugins/core.py#L15) and the [plugin interfaces](https://github.com/ckan/ckan/blob/b180fdbf1fa983a7b7ee111efd44568c606396ef/ckan/plugins/interfaces.py#L14). So this will require careful planning.

**Comment by amercader** [comment]
Regarding the pyutilib replacement, some options discussed during the dev meeting:

* Re-implement the necessary logic ourselves
* Vendor or fork just the `pyutilib.components.core` module
* Explore using other plugin systems like [pluggy](https://github.com/pytest-dev/pluggy)

**Comment by EricSoroos** [comment]
The sanitize_url test failure is a change in behavior in python 3.12:
```
Python 3.10.13 (main, Aug 24 2023, 22:36:46) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.parse import urlparse
>>> urlparse('sh+eme://[net:loc]:12345/a/path?a=b&c=d')
ParseResult(scheme='sh+eme', netloc='[net:loc]:12345', path='/a/path', params='', query='a=b&c=d', fragment='')
>>>
```

```
Python 3.12.0 (main, Nov 29 2023, 03:32:06) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.parse import urlparse
>>> urlparse('sh+eme://[net:loc]:12345/a/path?a=b&c=d')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/urllib/parse.py", line 395, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 500, in urlsplit
    _check_bracketed_host(bracketed_host)
  File "/usr/local/lib/python3.12/urllib/parse.py", line 446, in _check_bracketed_host
    ip = ipaddress.ip_address(hostname) # Throws Value Error if not IPv6 or IPv4
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'net:loc' does not appear to be an IPv4 or IPv6 address
```

**Comment by Gauravp-NEC** [comment]
> Changes are needed for CKAN to run on Python 3.12
> 
> * There are a couple of requirements listed in `requirements.txt` that are incompatible (`greenlet` needs to be bumped to 3.0.1 and lxml to 4.9.3)

@smotornyuk @amercader , I have raised the PR https://github.com/ckan/ckan/pull/7960 to fix the first sub-point of this issue.

**Comment by smotornyuk** [comment]
Closing as 3.12 is supported by CKAN. New similar issue can be found at #9237
