### ISSUE TITLE
Activity Stream Changes link

### ISSUE THREAD

**Issue by blagojabozinovski** [ckan/ckan#8034]
## CKAN version
CKAN 2.10.3

## Describe the bug
Activity Stream Changes link breaks

### Steps to reproduce
Login to CKAN and create a new dataset and add resource. Go to Activity stream and hit the oldest Changes link

### Expected behavior
Show the Changes

### Additional details
Full stack trace of the error raised
Traceback (most recent call last):
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 157, in dispatch_request
    return view_func(**req.view_args)
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckanext/activity/views.py", line 404, in package_changes
    return tk.render(
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckanext/activity/templates/package/changes.html", line 1, in top-level template code
    {% extends "package/base.html" %}
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/templates/package/base.html", line 4, in top-level template code
    {% set dataset_type = dataset_type or pkg.type or 'dataset' %}
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckanext/activity/templates/page.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckanext/activity/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/templates/base.html", line 108, in top-level template code
    {%- block page %}{% endblock -%}
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/templates/page.html", line 19, in block 'page'
    {%- block content %}
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/templates/page.html", line 22, in block 'content'
    {% block main_content %}
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/templates/page.html", line 74, in block 'main_content'
    {% block primary %}
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckanext/activity/templates/package/changes.html", line 43, in block 'primary'
    {% snippet "package/snippets/change_item.html", activity_diff=activity_diffs[i], pkg_dict=pkg_dict %}
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/lib/jinja_extensions.py", line 277, in _call
    return base.render_snippet(*args, **kwargs)
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/lib/base.py", line 72, in render_snippet
    output = render(template_name, extra_vars=kw)
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckanext/activity/templates/package/snippets/change_item.html", line 6, in top-level template code
    {% snippet "snippets/changes/{}.html".format(
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/lib/jinja_extensions.py", line 277, in _call
    return base.render_snippet(*args, **kwargs)
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/lib/base.py", line 72, in render_snippet
    output = render(template_name, extra_vars=kw)
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckanext/activity/templates/snippets/changes/new_resource.html", line 2, in top-level template code
    {% set pkg_url = h.url_for(dataset_type ~ '.read', id=change.pkg_id) %}
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/lib/helpers.py", line 385, in url_for
    my_url = _url_for_flask(*args, **kw)
  File "/home/blagoja/Projects/CKAN/kepa/ckan/ckan/lib/helpers.py", line 443, in _url_for_flask
    my_url = _flask_default_url_for(*args, **kw)
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/home/blagoja/Envs/kepa02/lib/python3.8/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'activity.read' with values ['id']. Did you mean 'dataset.read' instead?

**Comment by duttonw** [comment]
fyi, #8035 was reverted on https://github.com/ckan/ckan/pull/8040 
was also cherry-picked into master on commit https://github.com/ckan/ckan/commit/5fd49136d0ebf1a7c64d9cc2a49c7703693b4bdf
