### ISSUE TITLE
HTTP 500 when trying to save admin config (validator function issue)

### ISSUE THREAD

**Issue by Lana-chan** [ckan/ckan#8156]
## CKAN version
2.10.4

## Describe the bug
CKAN throws Internal Server Error when trying to save any admin settings.

### Steps to reproduce
Visit /ckan-admin/config, make any changes and try to save config.

### Expected behavior
The page reloads with the new site config applied.

### Additional details
```
2024-04-04 20:27:50,159 ERROR [ckan.config.middleware.flask_app] str cannot be used as validator because it is not a user-defined function
Traceback (most recent call last):
  File "/home/ckan/ckan/lib/plymouth/src/ckan/ckan/lib/navl/dictization_functions.py", line 246, in convert
    nargs = converter.__code__.co_argcount
AttributeError: type object 'str' has no attribute '__code__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ckan/plymouth/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/plymouth/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/ckan/plymouth/lib/python3.10/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/lib/ckan/plymouth/lib/python3.10/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/home/ckan/ckan/lib/plymouth/src/ckan/ckan/config/middleware/../../views/admin.py", line 120, in post
    data = logic.get_action(u'config_option_update')({
  File "/home/ckan/ckan/lib/plymouth/src/ckan/ckan/logic/__init__.py", line 580, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/ckan/ckan/lib/plymouth/src/ckan/ckan/logic/action/update.py", line 1281, in config_option_update
    data, errors = _validate(data_dict, schema, context)
  File "/home/ckan/ckan/lib/plymouth/src/ckan/ckan/lib/navl/dictization_functions.py", line 305, in validate
    flat_data, errors = _validate(flattened, schema, validators_context)
  File "/home/ckan/ckan/lib/plymouth/src/ckan/ckan/lib/navl/dictization_functions.py", line 356, in _validate
    convert(converter, key, converted_data, errors, context)
  File "/home/ckan/ckan/lib/plymouth/src/ckan/ckan/lib/navl/dictization_functions.py", line 248, in convert
    raise TypeError(
TypeError: str cannot be used as validator because it is not a user-defined function
2024-04-04 20:27:50,232 INFO  [ckan.config.middleware.flask_app]  500 /ckan-admin/config render time 0.133 seconds
```

I have looked at other similar issues but I cannot find any indication that attributes this to any extensions I have installed. None of our extensions should be overriding ckan-admin/config. I cannot find any documentation to tell if we have an older setting somewhere (server has been running contiguously upgrading since CKAN 2.7) that overrides what validator function ckan-admin/config should be using.

```
(plymouth) ckan@plymouth2:~$ pip show flask
Name: Flask
Version: 2.0.3
Summary: A simple framework for building complex web applications.
Home-page: https://palletsprojects.com/p/flask
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /home/ckan/ckan/lib/plymouth/lib/python3.10/site-packages
Requires: click, itsdangerous, Jinja2, Werkzeug
Required-by: Flask-Babel, Flask-DebugToolbar, Flask-Login, flask-multistatic, Flask-WTF
```

```
ckan.plugins = activity status text_view image_view pdf_view geo_view geojson_view datatables_view datastore xloader resource_proxy recline_view recline_grid_view recline_graph_view tdp pcc
```

**Comment by amercader** [comment]
Thanks for the detailed report @Lana-chan 

Starting from CKAN 2.10 Python built-in functions can not be used as validators. There are none of these left in CKAN core, so it must be a validator from a schema defined in one of your plugins. Looking at the stacktrace, the action `config_option_update` uses the `udpate_configuration_schema`, that will [import schemas](https://github.com/ckan/ckan/blob/18cda5ec956afeae03121bb3e798d93596f1c451/ckan/logic/schema.py#L776) from plugins to add editable config options.

Check your list of plugins (must be one of `status tdp pcc`) and look for ones that implement the `IConfigurer.update_config_schema()` method. One or more schema fields there are using `str` as validator, you need to replace it with `unicode_safe`, eg change:

```python
schema = {
    "my_field": [ignore_missing, str]
}
```

to

```python
unicode_safe = toolkit.get_validator("unicode_safe")
schema = {
    "my_field": [ignore_missing, unicode_safe]
}
```

Hope this helps
