### ISSUE TITLE
License Schema Needed(?)

### ISSUE THREAD

**Issue by JVickery-TBS** [ckan/ckan#8263]
## CKAN version

2.10

## Describe the bug

With a custom license group defined with `licenses_group_url` config option, the custom licenses can cause 500 errors if missing certain attributes.

### Steps to reproduce

- Make a custom JSON license definition file;
- Exclude a required attribute such as `osd_conformance` or `od_conformance`;
- Define JSON file location in `licenses_group_url`;
- Add a new Dataset/Package and select the license;
- Get error.

### Expected behavior

Preferably there is no fatal error and the framework is able to validate custom licenses in a license group. Not sure if this would be a schema for the licenses and that would run at run-time or when creating/updating a Dataset.

### Additional details
Stack trace:
```
Traceback (most recent call last):
  File "/srv/app/ckan/registry/src/ckan/ckan/model/license.py", line 37, in __getattr__
    return self._data[name]
KeyError: 'osd_conformance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/app/ckan/registry/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/srv/app/ckan/registry/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/app/ckan/registry/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/app/ckan/registry/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/app/ckan/registry/lib/python3.9/site-packages/flask_debugtoolbar/__init__.py", line 142, in dispatch_request
    return view_func(**req.view_args)
  File "/srv/app/ckan/registry/lib/python3.9/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/srv/app/ckan/registry/lib/python3.9/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/srv/app/ckan/registry/src/ckanext-canada/ckanext/canada/view.py", line 167, in post
    response = super(CanadaDatasetCreateView, self).post(package_type)
  File "/srv/app/ckan/registry/src/ckan/ckan/views/dataset.py", line 585, in post
    pkg_dict = get_action(u'package_create')(context, data_dict)
  File "/srv/app/ckan/registry/src/ckan/ckan/logic/__init__.py", line 580, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/ckan/registry/src/ckan/ckan/logic/action/create.py", line 250, in package_create
    return _get_action('package_show')(
  File "/srv/app/ckan/registry/src/ckan/ckan/logic/__init__.py", line 580, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/ckan/registry/src/ckan/ckan/logic/action/get.py", line 1053, in package_show
    package_dict = model_dictize.package_dictize(
  File "/srv/app/ckan/registry/src/ckan/ckan/lib/dictization/model_dictize.py", line 257, in package_dictize
    else pkg.isopen()
  File "/srv/app/ckan/registry/src/ckan/ckan/model/package.py", line 247, in isopen
    if self.license and self.license.isopen():
  File "/srv/app/ckan/registry/src/ckan/ckan/model/license.py", line 46, in isopen
    self.osd_conformance == 'approved'
  File "/srv/app/ckan/registry/src/ckan/ckan/model/license.py", line 41, in __getattr__
    raise AttributeError(*e.args)
AttributeError: osd_conformance
```

**Comment by JVickery-TBS** [comment]
discussed with @wardi and setting the `od_conformance` and `osd_conformance` to default to `False` will be enough here. PR to fix: https://github.com/ckan/ckan/pull/8268

**Comment by JVickery-TBS** [comment]
This was fixed with: https://github.com/ckan/ckan/pull/8268
