### ISSUE TITLE
Sometimes Internal Server Error is occurred on CKAN UI while adding Resource

### ISSUE THREAD

**Issue by kumardeepak5** [ckan/ckan#8333]
## CKAN version
2.10.1
I have set up the CKAN Docker setup by following this link: https://github.com/ckan/ckan-docker
## Describe the bug
While adding resources on the CKAN UI, getting 500 internal server error on the UI.

### Steps to reproduce

1. Login to CKAN UI
2. Add Organization and dataset
3. Try to add Resource file (CSV) multiple time in created dataset.

### Error in CKAN Logs
```
Traceback (most recent call last): File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen retries = retries.increment( File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment raise six.reraise(type(error), error, _stacktrace) File "/usr/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise raise value File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request self._raise_timeout(err=e, url=url, timeout_value=read_timeout) File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout raise ReadTimeoutError( urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='datapusher', port=8800): Read timed out. (read timeout=5)
``` 
### Error in Datapusher Logs
```
Tue Jul  9 07:54:32 2024 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during POST /job (192.168.0.3)
OSError: write error
```
### Expected behavior
500 internal server error should not be displayed on the UI and connection read timeout error should not be occurred.

### Additional details
I have observed a read timeout error in the CKAN logs while submitting the job to the data pusher. I tried increasing the ckan.request.timeout value from 5 to 10 and then to 15 in the ckan.ini file. As a result, the frequency of the issue has been reduced.
Does this issue still exist, or is there any solution for this issue?

**Comment by kowh-ai** [comment]
This is not normal and shouldn't happen. 

- How large is the resource file?
- How is your CKAN Docker environment set up ie: all the containers running on the same host/machine?
- If so what are the specs of the host?

**Comment by kumardeepak5** [comment]
> This is not normal and shouldn't happen.
> 
> * How large is the resource file?
We have tried 30 csv file uploads by randomly choosing file out of 3 files of size 1kb, 3kb and 289kb.
> * How is your CKAN Docker environment set up ie: all the containers running on the same host/machine?
Yes, Ckan and Datapusher are running on same Host.
> * If so what are the specs of the host?
below is host spec
	Memory - total-7.6G, Available-5.9G
	CPUS- 4 (Intel Core Processor (Broadwell, IBRS)
	OS - CentOS Linux 7 (Core)

**Comment by bhavin2897** [comment]
Hello, 
As the issue is still open, Would like to know if there is a process on this issue? What is the on-going solution?

We have a large database with 140,000+ datasets currently, and happen to occur this error occasionally. 
Tried changing the uwsgi configurations to get a temporary solution to buy time. 

Hoping for an upgraded solution, if solved. 
Thanks
