### ISSUE TITLE
CKAN login breaks when setting to beaker.session.data_serializer cookie setting to json

### ISSUE THREAD

**Issue by rosinaderks** [ckan/ckan#8379]
## CKAN version
2.10.4

## Describe the bug
When upgrading from CKAN 2.9.11 to 2.10.4 with the recommended settings from the changelog for Beaker and Flask authentication, login breaks and shows a blank page (Chrome) or nothing happens (Firefox). CKAN crashes with the following error message: "TypeError: Object of type datetime is not JSON serializable" (see full error message below). We see two cookies set when trying to login, ckan and remember_token (see image below). 

The setting for beaker.session.data_serializer to json seems to break the setup, when this is not set, login works fine. It seems that within CKAN a date is added in the cookie which cannot be JSON serialized?

I followed the changelog (https://docs.ckan.org/en/2.10/changelog.html) where the settings for 2.10.1 migration guide are used.

### Steps to reproduce
This setup does not setup the flask remember_me cookie, as the issues seems to lie within the beaker session cookie. 

- git clone https://github.com/ckan/ckan-docker.git
- cd ckan-docker
- cp .env.example .env
- Edit .env and set 
  - line 30 to: CKAN_VERSION=2.10.4
  - line 32 to: CKAN_SITE_URL=http://localhost:5000
  - Add after line 32:
CKAN___BEAKER__SESSION__KEY=ckan
CKAN___BEAKER__SESSION__TYPE=cookie
CKAN___BEAKER__SESSION__SECRET=arandomstring
CKAN___BEAKER__SESSION__VALIDATE_KEY=arandomstring
CKAN___BEAKER__SESSION__DATA_SERIALIZER=json
CKAN___BEAKER__SESSION__COOKIE_EXPIRES=true
CKAN___BEAKER__SESSION__SAVE_ACCESSED_TIME=false
CKAN___BEAKER__SESSION__SECURE=true
CKAN___BEAKER__SESSION__HTTPONLY=true
CKAN___BEAKER__SESSION__SAMESITE=strict
- docker compose -f docker-compose.dev.yml --env-file .env up --build -d
- Navigate to http://localhost:5000/user/login
- Try and log in as ckan_admin:test1234
- Login fails with a 500, and the error TypeError: Object of type datetime is not JSON serializable. Whole of localhost:5000 is now unavailable.
- Manually delete the ckan cookie and localhost is available again.

### Expected behavior
During the update to 2.10.4, we want to set data_serializer to json for security issues around pickle. We expected no login issues after setting the repoze.who settings to Flask and the beaker settings to json. 

### Additional details

**Error message when after login**
ckan   | Debugging middleware caught exception in streamed response at a point where response headers were already sent.
ckan   | Traceback (most recent call last):
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/flask/app.py", line 2080, in wsgi_app
ckan   |     return response(environ, start_response)
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 632, in __call__
ckan   |     start_response(status, headers)
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/middleware.py", line 150, in session_start_response
ckan   |     session.persist()
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/session.py", line 880, in persist
ckan   |     self._session().save()
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/session.py", line 723, in save
ckan   |     self._create_cookie()
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/session.py", line 737, in _create_cookie
ckan   |     val = self._encrypt_data()
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/session.py", line 381, in _encrypt_data
ckan   |     data = self.serializer.dumps(session_data)
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/util.py", line 469, in dumps
ckan   |     return zlib.compress(json.dumps(data).encode('utf-8'))
ckan   |   File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
ckan   |     return _default_encoder.encode(obj)
ckan   |   File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
ckan   |     chunks = self.iterencode(o, _one_shot=True)
ckan   |   File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
ckan   |     return _iterencode(o, 0)
ckan   |   File "/usr/lib/python3.10/json/encoder.py", line 179, in default
ckan   |     raise TypeError(f'Object of type {o.__class__.__name__} '
ckan   | TypeError: Object of type datetime is not JSON serializable
ckan   | 2024-07-30 09:07:05,063 INFO  [ckan.config.middleware.flask_app]  404 /webassets/webassets-external/activity.css.map render time 0.016 seconds
ckan   | Debugging middleware caught exception in streamed response at a point where response headers were already sent.
ckan   | Traceback (most recent call last):
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/flask/app.py", line 2080, in wsgi_app
ckan   |     return response(environ, start_response)
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 632, in __call__
ckan   |     start_response(status, headers)
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/middleware.py", line 150, in session_start_response
ckan   |     session.persist()
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/session.py", line 880, in persist
ckan   |     self._session().save()
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/session.py", line 723, in save
ckan   |     self._create_cookie()
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/session.py", line 737, in _create_cookie
ckan   |     val = self._encrypt_data()
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/session.py", line 381, in _encrypt_data
ckan   |     data = self.serializer.dumps(session_data)
ckan   |   File "/usr/lib/ckan/venv/lib/python3.10/site-packages/beaker/util.py", line 469, in dumps
ckan   |     return zlib.compress(json.dumps(data).encode('utf-8'))
ckan   |   File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
ckan   |     return _default_encoder.encode(obj)
ckan   |   File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
ckan   |     chunks = self.iterencode(o, _one_shot=True)
ckan   |   File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
ckan   |     return _iterencode(o, 0)
ckan   |   File "/usr/lib/python3.10/json/encoder.py", line 179, in default
ckan   |     raise TypeError(f'Object of type {o.__class__.__name__} '
ckan   | TypeError: Object of type datetime is not JSON serializable

**Cookies set after login:**
![image](https://github.com/user-attachments/assets/8f32b5e5-59a7-464b-a229-e0fd3b4c49da)

**Comment by JamieBeverley** [comment]
I'm experiencing this issue with `2.10` as well. I think I've traced it to an issue in `beaker` itself - I was able to reproduce the same error outside of a CKAN context.

I've opened an issue on `beaker` detailing that [here](https://github.com/bbangert/beaker/issues/247)

**Comment by JamieBeverley** [comment]
On closer look, I think there are 2 distinct issues here, 1 specific to beaker, and 1 specific to CKAN 2.10:

## Bug in `beaker`
Details in [this issue](https://github.com/bbangert/beaker/issues/247) in beaker.

The TLDR; to get json-serialized cookies  to work with CKAN 2.10 you may need to set `beaker.session.cookie_expires = true` so long as that works for your setup (at least until/if that bug in beaker gets fixed).

## Issue in CKAN (?)
CKAN 2.10 introduced tracking `last_active` timestamps for users.
> CKAN now records the last time a user was active on the site. The minimum interval between records can be controlled with the ckan.user.last_active_interval config option. (#6466)

A `"last_active"` `datetime` object is saved to the session [here](https://github.com/ckan/ckan/blob/042f6ffd3662e3a41e63a41b9b0c7079decb3b29/ckan/model/user.py#L358C1-L358C58)

So when `beaker` tries to serialize the session to a JSON cookie, it fails with the `TypeError`

## Temporary Workaround
Another work-around is to switch to a server-side session storage (e.g. `beaker.session.type=file`), but that may be a somewhat larger architectural decision and there may be reasons you don't want to use server-side sessions.
