### ISSUE TITLE
Transition to pyproject.toml

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#8382]
In https://github.com/ckan/ckan/pull/6620 setup.py was largely simplified but still some bits remain in old setup.py files. Now with lates pip and setuptools installing extensions as editable for development, there are following warnings:

`DEPRECATION: Legacy editable install of <some_extension> from file:///srv/app/ckanext/<some_extension> (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457`

Should we try to solve the remaining issues and start transitioning to pyproject.toml configurations in extensions and core or do we want to maintain setup.py/setup.cfg configurations ?

**Comment by duttonw** [comment]
ckan core may be simplish, but when you start to add all the extensions, the order of each dependency install starts to matter.  I'd love to see us following and promoting a 'best of breed' way of installing and allowing the mangability of direct from git/tag.  

Unsure if Python has this but in the npm project ecosystem you can point to a repo/branch|commit|tag and it will download, and run the 'prepare' tag to do local "snapshot" style include.

**Comment by EricSoroos** [comment]
@duttonw 

Install order shouldn't matter, and can't matter if the requirements are specified and obeyed. It only matters if you're installing one dependency, and then separately installing another extension with conflicting requirements. If you can't install them together, with one resolution, technically you've got a broken system and one of the extensions is operating outside of it's desired versions. The python system may refuse to run in this case.

There's a definite balancing act with extensions and pinning versions:
1) Don't ever pin a version of a dependency that's part of core ckan.  Requiring a range of versions on CKAN is appropriate.
2) Avoid tight pins on anything that's common and 'stable', e.g. six, requests, pillow.
3) Only have tight/exact pins for things that you're particularly dependent on. 
4) pip install ckanext-foo must install the requirements, it should never be `pip install ckanext-foo ; pip install -r ckanext-foo/requirements.txt`

Then, when someone installs, the pip dependency solver can do the best job getting some combination of all of the requirements. 

Finally, when the person responsible for the system gets a tested build, it's then possible to freeze versions and install from that list, essentially giving the solver the required solution, rather than letting it build up. 

It's certainly possible and common around here to be using git urls (including tags/branches/commits) as the specifier in a requirements file. NPM does some things that python cant' though, in that it allows for multiple conflicting versions of the same code to be installed as dependencies, where python gets one version.

**Comment by duttonw** [comment]
I get ya, we have 19 extensions that we need to play well with each other as well as be installed in the correct order for ckan.ini.

What we have seems to work but is slow and does need a bit of an overhaul since we moved off the now defunct opsworks 'pets' system to Auto Scaling Groups that start clean...

Problem is having things semi pinned for unit testing but also allow slight drift we did not get back to that plugin if we updated one of its dependancies with a patch change.

You can see our set here as well as how it currently installs with chef/puppet:
https://github.com/qld-gov-au/ckan-qld-infrastructure/blob/master/vars/shared-OpenData.var.yml
https://github.com/qld-gov-au/opswx-ckan-cookbook/blob/master/recipes/ckanweb-deploy-exts.rb#L84
https://github.com/qld-gov-au/opswx-ckan-cookbook/blob/master/resources/pip_install_app.rb#L3
 (and yes I think there is a better way but currently too streched to rejig it)

**Comment by EricSoroos** [comment]
Order certainly matters in ckan.ini, and yeah, that's a pain. 

What I'd recommend is look at the string of pip installs that you're doing and see if anything is ever uninstalled. That's the red flag for me.

**Comment by Zharktas** [comment]
What i've been thinking about this is, that we have extension template https://github.com/ckan/ckan/tree/master/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D and various ways to handle installing extensions even in core extensions. We should design and implement modern way to install ckan and extensions and their dependencies, both in production and for development, so that not everyone needs to figure them out on their own. I think ckan core should have a recommendation how to handle them and dependencies, then its about the extension maintainers themselves if they want to move to the recommendation or not.

One alternative to look into is just announced project support in `uv` https://astral.sh/blog/uv-unified-python-packaging

**Comment by amercader** [comment]
Setting aside the debate about dependency management, which I agree would be good to settle once and for all, what it seems clear is that we need to transition to pyproject.toml from the legacy setup.py/setup.cfg regardless or we will have issues with setuptools and co in the future.

**Comment by amercader** [comment]
Good read: https://github.com/pypa/pip/issues/11457#issuecomment-2313932318

**Comment by amercader** [comment]
Let's split the issues into separate points to make them more manageable:

1. Recommended install mechanism in documentation / extension template
2. Deprecation notice about legacy editable installs
3. Centralize build metadata in pyproject.toml vs setup.py / setup.cfg
4. Namespace packages handling
5. Dependencies management (requirements.txt vs define requirements in pyproject.toml / setup.cfg)

### 1. Recommended install mechanism

I think everyone agrees that *ideally* we would recommend a "standard install" in most cases, and only recommend an editable install if users are going to actually work with the extension source (e.g. to develop on it)

Now, "standard install" is not yet set in stone because issues with the other points (namely point 5), but it could look like:
* `pip install ckanext-pdfview` (hopefully we will get there eventually)
* `pip install "ckanext-pdfview @ git+https://github.com/ckan/ckanext-pdfview.git"`
* git clone and `pip install .`

As of today, the easiest is to adapt the extension template README [here](https://github.com/ckan/ckan/blob/ffd2531495946e997c95c43a6659a3c59304ff44/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/README.md?plain=1#L48) to remove the `-e` flag in `pip install`. Once we settle on point 5 we can think about changing the "standard install" mechanism further

### 2. Deprecation notice for editable installs (original report)

The warning is shown when:

1. You do an editable install with pip (`pip install -e .`)
2. There is no `pyproject.toml` file (or using setuptools<64)

That's it. Even a placeholder pyproject.toml file with just `[test]` will get rid of the warning. But of course it's worth understanding the underlying issue. If pip 24.x does not find a pyproject.toml file it will fallback to the legacy command `python setup.py develop`, which [is deprecated](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/#should-setup-py-be-deleted). If it does find the pyproject.toml file, it will use the modern mechanism for editable installs ([PEP 660](https://peps.python.org/pep-0660/)). Starting from pip 25, pip will no longer try to use `python setup.py develop` and always use the modern mechanism.

The minimal [recommended](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#writing-your-pyproject-toml) pyproject.toml file just includes `[build.system]`:

```toml
[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
```

Adding these in the cookiecutter extension template, and to the existing official extensions (the ones we updated for 2.11 in the ckan org) will hopefully reduce the number of scary warnings users see.

We could leave it at that or while we are at it migrate other build metadata options in setup.py / setup.cfg to pyproject.toml (next section)

### 3. Move build metadata to pyproject.toml

To be clear, setup.py and setup.cfg are [not deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#setup-py-deprecated). These are valid configuration files for setuptools, and even modern tools like uv [support them](https://github.com/astral-sh/uv/pull/2634). But it's clear that a lot of tools in the Python ecosystem are migrating towards pyproject.toml so it makes sense to to move metadata there. This is not difficult, if a bit tedious, and once you have a template is easy to migrate existing extensions (see some WIP PRs for [harvest](https://github.com/ckan/ckanext-harvest/pull/554), [dcat](https://github.com/ckan/ckanext-dcat/pull/304), [geoview](https://github.com/ckan/ckanext-geoview/pull/106) and [envvars](https://github.com/ckan/ckanext-envvars/pull/12)).

One thing to note is that if you write a `[project]` section (or table as TOML calls it) with the mandatory `name` and `version` then you can't have other metadata like `authors`, `keywords`, `classifiers` etc in setup.py unless it's marked as `dynamic` or you'll get a lot of warnings.

The only items in the migrated pyproject.toml which need more consideration are the setuptools configuration options (`[tool.setuptools]`), specially `namespace-packages` (next section)

### 4. Namespace packages handling

CKAN extensions are namespace packages, i.e. they all share the `ckanext.` namespace. In setup.py we define `namespace_packages=['ckanext']` to flag this, but adding the corresponding `namespace-packages` item to pyproject.toml makes the install fail with a scary message:

```
pip install -e .
Obtaining file:///home/adria/dev/pyenvs/ckan-py3.9/pypackaging/ckanext-geoview
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      /tmp/pip-build-env-bap3rgpq/overlay/lib/python3.9/site-packages/setuptools/config/expand.py:124: SetuptoolsWarning: File '/home/adria/dev/pyenvs/ckan-py3.9/pypackaging/ckanext-geoview/README.md' cannot be found
        return '\n'.join(
      Traceback (most recent call last):
        File "/home/adria/.pyenv/versions/3.9.16/envs/pypackaging/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/adria/.pyenv/versions/3.9.16/envs/pypackaging/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/adria/.pyenv/versions/3.9.16/envs/pypackaging/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-bap3rgpq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 464, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-bap3rgpq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-bap3rgpq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-bap3rgpq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
        File "/tmp/pip-build-env-bap3rgpq/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-bap3rgpq/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 157, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-bap3rgpq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 608, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-bap3rgpq/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 72, in apply_configuration
          return _apply(dist, config, filepath)
        File "/tmp/pip-build-env-bap3rgpq/overlay/lib/python3.9/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 53, in apply
          _apply_tool_table(dist, config, filename)
        File "/tmp/pip-build-env-bap3rgpq/overlay/lib/python3.9/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 97, in _apply_tool_table
          raise RemovedConfigError("\n".join([cleandoc(msg), suggestion]))
      setuptools.errors.RemovedConfigError: The parameter `tool.setuptools.namespace-packages` was long deprecated
      and has been removed from `pyproject.toml`.
      Please migrate to implicit native namespaces instead.
      See https://packaging.python.org/en/latest/guides/packaging-namespace-packages/.
      [end of output]

```

Here's the documentation on namespace packages:

https://packaging.python.org/en/latest/guides/packaging-namespace-packages/

CKAN extensions use the legacy ["pkg_resources-style"](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages) method (actually it uses the non-recommended fallback to "pkgutil-style" mentioned in the first note :roll_eyes: ). According to the docs:

>  While this approach is no longer recommended, it is widely present in most existing namespace packages. If you are creating a new distribution within an existing namespace package that uses this method then it’s recommended to continue using this as the different methods are not cross-compatible and it’s not advisable to try to migrate an existing package.

So my understanding is that we should keep the `__init__.py` files as they are (i.e. keep using "pkg_resources-style" namespace packages) and omit the `namespace-packages` item to pyproject.toml. Installing the 4 extensions metioned in the previous section with this configuration seems to work fine, but I'd appreciate if someone else could look into the docs and confirm that's their understanding as well.

### 5. Dependencies management

I'll leave that for later as I've run out of time but I agree with @EricSoroos comment in https://github.com/ckan/ckan/issues/8382#issuecomment-2290808930. I'm pretty confident that loose requirements in extensions are possible, and maybe we can document a work around for when conflicts do occur.

**Comment by smotornyuk** [comment]
I experimented with 4th point and it works for me as well. Eventually, support for this old format of namespace definition will be removed. It's not urgent, but the sooner we choose the migration strategy, the better, right?

I cannot find a simple way to make packages compatible with pkg_resources-style(with __init__.py) and naive-style(no __init__.py). There is an option to add a post-install script, that will modify venv's `site-packages` folder and create necessary namespace files, but it's just so wrong, that I don't even consider this option a real solution.

Even if we agree to remove `__init__.py` in all extensions to at some point switch to naive namespaces, this will lock us out of unmaintained extensions. And it's just a hard task to synchronize. On the other hand, it may be a good reason for CKAN v3.

The safer, but more tedious solution would be to create either a different naive namespace (`ckan.ext.PLUGIN`, if we **really** need namespaces for extensions) or a non-namespace(`ckanext_PLUGIN`, like flask plugins). This will be the main entry point of the plugin. And in addition, we keep `ckanext.PLUGIN` with the pkg_resources namespace, which just re-exports everything from `ckan.ext.PLUGIN` or `ckanext_PLUGIN`. This option gives us time for the migration but means that every module in the end will be rewritten from `import ckanext.PLUGIN` to a new form. Even with an automated fix, it's a lot of changes, so the previous option with a controlled immediate switch to naive namespaces may be a much simpler strategy.

**Comment by smotornyuk** [comment]
Re: dependency management

The first exact pin of the library, even if it's a direct dependency of the extension, will cause pain. For example, `shapely` that is used by spatial - it's a cool library and every new version that is still compatible with ckanext-spatial has fantastic improvements. So we often add the latest available version on our projects, as long as it doesn't break tests of ckanext-spatial.

How about such recommendations to dependencies specified in pyproject.toml:

1. MUST: specify all the dependencies in pyproject.toml. Package must be installable via `pip install PACKAGE`, without `-r` or `-c` flags.
2. MAY: specify the lower bound for the version if relying on functionality introduced in this version.
3. SHOULD NOT: specify the upper bound for the version. If new version of dependency is released and it's not compatible with the extension, you can add `!=x.y.z`. In worst case, you can add upper bound, but only when the new incompatible version of the dependency is released. For example, currently there is no v3 of `shapely`, so ckanext-scheming can use `>2` and cannot use `>2, <3`. When `shapely` v3 is released, if it's not compatible with spatial extension, we can temporally add `>2, <3`, but it's better to update code and make it compatible with the new version.
4. MUST NOT: specify exact version of the dependency. Even if the extension doesn't work with other versions, it may cause unsolvable conflicts between extensions. Instead, exact dependency versions must be added as extra requirements. I.e `pip install PLUGIN` installs the loose version and never produces conflicts with extensions. And `pip install PLUGIN[safe]` (note the `[safe]` part) installs exact version of dependency, that is guaranteed to work but may cause conflict. In this way user can generally install `[safe]`, but opt-out from it and somehow solve conflict if `[safe]` breaks dependency tree

**Comment by EricSoroos** [comment]
@smotornyuk I'd add -- Must/Should not set any versions on dependencies that are also dependencies of ckan core.

**Comment by amercader** [comment]
Some interesting comments and pointers here regarding namespace packages in our particular case:

https://github.com/pypa/packaging-problems/issues/813

**Comment by amercader** [comment]
I've created a dedicated issue for the namespace packages https://github.com/ckan/ckan/issues/8465

We can do the same for the requirements when we are ready to progress with that

**Comment by ThrawnCA** [comment]
I'm concerned about the "no upper bounds" rule leading to situations where a production application mysteriously breaks because it turns out that a third-party library released an incompatible (or even broken) update yesterday.

**Comment by Zharktas** [comment]
Upper bounds should be used in cases where newer version actually is incompatible. If upper bounds would be used by default, they hardly get updated ever.

**Comment by ThrawnCA** [comment]
> Upper bounds should be used in cases where newer version actually is incompatible.

But that may mean that you find out it's incompatible when your site suddenly breaks due to an inadequately tested new release being added to PyPI. You then have to go add a pin to the relevant plugin and deploy the patched plugin, just to get your site working properly again. That's going to be an unacceptably reactive approach for organisations that want their production systems to be stable.

**Comment by EricSoroos** [comment]
We had an exact pin fail because of a transitive dependency that was unpinned. (pysolr and setuptools-scm). Boto3 just had a backwards incompatible change somewhere in the middle of the 1.36 (iirc) because they set a flag for S3 by default for a new s3 feature that's not in other S3 compatible systems.

**Comment by Zharktas** [comment]
Over the years I've had a few cases where builds fail due to broken dependencies and those need to be solved then. On the other hand while maintaining `ckanext-qa` for example which isn't actively used, its dependencies seem to be ancient https://github.com/ckan/ckanext-qa/blob/master/requirements.txt and probably riddled with security issues. I'm just guessing its more or less the same with other extensions as well.

**Comment by duttonw** [comment]
Hi @Zharktas , 

For your example, do note that https://github.com/ckan/ckanext-qa/issues/84 was open to uplift said plugin since it is very actively used on data.qld.gov.au (now supporting 2.10 and very soon 2.11). We require it to be in good shape for said security posture.

**Comment by Zharktas** [comment]
@duttonw, I know, i've been looking at it while getting the extension in maintainable state. But the same problem with old dependencies happen with other extensions as well, as the tech team hardly can keep the core ckan extensions up to date.

**Comment by ThrawnCA** [comment]
> But the same problem with old dependencies happen with other extensions as well, as the tech team hardly can keep the core ckan extensions up to date.

That isn't going to be solved by unpinning the transitive dependencies of those extensions, though.

I'm guessing the opposite. An unmaintained plugin with unpinned transitive dependencies will probably just completely break, when dependencies are updated and the plugin isn't revised to match.

**Comment by frafra** [comment]
Are you willing to accept a PR to add dependencies to pyproject.toml as well and do the pinning via `uv export` or similar?

**Comment by ThrawnCA** [comment]
> Are you willing to accept a PR

I'm sure people would be willing to review it.
