### ISSUE TITLE
CKAN 2.11 crash error activities schema missing permission_labels

### ISSUE THREAD

**Issue by brooks-eco** [ckan/ckan#8422]
## CKAN version
2.11

## Describe the bug
crash adding initial sysadmin when "activity" plugin is loaded (default in package install).
It appears the db schema is missing a table column 
ERROR **sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "permission_labels" of relation "activity" does not exist**

### Steps to reproduce

1. bare metal install of Ubuntu 22.04.4 LTS
2. Package install of CKAN 2.11 following [ckan 2.11 docs](https://docs.ckan.org/en/2.11/maintaining/installing/install-from-package.html) completed OK
3. verify CKAN web interface is working
4. Add first sysadmin user as per [Getting Started](https://docs.ckan.org/en/2.11/maintaining/getting-started.html)
5. Error occurs adding user - trace in report below
6. go to browser and try to log in (despite crash adding sysadmin)
7. website will crash out to nginx error.
8. edit config file ckan.ini to remove "activity" from ckan.plugins =
9. sudo supervisorctl restart all
10. CKAN working again

FWIW The error persists following ckan db clean > ckan db init provided ckan.plugins = activity

Running without activity all works as expected.

### Expected behavior
expected to add sysadmin user without crash and be able to use activity plugin in CKAN as it is included in the package install default ini as `ckan.plugins = activity`

### Additional details

removing the activity plugin allows CKAN to run.

This bug was first encountered in the AWS image AWS Marketplace: CKAN 2.11 pre-configured by Link Digital
which by default does NOT have activity loaded -  adding "activity" to ckan.plugins crashed a running test system.  Removing activity brings CKAN 2.11 back from the dead.  Confirmed on a clean deployment. and then confirmed again by fresh package install to ubuntu.

consol log of traceback following  ckan -c /etc/ckan/default/ckan.ini sysadmin add ckan

`
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "permission_labels" of relation "activity" does not exist
LINE 1: ..._id, object_id, revision_id, activity_type, data, permission...
                                                             ^

The above exception was the direct cause of the following exception:

...snip traceback...

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "permission_labels" of relation "activity" does not exist
LINE 1: ..._id, object_id, revision_id, activity_type, data, permission...
                                                             ^

[SQL: INSERT INTO activity (id, timestamp, user_id, object_id, revision_id, activity_type, data, permission_labels) VALUES (%(id)s, %(timestamp)s, %(user_id)s, %(object_id)s, %(revision_id)s, %(activity_type)s, %(data)s, %(permission_labels)s)]
[parameters: {'id': '77746ab6-ac0f-46f2-92f3-b08b03ab2a3f', 'timestamp': datetime.datetime(2024, 9, 6, 12, 37, 47, 222461), 'user_id': '80181750-bb2e-4710-a8e8-dd56215fb42c', 'object_id': '80181750-bb2e-4710-a8e8-dd56215fb42c', 'revision_id': None, 'activity_type': 'new user', 'data': None, 'permission_labels': None}]
(Background on this error at: https://sqlalche.me/e/14/f405)
`

### Lastly
 I am not familiar with postgres at all.  If it is possible to fix this by creating the missing table column in the consol I'd appreciate a point in the right direction.  I can follow instructions and tried a dbdump > db clean > db init  but this

**Comment by brooks-eco** [comment]
poking around I found ....
[
/usr/lib/ckan/default/src/ckan/ckanext/activity/migration/activity/versions/71713a055d5c_add_permission_labels_in_activity_table.py](https://github.com/ckan/ckan/blob/master/ckanext/activity/migration/activity/versions/71713a055d5c_add_permission_labels_in_activity_table.py)

This file is present in 2.11 but I have no idea how to use it 🤔  However it does give clue to bug origin and fix

**Comment by brooks-eco** [comment]
many thanks - sorry I think I was editing my post when you replied.

I did try  `ckan db upgrade`  with the activated plugin and it did not resolve the issue.

**Comment by brooks-eco** [comment]
detailed report of another clean install

again the initial `ckan db init` and `ckan db upgrade` are not picking up the activity table db migration file that the pkg installs to:

> /usr/lib/ckan/default/src/ckan/ckanext/activity/migration/activity/versions/71713a055d5c_add_permission_labels_in_activity_table.py

Shouldn't  `permission_labels` column be included in the initial schema for a clean **2.11** `ckan db init` ...without relying on a patch?

This time I verified that `ckan.plugins = activity` was present in the ini after the initial install

1. `ckan db init`
2. ckecked that "permission_labels" was NOT in the activity table
3. `ckan db pending-migrations --apply`
4. `ckan db upgrade`  **(no changes made)**

so I deleted the entire database and started fresh this time with `ckan.plugins =`  and reload before the first `ckan db init`.
then I added back `ckan.plugins = activity` and recycled the server before `ckan db upgrade`  
again no changes made and permission_labels column missing from activity table



On a fresh clean install with no activity recorded the issue was fixed manually with:

```
sudo -u postgres psql ckan_default
ALTER TABLE activity ADD COLUMN permission_labels TEXT[];
```

For my other installed system that had accrued some data in the activity table during testing I was able to get it working by using (might help others)
```
sudo -u postgres psql ckan_default
ALTER TABLE activity ALTER COLUMN permission_labels TYPE TEXT[] USING (NULLIF(permission_labels, '')::text[]);
```



Log showing first `ckan db init` and  check of activity table
```
(default) ubuntu@ip-172-31-3-204:/usr/lib/ckan/default$ sudo ckan db init
2024-09-19 17:24:23,516 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2024-09-19 17:24:23,516 INFO  [ckan.config.environment] Loading static files from public
2024-09-19 17:24:23,765 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates
2024-09-19 17:24:24,043 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
2024-09-19 17:24:25,818 INFO  [ckan.model] CKAN database version upgraded: base -> 4a5e3465beb6 (head)
Upgrading DB: SUCCESS
(default) ubuntu@ip-172-31-3-204:/usr/lib/ckan/default$ sudo -u postgres psql ckan_default
psql (14.13 (Ubuntu 14.13-0ubuntu0.22.04.1))
Type "help" for help.

ckan_default=# \d activity
                           Table "public.activity"
    Column     |            Type             | Collation | Nullable | Default
---------------+-----------------------------+-----------+----------+---------
 id            | text                        |           | not null |
 timestamp     | timestamp without time zone |           |          |
 user_id       | text                        |           |          |
 object_id     | text                        |           |          |
 revision_id   | text                        |           |          |
 activity_type | text                        |           |          |
 data          | text                        |           |          |
Indexes:
    "activity_pkey" PRIMARY KEY, btree (id)
    "idx_activity_object_id" btree (object_id, "timestamp")
    "idx_activity_user_id" btree (user_id, "timestamp")
Referenced by:
    TABLE "activity_detail" CONSTRAINT "activity_detail_activity_id_fkey" FOREIGN KEY (activity_id) REFERENCES activity(id)
ckan_default=# \q
```
followed by  `ckan db upgrade` and the patch is still not applied:
- database version remains as: 4a5e3465beb6
-  permission_labels not visible in activity table).:
```
(default) ubuntu@ip-172-31-3-204:/usr/lib/ckan/default$ sudo ckan db upgrade
2024-09-19 17:27:05,992 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2024-09-19 17:27:05,992 INFO  [ckan.config.environment] Loading static files from public
2024-09-19 17:27:06,320 WARNI [ckan.common] Option lang is not declared
2024-09-19 17:27:06,380 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates
2024-09-19 17:27:06,750 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
2024-09-19 17:27:06,988 INFO  [ckan.model] CKAN database version remains as: 4a5e3465beb6 (head)
Upgrading DB: SUCCESS
(default) ubuntu@ip-172-31-3-204:/usr/lib/ckan/default$ sudo -u postgres psql ckan_default
psql (14.13 (Ubuntu 14.13-0ubuntu0.22.04.1))
Type "help" for help.

ckan_default=# \d activity
                           Table "public.activity"
    Column     |            Type             | Collation | Nullable | Default
---------------+-----------------------------+-----------+----------+---------
 id            | text                        |           | not null |
 timestamp     | timestamp without time zone |           |          |
 user_id       | text                        |           |          |
 object_id     | text                        |           |          |
 revision_id   | text                        |           |          |
 activity_type | text                        |           |          |
 data          | text                        |           |          |
Indexes:
    "activity_pkey" PRIMARY KEY, btree (id)
    "idx_activity_object_id" btree (object_id, "timestamp")
    "idx_activity_user_id" btree (user_id, "timestamp")
Referenced by:
    TABLE "activity_detail" CONSTRAINT "activity_detail_activity_id_fkey" FOREIGN KEY (activity_id) REFERENCES activity(id)
ckan_default=# \q

```
manual fix by adding permission_labels  as TEXT[]    (text array)
```
sudo -u postgres psql ckan_default
ckan_default=# ALTER TABLE activity ADD COLUMN permission_labels TEXT[];
ALTER TABLE
ckan_default=# \d activity;
                             Table "public.activity"
      Column       |            Type             | Collation | Nullable | Default
-------------------+-----------------------------+-----------+----------+---------
 id                | text                        |           | not null |
 timestamp         | timestamp without time zone |           |          |
 user_id           | text                        |           |          |
 object_id         | text                        |           |          |
 revision_id       | text                        |           |          |
 activity_type     | text                        |           |          |
 data              | text                        |           |          |
 permission_labels | text[]                      |           |          |
Indexes:
    "activity_pkey" PRIMARY KEY, btree (id)
    "idx_activity_object_id" btree (object_id, "timestamp")
    "idx_activity_user_id" btree (user_id, "timestamp")
Referenced by:
    TABLE "activity_detail" CONSTRAINT "activity_detail_activity_id_fkey" FOREIGN KEY (activity_id) REFERENCES activity(id)
ckan_default=# \q
```
working.

**Comment by tino097** [comment]
ive got this error on one instance, and it got it fixed with `ckan db upgrade -p activity`  

@brooks-eco have you tried in this way ?

**Comment by D3AH** [comment]
Hi @tino097, I tried `ckan db upgrade -p activity` in a fresh install from package in ubuntu 22.04 and `python-ckan/now 2.11.0-jammy1` . I got this error:

`alembic.util.exc.CommandError: No 'script_location' key found in configuration`

**Comment by brooks-eco** [comment]
confirm `alembic.util.exc.CommandError: No 'script_location' key found in configuration`

stepped through it one last time for good measure.

- minimal Ubuntu install and pkg install as per the docs.... up to adding sysadmin user.

### 1st error adding sysadmin
caused by the combination of (1) pkg install includes activity plugin by default. combined with (2) db upgrade patch to install the permission_lablels columns as discussed above is not applied


> sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "permission_labels" of relation "activity" does not exist

```
ckan -c /etc/ckan/default/ckan.ini sysadmin add ckan email=xxxx@xxxx.xx name=ckan
2024-10-02 08:34:52,314 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2024-10-02 08:34:52,315 INFO  [ckan.config.environment] Loading static files from public
2024-10-02 08:34:52,773 WARNI [ckan.common] Option lang is not declared
2024-10-02 08:34:52,883 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates
2024-10-02 08:34:53,283 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
User "ckan" not found
Create new user: ckan? [Y/n]: y
Password :
Repeat for confirmation:
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "permission_labels" of relation "activity" does not exist
LINE 1: ..._id, object_id, revision_id, activity_type, data, permission...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/cli/sysadmin.py", line 54, in add
    ctx.forward(add_user)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 804, in forward
    return __self.invoke(__cmd, *args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/cli/user.py", line 67, in add_user
    user_dict = logic.get_action(u'user_create')(context, data_dict)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/logic/__init__.py", line 596, in wrapped
    signals.action_succeeded.send(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/blinker/base.py", line 279, in send
    result = receiver(sender, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/activity/subscriptions.py", line 298, in user_changed
    tk.get_action("activity_create")(activity_create_context, activity_dict)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/logic/__init__.py", line 580, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/activity/logic/action.py", line 124, in activity_create
    model.repo.commit()
  File "<string>", line 2, in commit
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 832, in commit
    self._prepare_impl()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 800, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/model/meta.py", line 69, in ckan_before_commit
    dome.before_commit(session)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/model/modification.py", line 25, in before_commit
    self.notify_observers(session, self.notify)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/model/modification.py", line 28, in notify_observers
    session.flush()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
    with util.safe_reraise():
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "permission_labels" of relation "activity" does not exist
LINE 1: ..._id, object_id, revision_id, activity_type, data, permission...



[SQL: INSERT INTO activity (id, timestamp, user_id, object_id, revision_id, activity_type, data, permission_labels) VALUES (%(id)s, %(timestamp)s, %(user_id)s, %(object_id)s, %(revision_id)s, %(activity_type)s, %(data)s, %(permission_labels)s)]
[parameters: {'id': 'd250f77b-a34a-4b63-8878-36f6ccc559cc', 'timestamp': datetime.datetime(2024, 10, 2, 8, 35, 8, 349678), 'user_id': 'a9178508-aabb-47a6-af78-74d8153673bc', 'object_id': 'a9178508-aabb-47a6-af78-74d8153673bc', 'revision_id': None, 'activity_type': 'new user', 'data': None, 'permission_labels': None}]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

### ckan db init

```
(default) ubuntu@ip-172-31-1-117:/usr/lib/ckan/default$ ckan -c /etc/ckan/default/ckan.ini db init
2024-10-02 08:36:20,333 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2024-10-02 08:36:20,333 INFO  [ckan.config.environment] Loading static files from public
2024-10-02 08:36:20,698 WARNI [ckan.common] Option lang is not declared
2024-10-02 08:36:20,772 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates
2024-10-02 08:36:21,125 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
2024-10-02 08:36:21,462 INFO  [ckan.model] CKAN database version remains as: 4a5e3465beb6 (head)
Upgrading DB: SUCCESS
```
### ckan db upgrade  (does nothing)

```
(default) ubuntu@ip-172-31-1-117:/usr/lib/ckan/default$ ckan -c /etc/ckan/default/ckan.ini db upgrade
2024-10-02 08:36:38,639 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2024-10-02 08:36:38,639 INFO  [ckan.config.environment] Loading static files from public
2024-10-02 08:36:38,973 WARNI [ckan.common] Option lang is not declared
2024-10-02 08:36:39,049 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates
2024-10-02 08:36:39,372 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
2024-10-02 08:36:39,612 INFO  [ckan.model] CKAN database version remains as: 4a5e3465beb6 (head)
Upgrading DB: SUCCESS
```
### ckan db upgrade -p activity   (bombs)

>  alembic.util.exc.CommandError: No 'script_location' key found in configuration

```

(default) ubuntu@ip-172-31-1-117:/usr/lib/ckan/default$ ckan -c /etc/ckan/default/ckan.ini db upgrade -p activity
2024-10-02 08:36:55,462 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2024-10-02 08:36:55,463 INFO  [ckan.config.environment] Loading static files from public
2024-10-02 08:36:55,816 WARNI [ckan.common] Option lang is not declared
2024-10-02 08:36:55,908 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/lib/python3.10/site-packages/ckan/templates
2024-10-02 08:36:56,264 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/cli/db.py", line 88, in upgrade
    _run_migrations(plugin, version)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/cli/db.py", line 158, in _run_migrations
    repo.upgrade_db(version)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/model/__init__.py", line 372, in upgrade_db
    alembic_upgrade(self.alembic_config, version)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/alembic/command.py", line 386, in upgrade
    script = ScriptDirectory.from_config(config)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/alembic/script/base.py", line 170, in from_config
    raise util.CommandError(
alembic.util.exc.CommandError: No 'script_location' key found in configuration.
```

### manual fix in postgres as outlined above

```
(default) ubuntu@ip-172-31-1-117:/usr/lib/ckan/default$ sudo -u postgres psql ckan_default
psql (14.13 (Ubuntu 14.13-0ubuntu0.22.04.1))
Type "help" for help.

ckan_default=# \d activity
                           Table "public.activity"
    Column     |            Type             | Collation | Nullable | Default
---------------+-----------------------------+-----------+----------+---------
 id            | text                        |           | not null |
 timestamp     | timestamp without time zone |           |          |
 user_id       | text                        |           |          |
 object_id     | text                        |           |          |
 revision_id   | text                        |           |          |
 activity_type | text                        |           |          |
 data          | text                        |           |          |
Indexes:
    "activity_pkey" PRIMARY KEY, btree (id)
    "idx_activity_object_id" btree (object_id, "timestamp")
    "idx_activity_user_id" btree (user_id, "timestamp")
Referenced by:
    TABLE "activity_detail" CONSTRAINT "activity_detail_activity_id_fkey" FOREIGN KEY (activity_id) REFERENCES activity(id)

ckan_default=# ALTER TABLE activity ADD COLUMN permission_labels TEXT[];
ALTER TABLE
ckan_default=# \d activity
                             Table "public.activity"
      Column       |            Type             | Collation | Nullable | Default
-------------------+-----------------------------+-----------+----------+---------
 id                | text                        |           | not null |
 timestamp         | timestamp without time zone |           |          |
 user_id           | text                        |           |          |
 object_id         | text                        |           |          |
 revision_id       | text                        |           |          |
 activity_type     | text                        |           |          |
 data              | text                        |           |          |
 permission_labels | text[]                      |           |          |
Indexes:
    "activity_pkey" PRIMARY KEY, btree (id)
    "idx_activity_object_id" btree (object_id, "timestamp")
    "idx_activity_user_id" btree (user_id, "timestamp")
Referenced by:
    TABLE "activity_detail" CONSTRAINT "activity_detail_activity_id_fkey" FOREIGN KEY (activity_id) REFERENCES activity(id)

ckan_default=# exit
```

system operational

**Comment by avdata99** [comment]
Rename your fixture from `clean_db` to m`my_plugin_clean_db` could help
I'll not expect a conflict but maybe it's happening

Something like this could fix the issue

```py
@pytest.fixture
def my_plugin_clean_db(reset_db, migrate_db_for):
    reset_db()
    migrate_db_for("activity")
    migrate_db_for('my_plugin')

@pytest.mark.usefixtures('my_plugin_clean_db')
class TestSomething:
    def test_something()
```

I'm still investigating
