### ISSUE TITLE
CKAN error

### ISSUE THREAD

**Issue by skibigi** [ckan/ckan#8464]
## CKAN version
newest version
## Describe the bug
exact error : CKAN.TransactionalKraken: Registry already enlisted with tx 5c1549ec-e149-4293-beef-675b4b767b49:4, can't enlist with tx 5c1549ec-e149-4293-beef-675b4b767b49:9
   at CKAN.Registry.EnlistWithTransaction()
   at CKAN.Registry.DeregisterModule(GameInstance inst, String identifier)
   at CKAN.ModuleInstaller.Uninstall(String identifier, HashSet`1& possibleConfigOnlyDirs, Registry registry, IProgress`1 progress)
   at CKAN.ModuleInstaller.AddRemove(HashSet`1& possibleConfigOnlyDirs, RegistryManager registry_manager, ICollection`1 add, ICollection`1 autoInstalled, ICollection`1 remove, Boolean enforceConsistency)
   at CKAN.ModuleInstaller.Upgrade(ICollection`1 modules, IDownloader netAsyncDownloader, HashSet`1& possibleConfigOnlyDirs, RegistryManager registry_manager, Boolean enforceConsistency, Boolean resolveRelationships, Boolean ConfirmPrompt)
   at CKAN.GUI.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

### Steps to reproduce
Steps to reproduce the behavior: i updated a bunch of my mods

### Expected behavior
i expected to update a lot of my mods
### Additional details
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by skibigi** [comment]
nvm i think i know why

**Comment by skibigi** [comment]
nvm i dont

**Comment by skibigi** [comment]
it works now i had to restart ckan

**Comment by tino097** [comment]
@skibigi also wrong CKAN
