### ISSUE TITLE
Error generating new ckan extension template

### ISSUE THREAD

**Issue by fpichardom** [ckan/ckan#8488]
## CKAN version
CKAN 2.11

## Describe the bug

When creating a new extension template using `ckan generate extension` or using `cookiecutter` directly results in error and extension template is not generated. It instead gives this message:

```
Traceback (most recent call last):
  File "/tmp/tmpwdw3h9gj.py", line 88, in <module>
    "_checkout": null,
NameError: name 'null' is not defined
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

### Steps to reproduce

- My setup is Windows 11 using Docker Desktop with WSL2.
- I'm loading CKAN using the ckan-docker repo docker compose files.

#### Using `ckan generate extension`
- After running the `docker-compose.dev.yml` file from the ckan-docker repo I entered the ckan-dev-1 container
- Navigated to `/srv/app/src_extensions` and executed `ckan generate extension`
- Filled up the extension name correctly in all trial but tried different combinations of the other information asked and none worked.
- After last prompt it returns the error.

#### Using `cookiecutter`

- Inside the `ckan-dev-1` container navigated to `/srv/app/src` and executed `cookiecutter ckan/contrib/cookiecutter/ckan_extension`
- Followed the prompts entering a valid ckan extension name and different values for the other prompts.
- After last prompt it returns the error.

### Expected behavior

It should have created a new extension template directory in the current directory where the code was executed.

### Additional details
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

#### `ckan generate extension` trial

```
Extension's name [must begin 'ckanext-']: ckanext-knowledgebase
Author's name []: 
Author's email []: 
Your Github user or organization name []: 
Brief description of the project []: 
List of keywords (separated by spaces) [CKAN]: 
Do you want to include code examples? [y/N]: y
Traceback (most recent call last):
  File "/tmp/tmpcwy7avy4.py", line 88, in <module>
    "_checkout": null,
NameError: name 'null' is not defined
Stopping generation because post_gen_project hook script didn't exit successfully
Traceback (most recent call last):
  File "/usr/local/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/srv/app/src/ckan/ckan/cli/generate.py", line 114, in extension
    cookiecutter(template_loc, no_input=True, extra_context=context,
  File "/usr/local/lib/python3.10/site-packages/cookiecutter/main.py", line 182, in cookiecutter
    result = generate_files(
  File "/usr/local/lib/python3.10/site-packages/cookiecutter/generate.py", line 419, in generate_files
    run_hook_from_repo_dir(
  File "/usr/local/lib/python3.10/site-packages/cookiecutter/hooks.py", line 157, in run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "/usr/local/lib/python3.10/site-packages/cookiecutter/hooks.py", line 140, in run_hook
    run_script_with_context(script, project_dir, context)
  File "/usr/local/lib/python3.10/site-packages/cookiecutter/hooks.py", line 123, in run_script_with_context
    run_script(temp.name, cwd)
  File "/usr/local/lib/python3.10/site-packages/cookiecutter/hooks.py", line 94, in run_script
    raise FailedHookException(
cookiecutter.exceptions.FailedHookException: Hook script failed (exit status: 1)
```

#### `cookiecutter` trial

```
# cookiecutter ckan/contrib/cookiecutter/ckan_extension
  [1/10] project (Project's name (must begin with 'ckanext-')): ckanext-knowledgebase
  [2/10] keywords (A space separated list of keywords): 
  [3/10] description (): 
  [4/10] author (): 
  [5/10] author_email (): 
  [6/10] github_user_name (Github user or organization name): 
  [7/10] project_shortname (knowledgebase): 
  [8/10] plugin_class_name (KnowledgebasePlugin): 
  [9/10] include_examples (0): 
  [10/10] ckan_version (): 
Traceback (most recent call last):
  File "/tmp/tmpwdw3h9gj.py", line 88, in <module>
    "_checkout": null,
NameError: name 'null' is not defined
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

#### Example of the referenced tmp file in the error message (`/tmp/tmpwdw3h9gj.py`)

```
# cat /tmp/tmpwdw3h9gj.py
# encoding: utf-8

import os
import jinja2
import cookiecutter.find as find
import cookiecutter.generate as gen
from cookiecutter.config import DEFAULT_CONFIG as config
from cookiecutter.environment import StrictEnvironment
from cookiecutter.exceptions import NonTemplatedInputDirException
from ckan.common import asbool
from ckan.cli.generate import remove_code_examples


def recut():
    """
    Recreate setup.py so that we can edit keywords
    Remove unnecessary code examples
    """
    # template location
    try:
        # cutting cookie from directory with template
        temp_dir = find.find_template('..')
    except NonTemplatedInputDirException as e:
        # template coming from Github
        # Hooks are passed through jinja2. raw will
        # Make sure `cookiecutter.project` isn't replaced
        
        temp_dir = os.path.join(config['cookiecutters_dir'],
                                'cookiecutter-ckan-extension',
                                '{{cookiecutter.project}}')
        

    # Location for resulting file
    destination = os.getcwd()
    # name of template
    setup_template = 'setup.py'

    # get context
    context = {
    "_checkout": null,
    "_output_dir": "/srv/app/src",
    "_repo_dir": "ckan/contrib/cookiecutter/ckan_extension",
    "_source": "local",
    "_template": "ckan/contrib/cookiecutter/ckan_extension",
    "author": "",
    "author_email": "",
    "ckan_version": "",
    "description": "",
    "github_user_name": "Github user or organization name",
    "include_examples": "0",
    "keywords": "A space separated list of keywords",
    "plugin_class_name": "KnowledgebasePlugin",
    "project": "ckanext-knowledgebase",
    "project_shortname": "knowledgebase"
}

    # Process keywords
    keywords = context['keywords'].strip().split()
    keywords = [keyword for keyword in keywords
                if keyword not in ('ckan', 'CKAN', 'A', 'space',
                                   'seperated', 'list', 'of', 'keywords')]
    keywords.insert(0, 'CKAN')
    keywords = u' '.join(keywords)
    context['keywords'] = keywords

    # Double check 'project_shortname' and 'plugin_class_name'
    short_name = context['project'][8:].replace('-','_')
    if context['project_shortname'] != short_name:
        context['project_shortname'] = short_name

    plugin_class_name = '{}Plugin'.format(context['project_shortname']
                        .title().replace('_', ''))
    if context['plugin_class_name'] != plugin_class_name:
        context['plugin_class_name'] = plugin_class_name
    # Recut cookie
    env = StrictEnvironment()
    env.loader = jinja2.FileSystemLoader(temp_dir)
    gen.generate_file(project_dir=destination,
                      infile=setup_template,
                      context={'cookiecutter': context},
                      env=env)
    if not asbool(context['include_examples']):
        remove_code_examples(os.path.join(destination, 'ckanext', short_name))


if __name__ == '__main__':
    context = {
    "_checkout": null,
    "_output_dir": "/srv/app/src",
    "_repo_dir": "ckan/contrib/cookiecutter/ckan_extension",
    "_source": "local",
    "_template": "ckan/contrib/cookiecutter/ckan_extension",
    "author": "",
    "author_email": "",
    "ckan_version": "",
    "description": "",
    "github_user_name": "Github user or organization name",
    "include_examples": "0",
    "keywords": "A space separated list of keywords",
    "plugin_class_name": "KnowledgebasePlugin",
    "project": "ckanext-knowledgebase",
    "project_shortname": "knowledgebase"
}
    if context['_source'] == 'local':
        recut()
```

**Comment by wardi** [comment]
Hello @fpichardom this was fixed by #8456, is available in the dev-2.11 branch and will be available in the next patch release.
