### ISSUE TITLE
Password reset don't work if ckan.auth.public_user_details = false 

### ISSUE THREAD

**Issue by gatiszeiris** [ckan/ckan#8539]
## CKAN version
2.10.1
## Describe the bug
Password reset don't work if ckan.auth.public_user_details = false 
Page return Internal server error.
![image](https://github.com/user-attachments/assets/39d3fd07-9a75-44c7-a667-cffe58a55432)

Backend logs show
2024-11-19 16:02:38,809 DEBUG [ckan.logic] check access OK - site_read user=
2024-11-19 16:02:38,812 DEBUG [ckan.logic] check access OK - user_reset user=e52f32d6-ba45-4467-a071-320317ae0ac7
2024-11-19 16:02:38,815 DEBUG [ckan.logic] check access NotAuthorized - user_show user=e52f32d6-ba45-4467-a071-320317ae0ac7 ""
2024-11-19 16:02:38,815 ERROR [ckan.config.middleware.flask_app]
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib64/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib64/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/ckan/default/lib64/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/lib/ckan/default/lib64/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/user.py", line 800, in get
    user_dict = self._prepare(id)[1]
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/user.py", line 727, in _prepare
    user_dict = logic.get_action(u'user_show')(context, {u'id': id})
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 1470, in user_show
    _check_access('user_show', context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 362, in check_access
    raise NotAuthorized(msg)
ckan.logic.NotAuthorized
2024-11-19 16:02:38,971 INFO  [ckan.config.middleware.flask_app]  500 /user/reset/e52f32d6-ba45-4467-a071-320317ae0ac7 render time 0.165 seconds
[pid: 8290|app: 1|req: 34/89] 127.0.0.1 () {52 vars in 1234 bytes} [Tue Nov 19 16:02:38 2024] GET /dati/user/reset/e52f32d6-ba45-4467-a071-320317ae0ac7?key=ce249086c8c0b46bf25b24649198a2c4 => generated 20263 bytes in 166 msecs (HTTP/1.0 500) 3 headers in 152 bytes (1 switches on core 2)

### Steps to reproduce
In ckan.ini enable the following
## Authorization Settings ######################################################
ckan.auth.anon_create_dataset = false
ckan.auth.create_unowned_dataset = false
ckan.auth.create_dataset_if_not_in_organization = true
ckan.auth.user_create_groups = true
ckan.auth.user_create_organizations = true
ckan.auth.user_delete_groups = true
ckan.auth.user_delete_organizations = true
ckan.auth.create_user_via_api = false
ckan.auth.create_user_via_web = false
ckan.auth.roles_that_cascade_to_sub_groups = admin
**ckan.auth.public_user_details = false**
ckan.auth.public_activity_stream_detail = false
ckan.auth.allow_dataset_collaborators = false
ckan.auth.allow_admin_collaborators = false
ckan.auth.allow_collaborators_to_change_owner_org = false
ckan.auth.create_default_api_keys = false
ckan.auth.login_view = user.login
ckan.auth.reveal_private_datasets = false
ckan.auth.enable_cookie_auth_in_api = true

### Expected behavior
User can reset password also when user details is not public **ckan.auth.public_user_details = false**
User details is private information and we cant expose it to public.

### Additional details
If **ckan.auth.public_user_details = true** password reset works with no error

**Comment by tino097** [comment]
There is a [PR ](https://github.com/ckan/ckan/pull/7266)for this issue

**Comment by gatiszeiris** [comment]
This remains an issue, even in CKAN 2.10.1.

**Comment by Zharktas** [comment]
The issue which reveals itself as side effect in user reset has been fixed in 2.10.3 https://github.com/ckan/ckan/pull/7871

**Comment by tino097** [comment]
@gatiszeiris you should update to the latest patch release 2.10.5

**Comment by gatiszeiris** [comment]
Thanks a lot @Zharktas and @tino097
