### ISSUE TITLE
Organization admin can't invite new user to organization if  ckan.auth.create_user_via_web = false

### ISSUE THREAD

**Issue by gatiszeiris** [ckan/ckan#8553]
## CKAN version
2.10.1

## Describe the bug
Organization admin can't invite new user to organization if  ckan.auth.create_user_via_web = false
Page return Internal server error.
![image](https://github.com/user-attachments/assets/38122dcd-bbe4-4c03-bee8-5f7694c9023e)
![image](https://github.com/user-attachments/assets/885d521d-5078-4930-b529-40086c62a32d)
![image](https://github.com/user-attachments/assets/4df9c054-e304-4794-9851-f556fe270cbb)
2024-11-28 09:12:18,087 INFO  [ckan.config.middleware.flask_app]  200 /api/i18n/en render time 0.007 seconds
2024-11-28 09:14:59,942 DEBUG [ckan.logic] check access OK - organization_member_create user=info-555
2024-11-28 09:14:59,946 DEBUG [ckan.logic] check access OK - user_invite user=info-555
2024-11-28 09:14:59,950 DEBUG [ckan.logic] check access NotAuthorized - user_create user=info-555 "Not authorized to create users"
2024-11-28 09:14:59,950 ERROR [ckan.config.middleware.flask_app] Not authorized to create users
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib64/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib64/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/ckan/default/lib64/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/lib/ckan/default/lib64/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/group.py", line 1111, in post
    user_dict = _action(u'user_invite')(context, user_data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 1100, in user_invite
    user_dict = _get_action('user_create')(
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 996, in user_create
    _check_access('user_create', context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 362, in check_access
    raise NotAuthorized(msg)
ckan.logic.NotAuthorized: Not authorized to create users
2024-11-28 09:14:59,956 DEBUG [ckan.logic] check access OK - user_show user=info-555
2024-11-28 09:14:59,972 INFO  [ckan.config.middleware.flask_app]  500 /organization/member_new/b663e955-19c0-434c-8a57-3ea80f105a12 render time 0.041 seconds
[pid: 222062|app: 1|req: 76/143] 127.0.0.1 () {60 vars in 2322 bytes} [Thu Nov 28 09:14:59 2024] POST /dati/organization/member_new/b663e955-19c0-434c-8a57-3ea80f105a12 => generated 7286 bytes in 42 msecs (HTTP/1.0 500) 5 headers in 504 bytes (1 switches on core 0)

### Steps to reproduce
In ckan.ini enable the following

ckan.auth.anon_create_dataset = false
ckan.auth.create_unowned_dataset = false
ckan.auth.create_dataset_if_not_in_organization = true
ckan.auth.user_create_groups = true
ckan.auth.user_create_organizations = true
ckan.auth.user_delete_groups = true
ckan.auth.user_delete_organizations = true
ckan.auth.create_user_via_api = true
**ckan.auth.create_user_via_web = false**
ckan.auth.roles_that_cascade_to_sub_groups = admin
ckan.auth.public_user_details = true
ckan.auth.public_activity_stream_detail = false
ckan.auth.allow_dataset_collaborators = false
ckan.auth.allow_admin_collaborators = false
ckan.auth.allow_collaborators_to_change_owner_org = false
ckan.auth.create_default_api_keys = false
ckan.auth.login_view = user.login
ckan.auth.reveal_private_datasets = false
ckan.auth.enable_cookie_auth_in_api = true
ckan.auth.route_after_login = dashboard.datasets

### Expected behavior
Organization admin can invite new users if public registration is disabled.
CKAN works as expected described in documentation regarding to new user registration.

### Additional details
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by gatiszeiris** [comment]
Thanks a lot for fast feedback @tino097
